### ISSUE TITLE
:robot: CI fails in pushing cosign signatures

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1005]
**Kairos version:**
master CI

**CPU architecture, OS, and Version:**

**Describe the bug**
cosign fails, seems we are doing something wrong in our steps:

```
 359cb4dd84cb: Pushed
latest: digest: sha256:02d3c0b63091ead1fdd89c2d101d8c030950667645f75417a9db9e1e74d52a03 size: 5097
Generating ephemeral keys...
Retrieving signed certificate...
Successfully verified SCT...
WARNING: Image reference quay.io/kairos/core-fedora:latest uses a tag, not a digest, to identify the image to sign.
    This can lead you to sign a different image than the intended one. Please use a
    digest (example.com/ubuntu@sha256:abc123...) rather than tag
    (example.com/ubuntu:latest) for the input to cosign. The ability to refer to
    images by tag will be removed in a future release.


	Note that there may be personally identifiable information associated with this signed artifact.
	This may include the email address associated with the account with which you authenticate.
	This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.

By typing 'y', you attest that you grant (or have permission to grant) and agree to have this information stored permanently in transparency logs.
Are you sure you would like to continue? [y/N] Error: signing [quay.io/kairos/core-fedora:latest]: recursively signing: signing digest: should upload to tlog: user declined the prompt
main.go:74: error during command execution: signing [quay.io/kairos/core-fedora:latest]: recursively signing: signing digest: should upload to tlog: user declined the prompt
Error: Process completed with exit code 1.
```

We should use sha, instead of image references.

**To Reproduce**

**Expected behavior**

**Logs**
https://github.com/kairos-io/kairos/actions/runs/4312122113/jobs/7522297755

**Additional context**

**Comment by mudler** [comment]
This is a blocker for #754 #984 #996

**Comment by mudler** [comment]
Likely will be an issue for provider-kairos as well

**Comment by mudler** [comment]
@jimmykarily this just needs to be propagated back to the provider repo, otherwise we are good, right?

**Comment by jimmykarily** [comment]
yes, I will have a look there too

**Comment by jimmykarily** [comment]
Created a PR: https://github.com/kairos-io/provider-kairos/pull/260/files

**Comment by mudler** [comment]
Seems we have other pieces of the CI still failing that prevents tagging, currently WIP

**Comment by mudler** [comment]
one more: https://github.com/kairos-io/provider-kairos/actions/runs/4345179869/jobs/7589532192 @jimmykarily

**Comment by jimmykarily** [comment]
> one more: https://github.com/kairos-io/provider-kairos/actions/runs/4345179869/jobs/7589532192 @jimmykarily

One more try: https://github.com/kairos-io/provider-kairos/pull/271
