### ISSUE TITLE
:bug: Repo for core-opensuse-leap-kubeadm should be created for provider image push

### ISSUE THREAD

**Issue by rishi-anand** [kairos-io/kairos#1008]
In kairos 1.5.0, opensuse repo is changed to -leap and -tumbleweed . In providers, we are bumping up kairos version to 1.5.0 and opensuse image to opensuse-leap and I have noticed that repos core-opensuse-leap-k3s, core-opensuse-leap-rke2 and core-opensuse-leap-kubeadm aren’t there as of now and release build of providers will fail.

**Comment by mudler** [comment]
is there anything we have to do here @rishi-anand ? can we close this issue?

**Comment by mudler** [comment]
Closing, there is no clear action item from it
