### ISSUE TITLE
Running out of partition space during install...what config option will remedy this?

### ISSUE THREAD

**Issue by avfuturist** [kairos-io/kairos#1025]
**Kairos version:**
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="v0.1.4-n1.4-k1.6.0" (My own version number)
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**CPU architecture, OS, and Version:**
x86_64, also before anyone asks it's a 512GB nvme drive that's empty...so plenty of room.

**Describe the bug**
During install of my meta-distro, I run out of partition space it seems. I'm not sure what lever to flip here to expand the partition sizes properly. Was trying to find where this is dictated in /system/oem but can't find it anywhere.

**To Reproduce**
From Kairos Core, install run an install of my distro from the web ui. 

**Expected behavior**
Install should proceed normally.

**Logs**
```
INFO[2023-03-03T00:06:34Z] Starting elemental version 0.20221121.1+kairos 
INFO[2023-03-03T00:06:34Z] Install called                               
INFO[2023-03-03T00:06:34Z] Partitioning device...                       
INFO[2023-03-03T00:06:38Z] Mounting disk partitions                     
INFO[2023-03-03T00:06:39Z] Running before-install hook                  
INFO[2023-03-03T00:06:39Z] Creating file system image /run/cos/state/cOS/active.img 
time="2023-03-03T00:06:39Z" level=info msg="Unpacking a container image: docker.io/floucksl3av/kairos-nomad:v0.1.4-n1.4-k1.6.0"
time="2023-03-03T00:06:39Z" level=info msg="Pulling an image from remote repository"
INFO[2023-03-03T00:06:39Z] Copying docker.io/floucksl3av/kairos-nomad:v0.1.4-n1.4-k1.6.0 source... 
INFO[2023-03-03T00:07:51Z] Unmounting disk partitions                   
Error: 1 error occurred:
        * write /run/cos/active/usr/lib/modules/5.19.0-32-generic/kernel/sound/soc/codecs/snd-soc-sti-sas.ko: no space left on device


exit status 1
```

**Additional context**
My meta-distro is purpose built for running Hashicorp Nomad with Docker and QEMU drivers. Everything was fine with just Docker. Once I added QEMU (and what I'm sure were several dependencies & packages) I wasn't able to run the install anymore due to this issue.

**Comment by avfuturist** [comment]
Looks like COS_ACTIVE during the install process is 2.9GB, whereas my image is 3.4GB. I'm using the Kairos Ubuntu 22 LTS Core ISO as the base OS for install. Any way to modify the size of COS_ACTIVE in the cloud-config? Looking at "layout" but not really understanding how I'd accomplish this.

**Comment by avfuturist** [comment]
Here's the output of lsblk -o name,mountpoint,label,size,uuid _during install_...active disappears again after the install fails. 

```
NAME        MOUNTPOINT          LABEL            SIZE UUID
loop0       /run/rootfsbase                    857.1M
loop1       /run/cos/active     COS_ACTIVE       2.9G ae3db42c-a027-49e0-8e0f-846b8a33f0f1
sda                             COS_LIVE        29.3G 2023-01-26-18-11-47-00
├─sda1      /run/initramfs/live COS_LIVE       959.8M 2023-01-26-18-11-47-00
└─sda2                          COS_GRUB           4M 2632-02FD
nvme0n1                                        465.8G
├─nvme0n1p1 /run/cos/efi        COS_GRUB          64M D887-CF33
├─nvme0n1p2 /run/cos/oem        COS_OEM           64M 61e422ee-c79c-4fef-8f97-dab992b62902
├─nvme0n1p3 /run/cos/recovery   COS_RECOVERY       8G 72bcb1d9-0a9f-4f0a-a567-53704a6953fe
├─nvme0n1p4 /run/cos/state      COS_STATE         15G 0780e0d7-f657-4cb7-8875-8adf32671673
└─nvme0n1p5 /run/cos/persistent COS_PERSISTENT 442.6G 519689d1-b7e2-4e8a-a6fd-029a76693540
```

**Comment by mudler** [comment]
Hey @avfuturist :wave: 

The images have a fixed size. If you are customizing the image and exceeding defaults, you must configure the `size` in the `/etc/elemental/config.yaml` file accordingly:

```yaml
install:
  grub-entry-name: "Kairos"
  system:
    size: 3000
  recovery-system:
    size: 3000
upgrade:
  grub-entry-name: "Kairos"
  recovery-system:
    size: 3000
  system:
    size: 3000
reset:
  grub-entry-name: "Kairos"
  system:
    size: 3000

```

**Comment by avfuturist** [comment]
Nailed it @mudler! 
Added this file with size bumped to 4000 to my Dockerfile. Install looks good now! 

Thank you!! 🙏
