### ISSUE TITLE
:bug: Images missing latest tag on quay

### ISSUE THREAD

**Issue by geetikabatra** [kairos-io/kairos#1026]
`docker pull quay.io/kairos/kairos-ubuntu-22-lts
`Using default tag: latest
Error response from daemon: manifest for quay.io/kairos/kairos-ubuntu-22-lts:latest not found: manifest unknown: manifest unknown

**Comment by mauromorales** [comment]
Thanks for reporting this @geetikabatra. The issue applies to other images as well, like fedora. Changing the title to reflect this

**Comment by mauromorales** [comment]
Also keep in mind latest sometimes points to latest master not latest release

**Comment by mauromorales** [comment]
And some of the release flavors are missing from the matrix

**Comment by mauromorales** [comment]
https://github.com/kairos-io/provider-kairos/pull/301
