### ISSUE TITLE
Debian based machine is missing /etc/resolv.conf on boot

### ISSUE THREAD

**Issue by nano2007** [kairos-io/kairos#1035]
**Kairos version:**

NAME="kairos-debian"
VERSION="v1.6.1-k3sv1.26.1+k3s1"
ID="kairos"
ID_LIKE="kairos-debian"
VERSION_ID="v1.6.1-k3sv1.26.1+k3s1"
PRETTY_NAME="kairos-debian v1.6.1-k3sv1.26.1+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-debian"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse-leap"

**CPU architecture, OS, and Version:**

Linux cryptoflow 6.1.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29) x86_64 GNU/Linux

**Describe the bug**

After installing from iso or booting from cloudimage, the network interface is assigned an IP address from DHCP. But the  /etc/resolv.conf is missing and some of the services do not start up properly. Also name resolution does not work as expected.

**To Reproduce**

- create an iso or cloudImage from 1.6.1 debian 
- create a VM using the iso or cloudImage
- Check contents of /etc/resolv.conf

**Expected behavior**

The /etc/resolv.conf should get populated and name resolution should work correctly

**Logs**

*On VM Boot*

> 2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 52:54:00:fc:78:2b brd ff:ff:ff:ff:ff:ff
>     altname enp0s3
>     inet 10.15.2.148/16 metric 1024 brd 10.15.255.255 scope global dynamic ens3
>        valid_lft 3164sec preferred_lft 3164sec
>     inet6 fe80::5054:ff:fefc:782b/64 scope link
>        valid_lft forever preferred_lft forever
> 
> pserver@cryptoflow:~$ ls -ltr /etc/resolv.conf
> lrwxrwxrwx 1 root root 32 Mar  4 06:33 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf

*After running `sudo dhclient ens3` manually*

> 2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 52:54:00:fc:78:2b brd ff:ff:ff:ff:ff:ff
>     altname enp0s3
>     inet 10.15.2.148/16 metric 1024 brd 10.15.255.255 scope global dynamic ens3
>        valid_lft 2975sec preferred_lft 2975sec
>     inet 10.15.2.172/16 brd 10.15.255.255 scope global secondary dynamic ens3
>        valid_lft 3539sec preferred_lft 3539sec
>     inet6 fe80::5054:ff:fefc:782b/64 scope link
>        valid_lft forever preferred_lft forever
> 
> pserver@cryptoflow:~$ cat /etc/resolv.conf
> domain xyz.com
> search xyz.com
> nameserver 10.15.2.1

**Additional context**

**Comment by cristian98149** [comment]
Same issue for me.

**Comment by mudler** [comment]
@cristian98149 only RC's at the moment, but we should be able to cut a 2.0 really soon - we hit several showstoppers that are being addressed right now
