### ISSUE TITLE
:bug: elemental-cli identifies all distros as suse

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1051]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
There is some distro discovery code in elemental-cli that tries to know which distro is it runnning on for some paths and some files needed to copy. It relies in getting the os-release ID field as that its supposed to be respected on derivative distros. Unfortunately, when It can, it just defaults to suse. On every distro, as we override the ID.

This means we are copying some grub artifacts that may or may not be the proper ones. 

**To Reproduce**
run `elemental-cli --debug install DEVICE` and watch what it reports the system as:
`INFO[2023-03-06T18:46:41Z] Identified source system as suse`

**Expected behavior**
To identify the system correctly by other means maybe...state sdk? And copy the proper files given by the distribution as they differ.

OR to provide the grub artifacts as part of the framework/base image with a luet package (same for all distros?) and change elemental-cli to not search for them, but pick them from whatever (/usr/share/kairos/grub?)

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
also the shim-signed package that provides the signed files (mokmanager, shim and grub) are missing :D

So this requires:

 - Add shim-signed files to dockerfiles
 - Fix elemental-cli to detect the flavor properly
 - Make it copy the proper files (secureboot signed if possible)

And then to improve upon this:
 - Build luet packages for the signed artifacts and provide one single package for all with the artifacts in a known location
 - Change elemental-cli to not search for those but get them from a know location

This change would also make it possible to override those shim/grub efi files with an end user ones, so they can provide the efi binaries signed by them.

**Comment by mudler** [comment]
we do stab efi files coming from the packages respository - IIRC we don't rely on distro-specific efi shells for this to be consistent

**Comment by Itxaka** [comment]
> we do stab efi files coming from the packages respository and let elemental think are all SUSE - IIRC we don't rely on distro-specific efi shells for this to be consistent

Are you sure about that? I think we wrongly get all systems as suse and then becuase the suse names for the artifacts are also in other distros we just get lucky and use them. But we dont provide any from luet packages as far as I can see. We DO provide other grub files, but those are for the x86_64 bios boot only. Cant see any efi files in those grub packages.

**Comment by Itxaka** [comment]
Also this makes it always default to non-signed artifacts which is bad:

`root@9efd31a7d4a7:/# sbverify /usr/share/efi/x86_64/grub.efi
Signature verification failed`

Probably kairos doesnt boot wiht secureboot enabled and this is the reason, we dont provide signed artifacts.

>[kairos/framework-profile.yaml](https://github.com/kairos-io/kairos/blob/975b5ab5d0cdc31d388421c809db25ca35f4e629/framework-profile.yaml#L9)

>Line 9 in [975b5ab](https://github.com/kairos-io/kairos/commit/975b5ab5d0cdc31d388421c809db25ca35f4e629)
 - system/grub2-efi


Yes. That only provides the unsigned grub.efi which is not enough for secureboot. No mokmanager to manage signatures, nor a shim to chainload.


Not to mention the main issue of the bug, if we misidentify a derivative, then it may not even install :D

**Comment by mudler** [comment]
> Also this makes it always default to non-signed artifacts which is bad:
> 
> `root@9efd31a7d4a7:/# sbverify /usr/share/efi/x86_64/grub.efi Signature verification failed`
> 
> Probably kairos doesnt boot wiht secureboot enabled and this is the reason, we dont provide signed artifacts.
> 
> > [kairos/framework-profile.yaml](https://github.com/kairos-io/kairos/blob/975b5ab5d0cdc31d388421c809db25ca35f4e629/framework-profile.yaml#L9)
> 
> > Line 9 in [975b5ab](https://github.com/kairos-io/kairos/commit/975b5ab5d0cdc31d388421c809db25ca35f4e629)
> 
>     * system/grub2-efi
> 
> 
> Yes. That only provides the unsigned grub.efi which is not enough for secureboot. No mokmanager to manage signatures, nor a shim to chainload.
> 
> Not to mention the main issue of the bug, if we misidentify a derivative, then it may not even install :D

yep agreed, but that's another thing - we do provide the efi shell and the efi shim is here: https://github.com/kairos-io/kairos/blob/975b5ab5d0cdc31d388421c809db25ca35f4e629/framework-profile.yaml#L8

**Comment by mudler** [comment]
> > Also this makes it always default to non-signed artifacts which is bad:
> > `root@9efd31a7d4a7:/# sbverify /usr/share/efi/x86_64/grub.efi Signature verification failed`
> > Probably kairos doesnt boot wiht secureboot enabled and this is the reason, we dont provide signed artifacts.

almost toothless without static measured boot, that should come with #347 

> > > [kairos/framework-profile.yaml](https://github.com/kairos-io/kairos/blob/975b5ab5d0cdc31d388421c809db25ca35f4e629/framework-profile.yaml#L9)
> > 
> > 
> > > Line 9 in [975b5ab](https://github.com/kairos-io/kairos/commit/975b5ab5d0cdc31d388421c809db25ca35f4e629)
> > 
> > 
> > ```
> > * system/grub2-efi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yes. That only provides the unsigned grub.efi which is not enough for secureboot. No mokmanager to manage signatures, nor a shim to chainload.
> > Not to mention the main issue of the bug, if we misidentify a derivative, then it may not even install :D
> 
> yep agreed, but that's another thing - we do provide the efi shell and the efi shim is here:
> 
> https://github.com/kairos-io/kairos/blob/975b5ab5d0cdc31d388421c809db25ca35f4e629/framework-profile.yaml#L8

**Comment by Itxaka** [comment]
> IIRC we don't rely on distro-specific efi shells for this to be consistent and avoid runtime guessing (we rather want the efi-shells in a fixed location, or to specify them)
> yep agreed, but that's another thing - we do provide the efi shell and the efi shim is here: 

Shiiiiet, then we almost there

This is very good and we should expand on this.
 - Drop all the detection crap from elemental-cli
 - Drop all the search for grub files from elemental-cli and copy them from our known route

That should fix this issue AND improve both elemental-cli and kairos.

**Comment by mudler** [comment]
> > IIRC we don't rely on distro-specific efi shells for this to be consistent and avoid runtime guessing (we rather want the efi-shells in a fixed location, or to specify them)
> > yep agreed, but that's another thing - we do provide the efi shell and the efi shim is here:
> 
> Shiiiiet, then we almost there
> 
> This is very good and we should expand on this.
> 
> * Drop all the detection crap from elemental-cli
> * Drop all the search for grub files from elemental-cli and copy them from our known route
> 
> That should fix this issue AND improve both elemental-cli and kairos.

correct :+1:  IIRC that indeed was the plan, but welp, many things arised in between

**Comment by Itxaka** [comment]
elemental-cli patch: https://github.com/kairos-io/elemental-cli/pull/44 - Fixes searching for artifacts and identifying the system, instead will pick artifacts from a fixed position
packages patch: https://github.com/kairos-io/packages/pull/136 - Bundles the needed efi files in the grub2-efi package

Missing:
 - Bump this packages in kairos. I would wait a bit maybe with immucore in the middle it can lead to breaking things...plus I ain't got time to do it :D

**Comment by Itxaka** [comment]
This was fixed already and the new elemental-cli version without the detection stuff is already on master with no issues so far. Closing this
