### ISSUE TITLE
:seedling: ARM64 support for non-embedded systems

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1070]
### Discussed in https://github.com/kairos-io/kairos/discussions/498

<div type='discussions-op-text'>

<sup>Originally posted by **jtcressy** November 25, 2022</sup>
Several public cloud providers are providing ARM64 architecture instances (often at reduced cost or better performance per unit of currency) such as:
- AWS - EC2 Graviton Instances
- Google Cloud / Oracle Cloud - Ampere Altra CPU's

Additionally, and less common, would be Apple's M1/M2 chips on top of which you can run virtualized ARM64 QEMU VM's

Kairos currently publishes builds for _embedded_ ARM64 systems such as Raspberry Pi, but these builds cannot be consumed by the above ARM64 system types. 

The above system types behave just like other x86_64/AMD64 cloud instances with full ACPI firmware, so we would continue to build these images the same way except the CPU arch is changed to ARM64. I've experimented with this kind of stuff on my own elemental derivative that I build for learning purposes (https://github.com/jtcressy-home/edge-images) and I am able to generate ARM iso images that can install on cloud VM's or even local QEMU VM's on my M1 macbook.

I have ran into some challenges, however, with container images during upgrades. The version of elemental I was using (which may or may not be kairos's fork - I have to go back and check) does NOT support selecting container images from a multi-arch manifest. I can build my derivative's container image for both architectures using docker buildx and upload both of them with the same tag to create a multi-arch image manifest. As far as I know, nearly every container runtime supports multi-arch manifests, be it podman, docker, containerd, etc. 

This discussion could've been a FR issue, but I feel like this kind of ARM64 support may be a bit of a can of worms and I would love to see the perspective of the Kairos maintainers and contributors before setting up a full fledged issue ticket.</div>

**Comment by mudler** [comment]
This is done @Itxaka ?

**Comment by mudler** [comment]
I think this was covering generic arm64 images mostly. for multi-arch we have the #1061 story :+1:

**Comment by mauromorales** [comment]
I would say let's keep it open until:

- We also release the ubuntu one, which is already working it's just not part of the CI
- We document where to get these releases

**Comment by thomasmhofmann** [comment]
Hi there, I came here looking for an ISO I can run in a VM on the aarch64 architecture (apple silicone).
I couldn't find any prebuilt ISO images. Are there any or can I build one myself using anything already provided by the kairos project?

**Comment by mauromorales** [comment]
@thomasmhofmann we currently only have [opensuse for generic arm](https://github.com/kairos-io/kairos/releases/download/v2.4.1/kairos-core-opensuse-leap-arm64-generic-v2.4.1.iso) would you please give it a go and let me know if that works? You should also be able to build ubuntu and debian, but we're in the middle of a release so there might be some issues until it's out, but you can try running the following (choose core or standard):

```
earthly +all-arm-generic --FAMILY=ubuntu --FLAVOR=ubuntu --FLAVOR_RELEASE=23.01 --VARIANT=core
```

If that breaks (sorry, still testing things) then you might need to checkout v2.4.1 and do the following

```
earthly +all-arm-generic --FLAVOR=ubuntu
```
