### ISSUE TITLE
:bug: :robot: unit tests job is broken

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1089]
Seems like it cant find the coverage files, probably something to do with running in earthly and paths.

https://github.com/kairos-io/kairos/actions/workflows/unit-tests.yml

**Comment by mudler** [comment]
This started way back with https://github.com/kairos-io/kairos/pull/963. I think @paynejacob was attempting a fix here: https://github.com/kairos-io/kairos/pull/1068

**Comment by mudler** [comment]
I'll try to have a look
