### ISSUE TITLE
:seedling: Sync the names of the artifacts

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1109]
**Is your feature request related to a problem? Please describe.**
Checking the release there seems to be a difference in the artifacts name that its a bit confusing

All this artifacts are for the same flavor:

core-alpine-ubuntu-v2.0.0-alpha1-grype.json
core-alpine-ubuntu-v2.0.0-alpha1-grype.sarif
core-alpine-ubuntu-v2.0.0-alpha1-sbom.spdx.json
core-alpine-ubuntu-v2.0.0-alpha1-sbom.syft.json
core-alpine-ubuntu-v2.0.0-alpha1-trivy.html
core-alpine-ubuntu-v2.0.0-alpha1-trivy.json
core-alpine-ubuntu-v2.0.0-alpha1-trivy.sarif 
kairos-alpine-ubuntu-v2.0.0-alpha1-initrd
kairos-alpine-ubuntu-v2.0.0-alpha1-ipxe-usb.img.ipxe
kairos-alpine-ubuntu-v2.0.0-alpha1-ipxe.iso.ipxe
kairos-alpine-ubuntu-v2.0.0-alpha1-kernel
kairos-alpine-ubuntu-v2.0.0-alpha1.ipxe
kairos-alpine-ubuntu-v2.0.0-alpha1.iso
kairos-alpine-ubuntu-v2.0.0-alpha1.iso.sha256
kairos-alpine-ubuntu-v2.0.0-alpha1.iso.sha256.pem
kairos-alpine-ubuntu-v2.0.0-alpha1.iso.sha256.sig
kairos-alpine-ubuntu-v2.0.0-alpha1.squashfs 

and its docker repo: https://quay.io/repository/kairos/core-alpine-ubuntu

Meanwhile we also have:
https://quay.io/repository/kairos/kairos-alpine-ubuntu?tab=info

For the provider-kairos.

**Describe the solution you'd like**

Everything to hav ethe same name. Kairos should either output `core-X` or `kairos-X` or even `kairos-core-X`for all its artifacts and sync that with the repo name to avoid confusion.

**Describe alternatives you've considered**

Keep it this way

**Additional context**

**Comment by mauromorales** [comment]
Before I make any changes here, I'd like to start a conversation about the following topics:

## 1 Naming convention we agree on

How about `kairos-type-flavor-arch-device-version.extension` where:

- type can be `core` or `standard`
- arch is `amd64` or `arm64`
- device is `rpi4` or `onix` (this last one will depend on how we decide on support for the RPi but I think it will be worth in the future making the distinction in case there are major changes between a rpi4 and rpi5

## 2 Docker repository

Whatever change we choose, changing the docker repository might be problematic. Do you know if we can do a rename and forward traffic from the old repo to the new one? Or what do you suggest?

Thoughts @kairos-io/maintainers ?

**Comment by Itxaka** [comment]
I'm guessing core is pure Kairos and standard is the one with k3s? Good to me.

For normal non-device artifacts we drop the device or use a generic or something?


For the docker repo...there is a way of renaming things and moving things but it's a pita. But it can be done. Redirecting seems impossible no?  The repo stuff is out of our control. But we can rename it or change the repo and do a clean transition by duplicating the pushes to both repos for x versions and then finally dropping after a while

**Comment by mauromorales** [comment]
Oh BTW we also have `org/repo` and `org/repo-img` for arm

**Comment by jimmykarily** [comment]
I agree on the naming, I don't know about redirections. Itxaka's suggestion on the name migration strategy sounds good.

**Comment by Itxaka** [comment]
> > there is a way of renaming things and moving things but it's a pita
> 
> oki will look into it

IIRC, I did it via skopeo. I first pulled the whole repo into local, write a script to rename the whole thing to the new repo naming and then pushed again to the new one.

Supposedly it could be done with skopeo sync to sync between two repos, but I was never able to do it properly, it always mangled the names :/

**Comment by mauromorales** [comment]
ohh one more thing, we will also want to distinguish between community and supported ones. This is one of the action items on https://github.com/kairos-io/kairos/issues/1527

So maybe something like:

`kairos-support-type-flavor-arch-device-version.extension`

Where:

- kairos: fixed
- support: `official` or `community`
- type:  `core` or `standard` (IMO this should actually be the flavor, but won't start that or it might get messy 😅 )
- flavor: distribution name (IMO should be called distro)
- arch: `amd64` or `arm64`
- device: currently only `rpi64` but we should change this to have `rpi3` (if we decide to keep supporting) `rpi4` and `onix`
- extension: `iso`, `img` etc

**Comment by mudler** [comment]
sounds all good here. Just a note, there are non-obvious places where artifacts are hardcoded, see for e.g. ipxe, or AuroraBoot, or the agent (when finding new images)

**Comment by mauromorales** [comment]
Something that could be beneficial IMO but maybe it's too big of a change now, is to add the underlying distro version. We currently do it only to distinguish Ubuntu "rolling" vs 20-lts and 22-lts, but I think users could benefit from knowing if the underlying distro changed between Kairos releases. For example having `ubuntu-22.10-v2.2.0` vs `ubuntu-23.04-v2.3.0` what do you think? @kairos-io/maintainers

**Comment by jimmykarily** [comment]
ok let's continue on #1694 . Closing this.
