### ISSUE TITLE
🌱 openAMT

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1113]
https://open-amt-cloud-toolkit.github.io/docs/2.8/

## Notes

Bundles documentation: https://kairos.io/docs/advanced/bundles/

## Acceptance Criteria

- There is  way to setup openamt in kairos (a bundle + config?)
- This is documented
- This is not to implement an operator on top of openAMT 
- Probably this should be part of "official" bundles instead of community ones? ( cc @jimmykarily @mudler )

**Comment by paynejacob** [comment]
Initially this was implemented as  a live layer executed as a provider, see pull request discussion for why this was abandoned. 

https://github.com/kairos-io/packages/pull/175

This pr will add the amt provider as a bundle that can be run on installation

https://github.com/kairos-io/community-bundles/pull/40

The binary that interfaces with the amt provider is implemented here.
https://github.com/kairos-io/provider-amt
