### ISSUE TITLE
:seedling: Run `enclave-cc` on Kairos

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1114]
https://github.com/confidential-containers/enclave-cc

## Acceptance criteria
- [ ] We have a documentation page showing how to run confidential workloads on Kairos
- [ ] We have a bundle that sets up enclave-cc and the operator accordingly
- [ ] Have an e2e example to show confidential workloads running on Kairos

Useful docs links:
- https://kairos.io/docs/advanced/bundles/#create-bundles

**Comment by jimmykarily** [comment]
The Pod assumes `dbus` is running on the host: https://github.com/confidential-containers/operator/blob/a0fbbf40ad0848aee6c9ed90fbf7d001e50396c4/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml#L43

which is not the case for the k3d container.

**Comment by mudler** [comment]
I'd suggest to try on a real cluster with kairos and k3s as assumes you have services running, you might hit several limitations along the way with k3d

**Comment by mudler** [comment]
From the script you are linking: https://github.com/confidential-containers/operator/blob/a0fbbf40ad0848aee6c9ed90fbf7d001e50396c4/install/pre-install-payload/scripts/container-engine-for-cc-deploy.sh#LL48C8-L48C36

I'm assuming we should also add that to the persistent path during installation https://kairos.io/docs/advanced/customizing/#bind-mounts

**Comment by jimmykarily** [comment]
I switched to a kairos cluster. This is the next error:

```
│ Copying containerd-for-cc artifacts onto host                                                                                                                                              │
│ Restarting containerd                                                                                                                                                                      │
│ Failed to restart containerd.service: Unit containerd.service not found. 
```

`containerd` based cluster is [in the requirements](https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md#prerequisites)

**Comment by mudler** [comment]
> I switched to a kairos cluster. This is the next error:
> 
> ```
> │ Copying containerd-for-cc artifacts onto host                                                                                                                                              │
> │ Restarting containerd                                                                                                                                                                      │
> │ Failed to restart containerd.service: Unit containerd.service not found. 
> ```
> 
> `containerd` based cluster is [in the requirements](https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md#prerequisites)

K3s is containerd based: https://docs.k3s.io/advanced#using-docker-as-the-container-runtime

**Comment by mudler** [comment]
I think the issue is it tries to restart a service and gives for guaranteed there is one. maybe we can slightly adapt their script to work on k3s?

**Comment by jimmykarily** [comment]
After inspecting how the operator installs the needed binaries, we came up with this plan (cc @mudler ):

- The operator is replacing containerd in a strange way, assuming containerd is managed with systemd (which is not the case in k3s). For that reason, we will replace containerd ouside the cluster in a kairos bundle with one built from their fork: https://github.com/confidential-containers/containerd/tree/CC-main
- Then we also have to install the kata shim (from their fork: https://github.com/confidential-containers/kata-containers-CCv0). There is a daemon set created that runs some scripts that do that. Either we run them or we replicate what they do in a bundle.
- Hopefully, after all these are done, we should be able try a workload as described here: https://github.com/confidential-containers/documentation/blob/main/quickstart.md#running-a-workload (unless there are other steps we missed)

**Comment by jimmykarily** [comment]
There is one part of the k3s containerd config that we copy which makes the custom containerd break:

```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true
```
(if I remove this from `/etc/containerd/config.toml` Pods come up just fine).
When that's in place, Pods refuse to come up with errors like the one described here: https://github.com/containerd/containerd/issues/4857

Some explanation:
- https://github.com/k3s-io/k3s/issues/5738#issuecomment-1158428574
- https://github.com/k3s-io/k3s/blob/9980504196ce0cb53c8e04756598d6f8982a5756/pkg/agent/containerd/config_linux.go#L67

**Comment by jimmykarily** [comment]
@mauromorales let's remember that forcing the systemd cgroup driver might not work on alpine: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#systemd-cgroup-driver

```When [systemd](https://www.freedesktop.org/wiki/Software/systemd/) is chosen as the init system for a Linux distribution, the init process generates and consumes a root control group (cgroup) and acts as a cgroup manager.```

**Comment by jimmykarily** [comment]
Will wait for feedback from the enclave-cc team and if all is ok, will document this and close the issue.
