### ISSUE TITLE
Implementation of secure boot

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1153]
This affects UKI and non-uki.

UKI is basically done. Non-uki is ongoing

**Comment by mudler** [comment]
Blocked by https://github.com/kairos-io/kairos/issues/868

**Comment by jimmykarily** [comment]
The merged PR fixes secure boot for all non-uki flavors except Alpine.
Let's keep this open for fix secure boot with uki. Despite what the description above says, secureboot with uki doesn't work (at least without importing any keys to UEFI). If it's working by importing our keys, then let's close this after trying it out first.

**Comment by jimmykarily** [comment]
I added the "documentation" label and I'm keeping this open until this is documented.

**Comment by Itxaka** [comment]
Needs a secureboot part on docs where we explain how we are using the upstream artifacts for secureboot

Needs a UKI section. Like a full section explaining the whole thing.

**Comment by Itxaka** [comment]
UKI section of this is being done as part of https://github.com/kairos-io/kairos-docs/pull/133

**Comment by Itxaka** [comment]
secureboot docs at https://github.com/kairos-io/kairos-docs/pull/135
