### ISSUE TITLE
:seedling: run `kcrypt` from immucore

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1155]
**Is your feature request related to a problem? Please describe.**
Currently `kcrypt` runs as a dracut module

**Describe the solution you'd like**
`kcrypt` to run inside immucore:

- can be as a cloud-config `rootfs` stage
- directly included as a library and called in the immucore stages

**Describe alternatives you've considered**
Keep the dracut module around

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kcrypt/pull/17
https://github.com/kairos-io/immucore/pull/118

Merged and updated. Will be in next kairos release
