### ISSUE TITLE
:lock_with_ink_pen: spike: Avoid storing partition data into `/oem`

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1156]
**Is your feature request related to a problem? Please describe.**
We currently store the UUID mapping to the fs label into the /oem partition and the information to talk back to the KMS.
part of this can be stabbed in the cmdline, but SSL certificates can not (? or just not practical). 

**Describe the solution you'd like**
 - have a _separate_ partition for the encryption settings
 - can we reuse the EFI partition to store only the KMS/encryption data mappings?

**Describe alternatives you've considered**

**Additional context**

**Comment by mudler** [comment]
still relevant as today

**Comment by Itxaka** [comment]
ummm, I think we got over this by using pre-defined uuid for partitions at install time and decrypt time, so we dont have the info anymore, do we?

**Comment by Itxaka** [comment]
Yes, this is there since v0.6.0 https://github.com/kairos-io/kcrypt/pull/17
