### ISSUE TITLE
:art: introduce a standard logging library

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1188]
This library must know about soft errors and verbosity according to the user choices e.g. No Logs, Strict validation, etc

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kairos/issues/682

Closing that in favour of this.


Currently we have:
  - elemental-cli: logrus + custom implementation
  - yip: logrus
  - immucore: zerolog


No idea of other parts.

**Comment by jimmykarily** [comment]
Golang 1.21 introduced this: https://pkg.go.dev/log/slog
Let's check it out too.

**Comment by mauromorales** [comment]
@jimmykarily might be problematic with our FIPS packages though since they are fixed to 1.19

**Comment by jimmykarily** [comment]
Now we have this: https://github.com/kairos-io/kairos-sdk/blob/66ee3cb60f50d53cc3c6a38acee4b9554dbc8100/types/logger.go#L80 and it's used in various places. @Itxaka @mauromorales should we close this ticket?

**Comment by Itxaka** [comment]
I would say so, it's now a matter of implementation everywhere like the provider which still logs to whatever weird place it wants
