### ISSUE TITLE
:lock:  Offline encryption with static measured boot

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#119]
This is an epic card to track integration of full disk encryption (FDE) with FIDO and TPM.

- Explore FDE in c3os design

This is to prevent senarios like:

- One (with physical access to a machine), manages to boot another OS (e.g. by plugging a usb stick) and tries to decrypt the encrypt partition by asking the TPM for the passphrase.
- One manages to disable the static measurements and successfully boot a tampered version of the original OS, trying to achieve the same thing as above

The goal of this story, is to make sure none of these is possible. It shouldn't be possible to get the passphrase for decryption, unless the OS that is currently booted, is not tampered.

**Comment by mudler** [comment]
As we do have already support for disk encryption, the scope of this card changed slightly, now we just look to support offline encryption with static measured boot.

**Comment by mudler** [comment]
Blocked by #873 #872

**Comment by jimmykarily** [comment]
This is done
