### ISSUE TITLE
upgrade golang version for build time

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1199]
Let's bump to golang 1.20.2

Components:

- [x] https://github.com/kairos-io/kairos/pull/1213
- [x] https://github.com/kairos-io/provider-kairos/pull/299
- [x] https://github.com/kairos-io/kcrypt-challenger/pull/13
- [x]  https://github.com/kairos-io/kcrypt/pull/15
- [x] elemental-cli (needs bump from packages)
- [x] https://github.com/kairos-io/immucore/pull/107
- [x] https://github.com/kairos-io/packages/pull/162

 ( and maybe others?)

**Comment by Itxaka** [comment]
- https://github.com/kairos-io/immucore/pull/107
 - https://github.com/kairos-io/packages/pull/162

**Comment by mauromorales** [comment]
@Itxaka I think https://github.com/kairos-io/elemental-cli is already on 1.20, so we can scratch that out. Can you confirm?

**Comment by Itxaka** [comment]
@mauromorales Indeed! But the package being used on kairos is not, its part of the https://github.com/kairos-io/packages/pull/162 PR, a bit confusing :D
