### ISSUE TITLE
Fix CI and release 2.0.0-alpha3

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1200]

**Comment by Itxaka** [comment]
one of the problems is oepnsuse-leap not finding mkinitrd (its now deprecated in favour of dracut)

Im trying to fix it as part of https://github.com/kairos-io/kairos/pull/1194

**Comment by Itxaka** [comment]
Oh, I'm dumb. I added "partially fixes" to the pr and that auto closed this, good catch @mauromorales

**Comment by Itxaka** [comment]
all fixes are done:
 - https://github.com/kairos-io/kairos/pull/1205
 - https://github.com/kairos-io/kairos/pull/1203
 - https://github.com/kairos-io/kairos/pull/1194

Pushing alpha3!

**Comment by Itxaka** [comment]
alpha3 cut

**Comment by mudler** [comment]
After we have it green we need to sync the provider repo too

**Comment by mudler** [comment]
well... 2.0 is targeted for end of month, so this is more like a RC than at alpha as for now :)

**Comment by mudler** [comment]
Let's close this once we have the alpha in and have a new one for the RC, I didn't noticed the release I'm between.

**Comment by Itxaka** [comment]
small hiccup with the arm img pushing as the creds are probably not valid for those repos so it could not push the images:https://github.com/kairos-io/kairos/actions/runs/4551323808

**Comment by Itxaka** [comment]
All stuff done, release...uh...released. Closing!
