### ISSUE TITLE
Move elemental-cli to kairos as a `pkg` and archive the repo

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1210]
Plan:

-We will create a new binary called kairos-register which is the only thing the user should ever have to install on their workstation. It’s the binary that will be used to register a node (e.g. using QR code). `kairos-agent` will become simply `kairos` with all the subcommands it currently has plus the functionality that will be moved from elemental-cli. Additionally, it’s going to have a new `lifecycle` subcommand which is going to be what elemental-cli used to be (just the low level functionality). Optionally we could have a check, when the user runs this `kairos` binary outside a Kairos OS, it should print a warning and wait for confirmation. The elemental-cli code will be moved to a `pkg` in the `kairos` repository.

## Acceptance Criteria

- kairos-agent becomes `kairos`
- elemental-cli repo is archived
- new `kairos` binary has a `lifecycle` subommand that does what `elemental-cli` used to do
- The `elemental-cli` repo tests are now part of the `kairos` repo and they run when they have to run

[Optional - maybe move to other issues]

- move non-low-level functionality from `lifecycle` to top level `kairos` command
- show a warning when `kairos` binary is executed outside a Kairos OS

**Comment by Itxaka** [comment]
I do not remember this, but having it separated would be nicer? Wasnt that the point of trying to extract the sdk stuff so we dont:
 - rebuild the whole kairos on sdk changes
 - keep OS code and tools code in the same repo
 - have everything installed in the OS by luet packages


I think we need to rediscuss this becuase otherwise I dont think its the best way forward.

**Comment by Itxaka** [comment]
No longer blocked!

**Comment by jimmykarily** [comment]
These are the current elemental-cli commands:

```
  build-disk   Build a raw recovery image
  build-iso    Build bootable installation media ISOs
  cloud-init   Run cloud-init
  completion   Generate the autocompletion script for the specified shell
  convert-disk converts between a raw disk and a cloud operator disk image (azure,gce)
  help         Help about any command
  install      Elemental installer
  pull-image   Pull remote image to local file
  reset        Reset OS
  run-stage    Run stage from cloud-init
  upgrade      Upgrade the system
  version      Print the version
```

These are the ones I think belong to the kairos-agent lifecycle command:

```
  cloud-init   Run cloud-init
  install      Elemental installer
  pull-image   Pull remote image to local file
  reset        Reset OS
  run-stage    Run stage from cloud-init
  upgrade      Upgrade the system
```

@Itxaka do you agree?

**Comment by Itxaka** [comment]
@jimmykarily agreed. In fact cloud-init can also be dropped as I don't think it's used anywhere, only the run-stage 


Alós there is a PR for this already but needs manual QA

**Comment by jimmykarily** [comment]
Thanks @Itxaka, I linked the issue with the PR now. Please remember to update issues when you work on them to avoid other people working on the same things.

**Comment by Itxaka** [comment]
Sorry! Was gonna do it tonight but forgot that it's a local holiday and you folks are working 😂

**Comment by Itxaka** [comment]
libs merged, needs maybe the pull-image command to be exposed, but install/upgrade/reset are hooked to the old agent commands
