### ISSUE TITLE
:sparkles: Use config/collector on kairos-agent ex-elemental commands

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1225]
There was recently a refactoring of the config pkg to have a more generic way to collect the different config files. This allows us to split the responsibilities of the config between Kairos specific (config pkg) and non specific (collector pkg). In the case of the commands that were transferred from elemental-cli we want to use the generic configuration.

see: https://github.com/kairos-io/kairos/issues/391#issuecomment-1453787451

> User has to copy this file inside /oem because elemental will try to find stage steps there. Won't repect it here. Then the user has to install with `kairos-agent manual-install` with this file. Netbooting doesn't work for the same reason (elemental ignores the stages)

## Acceptance criteria

- the collector package is used for everything that needs to read cloud-config files
- `after-install` hooks defined in the user config.yaml are picked up by kairos-agent and work

**Comment by jimmykarily** [comment]
https://github.com/kairos-io/elemental-cli/tree/1225-use-collector-for-config

**Comment by jimmykarily** [comment]
Let' redefine this when this one is done: https://github.com/kairos-io/kairos/issues/1210
The "lifecycle" functionality will be part of kairos-agent so there will be no elemental-cli anymore.

**Comment by jimmykarily** [comment]
The `after-install` hooks should work now but there is a refactoring pending to consolidate all those "configs" (see discussion on the PR). I'll keep this open to redefine in planning or create a new card.

**Comment by Itxaka** [comment]
I think this has been solved or there is not much reason to exists.
