### ISSUE TITLE
:bug: :robot: Sbom is not being attached

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1228]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
sbom is supposed to be attached but a wrong flag in the sbom attachment command is breaking it

**To Reproduce**
check ci

https://github.com/kairos-io/kairos/actions/runs/4567186343/jobs/8060675440
https://github.com/kairos-io/kairos/actions/runs/4567186343/jobs/8060674917
etc...

**Expected behavior**

**Logs**

**Additional context**
probably `--output` was a valid flag on cosign 1.x but not on 2.x

**Comment by mudler** [comment]
you are so ff fast :D

**Comment by mudler** [comment]
temporarly reverted to avoid having a red master blocking us https://github.com/kairos-io/kairos/pull/1229

**Comment by Itxaka** [comment]
> temporarly reverted to avoid having a red master blocking us #1229

it only really blocks the sbom and testing images on master. Images are still pushed :P
