### ISSUE TITLE
:robot: CI fails pushing ARM images

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1270]
**Kairos version:**
2.0.0-rc5

The provider-kairos repository release seems to fail pushing arm images: https://github.com/kairos-io/provider-kairos/actions/runs/4638238521

Meanwhile, the core repository just builds and release fine: https://github.com/kairos-io/kairos/actions/runs/4630836751/jobs/8204438626

**Comment by Itxaka** [comment]
and was part of the 2.0.0 release: https://github.com/kairos-io/provider-kairos/actions/runs/4691127690
