### ISSUE TITLE
:bug: :hedgehog:  Cloud images mounting oem on recovery

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1276]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
when creating a raw/cloud image, docs show an example of a cloud config that will partition the disk, reset the system and then reboot, so you get a final system installed (cloud images only have the recovery partition on them)
But this is not happening, system gets to login but nothing is run.

**To Reproduce**
create a raw/cloud image and boot it

**Expected behavior**
image boots, system is partitioned and reset is called, then rebooted to the final working system

**Logs**

**Additional context**

reported via slack

**Comment by mudler** [comment]
I think nothing actually forbids to use the initramfs stage there, however, worth checking

**Comment by Itxaka** [comment]
welp. Problem is:

 - cos-immutable-rootfs used to generate a oem.mount file on dracut system init to mount the oem partition
 - then it would unmount it before mounting the final filesystem
 - immucore no longer generates that oem mount as it mounts everything during its workflow
 - on squashfs recovery, immucore does nothing as the dracut dmsquashfs module is the one that mounts any squashfs filesystems


Solution:
 - if we are on recovery, try to mount oem before running the stages

**Comment by Itxaka** [comment]
May be fixed by https://github.com/kairos-io/immucore/pull/110 pending further testing

**Comment by Itxaka** [comment]
2.0.0-rc6 was released with a fix for this!
