### ISSUE TITLE
:bug: config get fails to fetch deep nested keys

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1297]
see https://github.com/kairos-io/kairos/blob/master/pkg/config/collector/collector_test.go#L439

When having a config like:

```
foo:
  bar:
    baz: 123
```

It should be possible to retrieve the value of baz doing `get config foo.bar.baz` without errors

**Comment by mudler** [comment]
ouch, good catch. this might be really impactful on bundles !
