### ISSUE TITLE
:bug: v2.0.0 does not boot anymore on rpi 

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#1300]
**Kairos version:**

kairos-opensuse-leap-arm-rpi:v2.0.0-k3sv1.26.3-k3s1
**CPU architecture, OS, and Version:**

**Describe the bug**

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1231174/232063923-96cfbdaa-3885-4507-af70-473e21233208.png">
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1231174/232064447-5c9a891b-c0d5-4d9f-b361-c4e10daaea3c.png">

build with:
```
docker run -v $PWD:/HERE -v /var/run/docker.sock:/var/run/docker.sock --privileged -i --rm --entrypoint=/build-arm-image.sh quay.io/kairos/osbuilder-tools:latest \
 --model rpi64 \
 --local \
 --config /HERE/cloud-config.yaml \
 --efi-dir /HERE/boot \
 --docker-image kairos-rpi-ogi /HERE/build/out.img
```

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
umm...


```
$ docker run --platform=arm64 -it --rm quay.io/kairos/kairos-opensuse-leap-arm-rpi:v2.0.0-k3sv1.26.3-k3s1 ls -ltra /boot
total 55580
-rw-r--r--. 1 root root     1725 Jun  1  2022 boot.readme
drwxr-xr-x. 1 root root        0 Mar 17 15:49 grub2
-rw-r--r--. 1 root root   287288 Mar 28 15:18 config-5.14.21-150400.24.55-default
-rw-r--r--. 1 root root  5896900 Mar 28 17:38 System.map-5.14.21-150400.24.55-default
-rw-r--r--. 1 root root      377 Mar 28 18:04 sysctl.conf-5.14.21-150400.24.55-default
-rw-r--r--. 1 root root   475304 Mar 28 18:04 symvers-5.14.21-150400.24.55-default.gz
-rw-r--r--. 1 root root 13637359 Mar 28 18:15 vmlinux-5.14.21-150400.24.55-default.gz
-rw-r--r--. 1 root root 36579840 Mar 28 19:45 Image-5.14.21-150400.24.55-default
-rw-r--r--. 1 root root       65 Mar 28 19:45 .Image-5.14.21-150400.24.55-default.hmac
drwxr-xr-x. 1 root root      796 Apr 13 11:56 vc
lrwxrwxrwx. 1 root root       35 Apr 13 11:59 initrd -> initrd-5.14.21-150400.24.55-default
lrwxrwxrwx. 1 root root       34 Apr 13 11:59 Image -> Image-5.14.21-150400.24.55-default
lrwxrwxrwx. 1 root root        5 Apr 13 12:17 vmlinuz -> Image
drwxr-xr-x. 1 root root      604 Apr 13 12:17 .
drwxr-xr-x. 1 root root      168 Apr 17 07:48 ..

```

**Comment by Itxaka** [comment]
Looks like it may be an immucore bug then? as the /boot/initrd is there. But it doesnt look nice...

@Ognian you mention that you are using `kairos-opensuse-leap-arm-rpi:v2.0.0-k3sv1.26.3-k3s1` but on your build command there is a mention of `kairos-rpi-ogi` instead?  

also are you able to set a `rd.immucore.debug` and `rd.shell` so it can drop you into the dracut emergency shell adn then you can maybe extract the /run/immucore/* logs?

**Comment by Itxaka** [comment]
wrongly skipped the arm-rpi flavors from generating the mkinitrd in https://github.com/kairos-io/kairos/commit/dfa93054e7420d4ae4b98956e2013252393eae64

**Comment by Itxaka** [comment]
Reopened until confirmation

**Comment by mauromorales** [comment]
I just tested it and can confirm it's booting properly

**Comment by Itxaka** [comment]
Thanks @mauromorales !

**Comment by mudler** [comment]
Thanks @Ognian for the feedback, that was a really good catch!

And of course thanks to @Itxaka and @mauromorales for the quick fix and test, you were super-fast!
