### ISSUE TITLE
:bug: `kairos-agent upgrade` is wrong

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1320]
**Kairos version:**
```
kairos-LVM:~ # cat /etc/os-release 
NAME="kairos-core-opensuse-leap"
VERSION="v2.0.0-28-g434edb5-dirty"
ID="kairos"
ID_LIKE="kairos-core-opensuse-leap"
VERSION_ID="v2.0.0-28-g434edb5-dirty"
PRETTY_NAME="kairos-core-opensuse-leap v2.0.0-28-g434edb5-dirty"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
HOME_URL="https://github.com/kairos-io/kairos"
IMAGE_REPO="quay.io/kairos/core-opensuse-leap"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/kairos"
VARIANT="core"
```

**CPU architecture, OS, and Version:**
```
Linux kairos-LVM 5.14.21-150500.48-default #1 SMP PREEMPT_DYNAMIC Thu Apr 6 08:23:23 UTC 2023 (50e397b) x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**
running `kairos-agent upgrade` results in the agent suggesting to use version v1.0.0 as latest.

**To Reproduce**
```
kairos-LVM:~ # kairos-agent upgrade
Latest release is v1.0.0
Are you sure you want to upgrade to this release? (y/n) n
```

**Expected behavior**
running `kairos-agent upgrade` suggest the real latest version (i.e. v2.0.0 in this particular case?

**Logs**

**Additional context**

**Comment by mudler** [comment]
this should be an easy fix and possibly go in the next patch release

**Comment by mauromorales** [comment]
>  running kairos-agent upgrade suggest the real latest version (i.e. v2.0.0 in this particular case?

There's no later release in this case IMO. Since you're already running v2.0. Instead, it should show a message saying it's running latest already.

How does it look if executed from v1.6?

**Comment by Itxaka** [comment]
> > running kairos-agent upgrade suggest the real latest version (i.e. v2.0.0 in this particular case?
> 
> There's no later release in this case IMO. Since you're already running v2.0. Instead, it should show a message saying it's running latest already.
> 
> How does it look if executed from v1.6?

well, I guess because Im using a non-final 2.0.0 it may be confused? In any case, if it has to suggest the latest, it would still need to suggest 2.0.0 instead of 1.0.0 :D

**Comment by mauromorales** [comment]
So this would be the expected behaviour?

- v2.0-asdfasdf -> suggest v2.0
- v2.0 -> message saying there's nothing newer
- anything else -> suggest v2.0

**Comment by Itxaka** [comment]
> So this would be the expected behaviour?
> 
> - v2.0-asdfasdf -> suggest v2.0
> - v2.0 -> message saying there's nothing newer
> - anything else -> suggest v2.0

Yep, I guess that would be the expected outcome, so if you are on an rcX it would get you upgrade to the final version.
