### ISSUE TITLE
Kairos derivative images start all services when missing machine-id file

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/kairos#1355]
**Kairos version:**
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
KAIROS_NAME="kairos-core-ubuntu-20-lts"
KAIROS_VERSION="v2.0.2"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-core-ubuntu-20-lts"
KAIROS_VERSION_ID="v2.0.2"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-20-lts v2.0.2"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/core-ubuntu-20-lts"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VARIANT="core"
```

**CPU architecture, OS, and Version:**
`Linux localhost 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
**Describe the bug**
We built a derivative image from base kairos images and remove the machine-id file, and build iso , we see all the kairos services start - kairos-interactive kairos-reset kairos-install. 

**To Reproduce**
create a dockerfile with below contents
```
FROM quay.io/kairos/core-ubuntu-20-lts:v2.0.2
RUN apt-get clean && rm -rf /var/cache/* && rm -rf /etc/machine-id && rm -rf /var/lib/dbus/machine-id && rm -rf /etc/hostname
```
Build iso e.g
`quay.io/kairos/osbuilder-tools:v0.6.1 --name spectro-edge-installer-ubuntu-20 --debug build-iso --squash-no-compression --date=false docker:gcr.io/spectro-dev-public/palette/edge/capv-kairos-ubuntu-20/spectro-edge-installer-ubuntu-20:0.0.0-97a0c337 --local --overlay-iso /cOS/overlay/files-iso --output /cOS/`

Boot the iso into manual mode 
We can see all the services start and the system enters interactive mode
```
pr 24 20:18:50 localhost systemd[1]: Starting Remove Stale Online ext4 Metadata Check Snapshots...
Apr 24 20:18:50 localhost systemd[1]: Condition check resulted in getty on tty2-tty6 if dbus and logind are not available being skipped.
Apr 24 20:18:50 localhost systemd[1]: Condition check resulted in Record successful boot for GRUB being skipped.
Apr 24 20:18:50 localhost systemd[1]: Condition check resulted in GRUB failed boot detection being skipped.
Apr 24 20:18:50 localhost systemd[1]: Starting kairos interactive-installer...
Apr 24 20:18:50 localhost systemd[1]: Starting kairos recovery...
Apr 24 20:18:50 localhost systemd[1]: Starting kairos reset...
Apr 24 20:18:50 localhost systemd[1]: Started kairos installer.
Apr 24 20:18:50 localhost systemd[1]: Starting kairos installer...
```

As a workaround, adding this line to the dockerfile and rebuilding fixes the issue
`RUN touch /etc/machine-id && chmod 444 /etc/machine-id
`
**Expected behavior**
Booting iso in manual mode should enter autologin prompt.

**Logs**
journal log with systemd debug and dracut debug attached
**Additional context**

[out.log](https://github.com/kairos-io/kairos/files/11324712/out.log)

**Comment by Itxaka** [comment]
weird, according to [this](https://www.freedesktop.org/software/systemd/man/machine-id.html#First%20Boot%20Semantics) if it cant find the file it will treat it as a first boot and bind mount a temporary file and generate a machine id. So even if its not there, it should bind mount that file.


@venkatnsrinivasan why are you folks removing the machine-id file? Why not truncate it? There may be issues with systemd trying to bind mount into a RO dir, but not sure what you gain by removing that.

**Comment by Itxaka** [comment]
> @Itxaka we can truncate. We were removing it because 
> - In general habit we have done this before when building golden VM images and didn't cause any issues
> - The kairos base image Dockerfile definitions do the same - https://github.com/kairos-io/kairos/blob/master/images/Dockerfile.ubuntu-22-lts#L94
> - - This, was fine in v1.5.0 of kairos and didnt cause any issues .We observe this once we moved to 2.0.x
> 
> The machine-id file does get generated even when we move it. In this particular issue, it seems some timing is going on where that additional time to generate causes other things do weird things , but i am not sure. 

Indeed base dockerfile does, but when building the real image and/or framework, we regenerate and touch an empty machine-id file, I'm guessing there were some issues with no having the file and it was decided to touch it so nothing fails.

Notice that the immutability changed a lot between 1.5 and 2.0, it's now done even earlier in the boot process so it might contribute to having this issues now.

We don't recommend removing the machine-id manually. In systemd based os, systemd will fill it properly if needed and only when it boots in a system, not when running as a container, so there should be no issue in leaving the file alone.


I will revisit the base dockerfiles tomorrow as I'm not sure we should be deleting in in there either.

**Comment by venkatnsrinivasan** [comment]
Sure , we will leave it truncated. Just the behaviour is different in Kairos 1.5 vs 2.0 which is what we observed now even though the systemd hasnt changed.

**Comment by jimmykarily** [comment]
@Itxaka if the file shouldn't be deleted, then there is nothing to do. Free free to close this issue.
