### ISSUE TITLE
:bug: :hedgehog: RW doesnt work as expected

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1377]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
when setting `rd.immucore.debugrw` I expect the root FS to be set in RW mode
Currently this doesnt work. COS_STATE is mounted in RW, loop device is mounted in RW but / is mounted RO

**To Reproduce**
add `rd.immucore.debugrw` to the cmdline, try to create a dir in root

**Expected behavior**
Mounts / in RW

**Logs**
```
INF luetbuild/go/src/github.com/kairos-io/immucore/pkg/mount/state.go:177 > mount done options=["rw","suid","dev","exec","async"] type=ext4 what=/dev/disk/by-label/COS_ACTIVE where=/sysroot
```

**Additional context**
The / mount is missing from the /etc/fstab
Maybe this could lead to it being remounted with RO as there is no entry for it.
Entry should be added, not sure why its not, maybe the cleanup function is messing with it? https://github.com/kairos-io/immucore/blob/master/internal/utils/mounts.go#L118

**Comment by Itxaka** [comment]
Workaround is to boot with `rd.immucore.debugrw` and once its booted do a `mount -o remount,rw /` to remount root as RW

**Comment by Itxaka** [comment]
https://github.com/kairos-io/immucore/releases/tag/v0.0.21 should fix this issue, manually tested

**Comment by jimmykarily** [comment]
Package have been bumped, this should be in the next release.
