### ISSUE TITLE
machine-id is not persisted across reboots.

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/kairos#1381]
**Kairos version:**
```

cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
KAIROS_NAME="kairos-core-ubuntu-22-lts"
KAIROS_VERSION="v2.0.3"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-core-ubuntu-22-lts"
KAIROS_VERSION_ID="v2.0.3"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-22-lts v2.0.3"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/core-ubuntu-22-lts"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VARIANT="core"
KAIROS_FLAVOR="ubuntu-22-lts"
```

**CPU architecture, OS, and Version:**
`Linux localhost 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Describe the bug**
The kairos base images have an empty /etc/machine-id file. On bootup a new machine id gets generated by the OS but this does not get copied over to /usr/local/etc/machine-id as desired and defined here https://github.com/kairos-io/kairos/blob/master/overlay/files/system/oem/00_rootfs.yaml#L38  probably because the copying happens much earlier than when the OS generates the machine-id
As a result,  new machine-id is generated on every reboot and /usr/local/etc/machine-id is always empty.  This causes sideeffects like the DHCP ip's changing .

**To Reproduce**
Boot ISO kairos-ubuntu-22-lts-v2.0.3.iso  and install the OS to the disk .
Reboot after the installation a few times and check /etc/machine-id. It will be different everytime. 
**Expected behavior**
machine-id should be persistent for the lifetime of the machine.

**Comment by santhoshdaivajna** [comment]
```
root@metal-san-1:~# ls -l /etc/machine-id
-r--r--r-- 1 root root 33 May  5 19:31 /etc/machine-id
root@metal-san-1:~# cat /etc/machine-id
681330fe61d34891866a903841aa03ee
root@metal-san-1:~# cat /usr/local/etc/machine-id
root@metal-san-1:~# ls -l /usr/local/etc/machine-id
-r--r--r-- 1 root root 0 May  5 19:31 /usr/local/etc/machine-id
root@metal-san-1:~#
```
