### ISSUE TITLE
Copy over kcrypt-challenger tests to kairos-io/kairos

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1383]
To be able to catch issues that occur due to changes in other repos, we should try the encryption tests in kairos-io/kairos

Let's copy the tests over to kairos-io/kairos but keep them also in the challenger repo.
Alternatively, just run the tests from challenger (without copying them) but with and ISO built from kairos-io/kairos (if that's possible, to avoid duplication).

**Comment by Itxaka** [comment]
Makes more sense to have them on kairos and keep unit test or basic end2end test on the challenger repo
