### ISSUE TITLE
support for NVIDIA Jetson AGX Orin (Developer Kit)

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1395]
**Is your feature request related to a problem? Please describe.**
A tracker issue for Nvidia jetson AGX Orin support

## Action items
- [x] #1440 
- [ ] QA: Try upgrades
- [ ] Create equivalent image in provider-kairos
- [ ] https://github.com/kairos-io/kairos-docs/pull/29
- [ ] See what we can do about resets https://github.com/kairos-io/kairos/issues/622

**Comment by jimmykarily** [comment]
It works and we have docs. Let's close this.
