### ISSUE TITLE
webui doesn't render properly

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1404]
![Image](https://github.com/kairos-io/kairos/assets/2794419/2e9a98ca-e982-478a-91ce-42a7a3483562)

Using a latest build from kairos master the webui doesn't render fully and there is no validation (reported on Slack:
```
 ...the WebUI which does not render properly, although you can still paste the cloud-init-config (no validation) and it stops working during the install...
```

**Comment by Itxaka** [comment]
patch linked fixed this and adds the missing docs. Validation not checked yet.

**Comment by Itxaka** [comment]
validation seems to work as expected
