### ISSUE TITLE
:sparkles: Introduce "metapackage" that different releases can reference to in framework profile

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1408]
The information in the framework-profile.yaml is quite redundant and prone to ending up with unintended slight differences between systems.

One idea to fix this problem could be to have some sort of metapackages for example

> see how you mark here `systemd-base` and then below you can see that it contains 2 packages: `init-svc/systemd` and `systemd-default/network` ? So Im thinking that we may need to just merge more of the stuff seeing that there is a clear repetition here with systemd-base and dracut-network-legacy*

> so something similar to those, like ubuntu-base that includes all those packages, or something shared that includes all of that so its a one line for all. Dont know how, just thinking out loud seeing that this keeps frowing and lines repeating :D

_Originally posted by @Itxaka in https://github.com/kairos-io/kairos/pull/1170#discussion_r1192260038_

**Comment by Itxaka** [comment]
Mainly due to all the flavors that just share the same packages, it should be nicer to have for example a package that includes the same packages for all those flavors and just refer to that in the framework profile

**Comment by Itxaka** [comment]
this is no longer valid!
