### ISSUE TITLE
kairos-opensuse-leap-arm-rpi last working version was v1.6.1

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#1435]
After #1342 is now resolved and there is a provider-kairos version build, `kairos/kairos-opensuse-leap-arm-rpi:v2.1.0-k3sv1.26.4-k3s1` boots but is not pingable since there is no network stack started...
Any quick ideas what could have changed before starting to dig deeper

**Comment by Itxaka** [comment]
> After #1342 is now resolved and there is a provider-kairos version build, `kairos/kairos-opensuse-leap-arm-rpi:v2.1.0-k3sv1.26.4-k3s1` boots but is not pingable since there is no network stack started... Any quick ideas what could have changed before starting to dig deeper

@Ognian we moved rpi images (core) to use lvm by default which means that now they all should have an OEM partition. provider-kairos images havent been updated to enable the lvm by default as well, so on boot there is no OEM and we rely on that for several things. If they are not there, the boot process kind of break completely.

This will make the default images all use lvm so there is oem in all the arm devices: https://github.com/kairos-io/osbuilder/pull/54

This updated the instructions you you can build an image based on kairos and enable lvm: https://github.com/kairos-io/kairos-docs/pull/21 and  https://kairos.io/docs/installation/raspberry/#customizing-the-disk-image

**Comment by mauromorales** [comment]
Merged the fix, should be included in next release

**Comment by jimmykarily** [comment]
ok I'm closing. @Ognian if you still encounter issues, please re-open.
