### ISSUE TITLE
Ubuntu standard images for RPi are missing

### ISSUE THREAD

**Issue by zewelor** [kairos-io/kairos#1439]
Hi

I'm interested in testing kairos in my k8s setup using rpi. I saw ubuntu version of kairos is now merged here: https://github.com/kairos-io/kairos/pull/1170 . How can I get rpi image for ubuntu with k3s ? I don't see it in release assets. I need to build it manually or other way ?

**Comment by zewelor** [comment]
I see, thank you for such detailed information.

**Comment by mauromorales** [comment]
core 2.2.0 images released and available ... just waiting on provider release now

**Comment by zewelor** [comment]
Looks like with version 2.2.1 they are already provided. Closing now
