### ISSUE TITLE
Support for Ubuntu 22.04  LTS

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/kairos#150]
Addtional flavor based on Ubuntu 22.04

**Comment by mudler** [comment]
20.04 is already there? or am I missing something?

**Comment by venkatnsrinivasan** [comment]
Yes 20.04 is there. I meant need to support both versions together  instead of an upgrade.

**Comment by mudler** [comment]
> Yes 20.04 is there. I meant need to support both versions together  instead of an upgrade.

Can you expand a bit?

**Comment by venkatnsrinivasan** [comment]
> > Yes 20.04 is there. I meant need to support both versions together  instead of an upgrade.
> 
> Can you expand a bit?

Sure. Currently we have core-ubuntu images which are based off ubuntu 20.04. We likely will need to version core images based of ubuntu versions e.g. core-ubuntu-20 and core-ubuntu-22 as different customers need different versions of the LTS.

**Comment by mudler** [comment]
Updated the card

**Comment by mudler** [comment]
I'd suggest then to move to use `lts` in the flavor name:

- ubuntu 22.04 as `quay.io/kairos/core-ubuntu-22-lts`
- ubuntu 20.04  as `quay.io/kairos/core-ubuntu-20-lts`
- ubuntu latest as `quay.io/kairos/core-ubuntu`

**Comment by venkatnsrinivasan** [comment]
This looks good to me.
