### ISSUE TITLE
:bug: Disable unnatended-upgrades service under ubuntu flavors

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1512]
**Kairos version:**
master ubuntu

**CPU architecture, OS, and Version:**
all

**Describe the bug**
looks like the service for unnatended upgrades is enabled automatically under ubuntu, which makes no sense for kairos

**To Reproduce**
run ubuntu, wait for the service to kick in (its on a timer probably?)

**Expected behavior**
its disabled by default

**Logs**

**Additional context**

**Comment by areitz86** [comment]
First draft: https://github.com/kairos-io/kairos/pull/1513

**Comment by mudler** [comment]
merged, thanks @areitz86 !
