### ISSUE TITLE
Typo in docs for Orin install instructions from custom container image

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/kairos#1515]
In the docs here
https://kairos.io/docs/installation/nvidia_agx_orin/

if you are customizing the image, or either modifying the default partition sizes you can build the images by running:
```

IMAGE=quay.io/kairos/core-ubuntu-20-lts-arm-nvidia-jetson-agx-orin:latest
docker run --privileged \
        -e **container**=$IMAGE \
        -e STATE_SIZE="6200" \
        -e RECOVERY_SIZE="4200" \
        -e DEFAULT_ACTIVE_SIZE="2000" \
        -v $PWD/bootloader:/bootloader --entrypoint /prepare_arm_images.sh -ti --rm quay.io/kairos/osbuilder-tools
```
should be

f you are customizing the image, or either modifying the default partition sizes you can build the images by running:

```
IMAGE=quay.io/kairos/core-ubuntu-20-lts-arm-nvidia-jetson-agx-orin:latest
docker run --privileged \
        -e **container_image**=$IMAGE \
        -e STATE_SIZE="6200" \
        -e RECOVERY_SIZE="4200" \
        -e DEFAULT_ACTIVE_SIZE="2000" \
        -v $PWD/bootloader:/bootloader --entrypoint /prepare_arm_images.sh -ti --rm quay.io/kairos/osbuilder-tools
```

**Comment by mudler** [comment]
@venkatnsrinivasan why not opening up a PR instead? :)  there is an edit button in the docs that should do the trick

**Comment by venkatnsrinivasan** [comment]
Yeah , sorry , didnt see the edit option on the docs page.  Was going to open PR on this ticket once i finished all the steps with the docs today to see if there are any other gotchas.

**Comment by mudler** [comment]
> Yeah , sorry , didnt see the edit option on the docs page.  Was going to open PR on this ticket once i finished all the steps with the docs today to see if there are any other gotchas.

No worries PR is there already :)
