### ISSUE TITLE
:bug: provider-kairos released binaries have the worng name

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1520]
**Kairos version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

see https://github.com/kairos-io/provider-kairos/releases

Looks like something is missing from the naming template or maybe the templating has stopped working

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by jimmykarily** [comment]
<img width="704" alt="image" src="https://github.com/kairos-io/kairos/assets/2794419/23c3cc48-0a75-41df-8c5d-6ed660b152cd">

**Comment by jimmykarily** [comment]
Docs: https://goreleaser.com/customization/archive/?h=name_template
