### ISSUE TITLE
Debug failed test

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1526]
There is a test that fails consistently in CI:

https://github.com/kairos-io/kairos/actions/runs/5291512748/jobs/9577776783#step:7:1

Let's try to reproduce manually and check if there is really something broken or if the tests need fixing.

**Comment by jimmykarily** [comment]
I think somehow /tmp/xxxx4001315653 is a directory and not a cloud config file, thus the error:

```
       +run-qemu-test |   INFO[2023-06-16T16:48:31Z] List of cloud inits to copy: [/tmp/xxxx4001315653] 
      +run-qemu-test |   INFO[2023-06-16T16:48:31Z] Starting copying cloud config file /tmp/xxxx4001315653 to /run/cos/oem/90_custom.yaml 
      +run-qemu-test |   INFO[2023-06-16T16:48:33Z] Unmounting disk partitions                   
      +run-qemu-test |   2 errors occurred:
      +run-qemu-test |   	* write /run/cos/oem/90_custom.yaml: copy_file_range: is a directory
      +run-qemu-test |   	* Failed to unmount /run/cos/oem
```

I had a look at the test but could not understand where /tmp/xxxx4001315653 comes from. The test just scp the file in the VM and calls kairos-agent with it. It must be something in kairos-agent then (edited)

**Comment by jimmykarily** [comment]
There is only one place I could find where we use `xxxx` to create a file or directory: https://github.com/kairos-io/kairos-agent/blob/ed372395d2556a6f777c9d54ab9252578982c1f0/internal/agent/install.go#L270

In this case, it's a file so I don't understand how that could end up being a directory. Maybe it's not what I thought.

**Comment by Itxaka** [comment]
Only thing I can think of is either the hook or the stage screwing up the /run/cos/oem dir somehow, thus making the file dissapear.

Notice that in the cases where it fails, there is 2 errors always:

```
+run-qemu-test |   	* write /run/cos/oem/90_custom.yaml: copy_file_range: is a directory
      +run-qemu-test |   	* Failed to unmount /run/cos/oem
```

elemental never had any issues unmounting the /run/cos/oem dir, so maybe something is tinkering with it and leaving it open or remounting it? Is the only thing that makes sense, as the order changed, we used to run the stage+hook and then create the file, but now we do it on reverse. Maybe even /tmp shenanigans are involved?

but the stages being run at that point are not touching anything IIRC. There is nothing that hooks in there I think?

**Comment by Itxaka** [comment]
Seems to be fixed by the workaround of waiting 5 minutes before starting the test so the stages are run and they dont collide with any existing data under /tmp.

Real fix is 1530 but that wont really work with this test until we release a new version, as in the test we start from the latest released version and then upgrade to the version build on the PR/branch

**Comment by jimmykarily** [comment]
Good catch @Itxaka ! Awesome!
