### ISSUE TITLE
Disable gzipping squashfs in Auroraboot

### ISSUE THREAD

**Issue by areitz86** [kairos-io/kairos#1553]
**Is your feature request related to a problem? Please describe.**

Build times are sometimes crucial. Testing boot media can be cumbersome, if I have to wait minutes just for gzipping squashfs, even though I don't care if the ISO gets a few MB bigger.

**Describe the solution you'd like**

Ability to disable gzip. But in general: more ability to configure how auroraboot invokes elemental would be amazing.

**Describe alternatives you've considered**

**Additional context**

**Comment by Itxaka** [comment]
Added a PR to disable the compression as we found some time ago that it doesnt bring a big size improvement but it slows down image creation considerably.

I thought of adding more flags to aurora and more config options to pass those down to elemental-cli but knowing that we are dropping the elemental-cli binary and extract the code into somewhere else like osbuilder/auroraboot directly it makes not much sense to me to do that work now, as its a bit complicated.

Meanwhile we can disable this ASAP and continue working on the rest.
