### ISSUE TITLE
Missing package `qemu-guest-agent` on some base images

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1564]
We install this package on openSUSE and Alpine-based images, but every other one is missing it

_Originally posted by @si458 in https://github.com/kairos-io/kairos/issues/796#issuecomment-1612202253_

**Comment by si458** [comment]
Does this include debian?

**Comment by mauromorales** [comment]
@si458 same issue with debian, I rewrote the ticket

**Comment by mauromorales** [comment]
@si458 indeed, we'll try to do a release tomorrow but depends on other bug fixes being ready too ... so yes if you can build yourself probably faster
