### ISSUE TITLE
:penguin: spike: UBI images

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1597]
**Is your feature request related to a problem? Please describe.**
Would be nice to have UBI core images, so can be used for BYOI to create downstream flavors

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

No idea if this is in contrast with UBI images EULA: https://www.redhat.com/licenses/EULA_Red_Hat_Universal_Base_Image_English_20190422.pdf

Timebox: 1 day

**Comment by mudler** [comment]
I'm not a lawyer, but by reading the EULA it seems that any use and re-distribution of modified images needs to have RedHat stripped off, an extract from the EULA:

```
If you modify the Red Hat Universal Base Image(s), you must remove
any Red Hat trademark(s) prior to any subsequent distribution. Any breach of this Section 2 is a material breach of the EULA and you may no
longer use and/or distribute the Red Hat trademark(s). Modifications to the software may corrupt the Programs
``

**Comment by mudler** [comment]
As I understand it, this is quite unfortunate, as - things like Systemd and other core packages would most likely display "Red Hat" - forcing any other derived image to have to rebrand internal components - which makes me thing that this is what exactly `rockylinux` or other RHEL based flavors do (just rebranding).

**Comment by mudler** [comment]
@kairos-io/maintainers I'll keep this open for discussion until today as this is timeboxed - my conclusion for now is that, to be safe, it's better to not have UBI-based images, as that would imply the cost of rebranding the components _INSIDE_ the image. It's just not about renaming the image tags, or something as simple as it.

**Comment by Itxaka** [comment]
I mean, rocky and alma does that exactly, get the srpms, strip branding, build from those. So supporting rocky+alma we already support redhat ubi images for sure. They are bug for bug compatible...

**Comment by mauromorales** [comment]
I would like to understand the actual use case of the request, seems like UBIs are quite limited in what they are supposed to be used for:

> As mentioned earlier, UBI should not be thought of as free Red Hat Enterprise Linux. UBI is targeted for specific use cases, not the wide variety of use cases that RHEL  can address. Today, the UBI use cases include developers looking to develop containerized, cloud-native applications based on popular languages like .NET, Golang, Node.js, Perl, PHP, Python, and Ruby.

Also, interesting that they mention:

> The entitlement for UBI comes from the host, not the container image. 

Seems to me like they really want to lock you into their platforms. So, again the question on why would we want to build with them

from https://developers.redhat.com/blog/2019/10/09/what-is-red-hat-universal-base-image#
