### ISSUE TITLE
`/var/lib/longhorn` is not shared mounted

### ISSUE THREAD

**Issue by simonfr** [kairos-io/kairos#1607]
**Kairos version:**

```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.2
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
KAIROS_NAME="kairos-alpine-opensuse-leap"
KAIROS_VERSION="v2.3.0-k3sv1.27.3+k3s1"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-alpine-opensuse-leap"
KAIROS_VERSION_ID="v2.3.0-k3sv1.27.3+k3s1"
KAIROS_PRETTY_NAME="kairos-alpine-opensuse-leap v2.3.0-k3sv1.27.3+k3s1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
KAIROS_HOME_URL="https://github.com/kairos-io/provider-kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/kairos-alpine-opensuse-leap"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/provider-kairos"
KAIROS_VARIANT="kairos"
KAIROS_FLAVOR="opensuse-leap"
```

**CPU architecture, OS, and Version:**

```
Linux node-vm-master-stark5932 5.14.21-150400.24.63-default #1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f) x86_64 GNU/Linux
```

**Describe the bug**

Alpine can't be installed as `/var/lib/longhorn` seems to not be shared mounted (like #440)

**To Reproduce**

**Expected behavior**

**Logs**

```
Warning  Failed          2m4s                kubelet            Error: failed to generate container "8424cf1a165ad1928a20fff7f65e863896018aedb1d8cbf47437b7dd8e7b6cee" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/var/lib/longhorn" but it is not a shared mount
```

**Additional context**

Maybe it was already fixed by https://github.com/kairos-io/kairos/pull/445 but when I check my flavor using image `kairos-alpine-opensuse-leap-v2.3.0-k3sv1.27.3`, with `kairos-agent state get kairos.flavor` I get : `opensuse-leap` and not `alpine-opensuse-leap`. See https://github.com/kairos-io/kairos/blob/master/overlay/files/system/oem/00_rootfs.yaml#L188

~~Should we use `kairos-agent state get system.os.vendor` instead ?~~

**EDIT:**
The cause is, when doing this : https://github.com/kairos-io/provider-kairos/blob/main/Earthfile#L145, the env is not passed to the import https://github.com/kairos-io/provider-kairos/blob/main/Earthfile#L3 resulting in using default ARG : https://github.com/kairos-io/kairos/blob/master/Earthfile#L4. All images are compromised. To fix, we can update arguments passed to the original command.

**Comment by simonfr** [comment]
After checking, the problem is at provider level : https://github.com/kairos-io/provider-kairos. I will close this issue and open a new one.

**Comment by simonfr** [comment]
Ready to merge, @mudler can you review it ? :)

**Comment by Itxaka** [comment]
Thanks @simonfr !

Not sure why github marks only @mudler as asignee, I would hope to have it ping everyone in the team :/
