### ISSUE TITLE
Produce 2 different images for rpi 3 and 4

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1636]
This is the continuation of: https://github.com/kairos-io/kairos/issues/1448

Rpi3 doesn't support GPT but rpi4 does.

For this reason and because community is still using rpi3, we decided to produce a different image for each platform.

The rpi3 image will not expand for now and will simply print a warning saying so. The rpi4 will expand like every other image does.

We will also [document how to manually expand on rpi3](https://github.com/kairos-io/kairos/issues/1637).

**Comment by Itxaka** [comment]
Still missing the earthly part for Kairos, cutting a new osbuilder, etc...

**Comment by Itxaka** [comment]
kairos now produces and allows for rpi3/rpi4 modes and osbuilder as well
