### ISSUE TITLE
🐧 Almalinux ARM Varient

### ISSUE THREAD

**Issue by DrKittens** [kairos-io/kairos#1639]
**Describe the solution you'd like**
It would be good to have a kairos varient based on RHEL for ARM as currently there isnt a RHEL based flavour for that architecture.

Almalinux has an ARM (aarch64) version [found here](https://mirrors.almalinux.org/isos.html)

Apologies if this is in the wrong location, i followed the link from [here ](https://kairos.io/docs/reference/image_matrix/)

**Comment by mauromorales** [comment]
Hi @DrKittens thanks for opening the ticket. I've put it in the incoming, so it gets triaged on our planning next week. 

Meanwhile, if you want to give it a shot, you might try to build it with Earthly `earthly +all-arm-generic --FLAVOR=almalinux`

**Comment by mauromorales** [comment]
@mudler @jimmykarily is this something we want to have? Should not be too much work to produce the artifact, otherwise maybe let's just close the issue, adding instructions on our docs on how to build?

**Comment by jimmykarily** [comment]
I lean more on the documentation side. After all, [we had Almalinux](https://github.com/kairos-io/kairos/commit/04f099a4225f622f09e3ea12b306a46a4aaa6cc4) in the past and we decided we don't have the capacity to build all flavors in our pipeline. If we have docs that work, it should be fairly easy for anyone to create a pipeline and build it.

**Comment by mauromorales** [comment]
@jimmykarily yup, agree with you. ok, will change this issue to be a documentation one

**Comment by cheese** [comment]
Help is also needed to build an ARM iso from an image.

**Comment by jimmykarily** [comment]
> Help is also needed to build an ARM iso from an image.

this? https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-container-images

**Comment by cheese** [comment]
> > Help is also needed to build an ARM iso from an image.
> 
> this? https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-container-images
> 
> also:
> 
> ```
> docker run -it quay.io/kairos/osbuilder-tools:v0.200.11 build-iso --help
> ```
> 
> (check how it's used in the last code snippet in [this section](https://kairos.io/docs/architecture/container/#container-image-based-os))

Yes. I tested that the same instruction works for ARM ISO. Just make sure an arm64 auroraboot image is used.
