### ISSUE TITLE
ci: try github hosted runners

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1644]
After discussing with the team and given our issues with CI (slow, overbooked) and we want to retire our self-hosted runner, we decided to give a shot to Github runners. It seems there is support to kvm too, so that should make everything go much faster as well.

https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/

This card is about setting this up (billing, etc) and trying it out. Ideally only test jobs that requires VM should run on hosted runners.

**Comment by jimmykarily** [comment]
Done
