### ISSUE TITLE
:bug: ARM generic image is broken on master

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1690]
The last release v2.3.2 works fine, but when building from master I get the following error:

```
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
      FS0: Alias(s):CD0a0b:;BLK2:
          PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/Scsi(0x0,0x0)/CDROM(0x1)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/Scsi(0x0,0x0)
     BLK1: Alias(s):
          PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/Scsi(0x0,0x0)/CDROM(0x0)
     BLK3: Alias(s):
          PciRoot(0x0)/Pci(0x1,0x4)/Pci(0x0,0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell> 
```

**Comment by mauromorales** [comment]
The issue was introduced with the update to osbuilder 0.8.2 https://github.com/kairos-io/kairos/commit/7c31364bb073f1ae3d6eb3fdc14736e653c05ae8

@Itxaka any ideas why this could be the case?

**Comment by Itxaka** [comment]
weird, I think I fixed that and tested the image myself on the rpi. Are you sure its the latest version and it wasnt cached somewhere?

@mauromorales Can you check the contents of the EFI/BOOT dir? It should have a file called bootaa64.efi

**Comment by Itxaka** [comment]
Doesnt make sense, that patch was introduced the first of August, and the release 2.3.2 was cut the third of August ??? Either both fail or none
