### ISSUE TITLE
Rename base repositories

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1694]
Split from #1109 

We now have a convention for the artifacts and binaries, but changing the name of the repositories requires a bit of extra work, since we need to move the old data into them. To avoid growing the original issue too big, this new issue was created.

Keep in mind that the repository name doesn't necessarily need to match the artifact's name because we can use tags and labels.

1. come up with a good convention for the repository names
2. create them and give the same permissions than the old ones have
3. migrate the old data into them
4. migrate the pipelines

**Comment by Itxaka** [comment]
rpi3 and rpi4 may need either different repos or artifact naming changes: https://github.com/kairos-io/kairos/pull/1820

**Comment by jimmykarily** [comment]
This story is now deprecated. We have a new naming scheme that should cover for any device/arch/whatever. Documented here: https://kairos.io/docs/reference/artifacts/
Closing this.
