### ISSUE TITLE
[arm] Errors on building dracut

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1698]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
arm64, openSUSE Leap and Tumbleweed for rpi64 (generic image not affected)

**Describe the bug**
```
         +base-image | dracut-install: ERROR: installing 'cryptsetup'
```

**To Reproduce**
Build arm images

**Expected behavior**
no errors while building dracut

**Logs**

**Additional context**

**Comment by mauromorales** [comment]
@Itxaka that link is green no? except for nvidia which seems to be a different error if I'm not misreading it

**Comment by mauromorales** [comment]
The error is only there on opensuse variants for RPi, the generic image does not have the error. Updating the description
