### ISSUE TITLE
Add more flexibility to cloud-config headers

### ISSUE THREAD

**Issue by AdrienEti** [kairos-io/kairos#1714]
**Is your feature request related to a problem? Please describe.**

The cloud-config generated by CAPI (for our case, using GCP as the infrastructure provider and kubeadm as the bootstrap provider) uses a template format that begins with ## template: jinja, as illustrated in the following example:
```yaml
## template: jinja
#cloud-config

write_files:
-   path: /etc/kubernetes/pki/ca.crt
    owner: root:root
...
```
As result, because the [supported header are limited](https://github.com/kairos-io/kairos-sdk/blob/f6ec86180b17801360a10ca05d592117fcb401d3/collector/collector.go#L402-L411) the cloud-config cannot be executed by kairos-agent:

_Aug 04 08:56:48 localhost kairos-agent[1400]: warning: skipping /oem/91_test.yaml because it has no valid header_

One potential solution might be to employ cloud-init. Nevertheless, it's not ideal to switch to a different tool instead of yip, especially considering that yip can execute the cloud-config if the jinja header was skipped.

**Describe the solution you'd like**
It would be great if we could override the supported headers with a configuration file.

**Describe alternatives you've considered**

Some of possible solutions have been discussed on the slack channel:
- add a certain flag/env var which can remove the requirement
- gather all comments and check for "#cloud-config" in them

**Additional context**

None

**Comment by jimmykarily** [comment]
It seems that this valid cloud-config syntax (https://cloudinit.readthedocs.io/en/latest/explanation/instancedata.html#example-cloud-config-with-instance-data).

Just to clarify, @AdrienEti is it expected that jinja will be parsed. e.g. by reading the json from these locations: https://cloudinit.readthedocs.io/en/latest/explanation/instancedata.html#storage-locations? 

or is the request simply to ignore the jinja header and just use the file as a normal cloud init file (already processed by jinja whatesoever)?

**Comment by AdrienEti** [comment]
The request is to just ignore the Jinja header. 
In our case, we don't actually need to process anything by jinja (the Jinja header seems to be added by the CAPI kubeadm bootstrapper every time, even if there's nothing to process).
Thanks
