### ISSUE TITLE
Support for OpenStack ConfigDrive datasource

### ISSUE THREAD

**Issue by JPedro2** [kairos-io/kairos#1719]
I've started a discussion with @Itxaka on this already (thank you so much for all the insights 🙏 ) but essentially we are looking for a way to configure edge-nodes (deployed as OpenStack VMs) via the ConfigDrive capability of OpenStack. Effectively the ideal outcome would be to use the ConfigDrive just like what we do today with a 2nd ISO that can be mounted as a 2nd media. In this case, mounting a a 2nd ISO is not an option and Config Drive has to be used - this will be mostly used to setup Static IP for the nodes

Some context:
1. Kairos version being used is v2.1.3
2. The OpenStack version being used is Newton
3. The meta-data service is available in the fixed IP: 169.254.169.254
4. The label of the config-drive in the booted system is config-2 or CONFIG-2, [as per cloud-init OpenStack datasource documentation](https://cloudinit.readthedocs.io/en/latest/reference/datasources/configdrive.html)

The preliminary investigation that @Itxaka (🙏 ) did:
Currently there's no support for the config drive in kairos datasources unfortunately - https://github.com/rancher-sandbox/linuxkit/
The idea is generic cloud config that opens the config-drive and copies the data into /oem so the real cloud-config comes from the config-drive
```
 - name: "Get cloud config from config-drive"
      commands:
        - mkdir -p /tmp/cc
        - DRIVE=$(blkid -t LABEL="config-2" -odevice) mount $DRIVE /tmp/cc
        - cp /tmp/cc/openstack/latest/user-data /oem/userdata
        - umount /tmp/cc
```

**Comment by JPedro2** [comment]
Also, adding to this, there's no DHCP available at any point, so that should also be taken into account

**Comment by Itxaka** [comment]
Thsi needs to expand the cdrom provider upstream in linuxkit to also read the metadata from the cdrom with this label. Should be simply enough.

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/linuxkit/pull/4

**Comment by Itxaka** [comment]
This is now supported in kairos 2.4.1 but its not added to the default metadata services
