### ISSUE TITLE
:bug: Reboot and Poweroff options don't work anymore on the Web UI

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1739]
Tested with 2.4.0 alpha1

Configuration is executed properly, but the node never restarts or shuts down automatically

**Comment by Itxaka** [comment]
I guess that now it checks on the spec values to trigger both options but we are setting them in the Config object only so they are ignored?
Probably we should drop the checkboxes adding the flags to the command and make it add to the cloud-config directly as now this is controlled by the settings:

```
install:
  reboot: true
  poweroff: true
```

**Comment by mauromorales** [comment]
not a bad idea, at the end of the day, our users are used to cloud-config, maybe just for first commers it might helpful. but maybe not worth having if we want to encourage to use cloud config all the time

**Comment by mauromorales** [comment]
@mudler @jimmykarily what do you say if we remove the checkboxes on the Web UI?
