### ISSUE TITLE
Welcome screen should be similar no matter the flavor

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1742]
We shouldn't need to have it in yaml like this:

- https://github.com/kairos-io/packages/blob/d0a5a889fd86116169f9ef5edb6030aa446f3011/packages/bundles/kairos-overlay-files/files/system/oem/13_openrc_services.yaml#L49-L64
- https://github.com/kairos-io/packages/blob/main/packages/bundles/kairos-overlay-files/files/etc/issue.d/01-KAIROS

Ideally all flavors should share the same file

**Comment by dangogh** [comment]
@jimmykarily this issue may already have been addressed?  The files you refer to are no longer in the packages repo and only a few "Welcome... " messages remain.

**Comment by jimmykarily** [comment]
Yup, the banner is now defined here:
https://github.com/kairos-io/kairos-agent/blob/a3aadbbaa970c55cbcf93d9fc2bf49d51a6a2fe3/internal/agent/iconunix.go#L8
and the welcome message here:
https://github.com/kairos-io/packages/tree/main/packages/static/kairos-overlay-files/files/etc/kairos/branding

Thanks for reporting this @dangogh !
