### ISSUE TITLE
:bug: Persistent is not being expanded consistently

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1762]
This was supposed to be fixed on https://github.com/kairos-io/kairos/issues/1448

However, on some occasions after booting the system, `lsblk` shows a 64M size, even when `sgdisk` shows an XG size

This is for rpi4, have tested it on opensuse-leap, ubuntu and ubuntu-20-lts, and they all had the issue sometimes

**Comment by mudler** [comment]
what disk layout is being used? GPT or MBR?

**Comment by mauromorales** [comment]
The issue does not happen consistently, many times it works from the first run. Something I've observed when it failes:

- sgdisk reports the correct size
- lsblk reports only 64M
