### ISSUE TITLE
You need to load the kernel first

### ISSUE THREAD

**Issue by GrabbenD** [kairos-io/kairos#1770]
Tried following instructions from: https://kairos.io/docs/reference/build-from-scratch/#build-bootable-asset
After a successful installation I cannot start the image due to:
```
Booting a command list

error: ../../grub-core/disk/loopback.c:98:device name already exists.
error: ../../grub-core/kern/fs.c:170:invalid file name `'.
error: ../../grub-core/loader/i386/efi/linux.c:168:you need to load the kernel first.
```

This also happens with image from: https://github.com/kairos-io/kairos/blob/master/examples/byoi/fedora-fips/Dockerfile

**Comment by sdwilsh** [comment]
I also am seeing this with a new image via `kairos-ubuntu-v2.3.1-k3sv1.26.6+k3s1.iso`.

**Comment by Itxaka** [comment]
Can confirm, followed up the docs to create the test-byoi image as mentioned in the example, installed no issues, after reboot same message.

**Comment by Itxaka** [comment]
Seems like bootargs.cfg is missing on active so it cannot get the kernel/initrd route.... not sure why

**Comment by Itxaka** [comment]
The current workaround is to create a bootargs.cfg file along your dockefile and copy it into the image at /etc/cos/bootargs.cfg when building your own image.

example bootargs.cfg images for each flavor are under the images dir in the kairos repo, on each flavor dir: https://github.com/kairos-io/kairos/tree/master/images.

Patch to fix this and ship the bootargs.cfg with the framework image is already sent.

Thanks for reporting this @GrabbenD @sdwilsh !

**Comment by Itxaka** [comment]
This has been merged and all the framework_master images updated! Problem should be fixed, I will test this tonight to confirm

**Comment by DevOpsFu** [comment]
I am seeing this problem with the latest stable Ubuntu image for the RPi4
