### ISSUE TITLE
k3s service is broken on systemd

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1797]
systemd has a compatibility feature with sysv (https://www.turnkeylinux.org/blog/debugging-systemd-sysv-init-compat). Since we copy all services, both systemd and openrc, when the service is started, it fails with an error.

We need to remove the openrc bits from systemd systemds

**Comment by jimmykarily** [comment]
> How is this not hitting our test suite? We have a check for k3s status no?

As it seems, no. We check various things but not that the service is running. We need to do add that check.

**Comment by Itxaka** [comment]
ah maybe its because on testing we use latest and that installs the k3s service directly! So it only installs the proper service file, while installing from package would install our package with both files.
