### ISSUE TITLE
[ubuntu] provider-kairos has no image assets for 2.4.0

### ISSUE THREAD

**Issue by sdwilsh** [kairos-io/kairos#1804]
The [release of 2.4.0](https://github.com/kairos-io/provider-kairos/releases/tag/v2.4.0) has no image assets.  Looking at what was uploaded to [quay.io for Ubuntu](https://quay.io/repository/kairos/kairos-ubuntu?tab=tags) (what I use) only shows RC1 for 2.4.0.  I haven't checked other OSes.

I'm not sure if the release was cut early on accident on GitHub, or if release automation failed to publish artifacts, but something seems off.

**Comment by jimmykarily** [comment]
The [provider-kairos](https://github.com/kairos-io/provider-kairos/) release pipelines have been merged with the [kairos](https://github.com/kairos-io/kairos/) ones. Now all artifacts are releases from the kairos repository, both core images and standard images (those with the provider). There will be new images as soon as we release `2.4.0` from kairos. From now on, the releases on this repo are just new releases of the provider binary.

Sorry for the confusion.
