### ISSUE TITLE
fips_enabled is set to 0 for ubuntu iso created for byoi/ubuntu-fips

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#1805]
**Kairos version:**
```
kairos@localhost:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
KAIROS_NAME="kairos-ubuntu-fips"
KAIROS_VERSION="v9.9.9"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-ubuntu-fips"
KAIROS_VERSION_ID="v9.9.9"
KAIROS_PRETTY_NAME="kairos-ubuntu-fips v9.9.9"
KAIROS_BUG_REPORT_URL="https://github.com/YOUR_ORG/YOUR_PROJECT/issues"
KAIROS_HOME_URL="https://github.com/YOUR_ORG/YOUR_PROJECT"
KAIROS_IMAGE_REPO="quay.io/YOUR_ORG/ubuntu-fips"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="YOUR_ORG/YOUR_PROJECT"
KAIROS_VARIANT="fips"
KAIROS_FLAVOR="ubuntu"
```

**CPU architecture, OS, and Version:**
Linux localhost 5.4.0-1024-fips #28+recert1-Ubuntu SMP Fri May 14 21:30:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Installer built with the instruction from here - https://github.com/kairos-io/kairos/tree/master/examples/byoi/ubuntu-fips
results 
```
kairos@localhost:~$ cat /proc/sys/crypto/fips_enabled
0
kairos@localhost:~$ uname -a
Linux localhost 5.4.0-1024-fips #28+recert1-Ubuntu SMP Fri May 14 21:30:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
kairos@localhost:~$
```

**To Reproduce**
 https://github.com/kairos-io/kairos/tree/master/examples/byoi/ubuntu-fips

**Expected behavior**
```
kairos@localhost:~$ cat /proc/sys/crypto/fips_enabled
0
```
should be 1.

cloud-config was as below 
cat /oem/userdata
```
#cloud-config
install:
  device: /dev/sda
  grub_options:
    # additional Kernel option cmdline to apply
    extra_cmdline: "fips=1"

stylus:
  debug: true
  trace: true 

stages:
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos
```

**Comment by santhoshdaivajna** [comment]
I use a variant of this one with kairos version set to v2.3.2 and osbuilder tools version set to v0.7.11. In that also I see the same behavior. 
https://github.com/spectrocloud/CanvOS/tree/main/ubuntu-fips

**Comment by Itxaka** [comment]
running this example with the given data (cloud-config) I get a fips system. Well, it kind of. It fails to verify fips mode due to an hmac missing issue but it starts in fips mode.

**Comment by Itxaka** [comment]
just one thing missing from the ubuntu example: https://github.com/kairos-io/kairos/pull/1834

**Comment by jimmykarily** [comment]
@santhoshdaivajna we fixed the missing hmac issue and we can't reproduce the issue you reported. Please provide more information and re-open is the issue persists.
