### ISSUE TITLE
Rpi3 artifacts

### ISSUE THREAD

**Issue by Ludea** [kairos-io/kairos#1816]
**Is your feature request related to a problem? Please describe.**

There is no binaries for RP3

**Describe the solution you'd like**

Build, and upload RPI3 assets on quay.
Add RPI3 section https://kairos.io/docs/reference/image_matrix/

**Describe alternatives you've considered**

Let user build Kairos Rpi3 img

**Additional context**

Separate Rpi3 img has added since 2.4 release

**Comment by jimmykarily** [comment]
Possibly fixed here: https://github.com/kairos-io/kairos/pull/1820

**Comment by jimmykarily** [comment]
Blocked by this: https://github.com/kairos-io/kairos/issues/1694
