### ISSUE TITLE
systemd-sysext directory change

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1821]
https://github.com/systemd/systemd/commit/de862276eddbbe76b436213b4d427205356d1886

The bundles-test on master breaks because we store the kubo extension in `/usr/local/lib/extension` which is no longer the right place for systemd-sysext

The proper paths documented here: https://www.freedesktop.org/software/systemd/man/systemd-sysext.html
are ephemeral in Kairos so we may need to add them to our persistent dirs.

We also need to update documentation: https://kairos.io/docs/advanced/livelayering/#installing-extensions

**Comment by mudler** [comment]
for reference, this is the systemd PR: https://github.com/systemd/systemd/pull/27044
