### ISSUE TITLE
Core Ubuntu Images fail to install apt packages

### ISSUE THREAD

**Issue by clanktron** [kairos-io/kairos#1849]
When using the core ubuntu images, installing apt packages fails unless the system is updated and /var/cache/apt/archives/partial directoty is created manually.

For example the following containerfiles both fail to build:
```dockerfile
FROM quay.io/kairos/core-ubuntu-22-lts:v2.4.0
# install any package
RUN apt install -y fish
```
error: `#0 0.499 E: Unable to locate package fish` (this applies to any package fish is just an example)
```dockerfile
FROM quay.io/kairos/core-ubuntu-22-lts:v2.4.0
RUN apt update -y
# install any package
RUN apt install -y fish
```
error: `#0 2.103 E: Archives directory /var/cache/apt/archives/partial is missing. - Acquire (2: No such file or directory)`

but if the system is updated *and* the cache dir is created
```dockerfile
FROM quay.io/kairos/core-ubuntu-22-lts:v2.4.0
# fix bug
RUN apt update -y && mkdir -p /var/cache/apt/archives/partial
# install any package
RUN apt install -y fish
```
then the container builds just fine.

I've tried this on:  
`quay.io/kairos/core-ubuntu-20-lts:v2.4.0`  
`quay.io/kairos/core-ubuntu-20-lts:latest`  
`quay.io/kairos/core-ubuntu-22-lts:v2.4.0`  
`quay.io/kairos/core-ubuntu-22-lts:latest`  
and they all have the same results. I haven't tried other tags.

Requiring the system to be updated at build time seems fine if that's the desired workflow...this just wasn't required when I tried modifying the opensuse images so not sure if this is a bug or a feature. 

That being said IMO the `/var/cache/apt/archives/partial` shouldn't need to be manually created.

**Comment by Itxaka** [comment]
Good catch @clanktron !

Indeed, I have seen this happen before but only in the last 2 to 3 weeks. Im guessing something has changed in how apt installs, or we never catched this before.
