### ISSUE TITLE
FOSDEM 24

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1868]
⚠ Oct 31: Dev rooms announced https://fosdem.org/2024/news/2023-11-08-devrooms-announced/

⚠  5 November (or earlier) Dev rooms will open CfPs

⚠ 8 Dec: Booths

On 2023 we presented at the Distributions Dev Room, this year we should try again to get another presentation. In my opinion Kairos has a lot to offer in other dev rooms besides the distributions one, so we should also give that a shot.

- [x] Come up with a list of dev rooms to apply to
- [x] Prepare CfPs
- [x] Apply for booth (@mudler) https://fosdem.org/2024/news/2023-09-18-stands-cfp/
- [x] write presentation ( @jimmykarily )
- [x] plan meetup ( @mauromorales & @jimmykarily )
- [x] talk with Nic to get some sweaters
- [x] get more stickers

https://fosdem.org/2024/

## Dev rooms to apply to

| Room | CfP | Deadline | Status |
|-------|-----|----------|--|
| [Confidential Computing](https://fosdem.org/2024/schedule/track/confidential-computing/) | [CfP](https://lists.fosdem.org/pipermail/fosdem/2023q4/003505.html) | Dec 1st | Not accepted |
| [Containers](https://fosdem.org/2024/schedule/track/containers/) | [CfP](https://discuss.linuxcontainers.org/t/fosdem-2024-containers-devroom-call-for-papers/18253) | Dec 8th | Not accepted |
| [Distributions](https://fosdem.org/2024/schedule/track/distributions/) | [CfP](https://lists.fosdem.org/pipermail/fosdem/2023q4/003529.html) |Dec 5th | Not accepted |
| [Go](https://fosdem.org/2024/schedule/track/go/) | [CfP](https://lists.fosdem.org/pipermail/fosdem/2023q4/003520.html) | Dec 1st | We decided not to apply |
| [SBOM](https://fosdem.org/2024/schedule/track/software-bill-of-materials/) | [CfP](https://hackmd.io/@spdx/fosdem2024-cfp) | Dec 8th | Not accepted |
| [AI](https://fosdem.org/2024/schedule/track/ai_ml/) | [CfP](https://lists.fosdem.org/pipermail/fosdem/2023q4/003514.html) |  Dec 4th| Missed the deadline :( |
| [Network](https://fosdem.org/2024/schedule/track/network/) | [CfP](https://lists.fosdem.org/pipermail/fosdem/2023q4/003490.html) | Dec 8th | Not accepted |
| [Testing & CD](https://fosdem.org/2024/schedule/track/testing-continuous-delivery/) | | | Accepted |

**Comment by mauromorales** [comment]
Unfortunately there wont be an [Image-based Linux and Secure Measured Boot devroom
](https://archive.fosdem.org/2023/schedule/track/image_based_linux_and_secure_measured_boot/) but I guess we can try to share some of those topics into one of the other rooms

**Comment by mauromorales** [comment]
Networks dev room rejected the talk

**Comment by mauromorales** [comment]
The talk for Testing & CD got accepted all others not

**Comment by mauromorales** [comment]
Today I ordered a new batch of stickers, they should be here around the 18th of January

**Comment by jimmykarily** [comment]
Our infra-as-code repository is private. I think we did all the work to encrypt keys and such. I wonder if we should make it public so that people can actually check out the things we are going to talk about in the presentation. We will have to check the git history in case we committed sensitive information before we had sops in place.

**Comment by mauromorales** [comment]
@jimmykarily good catch, yes we should try to make it public if possible

**Comment by mauromorales** [comment]
just putting this here cuz I always forget the website https://pretalx.fosdem.org/fosdem-2024/me/submissions/
