### ISSUE TITLE
Failure to install to /dev/disk/by-id/<id>

### ISSUE THREAD

**Issue by clanktron** [kairos-io/kairos#1879]
Kairos fails to install to disk id (aka /dev/disk/by-id/<id>). I'm not sure if this is in the category of "not yet supported" or if this is a true bug.

Either way, when specifying to a disk id with the following or by setting such with the `--device` flag...
```bash
cat config.yaml
# #cloud-config
# hostname: nas-{{ trunc 4 .MachineID }}
# users:
# - name: clayton
#   groups: [ docker ]
#   shell: /usr/bin/fish
#   ssh_authorized_keys:
#     - github:clanktron
# 
# ssh_pwauth: false
# timezone: America/Los_Angeles
# 
# # kairos debug logging
# debug: true
# 
# install:
#   device: /dev/disk/by-id/ata-walram_60G_SCRW210906G0093
#   reboot: false
#   poweroff: true
#   auto: true
kairos-agent m config.yaml
```

The following errors occur: 
(apologies that these are screenshots and not raw text but it was going to be a hassle to grab the stdout/stderr of the install to the physical machine)
![partition-error-1](https://github.com/kairos-io/kairos/assets/52805671/cc5d59ec-8eb3-4e5c-9100-018b63e26592)
![partition-error-2](https://github.com/kairos-io/kairos/assets/52805671/d633e8e0-1228-4120-b9c5-3a8f0736113d)

Looking at /dev/disk/by-id after the failure, it seems that the first partition is successfully created but that it has a different auto generated name than what kairos is attempting to find (see below).

![successful-first-partition](https://github.com/kairos-io/kairos/assets/52805671/91a2915a-dbfd-4d61-b978-94aa4c6c8489)

I don't fiddle with udev rules a ton so I'm not sure how this partition auto naming scheme might vary from distro to distro if at all. For context this installer is running a lightly customized quay.io/kairos/core-ubuntu-22-lts:v2.4.0 image (just a few extra packages installed).

**Comment by jimmykarily** [comment]
This is not supported. I changed the label from "bug" to "enhancement" . @clanktron can you tell us a little more about the use case? Is there a workaround? We are trying to prioritize this properly.

**Comment by clanktron** [comment]
I have servers that have multiple disks attached to them and would like to auto-install kairos on a given disk reliably. /dev/sdx addressing can change from boot to boot so something like /dev/disk/by-id or /dev/disk/by-label is certainly preferred.

As far as workarounds go I've just had to do manual installs to ensure it targets the right disk. If there's other approaches to this that I'm not aware of I'm open to such as well.

**Comment by jimmykarily** [comment]
This is another use case of custom partitioning which is already discussed here: https://github.com/kairos-io/kairos/issues/391 . I will add this use case on that issue. I think a "hook" or a custom script that does the partitioning would solve this too, no? (see the other issue for details)
