### ISSUE TITLE
Auroraboot tests are faillig

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1894]
Since this commit https://github.com/kairos-io/AuroraBoot/commit/d974ed4583e326ab3f92e37a85cbd931463be055
 (not sure if related) tests have been failing in AuroraBoot

https://github.com/kairos-io/AuroraBoot/actions/runs/6407845555/job/17395540022

**Comment by jimmykarily** [comment]
Fixed here: https://github.com/kairos-io/AuroraBoot/pull/45
