### ISSUE TITLE
Kairos dockerfiles should create full kairos images

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1897]
Currently, we build the Dockerfiles, and then we [do many more things in Earthly](https://github.com/kairos-io/kairos/blob/be7961bc8086838c378839364a9f0e77861ecdbd/Earthfile#L340-L484).

All this logic can be moved to the Dockerfiles. This will allow the creation of other derivatives without any Earthly knowledge.

Items extracted from TODOs (https://github.com/kairos-io/kairos/pull/1912):

- [x] Merge Alma, Rocky and Fedora to one family Dockerfile
- [ ] Move rest of logic from Earthfile to Dockerfiles
- [x] Create a reusable workflow that simply calls docker build, passing the required build-args
- [x] Delete the earthly base-image target and force the use of the above workflow anywhere needed
- [ ] Make all remaining earthly targets to use a pre-cooked KAIROS_IMAGE rather than calling +base-image

**Comment by jimmykarily** [comment]
Better merge this first: https://github.com/kairos-io/kairos/pull/1939

**Comment by mauromorales** [comment]
I will better not merge since it makes it less explicit for some of the actions in which distro they should be run and in which not
