### ISSUE TITLE
Opensuse derivative installer fails while booting with v2.3.2

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#1917]
**Kairos version:**
v2.3.2

**CPU architecture, OS, and Version:**
amd64
Opensuse 15.5

**Describe the bug**
Derivative built with the opensuse base image does not boot after installer handoff
Please check this recording - https://www.loom.com/share/b6fa427b255648df890f2b9e8c7f327e?sid=08635d0f-99a0-400f-a1f0-abe14cbc3715

**To Reproduce**
Build the opensuse iso with the installer with canvos here

.arg file contents
```
CUSTOM_TAG=opensuse
OS_DISTRIBUTION=opensuse-leap
IMAGE_REPO=gcr.io/santhosh
OS_VERSION=15.5
K8S_DISTRIBUTION=k3s
ISO_NAME=edge-os9
ARCH=amd64
IMAGE_REGISTRY=ttl.sh
HTTPS_PROXY=
HTTP_PROXY=
PROXY_CERT_PATH=
UPDATE_KERNEL=false
```
<img width="1251" alt="Screenshot 2023-10-11 at 5 33 36 PM" src="https://github.com/kairos-io/kairos/assets/504862/4d5fce5d-06a3-4452-91ba-7ca6f1948358">

**Expected behavior**
The device to boot into registration grub after installer handoff.

**Logs**
 The attached screenshot has some errors while booting the vm.

**Additional context**
the installer was built with canvos for building the installer iso using the kairos opensuse-leap v2.3.2 as the base image.

**Comment by mudler** [comment]
@santhoshdaivajna altought we don't support canvos builds - can you reproduce with the standard BYOI approach as described in the docs? 

Also what are the cmdline options? it looks FIPS is kicking in and failing to run checks - can you disable it?

**Comment by santhoshdaivajna** [comment]
I had the fips attributes in the userdata, without that it the installer works fine.
