### ISSUE TITLE
Fix /etc/os-release

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1960]
Seems to be currently wrong compared to what it was before.

Main differences:

Before:
```
KAIROS_NAME="kairos-core-alpine"
KAIROS_ID_LIKE="kairos-core-alpine"
KAIROS_PRETTY_NAME="kairos-core-alpine v2.4.1-19-gf771ccd0"
KAIROS_IMAGE_REPO="quay.io/kairos/core-alpine"
KAIROS_IMAGE_LABEL=""
```

Now
```
KAIROS_NAME="3.18-standard-amd64-generic-v2.4.1-33-gd163f3db-k3sv1.28.2+k3s1"
KAIROS_ID_LIKE="3.18-standard-amd64-generic-v2.4.1-33-gd163f3db-k3sv1.28.2+k3s1"
KAIROS_PRETTY_NAME="3.18-standard-amd64-generic-v2.4.1-33-gd163f3db-k3sv1.28.2+k3s1 v2.4.1-33-gd163f3db-k3sv1.28.2+k3s1"
KAIROS_IMAGE_REPO="quay.io/kairos/alpine:3.18-standard-amd64-generic-v2.4.1-33-gd163f3db-k3sv1.28.2-k3s1"
KAIROS_IMAGE_LABEL="v2.4.1-33-gd163f3db-k3sv1.28.2+k3s1"
```

So we need to make sure we respect the older state in here

**Comment by mauromorales** [comment]
@Itxaka It looks correct to me ... we actually have to create the new repos ... we changed the name of the repo in the byoi process

correct me if I'm wrong @jimmykarily

**Comment by Itxaka** [comment]
> @Itxaka It looks correct to me ... we actually have to create the new repos ... we changed the name of the repo in the byoi process
> 
> correct me if I'm wrong @jimmykarily 

Yeah indeed, bit the repo contains the artifact image which is wrong.

I sent a PR to fix this which respects the new repo structure but drops the artifact from it

Otherwise anything getting the repo and listing tags from it will fail like the provide upgrade...

**Comment by mauromorales** [comment]
ahhh sorry, misunderstood what was the issue then, thanks for clarifying
