### ISSUE TITLE
📖 Document new build parameters before release

### ISSUE THREAD

**Issue by labeth** [kairos-io/kairos#1964]
"Build Kairos" Chapter build instructions does not work.
using
./earthly +iso --FLAVOR=alpine
gives errors in missing arguments.
--FAMILY=
--FLAVOR_RELEASE=
--BASE_IMAGE=
--MODEL=
--VARIANT=
Seems to be required at least to be able to build. not sure what values they should have following the errors i got. then i got into another error probably because of me not understanding what values are OK to put here.

its also a bit confusing that -P option is not allowed to be used in the ./eartly but is required with earthly since .earthly has --allow-privileged set as default.

**Comment by jimmykarily** [comment]
e.g. this page: https://kairos.io/docs/development/development/#build-kairos

**Comment by labeth** [comment]
I could build master with the new instructions, in the pull request. Thanks!

I got an error building the v2.4.1 tagged release using the previous instructions, not sure if its important but here it is at least:
================================== ❌ FAILURE ===================================

          +framework *failed* | Repeating the failure error...
          +framework *failed* | FLAVOR=alpine
          +framework *failed* | --> RUN go run main.go ${FLAVOR} framework-profile.yaml /framework
          +framework *failed* | go: downloading github.com/kairos-io/kairos-sdk v0.0.14
          +framework *failed* | go: downloading github.com/urfave/cli v1.22.14
          +framework *failed* | go: downloading gopkg.in/yaml.v3 v3.0.1
          +framework *failed* | go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
          +framework *failed* | go: downloading github.com/containerd/containerd v1.7.1
          +framework *failed* | go: downloading github.com/denisbrodbeck/machineid v1.0.1
          +framework *failed* | go: downloading github.com/google/go-containerregistry v0.15.2
          +framework *failed* | go: downloading github.com/hashicorp/go-multierror v1.1.1
          +framework *failed* | go: downloading github.com/joho/godotenv v1.5.1
          +framework *failed* | go: downloading github.com/pterm/pterm v0.12.63
          +framework *failed* | go: downloading github.com/qeesung/image2ascii v1.0.1
          +framework *failed* | go: downloading gopkg.in/yaml.v1 v1.0.0-20140924161607-9f9df34309c0
          +framework *failed* | go: downloading github.com/russross/blackfriday/v2 v2.1.0
          +framework *failed* | go: downloading github.com/docker/cli v23.0.5+incompatible
          +framework *failed* | go: downloading github.com/mitchellh/go-homedir v1.1.0
          +framework *failed* | go: downloading github.com/docker/docker v23.0.5+incompatible
          +framework *failed* | go: downloading github.com/opencontainers/go-digest v1.0.0
          +framework *failed* | go: downloading github.com/docker/distribution v2.8.1+incompatible
          +framework *failed* | go: downloading golang.org/x/sync v0.2.0
          +framework *failed* | go: downloading github.com/hashicorp/errwrap v1.1.0
          +framework *failed* | go: downloading atomicgo.dev/cursor v0.1.3
          +framework *failed* | go: downloading atomicgo.dev/keyboard v0.2.9
          +framework *failed* | go: downloading atomicgo.dev/schedule v0.0.2
          +framework *failed* | go: downloading github.com/gookit/color v1.5.3
          +framework *failed* | go: downloading github.com/lithammer/fuzzysearch v1.1.8
          +framework *failed* | go: downloading github.com/mattn/go-runewidth v0.0.14
          +framework *failed* | go: downloading golang.org/x/term v0.10.0
          +framework *failed* | go: downloading golang.org/x/text v0.11.0
          +framework *failed* | go: downloading github.com/containerd/continuity v0.3.0
          +framework *failed* | go: downloading golang.org/x/sys v0.10.0
          +framework *failed* | go: downloading github.com/pkg/errors v0.9.1
          +framework *failed* | go: downloading github.com/sirupsen/logrus v1.9.0
          +framework *failed* | go: downloading github.com/docker/go-connections v0.4.0
          +framework *failed* | go: downloading github.com/docker/go-units v0.5.0
          +framework *failed* | go: downloading github.com/opencontainers/image-spec v1.1.0-rc3
          +framework *failed* | go: downloading github.com/containerd/stargz-snapshotter/estargz v0.14.3
          +framework *failed* | go: downloading github.com/containerd/console v1.0.3
          +framework *failed* | go: downloading github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e
          +framework *failed* | go: downloading github.com/rivo/uniseg v0.4.4
          +framework *failed* | go: downloading github.com/docker/docker-credential-helpers v0.7.0
          +framework *failed* | go: downloading github.com/klauspost/compress v1.16.5
          +framework *failed* | go: downloading github.com/vbatts/tar-split v0.11.3
          +framework *failed* | go: downloading golang.org/x/net v0.10.0
          +framework *failed* | go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
          +framework *failed* | go: downloading github.com/gogo/protobuf v1.3.2
          +framework *failed* | go: downloading github.com/aybabtme/rgbterm v0.0.0-20170906152045-cc83f3b3ce59
          +framework *failed* | go: downloading github.com/mattn/go-isatty v0.0.17
          +framework *failed* | go: downloading github.com/wayneashleyberry/terminal-dimensions v1.1.0
          +framework *failed* | No profile found
          +framework *failed* | exit status 1
          +framework *failed* | ERROR Earthfile line 261:4
          +framework *failed* |       The command
          +framework *failed* |           RUN go run main.go ${FLAVOR} framework-profile.yaml /framework
          +framework *failed* |       did not complete successfully. Exit code 1

**Comment by labeth** [comment]
I also tried to build --VARIANT=standard and then it has another variable that is required
--K3S_VERSION=
I set that to v1.27.3+k3s1
resulting in this error, not sure if it should work or not:
================================== ❌ FAILURE ===================================

         +base-image *failed* | Repeating the failure error...
         +base-image *failed* | BASE_IMAGE=fedora:38 FAMILY=rhel FLAVOR=fedora FLAVOR_RELEASE=38 K3S_VERSION=v1.27.3+k3s1 MODEL=generic VARIANT=standard
         +base-image *failed* | --> RUN luet install -y ${_LUET_K3S} utils/edgevpn utils/k9s utils/nerdctl container/kubectl utils/kube-vip
         +base-image *failed* |  INFO  Luet 0.34.0-gc47bf4833aef41e6ac3e8c831c1cfa8afc091592 2023-08-21 09:17:57 UTC
         +base-image *failed* |  INFO  Copyright (C) 2019-2022 Ettore Di Giacinto
         +base-image *failed* |        This program comes with ABSOLUTELY NO WARRANTY.
         +base-image *failed* |        This is free software, and you are welcome to redistribute it under certain conditions.
         +base-image *failed* |        For documentation, visit https://luet.io.
         +base-image *failed* |  INFO   :::> Install
         +base-image *failed* |  INFO   🤔  Checking for available upgrades
         +base-image *failed* |  INFO   Nothing to upgrade
         +base-image *failed* |   ERROR    Error: Failed matching solutions against repository for k8s/k3s-systemd-v1.27.3+k3s1 where are definitions coming from?!
         +base-image *failed* | ERROR Earthfile line 1355:4
         +base-image *failed* |       The command
         +base-image *failed* |           RUN luet install -y ${_LUET_K3S} utils/edgevpn utils/k9s utils/nerdctl container/kubectl utils/kube-vip
         +base-image *failed* |       did not complete successfully. Exit code 2

**Comment by jimmykarily** [comment]
`K3S_VERSION` should match the version of the luet package. Search for `k3s` here: https://packages.kairos.io/

A faster way to get the latest versions from the kairos repository root directory, if you have `luet` installed, is this:

```
~/workspace/kairos/kairos (master)*$ sudo luet --config framework-profile.yaml search -o json k8s/k3s  | jq '.packages | map(.version) | unique'
[
  "1.26.9+1",
  "1.27.6+1",
  "1.28.2+1"
]
```

**Comment by labeth** [comment]
Thanks that worked!
