### ISSUE TITLE
iPXE scripts in releases reference incorrect download URLs

### ISSUE THREAD

**Issue by jbalonso** [kairos-io/kairos#1984]
Release https://github.com/kairos-io/kairos/releases/tag/v2.4.0 includes the iPXE script https://github.com/kairos-io/kairos/releases/download/v2.4.0/kairos-standard-opensuse-tumbleweed-amd64-generic-v2.4.0-k3sv1.27.3+k3s1.ipxe, which includes the line:
```
kernel https://github.com/kairos-io/kairos/releases/download/v2.4.0-k3sv1.27.3+k3s1/kairos-standard-opensuse-tumbleweed-amd64-generic-v2.4.0-k3sv1.27.3+k3s1-kernel root=live:https://github.com/kairos-io/kairos/releases/download/v2.4.0-k3sv1.27.3+k3s1/kairos-standard-opensuse-tumbleweed-amd64-generic-v2.4.0-k3sv1.27.3+k3s1.squashfs initrd=kairos-standard-opensuse-tumbleweed-amd64-generic-v2.4.0-k3sv1.27.3+k3s1-initrd rd.neednet=1 ip=dhcp rd.cos.disable netboot nodepair.enable config_url= console=tty1 console=ttyS0 rd.live.overlay.overlayfs
```

It's a little hard to read, but the kernel URL is `https://github.com/kairos-io/kairos/releases/download/v2.4.0-k3sv1.27.3+k3s1/kairos-standard-opensuse-tumbleweed-amd64-generic-v2.4.0-k3sv1.27.3+k3s1-kernel`. You will get a 404 if you try to download it. Specifically, that URL contains the substring `releases/download/v2.4.0-k3sv1.27.3+k3s1/`, which has a superfluous `-k3sv1.27.3+k3s1`.

Note, moreover, that this superfluous substring appears multiple times throughout the script. Consequently this script (and the corresponding `*.ipxe-usb.img` asset, probably also the `*.ipxe.iso` one) are unusable.

**Comment by mauromorales** [comment]
In 2.4.2 the issue is that the version is not present at all 

```
https://github.com/kairos-io/kairos/releases/download//kairos-opensuse-leap-15.5-core-amd64-generic-v2.4.2-rc1-kerne
```

**Comment by mauromorales** [comment]
@jbalonso thanks a lot for the report 🙌
