### ISSUE TITLE
Surface immucore errors without requiring debug flags in GRUB

### ISSUE THREAD

**Issue by TylerGillson** [kairos-io/kairos#1989]
**Is your feature request related to a problem? Please describe.**
I spent several days attempting to debug https://github.com/kairos-io/kairos/issues/1979, which turned out to be a panic in `provider-k3s` and wasn't able to figure out the root issue until @jimmykarily showed me the procedure outlined [here](https://github.com/spectrocloud/CanvOS/blob/two-node/hack/README.md) (basically, booting with `rd.debug rd.immucore.debug` added to the linux line in GRUB).

It would be fantastic if the error being logged [here](https://github.com/kairos-io/kairos-agent/blob/main/internal/bus/bus.go#L61) was surfaced to the end user without having to jump through so many hoops.

**Describe the solution you'd like**
Preserve immucore logs after each boot (error logs at a minimum). Maybe this already exists and I'm just ignorant!

**Describe alternatives you've considered**
N/A

**Additional context**
Relevant excerpt of immucore logs:
```
[   54.640781] immucore[573]: time="2023-11-07T20:57:44Z" level=error msg="Provider k3s at /system/providers/agent-provider-k3s had an error: error while executing plugin: exit status 2panic: reflect: call of reflect.Value.Elem on struct Value\n\ngoroutine 1 [running]:\nreflect.Value.Elem({0x663000?, 0xc00013c480?, 0x28?})\n\t/usr/local/go/src/reflect/value.go:1271 +0x193\ngithub.com/mcuadros/go-defaults.(*Filler).getFields(0xd?, {0x663000?, 0xc00013c480?})\n\t/go/pkg/mod/github.com/mcuadros/go-defaults@v1.2.0/filler.go:34 +0x74\ngithub.com/mcuadros/go-defaults.(*Filler).Fill(0x1?, {0x663000?, 0xc00013c480?})\n\t/go/pkg/mod/github.com/mcuadros/go-defaults@v1.2.0/filler.go:29 +0x25\ngithub.com/mcuadros/go-defaults.SetDefaults({0x663000?, 0xc00013c480?})\n\t/go/pkg/mod/github.com/mcuadros/go-defaults@v1.2.0/defaults.go:25 +0x73\nmain.clusterProvider({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0xc000162a20, 0x0, ...})\n\t/build/main.go:37 +0xa5\ngithub.com/kairos-io/kairos-sdk/clusterplugin.ClusterPlugin.onBoot({0xc00015dbe8?}, 0xc000162510)\n\t/go/pkg/mod/github.com/!tyler!gillson/kairos-sdk@v0.0.2-dev/clusterplugin/plugin.go:48 +0x195\ngithub.com/mudler/go-pluggable.PluginFactory.Run(0x6486e0?, {0x7ffece9a5eef, 0xa}, {0x6dffe0, 0xc000038028}, {0x6dfec0, 0xc000038030})\n\t/go/pkg/mod/github.com/mudler/go-pluggable@v0.0.0-20230126220627-7710299a0ae5/factory.go:94 +0x2ce\ngithub.com/kairos-io/kairos-sdk/clusterplugin.ClusterPlugin.Run({0x60?})\n\t/go/pkg/mod/github.com/!tyler!gillson/kairos-sdk@v0.0.2-dev/clusterplugin/plugin.go:82 +0x17c\nmain.main()\n\t/build/main.go:245 +0x1a\n\n: failed to run kairos-agent notify agent.boot: exit status 1"
[   54.698309] immucore[573]: time="2023-11-07T20:57:44Z" level=error msg="1 error occurred:\n\t* failed to run kairos-agent notify agent.boot: exit status 1\n\n"
```
Full logs are available if that would be helpful.

**Comment by jimmykarily** [comment]
There are 2 parts to this:

- accessing the boot logs without having to pipe to a file (like we did with qemu locally)
- accessing the verbose logs

The first part you can avoid but looking at `cat /run/immucore/*` files after boot.
The second one needs you to add cmdline arg because the logs became way too noisy. Normally, the error should popup without `rd.immucore.debug` being set. Being in `level=error` means we didn't really need to add `rd.immucore.debug` to see it.

Are the above ok enough? Can I close this issue?

**Comment by TylerGillson** [comment]
Thanks @jimmykarily. I was unaware that boot logs could be found under `/run/immucore/`. Knowing that would have saved a lot of time! Closing the issue.

**Comment by jimmykarily** [comment]
> Thanks @jimmykarily. I was unaware that boot logs could be found under `/run/immucore/`. Knowing that would have saved a lot of time! Closing the issue.

Yes, me neither :D . Let's make sure this doesn't happen again: https://github.com/kairos-io/kairos-docs/pull/104
