### ISSUE TITLE
:bug: Adapt kairos upgrade list-releases command to handle new repositories

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1999]
- [ ] we don't let the provider return values, we handle everything in the agent. [link1](https://github.com/kairos-io/kairos-agent/blob/main/internal/agent/upgrade.go#L37) [link2](https://github.com/kairos-io/provider-kairos/blob/main/internal/provider/upgrade.go#L17) - What about other providers? Shouldn't they be able to return new versions with their own logic? We can simply use the same implementation in kairos-agent and provider-kairos and let other providers handle that as they want.
- [ ] by default we filter from the existing attributes that the current image has, e.g. if it's amd64 we only show amd64 and so on for the rest of the attributes, which means we need a place to save model. Maybe the best is to keep it in os-release like we already do for most attributes
- [ ] maybe an option to show all tags without smart filtering
- [ ] ensure that the output can be used to copy paste and use in `kairos-agent upgrade --source` or some fancy selector

relates to https://github.com/kairos-io/kairos/issues/1998

**Comment by jimmykarily** [comment]
wip branch: https://github.com/kairos-io/kairos-sdk/tree/1999-introduce-versioneer

I will move all logic to golang so that we can implement other things like:

- given an artifact name, what is the flavor?
- given an artifact name, what is the next version of the same arch/model/etc
- etc

**Comment by jimmykarily** [comment]
We need this change: https://github.com/kairos-io/kairos/discussions/2035

**Comment by jimmykarily** [comment]
The upgrade with no version passed must have been broken for a while:

```
localhost:/home/kairos # kairos-agent upgrade
INFO[2023-12-07T15:50:46Z] kairos-agent version v2.4.1                  
[  134.766809][ T1731] EXT4-fs (vda3): mounted filesystem with ordered data mode. Opts: (null). Quota mode: n.
sanitizing the upgrade spec: undefined upgrade source
```
because we sanitize the spec before we handle the empty source. I guess, since nobody complained, it's ok to deprecate that feature and always require a version.

**Comment by jimmykarily** [comment]
Instead of re-implementing the `ListReleases` in provider-kairos, I will simply make it return an empty list. This makes the kairos-agent use it's own logic to find available releases, with the same result.

**Comment by mauromorales** [comment]
> because we sanitize the spec before we handle the empty source. I guess, since nobody complained, it's ok to deprecate that feature and always require a version.

Didn't Santosh mentioned they were using it? not sure in which version they are atm ... but I agree, probably it's not being relied on so it's safe to remove

**Comment by mauromorales** [comment]
We need to make sure this does not break other provider upgrades because of the removal of the bus https://github.com/kairos-io/kairos/issues/2072
