### ISSUE TITLE
Error in documentation : generated an iso manually

### ISSUE THREAD

**Issue by fafarun** [kairos-io/kairos#2007]
**Kairos version:**
latest

**Describe the bug**
In the documentation [automated](https://kairos.io/docs/installation/automated/)

the example to generate an iso manually failed. 
the file `grub.cfg` was removed from there kairos repo

```
wget https://raw.githubusercontent.com/kairos-io/kairos/master/overlay/files-iso/boot/grub2/grub.cfg -O files-iso/boot/grub2/grub.cfg
```

**To Reproduce**
play the chapter manually in the automated documentation 

**Expected behavior**
wget can download the `grub.cfg` file 

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
This was fixed at some point, thanks for the report @fafarun
