### ISSUE TITLE
Raw images not booting

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2025]
>  when I covert the raw image to qcow2 and run via qemu using the following commands:sudo dd if=build/disk.raw of=kairos.img bs=4M conv=notrunc ;sudo qemu-img convert -f raw -O qcow2 kairos.img kairos.qcow2;sudo qemu-system-x86_64 -m 4096 -hda kairos1.qcow2 -bios /usr/share/qemu/ovmf-x86_64.bin -nographic. I am stuck in a loop: Kairos recovery boot menu automatically-> rebooting -booting i Kairos -> giving error-> trying other options and falling back to Kairos recovery . Is this expected behavior or am i am missing any steps?

https://spectrocloudcommunity.slack.com/archives/C04B1833NEA/p1701067930216879?thread_ts=1700818247.706069&cid=C04B1833NEA

![image](https://github.com/kairos-io/kairos/assets/433958/cc185ae3-864e-48ca-a785-28125cdec153)

**Comment by jimmykarily** [comment]
This ticket is missing some very important information:
- what image was used (kairos version flavors etc)
- what cloud-config was used

and the original Slack thread is no longer available. I'm close this. If someone faces this problem, they can open a new ticket with proper reproducing steps.
