### ISSUE TITLE
kairos-network module failing when building initramfs

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#2032]
**Kairos version:**
master framework images

On Fedora using the dockerfile from https://kairos.io/docs/reference/build-from-scratch/:
```
0.343 dracut: dracut module 'kairos-network' depends on 'network-legacy', which can't be installed
0.402 dracut: dracut module 'kairos-network' cannot be found or installed.
```

**Comment by Itxaka** [comment]
its missing the `dhcp-client` which Im guessing brings enough stuff so the module can be installed as expected.

**Comment by mudler** [comment]
is this still relevant? @Itxaka

**Comment by Itxaka** [comment]
> is this still relevant? @Itxaka 

Niet
