### ISSUE TITLE
There are no install logs when net booting from AuroraBoot

### ISSUE THREAD

**Issue by sarg3nt** [kairos-io/kairos#2033]
There are no install logs when net booting from AuroraBoot.  I worked with @jimmykarily to try and find them and we came up with nothing.  

This makes troubleshooting install issues extremely difficult and I've wasted a lot of time doing deployments and trying to take screenshots during the install process to find issues, which is extremely frustrating.  

**Recommended resolution steps:**
1. Save install logs so they are visible with `journalctl` post installation.
2. Document where the install logs are in the Kairos documentation and how to easily view them with `journalctl`

**Kairos version:**
This is using a master build as of 11/27/2023

```bash
./earthly.sh +iso \
  --FAMILY=rhel \
  --FLAVOR=rockylinux \
  --FLAVOR_RELEASE=9 \
  --BASE_IMAGE=rockylinux:9 \
  --MODEL=generic \
  --VARIANT=core;
```

**CPU architecture, OS, and Version:**
AMD/64 Rocky Linux 9 core

**Comment by mauromorales** [comment]
relates to https://github.com/kairos-io/kairos/issues/1393

**Comment by jimmykarily** [comment]
Maybe also to this: https://github.com/kairos-io/packages/pull/544 ? The fix will be there in the upcoming 2.4.3 release. We should check if it also fixes netbooting logs.

**Comment by jimmykarily** [comment]
We missed one here: https://github.com/kairos-io/AuroraBoot/blob/9e4aad8338f1326c3ba7801c705210964136ef5e/pkg/ops/netboot.go#L32C5-L32C5 (tty1 should come after ttyS0 for journalctl to pick it as the default system console). We should give it a try. Maybe that will fix it.

**Comment by sarg3nt** [comment]
I cloned the AuroraBot repo and made that change
```go
cmdLine := `rd.live.overlay.overlayfs rd.neednet=1 ip=dhcp rd.cos.disable root=live:{{ ID "%s" }} netboot nodepair.enable config_url={{ ID "%s" }} console=ttyS0 console=tty1 console=tty0`
```
built the docker image with `docker build` and used that image to start AuroraBoot and deploy a server.
Still no logs on the created server node before the reboot.

**Comment by sarg3nt** [comment]
I cloned the AuroraBot repo and made that change
```go
cmdLine := `rd.live.overlay.overlayfs rd.neednet=1 ip=dhcp rd.cos.disable root=live:{{ ID "%s" }} netboot nodepair.enable config_url={{ ID "%s" }} console=ttyS0 console=tty1 console=tty0`
```
built the docker image with `docker build` and used that image to start AuroraBoot and deploy a server.
Still no logs on the created server node before the reboot.
