### ISSUE TITLE
on reset the node moves into cos-recovery login

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#2038]
**Kairos version:**
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
KAIROS_NAME="kairos-core-ubuntu"
KAIROS_VERSION="v2.4.2"
KAIROS_ID="ubuntu"
KAIROS_ID_LIKE="kairos-core-ubuntu"
KAIROS_VERSION_ID="v2.4.2"
KAIROS_PRETTY_NAME="kairos-core-ubuntu v2.4.2"
KAIROS_BUG_REPORT_URL="https://github.com/spectrocloud/CanvOS/issues"
KAIROS_HOME_URL="https://github.com/spectrocloud/CanvOS"
KAIROS_IMAGE_REPO="spectrocloud/CanvOS"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO=""
KAIROS_VARIANT="ubuntu"
KAIROS_FLAVOR="ubuntu"
KAIROS_ARTIFACT=""
```

**CPU architecture, OS, and Version:**
Linux edge-bae03842a2779c726da656afc7842a55 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
   On reset it goes into reset properly on the grubmenu and gets started. And gets into cos-recovery login and does not execute further after-reset stages and move to registration.
   At this stage if I run the command manually, '/usr/bin/kairos-agent reset --unattended --reboot'
   reset succeeds.
   

**To Reproduce**
`
run the following commands
/usr/bin/grub2-editenv /oem/grubenv set next_entry=statereset
shutdown -r now

The grubmenu.cfg is as below 
```
menuentry "Palette eXtended Kubernetes Edge Reset" --id statereset {
    set img=/cOS/recovery.img
    search.fs_label COS_RECOVERY root
    set label=COS_SYSTEM
    loopback loop0 /$img
    set root=($root)
    source (loop0)/etc/cos/bootargs.cfg
    linux (loop0)$kernel $kernelcmd ${extra_cmdline} ${extra_recovery_cmdline} kairos.reset
    initrd (loop0)$initramfs
}

menuentry "Palette eXtended Kubernetes Edge Registration" --id registration {
    search --no-floppy --label --set=root COS_STATE
    set img=/cOS/active.img
    set label=COS_ACTIVE
    loopback loop0 /$img
    set root=($root)
    source (loop0)/etc/cos/bootargs.cfg
    linux (loop0)$kernel $kernelcmd ${extra_cmdline} ${extra_active_cmdline} stylus.registration
    initrd (loop0)$initramfs
}
```

in /system/oem/80_stylus.yaml we have a stage which defines the after-reset behavior

  after-reset-chroot:
  - commands:
    - grub2-editenv /oem/grubenv set saved_entry=registration
    name: "Set registration grub env entry after reset"

`

**Expected behavior**
reset and then reboot into registration

**Logs**
<img width="1400" alt="Screenshot 2023-11-30 at 12 46 00 PM" src="https://github.com/kairos-io/kairos/assets/504862/80967002-8888-4cab-9176-8a05ba5f05ed">

```
cos-recovery:~ # systemctl status kairos-reset
x kairos-reset.service - kairos reset
     Loaded: loaded (/etc/systemd/system/kairos-reset.service; enabled; vendor preset: disabled)
     Active: failed (Result: signal) since Thu 2023-11-30 07:03:55 UTC; 11min ago
    Process: 1324 ExecStart=/usr/bin/kairos-agent reset --unattended --reboot (code=killed, signal=HUP)
   Main PID: 1324 (code=killed, signal=HUP)
```

```
Nov 30 07:03:27 edge-6fb5384239248d5dd09dfb79560ef300 systemd[1]: Starting kairos reset...
Nov 30 07:03:37 cos-recovery /system/providers/agent-provider-stylus[1388]: time="2023-11-30T07:03:37Z" level=info msg="Starting agent-provider-stylus version v0.0.0-f33d346a"
Nov 30 07:03:37 cos-recovery /system/providers/agent-provider-stylus[1388]: time="2023-11-30T07:03:37Z" level=info msg="starting stylus reset plugin"
Nov 30 07:03:55 cos-recovery systemd[1]: kairos-reset.service: Main process exited, code=killed, status=1/HUP
Nov 30 07:03:55 cos-recovery systemd[1]: kairos-reset.service: Failed with result 'signal'.
Nov 30 07:03:55 cos-recovery systemd[1]: Failed to start kairos reset.
```

**Additional context**
This was working fine in kairos v2.3.2 and device used to move into registration state after reset.

**Comment by Itxaka** [comment]
umm, setting a normal reset worked for me...

- using `kairos-core-opensuse-leap-amd64-generic-v2.4.0`
-  `/usr/bin/grub2-editenv /oem/grubenv set next_entry=statereset`
- reboot
- it picks the proper entry
- it resets
- and reboots

gonna try adding a stage on the after-reset-chroot hook to see what could be the issue with that.

**Comment by Itxaka** [comment]
umm with the following custom config:

```
name: "Testing after reset hook"
stages:
  after-reset-chroot:
    - name: "TEST"
      commands:
        - touch /oem/reset 
```

And doing a reset(auto), after boot I get:

```
localhost:~ # ls /oem/
10_custom.yaml	90_custom.yaml	grubenv  lost+found  reset
```

so ITS running the stage, gonna check if its a grub2-edit issue or something

**Comment by Itxaka** [comment]
also @santhoshdaivajna you pasted a os-release from ubuntu but the reset says its opensuse?

Can you clarify which is it???

**Comment by Itxaka** [comment]
This seems to be a non-supported workflow

opensuse install -> upgrade to ubuntu -> reset from recovery (which is opensuse btw, unless the recovery has also been upgraded to ubuntu with the `--recovery` flag)

Has been confirmed to not happen with a ubuntu install -> upgrade -> reset from recovery

**Comment by santhoshdaivajna** [comment]
tried with a ubuntu installer and then to ubuntu upgrade image and then reset the node 

It got to a different screen this time but still in cos-recovery.

<img width="890" alt="Screenshot 2023-12-02 at 10 28 31 AM" src="https://github.com/kairos-io/kairos/assets/504862/9877eb30-ab2f-4ce0-b99f-d76157a558b2">

```root@cos-recovery:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
KAIROS_NAME="kairos-core-ubuntu"
KAIROS_VERSION="v2.4.2"
KAIROS_ID="ubuntu"
KAIROS_ID_LIKE="kairos-core-ubuntu"
KAIROS_VERSION_ID="v2.4.2"
KAIROS_PRETTY_NAME="kairos-core-ubuntu v2.4.2"
KAIROS_BUG_REPORT_URL="https://github.com/spectrocloud/CanvOS/issues"
KAIROS_HOME_URL="https://github.com/spectrocloud/CanvOS"
KAIROS_IMAGE_REPO="spectrocloud/CanvOS"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO=""
KAIROS_VARIANT="ubuntu"
KAIROS_FLAVOR="ubuntu"
KAIROS_ARTIFACT="kairos-core-ubuntu-v2.4.2```

```
root@cos-recovery:~# systemctl status kairos-reset
× kairos-reset.service - kairos reset
     Loaded: loaded (/etc/systemd/system/kairos-reset.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Sat 2023-12-02 04:35:17 UTC; 22min ago
    Process: 1235 ExecStart=/usr/bin/kairos-agent reset --unattended --reboot (code=killed, signal=HUP)
   Main PID: 1235 (code=killed, signal=HUP)
        CPU: 1.502s

Dec 02 04:35:10 edge-41f838422d577063d617e008e741dc1f systemd[1]: Starting kairos reset...
Dec 02 04:35:13 cos-recovery /system/providers/agent-provider-stylus[1564]: time="2023-12-02T04:35:13Z" level=info msg="Starting agent-provider-stylus version v4.2.0-alpha5"
Dec 02 04:35:13 cos-recovery /system/providers/agent-provider-stylus[1564]: time="2023-12-02T04:35:13Z" level=info msg="starting stylus reset plugin"
Dec 02 04:35:17 cos-recovery systemd[1]: kairos-reset.service: Main process exited, code=killed, status=1/HUP
Dec 02 04:35:17 cos-recovery systemd[1]: kairos-reset.service: Failed with result 'signal'.
Dec 02 04:35:17 cos-recovery systemd[1]: Failed to start kairos reset.
Dec 02 04:35:17 cos-recovery systemd[1]: kairos-reset.service: Consumed 1.502s CPU time.
```

**Comment by Itxaka** [comment]
ah no, I didnt select the proper entry xD

**Comment by jimmykarily** [comment]
@santhoshdaivajna is this still an issue? I see a thread in Slack that suggests this was fixed. If not please re-open.
