### ISSUE TITLE
UKI: (kairos-agent) install

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2049]
Follow-up of #1151 #872 

Currently, doing a UKI installation is a manual thing. There is a subcommand to do a UKI installation. We can to make this automated. `kairos-agent` should detect that is has booted a UKI image and should do a UKI installation if that's the case.

## Acceptance Criteria

- All installation types (automated, manual, interactive) should all perform a UKI installation when system is booted with UKI https://github.com/kairos-io/kairos-agent/pull/196 and https://github.com/kairos-io/kairos-agent/pull/198
- Remove the hardcoded `kairos` user that we added for UKI https://github.com/kairos-io/packages/pull/608
- Check that datasource also works with the above installation types.

**Comment by Itxaka** [comment]
- interactive install works perfectly
 - normal install passing a cc doesnt seem to work as expected, final config doesnt appear to be there, investigating
 - datasources work as expected

**Comment by Itxaka** [comment]
manual install DOES work actually, I just screwed the tests :)
