### ISSUE TITLE
change permissions of /oem/90_custom.yaml to 0640

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#2057]
**Kairos version:**
v2.4.x

**CPU architecture, OS, and Version:**
Linux amd64 ubuntu 22.04

**Describe the bug**
After installation the file in /oem/90_custom.yaml might contain sensitive info. The file permissions get set to 0666, it needs to be reduced to 0640.

**To Reproduce**

**Expected behavior**
/oem/9%d_custom.yaml file permissions set to 0640

**Logs**
```
# ls -alh /oem
total 64K
drwxrwx---  4 root admin 4.0K Nov 30 19:13 .
drwxr-xr-x 21 root root  4.0K Dec  6 10:41 ..
-rw-r--r--  1 root admin 1.2K Dec  6 11:03 .stylus-state
-r--------  1 root admin  411 Dec  5 12:17 10_user_custom_mounts.yaml
-rw-r--r--  1 root admin  14K Dec  6 10:40 80_stylus.yaml
-rw-rw-rw-  1 root admin 2.8K Dec  5 12:17 90_custom.yaml
```

**Additional context**

**Comment by antongisli** [comment]
@mudler can you guys double check there are no other unnecessary permissions with world read/write?
