### ISSUE TITLE
Runinng `kubectl logs` results in an error: `failed to create fsnotify watcher: too many open files`

### ISSUE THREAD

**Issue by tyzbit** [kairos-io/kairos#2071]
**Kairos version:**
```
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
KAIROS_NAME="kairos-kairos-debian"
KAIROS_VERSION="v2.4.1-k3sv1.27.3+k3s1"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-kairos-debian"
KAIROS_VERSION_ID="v2.4.1-k3sv1.27.3+k3s1"
KAIROS_PRETTY_NAME="kairos-kairos-debian v2.4.1-k3sv1.27.3+k3s1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/kairos-debian"
KAIROS_IMAGE_LABEL=""
KAIROS_GITHUB_REPO="kairos-io/provider-kairos"
KAIROS_VARIANT="kairos"
KAIROS_FLAVOR="debian"
```

**CPU architecture, OS, and Version:**
Linux myocyte4-axece 6.5.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1 (2023-09-13) x86_64 GNU/Linux

**Describe the bug**
When running `kubectl logs -f [podname]`, `kubectl` returns an error "failed to create fsnotify watcher: too many open files". This may cause other issues under the hood due to being unable to open new files on the node. I saw issues with Longhorn being unable to completely transfer replicas, but I was unable to pin down if this specific issue was causing it as I also discovered an issue causing packet loss in my cluster.

**To Reproduce**
Not 100% clear, this was on a moderately used cluster using Debian 2.4.1. and Longhorn.

**Expected behavior**
An adequately high threshold of files can be opened and `kubectl logs` does not return an error.

**Logs**
`failed to create fsnotify watcher: too many open file`

See also: https://github.com/derailed/k9s/issues/1399

**Additional context**
Adding this to my cloud_config solved the issue, and I suspect including the sysctl settings in the appropriate base images is probably a good thing:

```
  initramfs:
    - name: Increase number of open files
      sysctl:
        fs.inotify.max_user_instances: "8192"
        fs.inotify.max_user_watches: "524288"
```

Some users actually already had some of these settings set in their configs in a couple existing (and unrelated) issues.

**Comment by jimmykarily** [comment]
Since the actual setting is depending on various factors, maybe it's better to document this instead of hardcoding some values. @tyzbit what do you think?

**Comment by mauromorales** [comment]
https://github.com/spectrocloud/cluster-api/blob/bf9c1902182acddc1aebb553081e7cf9d5d9df3f/docs/book/src/user/troubleshooting.md?plain=1#L117-L125

**Comment by tyzbit** [comment]
@jimmykarily I think documenting it is great, but when a node has too many files open, `kubectl` is the least of its worries. Node stability overall is at risk.

I think picking a reasonable default that prevents users from encountering this bug would be good and the user can override the default settings via the sysctl steps in the cloud_config. It could be calculated or a static "one-size-fits-most" value. Otherwise I could see this being a "gotcha" that many users run into where they get punished for not reading documentation and knowing what they'll need in advance.

What are the implications if we pick a value that is too high for a system? Overall system lag?

**Comment by jimmykarily** [comment]
I'm not sure. But it seems that is was a problem in the past, then they tried to fix in in Kubernetes and then the problem was back: https://github.com/kubernetes/kubernetes/issues/64315

People are working around the issue by setting the value to the magic number `8192` (or magic spell if you prefer). 
Kairos has the default value of 128: 

```
localhost:~ # sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 128
```

We can try to bump it. What can possibly go wrong @kairos-io/maintainers ?

**Comment by jimmykarily** [comment]
Something like this: https://github.com/kairos-io/packages/pull/604/files

**Comment by tyzbit** [comment]
FWIW ChatGPT says

> Increased Resource Usage: Each inotify instance consumes system resources. Setting the limit too high may lead to excessive memory and CPU usage, potentially impacting system performance.

> File Descriptor Exhaustion: Inotify instances are managed using file descriptors. If the limit is set too high, it can lead to the exhaustion of available file descriptors, causing issues with other system operations.

> Kernel Resource Saturation: The inotify subsystem relies on kernel resources to maintain instances and handle events. Setting the limit excessively high may saturate these resources, potentially leading to instability or crashes.

> Denial of Service (DoS) Potential: If a user or application can create an excessive number of inotify instances, it might be used as a vector for a denial-of-service attack. By consuming all available resources, the system could become unresponsive to other legitimate activities.

> Performance Impact: While inotify is designed to be efficient, setting the instance limit too high can still have a performance impact. The system has to manage and process a larger number of inotify events, affecting overall responsiveness.

Kairos (at least debian) has a ridiculously high file descriptor limit:

```
cat /proc/sys/fs/file-max
9223372036854775807
```

To me, it seems this should be low-risk but something to be on the lookout for with users posting new vague issues that reference resource exhaustion, OOMKills, etc

**Comment by jimmykarily** [comment]
Makes sense. Merging. Thanks @tyzbit for reporting.
