### ISSUE TITLE
Evaluate moving framework installation outside of root dir

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2076]
Currently, when we are running the factory, we take the framework image and copy everything we find to the root directory.

```
boot    etc     system  usr     var
```

```
COPY --from=framework / /
```

It seems there are some reported issues related to this: https://github.com/kairos-io/kairos-framework/pull/17#issuecomment-1852081522

For me, it is not clear why this would be an issue since the contents of the framework image are exclusive to what was installed with Luet. So the question is, can we copy the framework content somewhere else? And what does that imply?

**Comment by jimmykarily** [comment]
The problem I mentioned was only with kaniko (more like a bug). It should be ok do do it like we do it here. If we ever have to build with kaniko and it doesn't work, we'll work around it then.
