### ISSUE TITLE
:bug: Upgrade issues

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2084]
Original report by Piyush Kumar:

> While doing upgrade on 3-node cluster, upgrade succeeded on one node and failed on other two even if it says that in the end that upgrade is completed. Attaching two logs file from the nodes where one failed and succeeded. One the failed upgrade node, we see the msg as upgrade completed but cat /proc/cmdline indicates upgrade_failure

Private discussion: https://spectrocloud.slack.com/archives/C056VJ4V1HP/p1702485749281219

**Comment by jimmykarily** [comment]
It was communicated internally that the failing cluster was under heavy load. By switching to another cluster the problem went away. Closing.
