### ISSUE TITLE
🤖 Install Go step of our jobs, constantly gets stuck

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2134]
This is happening more and more often. It spends hours trying to download but not making any progress. It would be nice to have a time limit for this step, or ideally to resolve the root cause.

**Comment by mauromorales** [comment]
Itxaka mentions that GH runners have it on cache, maybe we should do the same.

Let's add some examples

**Comment by mauromorales** [comment]
For what I see, the process seems to be working correctly until it hits the following:

```
 Received 67108864 of 376393923 (17.8%), 0.4 MBs/sec
Received 71303168 of 376393923 (18.9%), 0.4 MBs/sec
Warning: Failed to restore: downloadSegmentRetry failed due to timeout
Cache is not found
go version go1.20.12 linux/amd64
go env
Received 71303168 of 376393923 (18.9%), 0.4 MBs/sec
Received 71303168 of 376393923 (18.9%), 0.4 MBs/sec
Received 71303168 of 376393923 (18.9%), 0.4 MBs/sec
Received 71303168 of 376393923 (18.9%), 0.4 MBs/sec
```

There's no progress after that.

I will make this higher prio since the UKI test does not pass because of this, already tried multiple times.

**Comment by mauromorales** [comment]
contents of the `go env` section in the previous comment:

```
go env
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct/"
  GOROOT="/opt/hostedtoolcache/go/1.20.12/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.20.12/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.20.12"
  GCCGO="gccgo"
  GOAMD64="v1"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="0"
  GOMOD="/dev/null"
  GOWORK=""
  CGO_CFLAGS="-O2 -g"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-O2 -g"
  CGO_FFLAGS="-O2 -g"
  CGO_LDFLAGS="-O2 -g"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4187256804=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by mauromorales** [comment]
If I understand correctly, the caching is still done on GH side

> When using self-hosted runners, caches from workflow runs are stored on GitHub-owned cloud storage. A customer-owned storage solution is only available with GitHub Enterprise Server.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by Itxaka** [comment]
> If I understand correctly, the caching is still done on GH side
> 
> > When using self-hosted runners, caches from workflow runs are stored on GitHub-owned cloud storage. A customer-owned storage solution is only available with GitHub Enterprise Server.
> 
> [docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

isnt that for the deps with the cache action? We are talking about the setup-go action here, which stores the downloaded go under `/opt/hostedtoolcache/go/`

Im pretty sure that if we make the k8s runnners use a volume and attach it to `/opt/hostedtoolcache/` we will see the download being skipped and reusing the cached go

**Comment by mauromorales** [comment]
@Itxaka good question, you might be right, worth a try.

**Comment by mauromorales** [comment]
Followed Itxaka suggestion together with Dimitris and it seems to be working. We will let it run a bit before we try to implement any of the other suggested mounts because we don't really know how those will handle multiple go versions with multiple projects

https://github.com/kairos-io/infra-as-code/commit/27981c6610efaf850c76f1e058cd1f283fbd89d3

**Comment by mauromorales** [comment]
Issue seems to have been fixed, but will keep here a couple of days to monitor

**Comment by mauromorales** [comment]
Turns out it didn't work because the VPC could not be shared. So we went back and just made it use a local directory from the host

**Comment by mauromorales** [comment]
This is working as expected now, but we will need a mechanism to cleanup eventually and we also need to put in code the creation and permissions of `/opt/hostedtoolcache/`



https://github.com/kairos-io/kairos/issues/2155

https://github.com/kairos-io/kairos/issues/2156
