### ISSUE TITLE
Support for Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by cloudmaniac** [kairos-io/kairos#2138]
**Ubuntu 24.04 LTS** (Noble Numbat) is planned for April 25, 2024. We would like to get the support for a new core image based on this new version as some customers will require it.

A similar feature request was created to [support Ubuntu 22.04](https://github.com/kairos-io/kairos/issues/150). Based on [this comment](https://github.com/kairos-io/kairos/issues/150#issuecomment-1272909504)

# Test the following releases

- [x] #2241
- [x] #2480 

# Artifacts and Cleanup

- [x] https://github.com/kairos-io/kairos/pull/2447

**Comment by mauromorales** [comment]
@mudler @cloudmaniac What does that mean for our other LTS releases? Do we support them all the way till their EOL dates? Or do we plan to roll the versions and only keep a certain number of LTSs? e.g. stop building 20.04 artifacts as soon as 24.04 is released

**Comment by mudler** [comment]
> @mudler @cloudmaniac What does that mean for our other LTS releases? Do we support them all the way till their EOL dates? In the case of 20.04 this is 2030 for example. Or do we plan to roll the versions and only keep a certain number of LTSs? e.g. stop building 20.04 artifacts as soon as 24.04 is released

It would make sense to me to just keep LTSes until their end of standard support for now (not EOL) - all the rest can be cut off (intermediary releases, latest). But I'd like to hear what @cloudmaniac 's thoughts are on it.

https://wiki.ubuntu.com/Releases for reference

**Comment by mauromorales** [comment]
Blocks RPi https://github.com/kairos-io/kairos/issues/2249

**Comment by cloudmaniac** [comment]
> It would make sense to me to just keep LTSes until their end of standard support for now (not EOL) - all the rest can be cut off (intermediary releases, latest). But I'd like to hear what @cloudmaniac 's thoughts are on it.

I didn't forgot about that question: I agree with that statement @mudler but I'm still checking internally as I may not have the final word on this. 😅

**Comment by mauromorales** [comment]
btw @cloudmaniac with current master of Kairos, you should be able to build 24.04 for amd64, feel free to test it out and let me know if you find any issues. We are not yet producing artifacts ourselves, but this way you can already find out if there's any requirements that aren't met by the base image.

**Comment by mauromorales** [comment]
Regarding the artifact cleanup, the EOL for 23.10 is July 24, I think we should move that into an independent ticket because we might even have to delay that a bit to avoid braking the flow of anyone depending on this version. But if we do so, we must be very clear that the version is not supported so security wise is a bad idea
