### ISSUE TITLE
Order of sections in stages section affects if they apply or not

### ISSUE THREAD

**Issue by robarnold** [kairos-io/kairos#2146]
**Kairos version:**
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
KAIROS_NAME="kairos-kairos-ubuntu"
KAIROS_VERSION="v2.4.0-k3sv1.27.3+k3s1"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-kairos-ubuntu"
KAIROS_VERSION_ID="v2.4.0-k3sv1.27.3+k3s1"
KAIROS_PRETTY_NAME="kairos-kairos-ubuntu v2.4.0-k3sv1.27.3+k3s1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/kairos-ubuntu"
KAIROS_IMAGE_LABEL=""
KAIROS_GITHUB_REPO="kairos-io/provider-kairos"
KAIROS_VARIANT="kairos"
KAIROS_FLAVOR="ubuntu"

**CPU architecture, OS, and Version:**
amd64

**Describe the bug**

I'm trying to get Kairos to format a second disk after install (I didn't know how to do it on first install and don't want to reinstall the node). I'm following [the documentation](https://kairos.io/docs/reference/configuration/#layout) but it gives a simplified example. I already had some extra configuration for the `initramfs` stage, so I put the `boot` section afterwards:
```
stages:
  initramfs:
    # ...
  boot:
    # Does not execute
```
My new boot stage was not listed in the logs after boot. If I swap the ordering though, now I see logs in `journalctl -b 0` that show it trying to execute (and failing because of other mistakes/misunderstandings I made).
```
stages:
  boot:
    # Executes!
  initramfs:
    # ...
```

My mental model of YAML is that the order of the keys does not matter to the machine, only the user. I found this behavior very surprising and I'm hoping it's not intentional.

**Comment by mauromorales** [comment]
@robarnold I was testing this, but I don't see an issue executing commands regardless of the order of these two stages. Could you share your entire cloud-config? This way we might validate if it's related to the config itself.

**Comment by mauromorales** [comment]
Thanks @robarnold, unfortunately I couldn't reproduce with the existing config. I will close for now, and we can re-open once we have a failing config to test with.

**Comment by robarnold** [comment]
Makes sense, thank you. If it comes up again, I'll save the configs.
