### ISSUE TITLE
:bug: Improve error message when upgrading with a wrong image

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2152]
If I do an upgrade with the wrong image source, I see a map error on the logs. Ideally, the check to access the resource could even happen before starting the process, to avoid running a hook in a pre-stage if the image will anyhow not be present

```
kairos-agent upgrade --source oci:quay.io/kairos/ubuntu:22.04-core-amd64-generic-v2.5.0 --recovery
....
INFO[2024-01-17T18:36:57Z] Copying quay.io/kairos/22.04-core-amd64-generic-v2.5.0:latest source to /run/cos/transition 
ERRO[2024-01-17T18:36:58Z] Failed deploying image to file '/run/cos/recovery/cOS/transition.img': GET https://quay.io/v2/kairos/22.04-core-amd64-generic-v2.5.0/manifests/latest: UNAUTHORIZED: access to the requested resource is not authorized; map[] 
1 error occurred:
	* GET https://quay.io/v2/kairos/22.04-core-amd64-generic-v2.5.0/manifests/latest: UNAUTHORIZED: access to the requested resource is not authorized; map[]

```

**Comment by Itxaka** [comment]
This was implemented recently in UKI upgrade!
https://github.com/kairos-io/kairos-agent/blob/main/pkg/config/spec.go#L583

There is even a note to maybe port that to everywhere :D

**Comment by asteurer** [comment]
@Itxaka I can't tell if this issue needs work? Was this taken care of in the UKI upgrade?

**Comment by Itxaka** [comment]
@asteurer nope! It was added only to the UKI upgrade, the normal upgrade ( or other places where we check against an OCI source) do not have that safety check!

**Comment by asteurer** [comment]
@Itxaka If you have time, I could use some help figuring out where else the improved error message needs to be implemented.

**Comment by mauromorales** [comment]
@asteurer I think this is the section where the check is done for UKI

https://github.com/kairos-io/kairos-agent/blob/main/pkg/config/spec.go#L756-L765

and it would need to go into this function

https://github.com/kairos-io/kairos-agent/blob/main/pkg/config/spec.go#L274
