### ISSUE TITLE
:bug: Partition configuration not working in v2.5.0

### ISSUE THREAD

**Issue by danielffischer** [kairos-io/kairos#2164]
**Kairos version:**
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**CPU architecture, OS, and Version:**
Linux localhost 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
With Upgrade to Kairos Image kairos/ubuntu:22.04-core-amd64-generic-v2.5.0 the cloud-config file creating partitions when using a iso, is behaving differently than in /kairos/ubuntu:22.04-core-amd64-generic-v2.4.3. Reproducing other partition sizes than configured.

We build our Image from a Dockerfile having this cloud config file to create a qcow2 file with 80GB in size:
```
#cloud-config

debug: true

install:
  auto: true
  device: /dev/vda
  reboot: false
  poweroff: false

  # default partitions
  # only 'oem', 'recovery', 'state' and 'persistent' objects allowed
  # Only size and fs should be changed here
  # size in MiB
  partitions:
    oem:
      size: 10
      fs: ext4
    recovery:
      size: 10736
      fs: ext4
    state:
      size: 32212
      fs: ext4
    persistent:
      size: 21474
      fs: ext4

  extra-partitions:
    - name: upgrade
      size: 0
      fs: ext4
      label: OS_UPGRADE

  extra-dirs-rootfs:
    - /upgrade

  # Override image sizes for active/passive/recovery
  # Note that the active+passive images are stored in the state partition and
  # the recovery in the recovery partition, so they should be big enough to accommodate te images sizes set below
  # size in MiB
  system:
    size: 8590
  passive:
    size: 8590
  recovery-system:
    size: 10600

reset:
  extra-dirs-rootfs:
    - /upgrade

upgrade:
  # Override image sizes for active/recovery
  # Note that the active+passive images are stored in the state partition and
  # the recovery in the recovery partition, so they should be big enough to accommodate te images sizes set below
  # size in MiB
  # During upgrade only the active or recovery image cna be resized as those are the ones that contain the upgrade
  # passive image is the current system, and that its untouched during the upgrade
  system:
    size: 8590
  recovery-system:
    size: 10600

  # Creates these dirs in the rootfs during upgrade. As the rootfs is RO from boot, sometimes we find that we
  # some applications want to write to non-standard paths like /data
  # If that dir is not already in the rootfs it makes it difficult to create that path on an RO system
  # This allows to create some extra paths in the rootfs that then we count use for mounting or binding via
  # the cloud-config stages
  extra-dirs-rootfs:
    - /upgrade

stages:
  kairos-install.pre.before:
    - if: '[ -e /dev/vdb ] && [ ! -e /dev/vdb1 ]'
      name: "Create /dev/vdb partitions"
      commands:
        - parted --script --align optimal /dev/vdb mklabel msdos -- mkpart primary ext4 1 -1
        - mkfs.ext4 -T news -L CONTENT -m 1 /dev/vdb1
  after-upgrade:
    - &copyconfig
      name: "Sync OEM config"
      if: "[ $(kairos-agent state get oem.found) = 'true' ] && [ -d '/etc/opt/oem' ]"
      commands:
        - |
          OEMDIR=/tmp/mnt/OEM
          OEMDEV=$(kairos-agent state get oem.name)
          mkdir -p ${OEMDIR}
          mount ${OEMDEV} ${OEMDIR}
          rm ${OEMDIR}/9[1-9]*.yaml
          cp -fv /etc/opt/oem/9[1-9]*.yaml ${OEMDIR}
          umount ${OEMDIR}
  after-reset:
    - <<: *copyconfig
  after-install:
    - <<: *copyconfig
```

Running this cloud config in an ISO Install will abort the Installation, saying there are two partitions configured to be resizeable (size=0). According to the documentation with this cloud-config file, only the extra_partition UPGRADE should be resizeable. 

This first error can be fixed by giving the extra_partition a fixed size (21474) and the persistent partition a size=0. With this the Kairos-Installer will install from the ISO but now the partitions will have sizes different from the configured ones. Only the extra_partition has its configured size. It seems like all sizes in the section partitions are ignored and replaced with some kind of defaults.

**Expected behavior**
We expected the resulting partitions to be the same size as configured (working in the v2.4.3 Release).

**Comment by mauromorales** [comment]
Hi @danielffischer, thanks for opening the issue, this is indeed an issue atm since `install.partitions` is unfortunately being ignored.

We are tracking the issue [here](https://github.com/kairos-io/kairos/issues/2159), but I'll keep yours open also to update you and to split the multiple issues in the other ticket

**Comment by danielffischer** [comment]
Thanks for the Info @mauromorales

**Comment by cheese** [comment]
Any plan for a fix?

**Comment by cheese** [comment]
But setting of `fs` for `oem` to `xfs` or `btrfs` does not work.

**Comment by mauromorales** [comment]
I will close this ticket, and keep track of the fs problem in the original issue
