### ISSUE TITLE
UKI: branding and menu configuration for active, passive and recovery

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2167]
**Is your feature request related to a problem? Please describe.**
Currently in GRUB mode we can have custom menu entries and we can customize the installed entries for active, passive and recovery. We can also add new entries that uses the same files with different boot args

**Describe the solution you'd like**
Branding to work as compatible with what GRUB supports, however we can also document the required steps (as creating the entries manually) or make it part of the shim.

We need also to document how to create multiple entries for the same file (with different boot cmdargs)

**Describe alternatives you've considered**
Document the manual steps

**Additional context**
This should be part of the shim:

- We currently support GRUB
- systemd-boot have to be supported as well

**Comment by Itxaka** [comment]
Few links.

For branding, very simple is just text files:
 - https://wiki.archlinux.org/title/systemd-boot#Configuration
 - https://uapi-group.org/specifications/specs/boot_loader_specification/ (type 2, which is UKI)

For cmdline override and different configs:
 - https://www.freedesktop.org/software/systemd/man/latest/systemd-stub.html#Companion%20Files

Basically systemd-boot supports having `*.addon.efi` files (signed) which provide only the `.cmdline` and `.dbt` sections and can be used to "override" whats on the main UKI EFI file

**Comment by Itxaka** [comment]
one idea would be:

 - during build, we allow building those extra PE files with different cmdlines (as example, one normal one with rd.immucore.debug)
 - those PE have an extra section called .branding
 - That branding is what systemd-boot would show, so what we have to store in the conf file
 - During install/upgrade a hook checks for those PE files and extracts the .branding section (its plain text) and creates the conf files to have different entries


Another ide would be to actually build those cmdlines and CHECK what systemd-boot does with them, becuase we currently have no idea. If you got your `kairos.efi` file and then a `normal.efi` and a `debug.efi` files in there, what does systemd-boot does? Does it show 2 different entries? Becuase maybe it does it out of the box and we only need the branding to show up and the cmdline appears by itself somehow


Alos, we may need to check with upstream directly to ask for this use-case as thye may have it covered already. systemd has a nice matrix chat where the full dev team is in there, so it may be the fastest way to check this.

**Comment by Itxaka** [comment]
bad news, we have to duplicate each uki file for each cmdline that we want: https://github.com/systemd/systemd/issues/24539
