### ISSUE TITLE
:bug: machine-id of UKI images never changes

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2168]
With the current implementation of UKI, the machine-id stays the same during LiveCD and after installation (for every installation). We might need to investigate this a bit further to know what is the best approach to provide a configurable one

**Comment by jimmykarily** [comment]
We are suspecting that we put the `machine-id` in the uki file at build time, which means, it's going to be the same one for ever machine that runs our released artifacts. We want to make sure, we don't put any machine-id in the uki artifact and it is only generated at run time (and persisted so that it stays the same after installation).

Maybe it's already the case but this ticket is here to check.

**Comment by mudler** [comment]
After some debugging session, it seems that the Dockerfiles correctly remove the /etc/machine-id, but the kairos-agent automatically regenerate it here: 

https://github.com/kairos-io/kairos/blob/28c2785624fcbfa784f61b26f5c7b10a4a3aef82/Earthfile#L291

This workarounds the issue, but the agent is very stubborn and re-creates it whenever called:

```
diff --git a/Earthfile b/Earthfile
index 1f129795..3d5ed36d 100644
--- a/Earthfile
+++ b/Earthfile
@@ -212,6 +212,9 @@ kairos-dockerfile:
     ELSE
         ARG FAMILY_LIST=$FAMILY
     END
+
+    # Generate the Dockerfiles for each family
+    # We concatenate the Dockerfile for the family (Dockerfile.$FAMILY) with the common kairos Dockerfile (Dockerfile.kairos)
     FOR F IN $FAMILY_LIST
         RUN --no-cache cat <(echo "# This file is auto-generated with the command: earthly +kairos-dockerfile --FAMILY=${F}") \
             <(sed -n '/# WARNING:/!p' Dockerfile.$F) \
@@ -316,6 +319,9 @@ base-image:
 
     RUN --no-cache kairos-agent version
 
+    # Drop machine-id
+   RUN rm /etc/machine-id || true
+
     SAVE IMAGE $_CIMG
     SAVE ARTIFACT /IMAGE AS LOCAL build/IMAGE
     SAVE ARTIFACT VERSION AS LOCAL build/VERSION
```

**Comment by Itxaka** [comment]
https://github.com/zcalusic/sysinfo/pull/43
