### ISSUE TITLE
Change ukify binary validation

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2177]
https://github.com/kairos-io/enki/pull/27#discussion_r1462987923

**Comment by jimmykarily** [comment]
If we do this: https://github.com/kairos-io/kairos/issues/2412 this ticket won't be needed (except for the arch part).

**Comment by Itxaka** [comment]
this is not needed anymore, with go-ukify you pass the specific files (systemd-boot and stub)
