### ISSUE TITLE
Change validation of stub and efi files to be platform agnostic

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2178]
https://github.com/kairos-io/enki/pull/27#discussion_r1462988708

**Comment by jimmykarily** [comment]
Let's consider creating a luet package with these files and use it in every flavor (they should work on any flavor). We might also need the arm versions of those files.

**Comment by Itxaka** [comment]
> Let's consider creating a luet package with these files and use it in every flavor (they should work on any flavor). We might also need the arm versions of those files.

we already provide that as package/systemd-boot for both arches :D

**Comment by mudler** [comment]
This was done as part of https://github.com/kairos-io/kairos/issues/2177 - now we detect the arch and we select the corresponding stub.
