### ISSUE TITLE
Updating u-boot to `v2024.01`

### ISSUE THREAD

**Issue by SheGe** [kairos-io/kairos#2180]
**Is your feature request related to a problem? Please describe.**
Because of the issues with u-boot Kairos is not booting on CM4 modules when the PCI-E SATA adapter is connected.

**Describe the solution you'd like**
Update u-boot to the latest available version: `v2024.01`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mauromorales** [comment]
robots at work https://github.com/kairos-io/packages/pull/624

**Comment by mauromorales** [comment]
this is working with the latest release from osbuilder https://github.com/kairos-io/osbuilder/releases/tag/v0.15.0 please give it a shot and report in case you catch any issues
