### ISSUE TITLE
Kairos package versions is now empty

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#2186]
**Kairos version:**
master
**CPU architecture, OS, and Version:**

```
kairos-final | --> RUN luet database get-all-installed --output /etc/kairos/versions.yaml
kairos-final | []
```

Something must have happened during the movement to the dockerfiles and we lost this. Probably we are cleaning the database before extracting the versions.

**Comment by mauromorales** [comment]
missing to consume on kairos
