### ISSUE TITLE
osbuilder [image]: update to new enki and UKI compatibility (systemd version)

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2215]
https://build.opensuse.org/package/show/openSUSE:Factory/systemd

also need: sbsigntools

This is to make the consumption of enki similar to how people used the osbuilder tools-image before, until we finally finish the "factory" epic and they consume only osbuilder (in Kubernetes) or Auroraboot (as cli).

Acceptance Criteria

- `enki build-uki` works in using the osbuilder tools-image

**Comment by jimmykarily** [comment]
@mudler suggested that we use systemd from factory to avoid fully switching to Tumbleweed (which would make builds fail unexpectedly) or Fedora (for which we need a lot of work).

**Comment by Itxaka** [comment]
factory and leap do not mix well:

```
Problem: nothing provides 'libc.so.6(GLIBC_2.34)(64bit)' needed by the to be installed systemd-experimental-255.3-11.1.x86_64
```

Testing with using the yet-to-be-released 15.6 repos in a 15.5 container

**Comment by Itxaka** [comment]
with updated repos (15.6 repeos in leap 15.5) ukify is missing as its systemd-measure.

With tumbleweed, the measure utils its broken. Claims that its version 254.8-3.3 which should allow us measuring values without access to a tpm, as mentioned in the systemd 254 changelog, but no, it requires a tom to calculate those values.


Im out of options here @mudler , I still think that moving to fedora and doing some testing for a couple of days woud fix this.

Build iso works with fedora, build uki works with fedora. The res of the utils (create arm artifacts) also work with it, and the base tools are plain gnu utils (sgdisk, cp, rsync, etc...) which should not cause any issues. IMHO I already wasted a full morning on this to not avail. Not worth expending more time in this now until opensuse starts shipping modern stuff without their opinionated-we-hate-systemd-boot packages...

**Comment by mudler** [comment]
> with updated repos (15.6 repeos in leap 15.5) ukify is missing as its systemd-measure.
> 
> With tumbleweed, the measure utils its broken. Claims that its version 254.8-3.3 which should allow us measuring values without access to a tpm, as mentioned in the systemd 254 changelog, but no, it requires a tom to calculate those values.
> 
> Im out of options here @mudler , I still think that moving to fedora and doing some testing for a couple of days woud fix this.
> 
> Build iso works with fedora, build uki works with fedora. The res of the utils (create arm artifacts) also work with it, and the base tools are plain gnu utils (sgdisk, cp, rsync, etc...) which should not cause any issues. IMHO I already wasted a full morning on this to not avail. Not worth expending more time in this now until opensuse starts shipping modern stuff without their opinionated-we-hate-systemd-boot packages...

validating it's not a waste. It's good that we tried to keep using the openSUSE image to avoid as less disruption as possible.. in this case we can't do much and we have to just switch to fedora.

Testing on all the other use-cases takes even more time than a morning :)

**Comment by Itxaka** [comment]
Feels to me a waste when opensuse seems so hostile to uki or systemd-boot :(

**Comment by mudler** [comment]
> Feels to me a waste when opensuse seems so hostile to uki or systemd-boot :(

Indeed, but now we have enough data points to support why we need to switch from openSUSE to Fedora for the time being. If there are going to be regressions we'll have to tackle them down as bug

**Comment by jimmykarily** [comment]
We are testing the fedora based osbuilder image here: https://github.com/kairos-io/kairos/issues/2231

**Comment by jimmykarily** [comment]
We went back to using opensuse. Closing this.
