### ISSUE TITLE
UKI: kcrypt unlock-all doesn't unlock TPM-bound partitions

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2217]
Currently unlocking partitions encrypted with TPM manually by calling `kcrypt unlock-all` doesn't work.

Workaround exists, and documented in https://kairos.io/docs/installation/trustedboot/#mount-partitions-after-install

**Comment by jimmykarily** [comment]
To reproduce:

- In the Kairos config, try to run `kcrypt unlock-all` in an after-install stage (e.g. to write some files to the disk)
- Install Kairos in UKI mode
- See installation failing.

Possible solution:

Introduce a new stage/hook (e.g. "after-decrypt") to allow people to run code right after decrypting the disks. This stage will also make sure the disk is encrypted again when the stage is done.

Also, there is a `--tpm` flag in `kcrypt unlock-all` command that might workaround the issue.

**Comment by Itxaka** [comment]
`kcrypt unlock-all`  could work if we add a --tpm flag so it knows it needs to go over the tpm unlock workflow instead of the usual one.

**Comment by jimmykarily** [comment]
Introduced in version 0.9.0: https://github.com/kairos-io/kcrypt/compare/v0.7.0...v0.9.0 (cut in December 18th: https://github.com/kairos-io/kcrypt/releases/tag/v0.9.0)
