### ISSUE TITLE
Default system configuration file

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2221]
**Kairos version:**
>=2.5.0

**Describe the bug**
`/etc/elemental/config.yaml` was supported as a way to inject default system configs. As part of those we could configure branding menu to be applied during upgrade and reset, and additional cloud config path to look into the system.

Now we expect all that data to come from the user-data, however, we don't have a way to specify those settings when we build the images. The config collector scans configurations exclusively in paths that are either persistent or not accessible on build time (https://github.com/kairos-io/kairos-agent/blob/0119b9cfb264e9ddbdf91ca0b37f80a89059cea8/main.go#L39)

**To Reproduce**

**Expected behavior**
Have a canonical `/etc/kairos/config.yaml` where we collect configurations.

Why: it can be both ephemeral (dynamically written in the cloud config file, see for example jetson nano configuration here: https://github.com/kairos-io/packages/blob/27b86d41992d7a1deb76b2e2123f69ea2c7918c3/packages/static/kairos-overlay-files/files/system/oem/12_nvidia.yaml#L36 ) or static (if shipped by the OS image)

**Logs**

**Additional context**

**Comment by mauromorales** [comment]
@mudler I have a couple of questions:

1. now with the collector we think more of directories, would it make sense to just say everything  under `/etc/kairos`? or does it need to be a specific file?
2. do we need to stay backwards compatible in 3.0? so `/etc/elemental/config.yaml` and `/etc/kairos/config.yaml` or just the latter?
3. can you clarify the point of being ephemeral or static? is it just that because it is created during `initramfs` stage vs it being an overlay file, or what do you mean?

**Comment by jimmykarily** [comment]
If that's an option, I would suggest a directory that will be used only for configs. That's because when we use directories that have lots of irrelevant files in them, a huge debug log is created with the reasons for skipping. I think that's the case with one of the directories we currently scan.

**Comment by mudler** [comment]
> @mudler I have a couple of questions:
> 
>     1. now with the collector we think more of directories, would it make sense to just say everything  under `/etc/kairos`? or does it need to be a specific file?

This sounds fine :+1: 

> 
>     2. do we need to stay backwards compatible in 3.0? so `/etc/elemental/config.yaml` and `/etc/kairos/config.yaml` or just the latter?

I'd keep the compatibility for 3.0 - and mark it in the release note that we are not going to read `/etc/elemental/config.yaml` from the next versions.

> 
>     3. can you clarify the point of being ephemeral or static? is it just that because it is created during `initramfs` stage vs it being an overlay file, or what do you mean?

What I mean is that by supporting `/etc/kairos` as path being scanned we can:

- Generate on-the-fly a `/etc/kairos/config.yaml` with cloud config before boot (for example as we used for injecting jetson nano defaults when the `initramfs` stage was being run)
- Add a file `/etc/kairos/config.yaml` in the OS image that will take effect (while building the OS and preparing a downstream derivative)
