### ISSUE TITLE
/run/initramfs/live is not accessible when booting LiveCD in UKI mode

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2222]
**Kairos version:**
3.0-alpha2

**Describe the bug**
We used to mount the livecd content to `/run/initramfs/live` to allow automatic installation and custom user-data ( https://github.com/kairos-io/kairos-agent/blob/0119b9cfb264e9ddbdf91ca0b37f80a89059cea8/main.go#L39 )

**To Reproduce**
Boot an UKI iso, `/run/initramfs/live` does not exist.

**Expected behavior**
The iso to be mounted to `/run/initramfs/live`

**Comment by Itxaka** [comment]
Fixed by:
 - https://github.com/kairos-io/immucore/pull/223
 - https://github.com/kairos-io/kairos-agent/pull/225

Needs new versions, trickled down into packages -> framework, keeping this open until it does

**Comment by Itxaka** [comment]
missing mounting the efiboot under /run/rootfsbase so the media is available for install.

**Comment by Itxaka** [comment]
https://github.com/kairos-io/immucore/pull/224

**Comment by jimmykarily** [comment]
waiting until the packages are bumped in kairos

**Comment by Itxaka** [comment]
packages should now be available in kairos!
