### ISSUE TITLE
[QA] Test opensuse based osbuilder builds

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#2231]
Card to track the ~new fedora-based~ (update: we went back to opensuse) osbuilder artifacts\

 - [x] iso-uki artifacts
 - [x] iso artifacts
 - [ ] arm artifacts @Itxaka 
	 - Its bwoken! `Synchronous Exception at 0x00000002C5487DE0`
	 - Happens with older versions as well, not specific from this. May be the arm emulation unfortunately.
 - [ ] rpi3 artifacts
 - [ ] rpi4 artifacts @mauromorales 
	 - Works with latest fixed patch https://github.com/kairos-io/osbuilder/commit/89dec58dd97a7aa86640ed2c04e93f6ffa3eed50
 - [ ] nvidia jetson artifacts
 - [ ] raw disk images
   - [ ] GCE
   - [ ] AWS
   - [ ] Azure
   - [ ] EFI raw disk image (Autoinstall from recovery)
   - [ ] BIOS raw disk image (no Autoinstall)

**Comment by Itxaka** [comment]
- Iso artifacts seem to be good according to our tests on https://github.com/kairos-io/kairos/actions/runs/7828035143
 - Bundle test is failing because it needs changes to the test for the dependencies
 - arm artifacts are BUILD correctly but not tested
 - uki is failing yikes.

**Comment by Itxaka** [comment]
test-uki its still failing, while locally seems to work: https://github.com/kairos-io/kairos/actions/runs/7829097334/job/21364715618?pr=2232

**Comment by Itxaka** [comment]
got itt, its failing due to the uki output iso name change

**Comment by Itxaka** [comment]
uki test fixed, now it passes, it was a naming thing, nothing to do with the output artifact

**Comment by Itxaka** [comment]
Fedora 38 works out of the box. Fedora 40 as well. So probably the version of sgdisk in Fedora 39 is broken in a very subtle way.

![image](https://github.com/kairos-io/kairos/assets/1447686/1ad629d0-6c48-4bd0-a914-615e2ef3ab01)

**Comment by Itxaka** [comment]
Bumped (downgraded?) osbuilder to use Fedora 38 until Fedora 40 is available. Tested and rpi4 boots.

**Comment by Itxaka** [comment]
Retriggered master builds for Kairos images and uki to test the latest published osbuilder which fixes the arm images to see if they pass so we can confirm that uki and normal isos builds are not broken.

https://github.com/kairos-io/kairos/actions/runs/7843857723

https://github.com/kairos-io/kairos/actions/runs/7843857709/job/21435313799

**Comment by Itxaka** [comment]
Uki broken with this because the ukify version does not accept some flags

Ugh, neverending story

**Comment by Itxaka** [comment]
Tested several things but cant make it work as expected by just bumping ukify as systemd-measure also needs a bump.

Moved to fedora 40 which is almost on beta 1 (in 3 days). It sucks but I think we should go that way if we want to enjoy all the benefits unless someone can find the issue with gptdisk not creating proper raw images

**Comment by Itxaka** [comment]
Fixed by moving osbuilder to Fedora 40.
Fedora 39 seems to has a broken sgdisk as raw images are broken with it
Fedora 38 has a very old ukify version
Ubuntu 23.10 does not ship ukify
Suse (all) does not ship ukify
Fedora 40 is in beta tomorrow, so it should be pretty stable by now, at least related to the building part. Bug list is pretty small for now and it should get better by the end of the month.

Triggered https://github.com/kairos-io/kairos/actions/runs/7843857723 for normal tests with latest osbuilder artifact
Triggered https://github.com/kairos-io/kairos/actions/runs/7843857709 for uki tests with latest osbuilder artifact

**Comment by mauromorales** [comment]
wow seems were really doing some pioneer work here

**Comment by Itxaka** [comment]
uki tests will fail for now until https://github.com/kairos-io/kairos-agent/pull/228 is merged I guess? It will try to mount the disk but it will alread be mounted...testing manually

**Comment by jimmykarily** [comment]
For reference, we are planning to test with this package: https://github.com/kairos-io/packages/pull/680/files
So that we control the systemd-boot package version. Also we might be able to reach a "distro agnostic" state for osbuilder image if we can bundle some more dependencies.

**Comment by Itxaka** [comment]
gone back to leap 15.5 with the extra packages provided by luet (ukify and systemd-boot) 

triggered again https://github.com/kairos-io/kairos/actions/runs/7843857723 and https://github.com/kairos-io/kairos/actions/runs/7843857709 to see if they work as expected

**Comment by jimmykarily** [comment]
Let's close this and treat any issues that arise as bugs.
