### ISSUE TITLE
[RPI] EFI booting no longer supported on kernels shipped with ubuntu > 22.04

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#2249]
For some reason, the efi booting stuff was disabled on the upstream ubuntu kernel packages for raspi:

commit: https://git.launchpad.net/ubuntu/+source/linux-raspi/commit/?h=applied/ubuntu/devel&id=0d02ca7853f4e487ff8b912b0d1d43ceb31a528b

Change:
```diff
diff --git a/debian.raspi/config/annotations b/debian.raspi/config/annotations
index 5fddd3c1a9..136d8cf4af 100644

-CONFIG_EFI                                      policy<{'arm64': 'y', 'armhf': 'n'}> note<'Not supported on Pi'>
+CONFIG_EFI                                      policy<{'arm64': 'n', 'armhf': 'n'}> note<'Not supported on Pi'>
```

What this means is that for our usecase, we would not be able to boot with our current method uboot -> arm64 fallback file (grub) -> kernel as grub complains that the kernel doesnt have the required `CONFIG_EFI_STUB` option, which is true.

We should probably ask upstream why was this disabled and if they can enable it again, as it was enabled up to kernel [6.5.0-1001.1](https://git.launchpad.net/ubuntu/+source/linux-raspi/tag/?h=import/6.5.0-1001.1) with no apparent issues (could not find any bugs related to this)

**Comment by mudler** [comment]
one (hackish) way would be to use different kernels (even vanilla..) but this is not easy to maintain in the long run. 

Probably upstream needs to be educated that actually works on PI (given their note "Not supported on Pi"), as u-boot > GRUB is quite uncommon.

However for now we can block RPI4 support for ubuntu >22.04 as currently there are no requests around that.

**Comment by Itxaka** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/2053147

**Comment by Itxaka** [comment]
bug was closed upstream as they wont provide support for it.

**Comment by mauromorales** [comment]
shoot, what does that mean, no RPI Ubuntu ? so strange since they offer an Ubuntu RPi release themselves

**Comment by mauromorales** [comment]
yup good question, I think they don't use u-boot, but not sure

**Comment by mauromorales** [comment]
@kairos-io/maintainers should we stop producing Ubuntu RPi artifacts for 23+? IMO it is weird that we produce an artifact if we know it will not work, and have to keep adding a notice on the release

**Comment by Itxaka** [comment]
as last resort we should try https://github.com/pftf/RPi4 + systemd-boot with type 1 stuff to see if it works that way and its only grub the one being obtuse about it.

**Comment by liyimeng** [comment]
It is too bad that the upstream taking that decision. :( 
However, people play with uboot probably have good knowledge with re-configuring kernel on their own. Maybe we could just update the docs, explaining how kairos is dealing with u-boot based modes, like Jetson, RPI, etc. It would be even better to add some instructions, helping developer to enable their board with KairOS, which will bring KairOS to much larger user base.

I know little in the area. However, I've tried to absorb some knowledge from your  guys discussion and compose a list here. To have kairOS work with any boards, what is needed:

- Developer need to ship the uboot for their boards with UEFI support, detail instructions can be found at https://github.com/u-boot/u-boot/blob/master/doc/develop/uefi/uefi.rst
- Pack the firmware for the board with package manager tools, like rpm, deb, apk, etc.
- Build a custom kernel with necessary drivers and configs, especially `CONFIG_EFI_STUB=y` and pack it as above.

After this, KairOS can launch with uboot in EFI mode, which in turn runs grub.efi and then we load our grub entries from there. 

Not sure if this makes  sense. If yes, I can create a PR for the docs.

**Comment by liyimeng** [comment]
yaha, we actually already have a doc for this https://kairos.io/docs/development/nvidia/

**Comment by jimmykarily** [comment]
Idea that came up during planning: We can maybe create a ppa in launchpad (https://launchpad.net)  to build the kernel ourselves and just use our package instead. This of course needs someone that knows how to build in launchpad...

**Comment by Itxaka** [comment]
could also send a patch upstream, see if its accepted lol

**Comment by Itxaka** [comment]
or we could use the upstream linux kernel for rpi? https://github.com/raspberrypi/linux or even the raspberryos kernel?

**Comment by jimmykarily** [comment]
like this? https://git.launchpad.net/~dkarakasilis/ubuntu/+source/linux-raspi/commit/?id=917694f382899575eb587bb481cb02ef71d9821c

**Comment by Itxaka** [comment]
> like this? [git.launchpad.net/~dkarakasilis/ubuntu/+source/linux-raspi/commit?id=917694f382899575eb587bb481cb02ef71d9821c](https://git.launchpad.net/~dkarakasilis/ubuntu/+source/linux-raspi/commit/?id=917694f382899575eb587bb481cb02ef71d9821c)

sorcery!

**Comment by jimmykarily** [comment]
Uploading the artifact fails with:

```
DEBUG Considering changefile 3429361/ubuntu/linux-raspi_6.8.0-1~ubuntu24.04.1_source.changes
DEBUG Finding fresh policy
INFO Processing upload linux-raspi_6.8.0-1~ubuntu24.04.1_source.changes
INFO Upload was rejected:
INFO 	6.8.0-1~ubuntu24.04.1: should be 6.8.0-1011.12 according to changes file.
INFO Committing the transaction and any mails associated with this upload.
```

Maybe relevant: https://help.launchpad.net/PPAQuickStart/FAQ#I_get_an_error_about_versions

**Comment by jimmykarily** [comment]
I asked for some guidance in the launchpad users mailing list: https://lists.launchpad.net/launchpad-users/ (I will update the link as soon as my email appears there)

**Comment by jimmykarily** [comment]
In the meantime, we can just `dpkg -i https://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/linux-libc-dev_1.20230405-1_arm64.deb` and see if it works?

(repo with the kernel: https://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/)

**Comment by jimmykarily** [comment]
I'm trying it here: https://github.com/kairos-io/kairos/compare/2249-try-upstream-rpi-kernel?expand=1 but it turns out they've removed some packages too?

```
    ubuntu-22.04-rpi *failed* | E: Unable to locate package linux-modules-extra-raspi
    ubuntu-22.04-rpi *failed* | ERROR
    ubuntu-22.04-rpi *failed* |       The command
    ubuntu-22.04-rpi *failed* |           RUN apt-get update && apt-get install -y --no-install-recommends     linux-firmware-raspi     linux-modules-extra-raspi     && apt-get clean && rm -rf /var/lib/apt/lists/*
```

I tried to see if this is a mistake in our Dockerfile, maybe the file is renamed or something?

**Comment by jimmykarily** [comment]
Maybe this? https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/2048862

**Comment by jimmykarily** [comment]
This is what it boots into:

![image](https://github.com/user-attachments/assets/8e0d2e89-999e-434f-be67-9a6233edcea5)


Not excatly what we had in mind :D.

**Comment by jimmykarily** [comment]
Hitting `ESC` shows error like:

```
Failed to open device: 'sdcard' (cmd 371a0010 status 1fff0001)
```

**Comment by jimmykarily** [comment]
We tried things, it doesn't work. We have other flavors that work. Let's close it.
