### ISSUE TITLE
code obsoleted 

### ISSUE THREAD

**Issue by liyimeng** [kairos-io/kairos#2253]
To my understanding, [this part of code(INSTALL_K3S)](https://github.com/kairos-io/kairos/blob/7170dc2d5511cf3c61b32b7bb1958484a03bff0f/Earthfile#L1042
) has moved in Luet package, the same for [this part (PROVIDER_INSTALL)](https://github.com/kairos-io/kairos/blob/7170dc2d5511cf3c61b32b7bb1958484a03bff0f/Earthfile#L1024
) as well, do I get it right? if I do, should we clean it up?

**Comment by jimmykarily** [comment]
You are right @liyimeng , good catch!
