### ISSUE TITLE
Open Source Summit Vienna

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2259]
https://events.linuxfoundation.org/open-source-summit-europe/
https://events.linuxfoundation.org/open-source-summit-europe/program/cfp/

⚠ **CfP ends 30th of April**

- [ ] Booth
- [x] CfP

Candidate topics:

- Trusted boot (possible lanes: Container and Infrastructure Security, Confidential Computing and more)
- Learn Kubernetes kind of lab (Tutorial/Hands-on Lab (typically 1.5 – 2 hours in length))

**Comment by mauromorales** [comment]
cfp about trusted boot sent, but the conference is so big we could send other topics too

**Comment by jimmykarily** [comment]
I submitted one for for a worship about day-2 operations for edge computing

**Comment by mauromorales** [comment]
Working on a panel proposal for the wg-sp-os

**Comment by jimmykarily** [comment]
```
We regret to inform you that your submission, Thriving Beyond Deployment: Day-2 Operations for Edge Computing with Open Source, for [Open Source Summit Europe 2024 ](https://events.linuxfoundation.org/open-source-summit-europe/)has not been accepted.
```
