### ISSUE TITLE
build-uki: `--overlay` flag  adds content to rootfs rather than the ISO

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2271]
**Is your feature request related to a problem? Please describe.**
In order to do automated install and carry over files from the ISO we want to able to add arbitrary content to the ISO (and not the rootfs content, which would be lost between upgrades).

**Describe the solution you'd like**
We want this: https://github.com/kairos-io/enki/blob/be3be58a1b7cbd5c24ddd79f9384984925f9f0b2/cmd/build-iso.go#L79 in build-uki as `--overlay-iso` and map the current `--overlay` arg as `--overlay-rootfs` to keep compatibility

**Describe alternatives you've considered**

**Additional context**

**Comment by Itxaka** [comment]
https://github.com/kairos-io/enki/releases/tag/v0.019 contains this
