### ISSUE TITLE
Kubernetes doesn't work on uki installations

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2275]
I created an image with:

```
CGO_ENABLED=false go build -o build/enki   && docker run --rm --entrypoint /bin/enki -v $PWD/build/enki:/bin/enki  -v $PWD/build:/result -v $PWD/e2e/assets/keys/:/keys enki-image build-uki  quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.0-alpha3-k3sv1.27.9-k3s1 --output-dir /result --keys /keys --output-type iso --boot-branding "DimitrisOS-2"
```

I booted it, and installed with this config:

```
#cloud-config


k3s:
    enabled: true
users:
    - name: kairos
      passwd: kairos
```

The system boots but kubernetes Pods don't come up. They all show this error:

```
│   Warning  FailedCreatePodSandBox  7s (x19 over 4m6s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create f │
│ ailed: runc create failed: unable to start container process: error during container init: error jailing process inside rootfs: pivot_root .: invalid argument: unknown                                                     │
│                                                                                                                                                                               
```

Possible fix: https://github.com/containerd/cri/pull/851

Maybe relevant links:

- https://github.com/containerd/containerd/issues/5510
- https://github.com/k3s-io/k3s/issues/510
- https://forums.rancher.com/t/running-k3s-one-node-cluster-with-minimal-storage/37605
- https://github.com/k3s-io/k3s/pull/6209
- https://github.com/containerd/containerd/issues/1973

**Comment by mudler** [comment]
This is mostly related to the Kubernetes distribution being used. For K3s, we can configure containerd (as documented here: https://docs.k3s.io/advanced#configuring-containerd ) with NoPivotRoot. 

See for example: https://github.com/k3s-io/k3s/pull/6209/files#diff-a2804b856ab336e8feb96bbaa6ae931a6c5fc44f0ee54db9642f977f99e2de1b

**Comment by jimmykarily** [comment]
I built an standard Fedora image from kairos master branch, converted that to uki iso, installed and k8s starts fine.

Closing.
