### ISSUE TITLE
UKI NoPivot

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2295]
In UKI mode, when Pods start we see errors like this:

```
jailing process inside rootfs: pivot_root .: invalid argument: unknown\"" pod="kube-system/cilium-phbhk"
```
(in the pod descriptions and/or k3s logs)

We fixed the problem in containerd like this:

https://github.com/kairos-io/packages/commit/d89ec306df7856b7088ca92f6fdc0bc435628d43#diff-250ed56e511a78d55f2b836c7dd9dfe9acecdea1e63bf986036601b48da0a91eR42

but it turns out in rke2 with cillium the error still occurs.

Before immucore in non-uki mode we were preparing the chroot env like this: https://github.com/mocaccinoOS/desktop/blob/master/packages/kernels/initramfs/loader.sh

but now we use some different flags (e.g. when mounting `/proc`): https://github.com/kairos-io/immucore/blob/0cfddd485dae43f714235aeb4c60ba6e1e0bc83f/internal/utils/mounts.go#L204

We should first try mount with no flags at all, like we used to. If this doesn't work, we can try to prepare a directory with hardlinked directories and kernel dir mounts so that we can call the `switch_root` script in case we are missing some system calls that would otherwise happen:

![Image](https://github.com/kairos-io/kairos/assets/2794419/aa6d734c-bfb5-436c-90b5-ea6a34f57787)

Links:

- https://github.com/containerd/cri/pull/851
- https://github.com/containerd/containerd/issues/1973

**Comment by jimmykarily** [comment]
- Build a standard UKI iso from v3.0.0-alpha3 (or later)
- Deploy with Kuberentes enabled
- Delete `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` (which was our fix for k3s)
- Restart k3s service
- See many (all?) the Pods failing.
- `kubectl describe` a failing Pod to see the error.

**Comment by jimmykarily** [comment]
Completely removing the mount options gets stuck when booting after install here:

```
[    6.493746] usbcore: registered new interface driver usb-storage
[    6.501019] usbcore: registered new interface driver uas
[    8.736945] I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 2
[    8.739549] floppy: error 10 while reading block 0
[    9.184872] I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 2
[    9.194348] floppy: error 10 while reading block 0
[   15.072332] EXT4-fs (vda3): mounted filesystem 5188ea33-56c4-4672-9e34-2774b20a80bc r/w with ordered data mode. Quota mode: none.
```

The diff:

```
diff --git a/internal/utils/mounts.go b/internal/utils/mounts.go
index e093da3..ba0c9ee 100644
--- a/internal/utils/mounts.go
+++ b/internal/utils/mounts.go
@@ -201,11 +201,11 @@ func Fsck(device string) error {
 func MountBasic() {
        _ = os.MkdirAll("/proc", 0755)
        if !IsMounted("/proc") {
-               _ = syscall.Mount("proc", "/proc", "proc", syscall.MS_NOSUID|syscall.MS_NODEV|syscall.MS_NOEXEC|syscall.MS_RELATIME, "")
+               _ = syscall.Mount("proc", "/proc", "proc", 0, "")
        }
        _ = os.MkdirAll("/run", 0755)
        if !IsMounted("/run") {
-               _ = syscall.Mount("tmpfs", "/run", "tmpfs", syscall.MS_NOSUID|syscall.MS_NODEV|syscall.MS_NOEXEC|syscall.MS_RELATIME, "mode=755")
+               _ = syscall.Mount("tmpfs", "/run", "tmpfs", 0, "mode=755")
        }
 }
```

I gave it a shot because of the `none` here: https://github.com/mocaccinoOS/desktop/blob/35c7c85ba7e4498277c73cf9e34978d0a9d9f7ca/packages/kernels/initramfs/loader.sh#L5

**Comment by jimmykarily** [comment]
scratch that. Same thing without the change. Something else is wrong.

**Comment by jimmykarily** [comment]
Problem only happens with Fedora standard flavor. On opensuse core, I can boot after install just fine. Fedora standard used to work (that's how we discovered the bug in the first pace). I'm investigating...

**Comment by jimmykarily** [comment]
but I noticed opensuse says:

```
INFO[2024-03-01T09:26:22Z] systemd version is 249, we need 252 or higher for encrypting partitions 
```

**Comment by jimmykarily** [comment]
Never mind. The problem was that I was using [this enki image](https://github.com/kairos-io/enki/blob/main/Dockerfile). Using `quay.io/kairos/osbuilder-tools:v0.200.4` makes everything work. Probably some dependencies are different or missing.

**Comment by jimmykarily** [comment]
The error seems to originate [here](https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L208-L213) which means [this function](https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L1041) fails somehow.

**Comment by jimmykarily** [comment]
I'm trying the idea describe in the image (see description). I get this error when trying to move the mounts (e.g. /sys):

```
[root@fedora kairos]# mount --move /sys /tmp/fakeroot/sys
mount: /tmp/fakeroot/sys: bad option; moving a mount residing under a shared mount is unsupported.
```
It doesn't like where `/sys` was originally mounted?

**Comment by jimmykarily** [comment]
Adding the MS_PRIVATE or MS_SLAVE  to the mount flags in immucore drops me to a login prompt when booting livecd. I guess cloud configs weren't accessible ?

**Comment by jimmykarily** [comment]
Reading the [`pivot_root` docs](https://man7.org/linux/man-pages/man2/pivot_root.2.html):

```
The propagation type of the parent mount of new_root and the
          parent mount of the current root directory must not be
          MS_SHARED; similarly, if put_old is an existing mount point,
          its propagation type must not be MS_SHARED.  These
          restrictions ensure that pivot_root() never propagates any
          changes to another mount namespace.
```

strangely, there seems to be some relation between the problem described above (with moving the mounts) and the actual error [coming from `pivor_root`](https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L1065-L1067).

**Comment by jimmykarily** [comment]
This seems to work:

```
[root@fedora ~]# mount --make-private /
[root@fedora ~]# mkdir /usr/local/fakeroot/sys
[root@fedora ~]# mount --move /sys /usr/local/fakeroot/sys/
```

but I don't see to be able to mount `/ ` as private in the first place. When I add the flag `MS_PRIVATE` in immucore, things don't get mounted properly (though I don't see a specific error, just the fact that the overlay files are not applied correctly. I need to investigate more).

**Comment by jimmykarily** [comment]
btw, in the image we are talking about "hardlinks" of directories which is not a thing (you can't hardlink directories according to what I read, only files). I could `mount --bind` them though, but I'm not sure if that would work. After I made `/` private (with `mount --make-private /`), I managed to `mount --bind` : etc, home, usr etc  and move mounts (/dev, /sys, /proc etc) all in a dir under `/usr/local` and then chroot to that dir. I haven't tried that in immucore yet.

Before I tried that, I thought about giving this a try: `chroot /`. The command runs fine and if there are any system calls made by `chroot` then this should be enough to fix things (?). I'll try this first and if it doesn't work I'll try a full "fake root" directory through immucore.

**Comment by jimmykarily** [comment]
This was my experiment:

```
diff --git a/pkg/mount/dag_steps.go b/pkg/mount/dag_steps.go
index 0954a13..6c772c9 100644
--- a/pkg/mount/dag_steps.go
+++ b/pkg/mount/dag_steps.go
@@ -493,6 +493,9 @@ func (s *State) UKIBootInitDagStep(g *herd.Graph) error {
                herd.WeakDeps,
                herd.WithWeakDeps(cnst.OpRemountRootRO, cnst.OpRootfsHook, cnst.OpInitramfsHook, cnst.OpWriteFstab),
                herd.WithCallback(func(ctx context.Context) error {
+                       if err := unix.Exec("/usr/bin/chroot", []string{"/"}, os.Environ()); err != nil {
+                               internalUtils.Log.Err(err).Msg("$$$$$$$$$$$$$$$$$ chroot to /")
+                       }
                        output, err := internalUtils.CommandWithPath("/usr/lib/systemd/systemd-pcrphase --graceful leave-initrd")
                        if err != nil {
                                internalUtils.Log.Err(err).Msg("running systemd-pcrphase")
@@ -522,7 +525,7 @@ func (s *State) UKIRemountRootRODagStep(g *herd.Graph) error {
                        for i := 1; i < 5; i++ {
                                time.Sleep(1 * time.Second)
                                // Should we try to stop udev here?
-                               err = syscall.Mount("", "/", "", syscall.MS_REMOUNT|syscall.MS_RDONLY, "")
+                               err = syscall.Mount("", "/", "", syscall.MS_PRIVATE|syscall.MS_REMOUNT|syscall.MS_RDONLY, "")
```

but after removing `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` and restarting `k3s` service, if I delete the metrics server Pod, it refuses to come up with the same "jailing process inside rootfs" error. 

I don't know if that's the point where I should try to `chroot` but it doesn't seem to have any effect.

**Comment by Itxaka** [comment]
This is what switch_root actually does, not much different on what we do:

https://github.com/util-linux/util-linux/blob/master/sys-utils/switch_root.c#L125

Changes several mountpoints to the new root, chroots into the new root and execs the new init

**Comment by jimmykarily** [comment]
@Itxaka you may be right. I'm not 100% sure that I'm we are not missing one seemingly innocent line there.
I tried to run this on an installed system to see if it would work:

```
[root@fedora ~]# cat switch.sh 
#!/bin/bash

FAKEROOT=/usr/local/fakeroot

mount --make-private /

declare -a arr=("etc" "home" "usr" "var" "bin" "lib" "lib64" "sbin")
for i in "${arr[@]}"
do
  mkdir -p $FAKEROOT/$i
  mount --bind /$i $FAKEROOT/$i
done


declare -a arr=("dev" "sys" "proc" "tmp")
for i in "${arr[@]}"
do
  mkdir -p $FAKEROOT/$i
  mount --move /$i $FAKEROOT/$i
done

switch_root $FAKEROOT /sbin/init
```

and I got this error:

```
[root@fedora ~]# ./switch.sh 
switch_root: failed to mount moving /usr/local/fakeroot to /: Invalid argument
switch_root: failed. Sorry.
```

**Comment by jimmykarily** [comment]
From the manual:

```
       switch_root moves already mounted /proc, /dev, /sys and /run to newroot and makes newroot the new root filesystem and starts init
       process.

       WARNING: switch_root removes recursively all files and directories on the current root filesystem.
```

I probably shouldn't move the mounts myself then.

**Comment by jimmykarily** [comment]
nope, that's not the problem.

**Comment by jimmykarily** [comment]
This immucore diff:

```
diff --git a/pkg/mount/dag_steps.go b/pkg/mount/dag_steps.go
index 0954a13..64cf450 100644
--- a/pkg/mount/dag_steps.go
+++ b/pkg/mount/dag_steps.go
@@ -493,6 +493,9 @@ func (s *State) UKIBootInitDagStep(g *herd.Graph) error {
                herd.WeakDeps,
                herd.WithWeakDeps(cnst.OpRemountRootRO, cnst.OpRootfsHook, cnst.OpInitramfsHook, cnst.OpWriteFstab),
                herd.WithCallback(func(ctx context.Context) error {
+                       if err := unix.Exec("/usr/bin/switch_root", []string{"/", "/sbin/init"}, os.Environ()); err != nil {
+                               internalUtils.Log.Err(err).Msg("$$$$$$$$$$$$$$$$$ switch_root to /")
+                       }
                        output, err := internalUtils.CommandWithPath("/usr/lib/systemd/systemd-pcrphase --graceful leave-initrd")
                        if err != nil {
                                internalUtils.Log.Err(err).Msg("running systemd-pcrphase")
@@ -522,7 +525,7 @@ func (s *State) UKIRemountRootRODagStep(g *herd.Graph) error {
                        for i := 1; i < 5; i++ {
                                time.Sleep(1 * time.Second)
                                // Should we try to stop udev here?
-                               err = syscall.Mount("", "/", "", syscall.MS_REMOUNT|syscall.MS_RDONLY, "")
+                               err = syscall.Mount("", "/", "", syscall.MS_PRIVATE|syscall.MS_REMOUNT|syscall.MS_RDONLY, "")
                                if err != nil {
                                        continue
                                }
```

and then the rest of the steps from [my previous comment](https://github.com/kairos-io/kairos/issues/2295#issuecomment-1976916285) seems to work!

I'll try to deploy cilium too. It's kind of late in the day, I no longer trust my findings :D

**Comment by jimmykarily** [comment]
And I'm right not trusting my findings. I just forgot to restart the k3s service. Doesn't work.

**Comment by jimmykarily** [comment]
Well it boots fine and kubernetes runs. It's just that it doesn't solve the original problem, it still needs the NoPivot setting. It as if it doesn't have any effect at all. Maybe even the `switch_root` command fails but I can't find the error in the logs :shrug: .

**Comment by jimmykarily** [comment]
ok just to sum up an clarify:

with the `NoPivotRoot: true` in the config.toml.tmpl we are no longer [in the `pivot_root` path](https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L208) and this is also true for the cilium pod (that's why we don't see `pivot_root` in the error message. 

The cilium pod fails here: https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L1132 and might indeed have to do with the flags we use to mount things (as [seen in this comment](https://github.com/kairos-io/kairos/issues/2295#issuecomment-1973388898)).

If only there were better error messages...

**Comment by jimmykarily** [comment]
And the reason the cilium Pod is failing is probably because of this Volume definition:

```
  - hostPath:
      path: /proc
      type: Directory
```

Also a nice read: https://medium.com/kokster/kubernetes-mount-propagation-5306c36a4a2d

**Comment by jimmykarily** [comment]
I wonder what is the `unkown` that is printed. Eventually it all boils down to this call: https://github.com/golang/sys/blob/360f961f8978a4c9a7c2e849bb482780cd6bb553/unix/syscall_linux.go#L1784 . Maybe the fsType argument shouldn't be empty here? https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L1132
Some lines below, for `tmpfs` it's being passed :shrug:

**Comment by Itxaka** [comment]
> I wonder what is the `unkown` that is printed. Eventually it all boils down to this call: [golang/sys@`360f961`/unix/syscall_linux.go#L1784](https://github.com/golang/sys/blob/360f961f8978a4c9a7c2e849bb482780cd6bb553/unix/syscall_linux.go#L1784) . Maybe the fsType argument shouldn't be empty here? [opencontainers/runc@`6cf6ddc`/libcontainer/rootfs_linux.go#L1132](https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L1132) Some lines below, for `tmpfs` it's being passed 🤷

could it be something in their mount method? is not a simple syscall.mount but much mo,re complex: https://github.com/opencontainers/runc/blob/main/contrib/cmd/memfd-bind/memfd-bind.go#L135

**Comment by jimmykarily** [comment]
I don't think cilium calls anything itself. I think it just tries to mount `/proc`. I don't see anything in the runc code that allows more logs.

**Comment by jimmykarily** [comment]
> > I wonder what is the `unkown` that is printed. Eventually it all boils down to this call: [golang/sys@`360f961`/unix/syscall_linux.go#L1784](https://github.com/golang/sys/blob/360f961f8978a4c9a7c2e849bb482780cd6bb553/unix/syscall_linux.go#L1784) . Maybe the fsType argument shouldn't be empty here? [opencontainers/runc@`6cf6ddc`/libcontainer/rootfs_linux.go#L1132](https://github.com/opencontainers/runc/blob/6cf6ddc358eff384c47eb6ef749304b2edc23451/libcontainer/rootfs_linux.go#L1132) Some lines below, for `tmpfs` it's being passed 🤷
> 
> could it be something in their mount method? is not a simple syscall.mount but much more complex: https://github.com/opencontainers/runc/blob/main/libcontainer/mount_linux.go#L99

if you follow the conditions, eventually is simply calls `unix.Mount`, the rest are skipped because srcFile is `nil` or other.

**Comment by jimmykarily** [comment]
another data point. This Pod starts fine:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /proc
      name: hostproc
  volumes:
  - name: hostproc
    hostPath:
      path: /proc
```

and `/proc` inside the Pod's container has content. So it's not just mounting the `/proc` from host that breaks it. cilium must be doing something more on top. I'll try to narrow it down to the minimum Pod spec that fails.

**Comment by jimmykarily** [comment]
ok we have fixes on both paths:

## NoPivotRoot

@Itxaka found the right combination of MS_PRIVATE/MS_SHARED/etc flags to allow cilium to mount `/proc` properly. Itxaka, if you want to can put your findings here for reference. This would allow us to us the `NoPivotRoot` setting successfully.

## Fix-all solution

We successfully run switch_root in immucore and it worked. This is what we did.

We make this change in immucore:

```
diff --git a/pkg/mount/dag_steps.go b/pkg/mount/dag_steps.go
index 0954a13..c174ea2 100644
--- a/pkg/mount/dag_steps.go
+++ b/pkg/mount/dag_steps.go
@@ -498,15 +498,28 @@ func (s *State) UKIBootInitDagStep(g *herd.Graph) error {
                                internalUtils.Log.Err(err).Msg("running systemd-pcrphase")
                                internalUtils.Log.Debug().Str("out", output).Msg("systemd-pcrphase leave-initrd")
                        }
-                       // Print dag before exit, otherwise its never printed as we never exit the program
+
                        internalUtils.Log.Info().Msg(s.WriteDAG(g))
-                       internalUtils.Log.Debug().Msg("Executing init callback!")
-                       internalUtils.CloseLogFiles()
-                       if err := unix.Exec("/sbin/init", []string{"/sbin/init", "--system"}, os.Environ()); err != nil {
-                               internalUtils.Log.Err(err).Msg("running init")
-                               // drop to emergency shell
-                               if err := unix.Exec("/bin/bash", []string{"/bin/bash"}, os.Environ()); err != nil {
-                                       internalUtils.Log.Fatal().Msg("Could not drop to emergency shell")
+
+                       if _, err := os.Stat("/run/cos/live_mode"); err != nil {
+                               if err := unix.Exec("/bin/switch.sh", []string{"/bin/switch.sh"}, os.Environ()); err != nil {
+                                       internalUtils.Log.Fatal().Msg("Could not fake a chroot: " + err.Error() + output)
+
+                                       if err := unix.Exec("/bin/bash", []string{"/bin/bash"}, os.Environ()); err != nil {
+                                               internalUtils.Log.Fatal().Msg("Could not drop to emergency shell")
+                                       }
+                               }
+                       } else {
+                               // Print dag before exit, otherwise its never printed as we never exit the program
+                               // internalUtils.Log.Info().Msg(s.WriteDAG(g))
+                               // internalUtils.Log.Debug().Msg("Executing init callback!")
+                               internalUtils.CloseLogFiles()
+                               if err := unix.Exec("/sbin/init", []string{"/sbin/init", "--system"}, os.Environ()); err != nil {
+                                       internalUtils.Log.Err(err).Msg("running init")
+                                       // drop to emergency shell
+                                       if err := unix.Exec("/bin/bash", []string{"/bin/bash"}, os.Environ()); err != nil {
+                                               internalUtils.Log.Fatal().Msg("Could not drop to emergency shell")
+                                       }
                                }
                        }
                        return nil
```
this just runs a script when not in livecd mode.

The script is this:

```
#!/bin/bash

FAKEROOT=/tmp/fakeroot

mkdir -p $FAKEROOT

mount --type tmpfs none $FAKEROOT

#mount --make-private /

declare -a arr=("etc" "home" "usr" "var" "bin" "lib" "lib64" "sbin")
for i in "${arr[@]}"
do
  mkdir -p $FAKEROOT/$i
  mount --bind /$i $FAKEROOT/$i
done

exec /bin/custom_switch_root $FAKEROOT /sbin/init
```

the `custom_switch_root` command we run in the end it this binary: https://github.com/u-root/u-root/blob/main/pkg/mount/switch_root_linux.go#L164

with only this change;

```
diff --git a/pkg/mount/switch_root_linux.go b/pkg/mount/switch_root_linux.go
index daf945e3..da8bb440 100644
--- a/pkg/mount/switch_root_linux.go
+++ b/pkg/mount/switch_root_linux.go
@@ -199,8 +199,10 @@ func newRoot(newRootDir string) error {
                return fmt.Errorf("switch_root: fatal chroot error %v", err)
        }
 
-       log.Printf("switch_root: Deleting old /")
-       return recursiveDelete(int(oldRoot.Fd()))
+       return err
+
+       //log.Printf("switch_root: Deleting old /")
+       //return recursiveDelete(int(oldRoot.Fd()))
 }
```

to disable the recursiveDelete which fails because we are on a read only filesystem

With these changes everything works without the config.toml.tmpl and NoPivotRoot setting.

It might be that the only difference with what immucore was already doing is that `/` now is mounted as `tmpfs` while before it was `rootfs`. Checked with:

```
findmnt -o TARGET,PROPAGATION,SOURCE,VFS-OPTIONS,PARENT,FSTYPE /
```

Now that we have a solution that works, we can start stripping it down to see which parts are really needed.

**Comment by Itxaka** [comment]
For noPivotRoot:

/ and /proc need to be private NOT RECURSIVE
/dev needs to be private RECURSIVE

So just doing a 

```
mount --make-private /
mount --make-private /proc
mount --make-rprivate /dev
```

This seems to make it work as expected.


Otherwise a simple way of doing is to make rprivate / so ti just makes everything private and then make rshared both /dev and /sys

**Comment by jimmykarily** [comment]
Fix merged: https://github.com/kairos-io/immucore/pull/234/files

**Comment by jimmykarily** [comment]
The only thing left is to remove the config.toml.tmpl file

**Comment by jimmykarily** [comment]
Removed: https://github.com/kairos-io/packages/commit/d9da73bd5da9a70c24c8c346e4385fb4623dbf86

**Comment by jimmykarily** [comment]
I verified that a built from kairos master doesn't have the `tmpl` file and k3s works fine. Closing this.
