### ISSUE TITLE
Add xe-guest-utilities support

### ISSUE THREAD

**Issue by musklor** [kairos-io/kairos#2312]
Hi, kairos is fantastic!

I just need xe-guest-utilities. (I use xcp-ng)
Bundle?
Packages?
Included in the ISO?

**Comment by jimmykarily** [comment]
We are trying to avoid adding too many packages in the base Kairos images to keep the small (e.g. this allows us to use them in UKI mode as well).

Is a custom image an option for you? https://kairos.io/docs/advanced/customizing/

**Comment by musklor** [comment]
Or a bundle?

**Comment by musklor** [comment]
Xenserver is heavily used by amazon (aws).

**Comment by musklor** [comment]
> We are trying to avoid adding too many packages in the base Kairos images to keep the small (e.g. this allows us to use them in UKI mode as well).
> 
> Is a custom image an option for you? https://kairos.io/docs/advanced/customizing/

Hi, do you have some examples?

**Comment by jimmykarily** [comment]
Create a dockerfile to install the needed packages. E.g.: 

```Dockerfile
FROM quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1

dnf -y install xe-guest-utilities-latest
```

Build an image:

```
docker build -t mycustomimage .
```

and then follow the instructions here to build an ISO: https://kairos.io/docs/advanced/build/#build-an-iso
or using auroraboot: https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-local-container-image

**Comment by musklor** [comment]
> Create a dockerfile to install the needed packages. E.g.:
> 
> ```dockerfile
> FROM quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1
> 
> dnf -y install xe-guest-utilities-latest
> ```
> 
> Build an image:
> 
> ```
> docker build -t mycustomimage .
> ```
> 
> and then follow the instructions here to build an ISO: https://kairos.io/docs/advanced/build/#build-an-iso or using auroraboot: https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-local-container-image

Can I use upgrade/update an existing installation/cluster?

**Comment by jimmykarily** [comment]
> > Create a dockerfile to install the needed packages. E.g.:
> > ```dockerfile
> > FROM quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1
> > 
> > dnf -y install xe-guest-utilities-latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Build an image:
> > ```
> > docker build -t mycustomimage .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then follow the instructions here to build an ISO: https://kairos.io/docs/advanced/build/#build-an-iso or using auroraboot: https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-local-container-image
> 
> Can I use upgrade/update an existing installation/cluster?

Yes that works too (that way you don't need to create an ISO).

**Comment by musklor** [comment]
> > > Create a dockerfile to install the needed packages. E.g.:
> > > ```dockerfile
> > > FROM quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1
> > > 
> > > dnf -y install xe-guest-utilities-latest
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Build an image:
> > > ```
> > > docker build -t mycustomimage .
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and then follow the instructions here to build an ISO: https://kairos.io/docs/advanced/build/#build-an-iso or using auroraboot: https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-local-container-image
> > 
> > 
> > Can I use upgrade/update an existing installation/cluster?
> 
> Yes that works too (that way you don't need to create an ISO).

sudo kairos-agent upgrade --source dir:/tmp/ ???

**Comment by musklor** [comment]
> > > > > Create a dockerfile to install the needed packages. E.g.:
> > > > > ```dockerfile
> > > > > FROM quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1
> > > > > 
> > > > > dnf -y install xe-guest-utilities-latest
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Build an image:
> > > > > ```
> > > > > docker build -t mycustomimage .
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > and then follow the instructions here to build an ISO: https://kairos.io/docs/advanced/build/#build-an-iso or using auroraboot: https://kairos.io/docs/reference/auroraboot/#offline-iso-build-from-local-container-image
> > > > 
> > > > 
> > > > Can I use upgrade/update an existing installation/cluster?
> > > 
> > > 
> > > Yes that works too (that way you don't need to create an ISO).
> > 
> > 
> > sudo kairos-agent upgrade --source dir:/tmp/ ???
> 
> https://kairos.io/docs/upgrade/manual/

Thanks a lot but I can't create iso, I can't use my custom image in order to create iso.

**Comment by jimmykarily** [comment]
The link I sent, describes how to upgrade using an container image, not an ISO. You don't need to create an ISO if you don't want to.

**Comment by musklor** [comment]
Ok, I made an iso.
I have an image on dockerhub.
I have now a fully functional kairos fedora flavor with xe guest utilities integrated.

**Comment by musklor** [comment]
Dockerfile

FROM quay.io/kairos/fedora:38-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1
RUN dnf -y install xe-guest-utilities-latest
RUN systemctl enable xe-linux-distribution
RUN sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
RUN sed -i -e '/^#PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config

**Comment by musklor** [comment]
> The link I sent, describes how to upgrade using an container image, not an ISO. You don't need to create an ISO if you don't want to.

Hi, fedora flavor is fully functional with longhorn?
Selinux is activated?
If I want to upgrade/update kairos, I can use the official release or I have to build a new version with docker?

**Comment by jimmykarily** [comment]
> > The link I sent, describes how to upgrade using an container image, not an ISO. You don't need to create an ISO if you don't want to.
> 
> Hi, fedora flavor is fully functional with longhorn? Selinux is activated? Edit : ok it is not activated. If I want to upgrade/update kairos, I can use the official release or I have to build a new version with docker?

We don't have automated tests for longhorn (or other Kubernetes workloads) but we don't have any reason to think longhorn won't work. Please open an issue if you find that it doesn't work.

If you installed a custom version of Kairos with modifications, since Kairos upgrade is an atomic operation that fully replaces the OS with a new image, in order to keep your modifications, you'll need to apply them on top of the new version too. In other words, you'll need a pipeline that generates a new version of your custom image for every new Kairos version that you want to upgrade to.
