### ISSUE TITLE
Kairos is very useful. Sometimes, I want to disable the read-only system so that I can install tools such as packet capture and Git for testing. Is there any way to disable the read-only system

### ISSUE THREAD

**Issue by gaocheng001** [kairos-io/kairos#2324]
Kairos is very useful. Sometimes, I want to disable the read-only system so that I can install tools such as packet capture and Git for testing. Is there any way to disable the read-only system

**Comment by nianyush** [comment]
you can add `rd.cos.debugrw` to your cmdline. 
To modify your cmdline on boot, you can press E after highlighting the menu in grubmenu

**Comment by cheese** [comment]
Something like `ostree admin unlock` or `rpm-ostree usroverlay` is wanted.

**Comment by Itxaka** [comment]
This was already answered, there is a debug mode that can allow you to have the system on RW but its fully unsupported, only in there for dev/testing purposes.

To add things for the base image so they are available in the final, there is already a way of doing it vi creating your own derivatives as explained in the docs https://kairos.io/docs/advanced/customizing/
