### ISSUE TITLE
Branding Menu with version string is extending out of display width in QEMU VM

### ISSUE THREAD

**Issue by vipsharm** [kairos-io/kairos#2325]
**Kairos version:**
v3.0.0

Also shows cmdline in Menu item. Can we make it same as old non-secure OS grub menus.

<img width="964" alt="Screenshot 2024-03-09 at 9 19 26 PM" src="https://github.com/kairos-io/kairos/assets/13304280/2ae21c87-dfc4-4fdf-bf21-3951516d828c">

**Comment by mudler** [comment]
@vipsharm can you please share what you'd like to see?

**Comment by jimmykarily** [comment]
When fixed, let's also document it: https://github.com/kairos-io/kairos/issues/2239

**Comment by mauromorales** [comment]
@vipsharm would this be the right format?



![Image](https://github.com/kairos-io/kairos/assets/433958/09318fb2-c2be-4a28-9152-939f0ad253f8)

**Comment by jimmykarily** [comment]
I think they want something as close to this as possible:

![image](https://github.com/kairos-io/kairos/assets/2794419/23028fad-64b8-43e7-bffc-ad9c6db4cd83)

**Comment by vipsharm** [comment]
<img width="1715" alt="Screenshot 2024-03-11 at 9 05 15 PM" src="https://github.com/kairos-io/kairos/assets/13304280/805ccc32-7cd3-4a04-9bff-68f19db8d07e">

**Comment by vipsharm** [comment]
This is the menu item output in non-secure image. Can we make it as close to this as possible ?

**Comment by mauromorales** [comment]
@vipsharm sure thing:
<img width="461" alt="Screenshot 2024-03-12 at 10 50 01" src="https://github.com/kairos-io/kairos/assets/433958/1443374c-c3ee-4c07-a4e1-9512b5ea2703">

**Comment by mauromorales** [comment]
The only part missing now is to have `kairos-agent bootentry` also display the same names (cos, fallback and recovery) this is being handled on a different PR

**Comment by mauromorales** [comment]
https://github.com/kairos-io/kairos-agent/pull/247
