### ISSUE TITLE
Test calico on Kairos v3.0.0 with UKI

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2328]
We've seen some errors when installing calico with UKI mode. Let's try to fix it.

**Comment by mudler** [comment]
@jimmykarily this look way too much generic. Maybe we can wait for @vipsharm feedback here?

**Comment by jimmykarily** [comment]
@Itxaka was able to see it failing. I don't know the steps to reproduce but I'm guessing we should see it immediately if we try to follow upstream docs. Any additional information would help though, yes.

**Comment by Itxaka** [comment]
full error with containerd debug

```
E0312 13:40:22.937136   30195 remote_runtime.go:496] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"0e28793b5d60989cb21b5eb498cc97dad1d4e07ea01703feaa045fb4ca7008a1\": OCI runtime exec failed: exec failed: unable to start container process: error closing exec fds: open /proc/self/fd: no such file or directory: unknown" containerID="b222ecf861d5a70e1bf88a8567d14bb98440e75538c369f04826cb9f3b132b57" cmd=["/bin/calico-node","-felix-ready","-bird-ready"]
```

**Comment by Itxaka** [comment]
so anything that execs fails

**Comment by Itxaka** [comment]
some advance...kind of

If we dont allow immucore to bind mount the existing /proc and /sys onto the new fake sysroot and let systemd do it itself on the initialization, the error changes:


```
 Liveness probe errored: rpc error: code = Unknown desc = failed to e
xec in container: failed to start exec "b2f8267bbe841cdc6e8e524735f0decbdb021fda
2b9b7fe5ad43c3fdf533aa13": OCI runtime exec failed: exec failed: unable to start
 container process: unable to setup user: stat /dev/null: no such file or direct
ory: unknown
```

Which points to either the immucore mounts not being quite rigth, or that we should not move mount the existing /proc and /sys into the new fake sysroot.

MAybe if we drop /dev it will be recreated as well and work as expected?

**Comment by Itxaka** [comment]
ok, if we drop the move mount of /dev /sys and /proc into the new sysroot, a different error appears


```
Readiness probe errored: rpc erro
r: code = Unknown desc = failed to exec in container: failed to start exec "efaf
eb1fb7b7b5099823f2ae7c4555f4d6a07f97167930805e7417509d1940a2": OCI runtime exec 
failed: exec failed: unable to start container process: exec: "/bin/calico-node"
: stat /bin/calico-node: no such file or directory: unknown
```

**Comment by jimmykarily** [comment]
I would expect `/bin/calico-node` to be in the Pod's image. Can you check if this is mounted somehow (from host or other volume)? If it's in the image, how on earth could it not be found?

**Comment by Itxaka** [comment]
Looks like https://github.com/kairos-io/immucore/pull/241 fixes it.

A mixture of:
 - some mounts in initramfs not being shared so they were not moved correctly
 - some mounts were bind to the old sysroot which messed things up
 - not mounting /sysroot as / before switching to new root
 - some mounts missing (/dev/pts, /dev/mqueue, etc...) we messing things up


With that patch we could deploy calico and see that the container rootfs is the proper rootfs of the container, no more mixups
