### ISSUE TITLE
Display only images on upgrade

### ISSUE THREAD

**Issue by Ludea** [kairos-io/kairos#2329]
**Kairos version:**

2.5.0

**CPU architecture, OS, and Version:**

cpu: aarch64
host: Rpi4
flavor: tumbleweed

**Describe the bug**

When listing available images on `kairos-agent upgrade list-releases`, images with `img` suffix is displayed. 

**To Reproduce**

`kairos-agent upgrade list-releases` on rpi4 with standard kairos 2.5.0 and tumbleweed flavor

**Expected behavior**

Only images without img should be displayed
**Logs**

![screenshot_2024-03-11-08-12-48-74_84d3000e3f4017145260f7618db1d683](https://github.com/kairos-io/kairos/assets/2116692/e90fa196-43c2-4a0d-b0bd-81476481acf0)

**Additional context**

Note: I see another issue, the current image is also displayed as available source, it should not

**Comment by mauromorales** [comment]
the test suite seems to have a check for this 🧐 

https://github.com/kairos-io/kairos-sdk/blob/28e2af3bc6f0cb1346a1f4cb75daf97f100aea00/versioneer/tag_list_test.go#L358

**Comment by mauromorales** [comment]
I tried to boot tumbleweed and leap 3.0.1, but they didn't work. Same experience if built from master. Will add a blocked label and have a look at that first

**Comment by Ludea** [comment]
From 3.0.1
```
ludea@rpi-1868:/home/ludea> sudo kairos-agent upgrade list-releases
Current image:
quay.io/kairos/opensuse:tumbleweed-standard-arm64-rpi4-v3.0.1-k3sv1.29.0-k3s1

Available releases with higher version:
quay.io/kairos/opensuse:tumbleweed-standard-arm64-rpi4-v3.0.1-k3sv1.29.0-k3s1-img
```

**Comment by jimmykarily** [comment]
> I tried to boot tumbleweed and leap 3.0.1, but they didn't work. Same experience if built from master. Will add a blocked label and have a look at that first

I created this to test v3.0.x on rpi: https://github.com/kairos-io/kairos/issues/2413

**Comment by jimmykarily** [comment]
v3.0.3 works on rpi4 (see the linked issue above). I verify that the issue exists:

```
localhost:/home/kairos # kairos-agent upgrade list-releases
Current image:
quay.io/kairos/opensuse:leap-15.5-standard-arm64-rpi4-v3.0.3-k3sv1.27.9-k3s1

Available releases with higher version:
quay.io/kairos/opensuse:leap-15.5-standard-arm64-rpi4-v3.0.3-k3sv1.29.3-k3s1-img
quay.io/kairos/opensuse:leap-15.5-standard-arm64-rpi4-v3.0.3-k3sv1.29.3-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-arm64-rpi4-v3.0.3-k3sv1.28.5-k3s1-img
quay.io/kairos/opensuse:leap-15.5-standard-arm64-rpi4-v3.0.3-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-arm64-rpi4-v3.0.3-k3sv1.27.9-k3s1-img
```

we need to implement filtering here: https://github.com/kairos-io/kairos-sdk/blob/main/versioneer/tag_list.go

**Comment by jimmykarily** [comment]
There is this: https://github.com/kairos-io/kairos-sdk/blob/9125488d8f7c78cb65305e66bb8f856bb9e55bfa/versioneer/tag_list.go#L56

```
// Images returns only tags that represent images, skipping tags representing:
// - sbom
// - att
// - sig
// - -img
```
but we are not using it: https://github.com/kairos-io/kairos-agent/blob/08eefab4682542b131aefbc4f1bcd7e3c67336ea/internal/agent/upgrade.go#L37-L65

**Comment by jimmykarily** [comment]
Maybe we can extend this test to catch it: https://github.com/kairos-io/kairos/blob/1e550195d94b2958baee29f4654244e3f7cb6721/tests/provider_upgrade_k8s_test.go#L131

We can't use `-img` because that would only be returned if we were in arm64 in the test but maybe it already returns `sbom` or other in the amd64 case.

**Comment by jimmykarily** [comment]
My mistake, `sbom` images look like this:

```
sha256-ed9a774b429b2e1ea1a8e6feb92cfe0a34b69cc00d5c1b43fca17094fa148b49.sbom
```
they are never maching the current release thus they are never returned. In the arm64 case, the `-img` images match the current release. That's why we saw them only in rpi. Good catch @Ludea 

I'll skip the test since we don't have arm runners and it's not reproducible elsewhere.
