### ISSUE TITLE
Latest releases of k3s are not picked up by kairos-standard builds

### ISSUE THREAD

**Issue by jbalonso** [kairos-io/kairos#2332]
**Kairos version:**
v3.0.0

**Describe the bug**
The latest release of k3s for the 1.29.x series is [v1.29.2](https://github.com/k3s-io/k3s/releases/tag/v1.29.2%2Bk3s1), from 2 weeks ago. The latest release of v3.0.0 (from 4 days ago) includes only 1.29.0.

**Additional context**
May relate to #2058, but that seems to be a more subtle issue than this one.

I believe there is automation in github actions that's supposed to be doing this, but this is not the first time this has occurred.

**Comment by jimmykarily** [comment]
There is an automated PR that bumps it: https://github.com/kairos-io/packages/pull/601/files

but we need to revert to a non-rc version and merged it.

**Comment by jimmykarily** [comment]
Fixed here: https://github.com/kairos-io/packages/compare/226db9632942dd8a01f6e15024011b8cac0dcfaa...main

Next autobump will skip `rc` versions. I manually bumped to the latest for now (can't force the bot to fix the existing one).

**Comment by jimmykarily** [comment]
It's now bumped in kairos master:

```
[root@fedora ~]# k3s --version
k3s version v1.29.2+k3s1 (86f10213)
go version go1.21.7
```

will be included in the next release.

@jbalonso thanks for reporting this!
