### ISSUE TITLE
Multi nodes to HA

### ISSUE THREAD

**Issue by musklor** [kairos-io/kairos#2338]
Hi, I'd like to migrate to a HA cluster (from multi nodes configuration : 1 master and three nodes)

Is it possible ?
Could you explain this in the documentation ? Please.

**Comment by jimmykarily** [comment]
You'd probably have to setup the cluster from scratch. Here are docs on how to do it for various different setups:

- https://kairos.io/docs/examples/ha/
- https://kairos.io/docs/examples/multi-node-p2p-ha/
- https://kairos.io/docs/examples/multi-node-p2p-ha-kubevip/
