### ISSUE TITLE
`config_url` in kernel cmdline ignored in v3.0.0

### ISSUE THREAD

**Issue by cheese** [kairos-io/kairos#2343]
**Kairos version:**
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_SOFTWARE_VERSION="v1.29.0+k3s1"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_ID="kairos"
KAIROS_PRETTY_NAME="kairos-standard-debian-bookworm v3.0.0-v1.29.0-k3s1"
KAIROS_VARIANT="standard"
KAIROS_RELEASE="v3.0.0"
KAIROS_NAME="kairos-standard-debian-bookworm"
KAIROS_FLAVOR="debian"
KAIROS_MODEL="generic"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_ID_LIKE="kairos-standard-debian-bookworm"
KAIROS_VERSION_ID="v3.0.0-v1.29.0-k3s1"
KAIROS_IMAGE_REPO="quay.io/kairos/debian:bookworm-standard-amd64-generic-v3.0.0-k3sv1.29.0-k3s1"
KAIROS_ARTIFACT="kairos-debian-bookworm-standard-amd64-generic-v3.0.0-k3sv1.29.0+k3s1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_VERSION="v3.0.0-v1.29.0-k3s1"
KAIROS_IMAGE_LABEL="bookworm-standard-amd64-generic-v3.0.0-k3sv1.29.0-k3s1"
KAIROS_FLAVOR_RELEASE="bookworm"
KAIROS_TARGETARCH="amd64"
```

**CPU architecture, OS, and Version:**

Linux test-kairos 6.1.0-18-amd64 https://github.com/kairos-io/kairos/pull/1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

**Describe the bug**

Automated installation by setting `config_url` in kernel cmdline is broken in v3.0.0. The option seems simply ignored.
It works in v2.5.0 with kairos-debian-bookworm-core-amd64-generic-v2.5.0.iso.

**To Reproduce**

Append `config_url` option to kernel cmdline but automated installation is ignored.

**Expected behavior**

Append `config_url` option to kernel cmdline triggers automated installation.

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
Good catch!

This is a bug when parsing the cmdline if there is any key that has a dash in it.

Fix on the config collector at: https://github.com/kairos-io/kairos-sdk/pull/73
