### ISSUE TITLE
Latest image still has luet version 0.34.0

### ISSUE THREAD

**Issue by nianyush** [kairos-io/kairos#2370]
For quay.io/kairos/ubuntu:22.04-core-amd64-generic-master
```
root@bb2cce63984c:/# luet -v
luet version 0.34.0-g4c788ccbd18e287c15c9610594daa533b53ffdad 2024-03-15 08:27:52 UTC
root@bb2cce63984c:/# which luet
/usr/bin/luet
```
despite its already update to v0.35.1 [here](https://github.com/kairos-io/kairos/blob/master/Earthfile#L8)
Is this a bug somewhere in ci? I can see that this image got built very recently(~9hours ago)

**Comment by nianyush** [comment]
Build time is quite new, is this a bug in luet version? @mudler

**Comment by jimmykarily** [comment]
The luet in the image seems to originate from the framework: https://github.com/kairos-io/kairos-framework/blob/e7e08dd4b6233f953d0c3bb859ef5ebcd4d544ec/Dockerfile#L45 but [that's also bumped to the latest version](https://github.com/kairos-io/kairos-framework/blob/e7e08dd4b6233f953d0c3bb859ef5ebcd4d544ec/Dockerfile#L3).

**Comment by jimmykarily** [comment]
Yes, it seems like a luet version bug: 

```
~/workspace/kairos/kairos-framework (main)$ docker run --rm -it quay.io/luet/base:0.35.1 -v
luet version 0.34.0-g4c788ccbd18e287c15c9610594daa533b53ffdad 2024-03-15 08:27:52 UTC

```
