### ISSUE TITLE
UKI: Secure Boot not enabled when booting on LiveCD

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2376]
**Kairos version:**
3.0.1

**CPU architecture, OS, and Version:**

**Describe the bug**
Seems https://github.com/kairos-io/immucore/blob/2bd94e44ab00e3b3d61b51654719937285e7160d/pkg/state/steps_uki.go#L151 fails to identify when a LiveCD is running in UEFI setup mode (with no certificate loaded). And making LiveCD not-bootable anymore.

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by jimmykarily** [comment]
After this change: 

- https://github.com/kairos-io/kairos/issues/2377
- https://github.com/kairos-io/enki/commit/798c7bac12d685adbb2d6bdb4565b223a98a364f

the keys should be enrolled before we even boot Kairos (systemd-boot will present a menu entry to do so).

This means that the check for secure boot will succeed after the enrollment. Given there is no reason to ever boot the livecd with no keys enrolled, is there anything else to do here?

**Comment by vipsharm** [comment]
Hi @jimmykarily , I think this is fixed now with #2377

**Comment by mudler** [comment]
yes this is fixed now, closing
