### ISSUE TITLE
Auto enroll keys in UKI mode without removing the microsoft ones

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2377]
```
Replacing the platform keys with your own can end up bricking hardware on some machines, including laptops, making it impossible to get into the firmware settings to rectify the situation. This is due to the fact that some device (e.g GPU) firmware ([OpROMs](https://en.wikipedia.org/wiki/OpROM)), that get executed during boot, [are signed using Microsoft 3rd Party UEFI CA certificate](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Microsoft_Windows).
```

([From the arch docs](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/)Secure_Boot#Using_your_own_keys)

Some systems signs 3rd party firmware with the microsoft keys (e.g. machines without a iGPU).

`sbctl` has flags that should keep the microsoft keys around (https://man.archlinux.org/man/sbctl.8) so that the system is not bricked when we enroll our keys.

Let's try these commands to see if we can enroll the Kairos keys without removing the Microsoft ones.
Ideally, we shouldn't even need to enter "Setup mode" since we are only appending keys to the db.

**Comment by Itxaka** [comment]
Manually tested this on my own pc, extending my existing certs with the Kairos DB key and cert and it appended them + Microsoft default certs

**Comment by jimmykarily** [comment]
In your case, you were booted in an already trusted system with secureboot enabled, when you enrolled the keys, right?

**Comment by Itxaka** [comment]
From a setup mode machine:

 - Import our keys: `sbctl import-keys --directory /tmp/keys`
 - Create GUID: `sbctl create-keys`
 - Enroll our keys + Microsoft keys: `sbctl enroll-keys -m -c -a`


This results in a secureboot enabled machine with:
 - PK from kairos
 - KEK from MS
 - DB from MS

Which results in:
 - Able to boot kairos with SecureBoot enabled
 - Able to boot ubuntu (upstream iso, non touched, directly from Canonical) with SecureBoot enabled

So it seems that we can generate a proper mix of our certs and Microsoft crets which should result in the OpRoms being to be verified.

Should try this with something that has a OpRom AND the posibility of disabling SecureBoot via a jumper int he motherboard or something

**Comment by Itxaka** [comment]
According to the sbctl docs on this, just having the UEFI CA from Microsoft in there should fix any issues with OpRoms: https://github.com/Foxboron/sbctl/wiki/FAQ#option-rom

```
If there is Option ROM in your bootchain there are two ways one can solve this:

    Enroll the Microsoft Corporation UEFI CA 2011 file.
    Read the checksums from the TPM eventlog.
```

**Comment by jimmykarily** [comment]
I added the option to not auto-enroll keys in systemd-boot:

```
-       data := fmt.Sprintf("default %s\ntimeout 5\nconsole-mode max\neditor no\n", finalEfiConf)
+       data := fmt.Sprintf("default %s\ntimeout 5\nconsole-mode max\neditor no\nsecure-boot-enroll manual\n", finalEfiConf)
```
and added the extra cmdline `rd.immucore.securebootdisabled` . I then reset the keys in qemu and indeed sbctl now sees it in setup mode:

```
[root@fedora kairos]# sbctl status
Installed:	✗ sbctl is not installed
Setup Mode:	✗ Enabled
Secure Boot:	✗ Disabled
Vendor Keys:	none
```

When I try to enroll the keys (without  importing any), I get this:

```
Found OptionROM in the bootchain. This means we should not enroll keys into UEFI without some precautions.

There are three flags that can be used:
    --microsoft: Enroll the Microsoft OEM certificates into the signature database.
    --tpm-eventlog: Enroll OpRom checksums into the signature database (experimental!).
    --yes-this-might-brick-my-machine: Ignore this warning and continue regardless.

Please read the FAQ for more information: https://github.com/Foxboron/sbctl/wiki/FAQ#option-rom
```

and with the additional flag:

```
[root@fedora kairos]# sbctl enroll-keys --yes-this-might-brick-my-machine -a -f -i -p db 
open /usr/share/secureboot/GUID: no such file or directory
```

**Comment by jimmykarily** [comment]
After running Itxaka's commands above, it works:

```
[root@fedora kairos]# sbctl status
Installed:	✓ sbctl is installed
Owner GUID:	b57a5790-eab3-4436-a6b5-0fd063bc12e6
Setup Mode:	✓ Disabled
Secure Boot:	✗ Disabled
Vendor Keys:	microsoft
```

`sbctl import-keys --directory keys/` expects the various keys in subdirectories so I had to prepare the dir accordingly.

**Comment by jimmykarily** [comment]
This image should now enroll the microsoft keys: https://github.com/kairos-io/osbuilder/releases/tag/v0.200.8
