### ISSUE TITLE
config_url is not considered when network booting kairos installer

### ISSUE THREAD

**Issue by asteven** [kairos-io/kairos#2395]
**Kairos version:**
- v3.0.1
- v2.5.0
- v2.4.3
e.g. kairos-ubuntu-22.04-standard-amd64-generic-v3.0.1-k3sv1.29.0+k3s1

**CPU architecture, OS, and Version:**
x86_64, ubuntu

**Describe the bug**
The kernel cmdline parameter `config_url` is consequently ignored when trying to install kairos via pxe.
Reproducible with https://github.com/kairos-io/kairos/releases/download/v3.0.1/kairos-ubuntu-22.04-standard-amd64-generic-v3.0.1-k3sv1.29.0+k3s1{-kernel,initramfs,.squashfs}
But also does not work with v2.5.0 and v2.4.3.

The server loads kernel, initrd and squashfs, starts the installer, but never fetches the configuration from `config_url`.
Instead it starts the webui and generates a qrcode on tty1. (btw, kairos output only goes to tty1 and is missing on the serial console)

The http server logs GET requests for kernel, initrd and squashfs, but no trace of a get for config_url.
Manually running `curl $config_url` from the server works fine.

**To Reproduce**
Try to pxe boot kairos using one of the released ipxe scripts, e.g. 
https://github.com/kairos-io/kairos/releases/download/v3.0.1/kairos-ubuntu-22.04-standard-amd64-generic-v3.0.1-k3sv1.29.0+k3s1.ipxe
Obviously change config_url to point at some webserver.
I was using a config_url with an IP instead of a hostname in case that matters e.g. config_url=http://127.0.0.1/config.yaml

**Expected behavior**
The server loads kernel, initrd and squashfs and then starts the installer which fetches and uses the config file specified in the `config_url` kernel cmdline parameter to automatically install the server.

**Comment by cheese** [comment]
Duplicate of #2343?

**Comment by Itxaka** [comment]
Indeed it looks like a duplicate of the same issue. IIRC this should be fixed in 3.03

**Comment by asteven** [comment]
Seems to work with 3.03.
Thanks!

**Comment by asteven** [comment]
What I'm seeing now with 3.0.3 is that the config file from config_url is fetched via http 4 (or 3?) times.
It's parsed from /proc/cmdline correctly, but then get's added to the local/merged config.yaml.
I guess that's a bug? The installer (or something) is downloading the same file multiple times.

**Comment by Itxaka** [comment]
Yes, it should be ok. Every run of the agent or immucore will gather all the config info from all the sources, so if it's a config url it will try to fecth it just in time 

So it will try to fecth it multiple times as it's run several times for the stages for example.

Ideally this is so you can update the remote config and it will immediately be reflected on any actions that the nodes do, i.e. you update the users on the config file so on the next agent run it will pick the new config.


Otherwise it will just fetch it once and keep it static in the node forever

**Comment by asteven** [comment]
Ok, thanks for clarifying.
