### ISSUE TITLE
Kairos-agent bootentry --select is broken in 3.0.2

### ISSUE THREAD

**Issue by vipsharm** [kairos-io/kairos#2408]
**Kairos version:**
root@edge-5a6f5572c79f45bfa618a209d66bc182:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
KAIROS_IMAGE_REPO="quay.io/kairos/ubuntu:23.10-core-amd64-generic-v3.0.2"
KAIROS_RELEASE="v3.0.2"
KAIROS_FLAVOR="ubuntu"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_ID_LIKE="kairos-core-ubuntu-23.10"
KAIROS_VERSION_ID="v3.0.2"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-23.10 v3.0.2"
KAIROS_TARGETARCH="amd64"
KAIROS_NAME="kairos-core-ubuntu-23.10"
KAIROS_VERSION="v3.0.2"
KAIROS_IMAGE_LABEL="23.10-core-amd64-generic-v3.0.2"
KAIROS_VARIANT="core"
KAIROS_MODEL="generic"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_ID="kairos"
KAIROS_ARTIFACT="kairos-ubuntu-23.10-core-amd64-generic-v3.0.2"
KAIROS_FLAVOR_RELEASE="23.10"

KAIROS_NAME="kairos-core-ubuntu"
KAIROS_VERSION="v3.0.2"
KAIROS_ID="ubuntu"
KAIROS_ID_LIKE="kairos-core-ubuntu"
KAIROS_VERSION_ID="v3.0.2"
KAIROS_PRETTY_NAME="kairos-core-ubuntu v3.0.2"
KAIROS_BUG_REPORT_URL="https://github.com/spectrocloud/CanvOS/issues"
KAIROS_HOME_URL="https://github.com/spectrocloud/CanvOS"
KAIROS_IMAGE_REPO="spectrocloud/CanvOS"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO=""
KAIROS_VARIANT="ubuntu"
KAIROS_FLAVOR="ubuntu"
KAIROS_ARTIFACT="kairos-core-ubuntu-v3.0.2"
root@edge-5a6f5572c79f45bfa618a209d66bc182:~# 

root@edge-5a6f5572c79f45bfa618a209d66bc182:~# kairos-agent bootentry --select reset
2024-03-29T01:05:22Z INF Kairos Agent version=v2.8.6
2024-03-29T01:05:22Z INF Kairos System version=v3.0.2
2024-03-29T01:05:22Z INF creating a runtime
2024-03-29T01:05:22Z INF detecting boot state
2024-03-29T01:05:22Z INF Boot Mode boot_mode=active_boot
2024-03-29T01:05:22Z INF Boot in uki mode result=true
2024-03-29T01:05:22Z INF Setting default boot entry to reset
2024-03-29T01:05:22Z ERR entry reset does not exist
entry reset does not exist
root@edge-5a6f5572c79f45bfa618a209d66bc182:~# kairos-agent bootentry --select recovery
2024-03-29T01:05:25Z INF Kairos Agent version=v2.8.6
2024-03-29T01:05:25Z INF Kairos System version=v3.0.2
2024-03-29T01:05:25Z INF creating a runtime
2024-03-29T01:05:25Z INF detecting boot state
2024-03-29T01:05:25Z INF Boot Mode boot_mode=active_boot
2024-03-29T01:05:25Z INF Boot in uki mode result=true
2024-03-29T01:05:25Z INF Setting default boot entry to recovery
2024-03-29T01:05:25Z ERR entry recovery does not exist
entry recovery does not exist
root@edge-5a6f5572c79f45bfa618a209d66bc182:~#

**Comment by vipsharm** [comment]
Also active image is not set as default boot entry on install.

**Comment by mauromorales** [comment]
@vipsharm can you please add information of how you built this image? which enki flags did you pass for example?

**Comment by mauromorales** [comment]
@vipsharm the question before is not for this bug actually but because you also mentioned in the slack channel that you didn't see the boot menu

**Comment by mauromorales** [comment]
I can reproduce this issue. Additionally: recovery works only interactively, reset is not called reset internally but "auto reset" but doesn't work interactively either.
