### ISSUE TITLE
Skip the platform key when enrolling the Kairos keys

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2420]
We saw that when manually importing the Kairos keys, the plaform key stays that of the vendor and that works fine. When we put the machine in "setup mode" and enroll the Kairos keys, the platform key becomes the Kairos one.
Since that is not necessary, let's try to skip replacing the vendor platform key to stay on the safe side.

**Comment by Itxaka** [comment]
FYI: setup mode is only possible if the PK is empty. So this is only valid for manual importing keys.

**Comment by jimmykarily** [comment]
Also I think the reason it works when we manually enroll our keys is because the UEFI has the private keys available somewhere (otherwise what does it use to sign the `db` file we export?). We don't have the private key that matches with the vendor's PK so we can't keep the PK be the vendor one I think.

**Comment by jimmykarily** [comment]
Let's close this. If it's really required we can dig deeper and re-open.
