### ISSUE TITLE
Error when installing longhorn bundle with kairos-agent

### ISSUE THREAD

**Issue by xt0ph** [kairos-io/kairos#2438]
**Kairos version:**
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
KAIROS_IMAGE_REPO="quay.io/kairos/debian:bookworm-standard-amd64-generic-v3.0.3-k3sv1.29.3-k3s1"
KAIROS_IMAGE_LABEL="bookworm-standard-amd64-generic-v3.0.3-k3sv1.29.3-k3s1"
KAIROS_ARTIFACT="kairos-debian-bookworm-standard-amd64-generic-v3.0.3-k3sv1.29.3+k3s1"
KAIROS_FLAVOR_RELEASE="bookworm"
KAIROS_MODEL="generic"
KAIROS_SOFTWARE_VERSION="v1.29.3+k3s1"
KAIROS_VERSION="v3.0.3-v1.29.3-k3s1"
KAIROS_VERSION_ID="v3.0.3-v1.29.3-k3s1"
KAIROS_RELEASE="v3.0.3"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_FLAVOR="debian"
KAIROS_VARIANT="standard"
KAIROS_TARGETARCH="amd64"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_NAME="kairos-standard-debian-bookworm"
KAIROS_PRETTY_NAME="kairos-standard-debian-bookworm v3.0.3-v1.29.3-k3s1"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-standard-debian-bookworm"

**CPU architecture, OS, and Version:**
Linux ks1 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

**Describe the bug**
When i try to install longhorn bundle with kairos-agent, I get the following error:

```
root@ks1:~# kairos-agent install-bundle run://quay.io/kairos/community-bundles:longhorn_latest
1 error occurred:
        * could not execute container: exit status 2 - + K3S_MANIFEST_DIR=/var/lib/rancher/k3s/server/manifests/
+ VALUES={}
+ VERSION=1.5.3
+ mkdir -p /var/lib/rancher/k3s/server/manifests/
+ readConfig
+ getConfig longhorn.values
+ local key=longhorn.values
+ kairos-agent config get longhorn.values | @json
+ tr -d \n
+ _value="null"
run.sh: 12: Bad substitution
+ _values=
```
**To Reproduce**
Here are the steps I followed:

1. Installing an HA k3s cluster from the sample on kairos web site
1. Installing the k3s dashboard (not sure if this is necessary to reproduce the issue)
1. kairos-agent launch to install longhorn: `kairos-agent install-bundle run://quay.io/kairos/community-bundles:longhorn_latest`

**Expected behavior**
Have longhorn installed :-)

**Additional context**
I am new to kairos and I may not have installed all the prerequisites for longhorn on kairos

**Comment by jimmykarily** [comment]
His @xt0ph, thanks for opening this.
It's caused by this: https://github.com/kairos-io/kairos/issues/2315 let's track it there.

**Comment by mauromorales** [comment]
seems we got confused about issue #2315 and this is still relevant
