### ISSUE TITLE
backport: immucore timeout

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2451]
problem: we need to backport https://github.com/kairos-io/immucore/compare/v0.1.6...v0.1.6-timeout?expand=1 to a release of immucore that can be consumed with the same framework image of #2389

**Comment by mudler** [comment]
There was an error with tagging release artifacts of immucore. 0.1.7 is what we are targeting, but we tagged 0.1.17-<patch_number>

**Comment by Itxaka** [comment]
This is already ont he backport and forwardport no? should we close it? @mudler
