### ISSUE TITLE
Missing /boot/vmlinuz in jetson orin base image

### ISSUE THREAD

**Issue by nianyush** [kairos-io/kairos#2461]
Tried with kairos v2.4.3 and v3.0.4. Both results into same error.
![image](https://github.com/kairos-io/kairos/assets/5505684/6fbcd1ca-ab48-446e-b20c-201c7d4a7851)
And i noticed that with 2.3.2 image which was working before has this /boot/vmlinuz but neither 2.4.3 or 3.0.4 base image has it

**Comment by mauromorales** [comment]
2.3.2:

```
root@fd7c207f33b4:/# ls -las /boot/vmlinuz
0 lrwxrwxrwx 1 root root 5 Aug  3  2023 /boot/vmlinuz -> Image
```

However the generic link is trying to do this:

```
# symlink kernel to /boot/vmlinuz
RUN kernel=$(ls /boot/vmlinuz-* 2>/dev/null | head -n1) && if [ -e "$kernel" ]; then ln -sf "$kernel" /boot/vmlinuz; fi || true
RUN kernel=$(ls /boot/Image-* 2>/dev/null | head -n1) && if [ -e "$kernel" ]; then ln -sf "$kernel" /boot/vmlinuz; fi || true
```
from: https://github.com/kairos-io/kairos/blob/master/images/Dockerfile.kairos#L102-L103

Which of course misses the `/boot/Image` without any dashes
