### ISSUE TITLE
kairos-agent config get fails when trying to merge into an empty list

### ISSUE THREAD

**Issue by Akvanvig** [kairos-io/kairos#2513]
**Kairos version:**

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
KAIROS_VERSION="v3.0.6"
KAIROS_VERSION_ID="v3.0.6"
KAIROS_IMAGE_REPO="quay.io/kairos/ubuntu:22.04-core-amd64-generic-v3.0.6"
KAIROS_VARIANT="core"
KAIROS_MODEL="generic"
KAIROS_RELEASE="v3.0.6"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_ID="kairos"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-22.04 v3.0.6"
KAIROS_ARTIFACT="kairos-ubuntu-22.04-core-amd64-generic-v3.0.6"
KAIROS_FLAVOR="ubuntu"
KAIROS_FAMILY="ubuntu"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_NAME="kairos-core-ubuntu-22.04"
KAIROS_ID_LIKE="kairos-core-ubuntu-22.04"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_IMAGE_LABEL="22.04-core-amd64-generic-v3.0.6"
KAIROS_FLAVOR_RELEASE="22.04"
KAIROS_TARGETARCH="amd64"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"

**CPU architecture, OS, and Version:**

Linux kairos-test 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

When a list of items in the configuration is merged into an empty list, the agent returns an index out of range error

**To Reproduce**

Write a key with an empty slice to the first file, and then a slice containing items to the second. After this try running `kairos-agent config get`
```
printf "#cloud-config\nkey: []\n" > /oem/test1.yaml
printf "#cloud-config\nkey: \n- \"value1\"\n" > /oem/test2.yaml
kairos-agent c g key
``` 

Seems the problem is related to the slice merging function assuming lists contain items, and could be fixed by adding a length check before checking the type of the first item here in the kairos-sdk:
https://github.com/kairos-io/kairos-sdk/blob/main/collector/collector.go#L113

**Expected behavior**

**Logs**

```
root@kairos-test:~# printf "#cloud-config\nkey: []\n" > /oem/test1.yaml
root@kairos-test:~# printf "#cloud-config\nkey: \n- \"value1\"\n" > /oem/test2.yaml
root@kairos-test:~# kairos-agent c g key
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/kairos-io/kairos-sdk/collector.mergeSlices({0x1cb6e60?, 0x0?, 0x0?}, {0xc00037a9b0?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:113 +0x2ef
github.com/kairos-io/kairos-sdk/collector.DeepMerge({0xff3f00, 0xc000011b78?}, {0xff3f00, 0xc000011cc8?})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:183 +0x185
github.com/kairos-io/kairos-sdk/collector.deepMergeMaps(0x0?, 0xc00039cd20?)
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:154 +0x117
github.com/kairos-io/kairos-sdk/collector.DeepMerge({0x1059060, 0xc0004bbf80?}, {0x1059060, 0xc0000926c0?})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:187 +0x20f
github.com/kairos-io/kairos-sdk/collector.(*Config).MergeConfig(0xc0000580f0?, 0xc?)
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:102 +0x55
github.com/kairos-io/kairos-sdk/collector.Configs.Merge({0xc000139f20, 0xc, 0x50?})
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:212 +0xa5
github.com/kairos-io/kairos-sdk/collector.Scan(0xc0003dc000, 0x0?)
        /go/pkg/mod/github.com/kairos-io/kairos-sdk@v0.0.29/collector/collector.go:234 +0x237
github.com/kairos-io/kairos-agent/v2/pkg/config.scan(0xc0001a65a0, {0xc00049f670, 0x3, 0x0?})
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/config.go:353 +0xe5
github.com/kairos-io/kairos-agent/v2/pkg/config.ScanNoLogs({0xc00049f670, 0x3, 0x3})
        /go/src/github.com/kairos-io/kairos-agent/pkg/config/config.go:336 +0x129
main.glob..func12(0xc0003d6e00)
        /go/src/github.com/kairos-io/kairos-agent/main.go:354 +0x165
github.com/urfave/cli/v2.(*Command).Run(0x1c58500, 0xc0003d6e00, {0xc000409e60, 0x2, 0x2})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*Command).Run(0x1c58240, 0xc0003d6d40, {0xc0004ba540, 0x3, 0x3})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*Command).Run(0xc000194c60, 0xc0003d6b80, {0xc00013a040, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*App).RunContext(0xc0000fe800, {0x13c5540?, 0x1cb6e60}, {0xc00013a040, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
        /go/src/github.com/kairos-io/kairos-agent/main.go:827 +0x430
```

**Additional context**

**Comment by Akvanvig** [comment]
See PR for a possible fix

**Comment by jimmykarily** [comment]
NOTE: kairos-sdk needs to be bumped in kairos-agent (and then kairos-agent should be bumped all the way to the next kairos release) for the fix to be available.
