### ISSUE TITLE
opensuse rpi4 fails to boot in v3.0.9

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2563]
```
DISTRO_BASE="opensuse"
DISTRO_VERSION="leap-15.5"
VARIANT="standard"
ARCH="arm64"
MODEL="rpi4"
KAIROS_VERSION="v3.0.9"
K3S_VERSION="1.29.3"
```

Is broken.
![WhatsApp Bild 2024-05-02 um 23 32 50_c3b87247](https://github.com/kairos-io/kairos/assets/59036056/2c6089d0-0037-4310-8f0f-1d5f7b3bbe23)
![WhatsApp Bild 2024-05-02 um 23 32 49_3ff67ccb](https://github.com/kairos-io/kairos/assets/59036056/f3572bff-7200-420a-b5ab-5811279f64c3)

The old v3.0.6 works as expected. (https://github.com/kairos-io/kairos/compare/v3.0.6...v3.0.9)

_Originally posted by @kaiehrhardt in https://github.com/kairos-io/kairos/issues/2528#issuecomment-2091771671_

**Comment by kaiehrhardt** [comment]
i have not yet had time to instrument my installation with the debug arguments.

**Comment by kaiehrhardt** [comment]
![grafik](https://github.com/kairos-io/kairos/assets/59036056/bd346780-d6fa-4848-bd41-30483448ca94)

Is it helpful? I could provide more info, if you want. Is there any dracut debug flag? Not sure where that script come from.

**Comment by mauromorales** [comment]
I think you can also pass `rd.debug` and/or `rd.immucore.debug`

**Comment by kaiehrhardt** [comment]
This is the rd.debug log. I thought it's a global loglevel. Do i get more info if i also set rd.immucore.debug?

**Comment by jimmykarily** [comment]
Immucore [reads `rd.immucore.debug`](https://github.com/kairos-io/immucore/blob/4c4801cde3d38bd4198f63fa2bda69bf49bb147b/internal/utils/cloudinit.go#L63) for enable debug mode. But reading the actual logs might be tricky. You need to somehow get a shell. Probably using this: https://kairos.io/docs/reference/troubleshooting/#initramfs-breakpoints (with one of the stages [described here](https://man7.org/linux/man-pages/man7/dracut.modules.7.html))

**Comment by felixmw** [comment]
Any news on this issue? I am facing the same error messages. Happy to help but somehow I am not able to edit the boot options. The pi is not responding to my keyboard when in the boot menu.

**Comment by kaiehrhardt** [comment]
fixed in https://github.com/kairos-io/kairos/releases/tag/v3.1.0-rc1

**Comment by jimmykarily** [comment]
> fixed in https://github.com/kairos-io/kairos/releases/tag/v3.1.0-rc1

@felixmw can you try with `v3.1.0-rc1` ? If you verify that too we can close this issue.

**Comment by mauromorales** [comment]
probably related to how we were doing the backports https://github.com/kairos-io/kairos/issues/2624 my guess is that the latest 3.0.x release will probably also work

**Comment by felixmw** [comment]
I can confirm that the issue has been fixed in the current release (I tried with leap-15.6-standard-arm64-rpi4-v3.1.0-rc2-k3sv1.30.2-k3s1).

Thanx for your support!

**Comment by mauromorales** [comment]
@felixmw thanks for testing and the confirmation, closing
