### ISSUE TITLE
kairos-agent config get returns nothing when getting a single key with boolean false value

### ISSUE THREAD

**Issue by Akvanvig** [kairos-io/kairos#2581]
**Kairos version:**

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
KAIROS_ID_LIKE="kairos-core-ubuntu-24.04"
KAIROS_VERSION_ID="v3.0.10"
KAIROS_FAMILY="ubuntu"
KAIROS_VERSION="v3.0.10"
KAIROS_FLAVOR_RELEASE="24.04"
KAIROS_VARIANT="core"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_ID="kairos"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-24.04 v3.0.10"
KAIROS_IMAGE_REPO="quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.0.10"
KAIROS_IMAGE_LABEL="24.04-core-amd64-generic-v3.0.10"
KAIROS_ARTIFACT="kairos-ubuntu-24.04-core-amd64-generic-v3.0.10"
KAIROS_TARGETARCH="amd64"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_NAME="kairos-core-ubuntu-24.04"
KAIROS_FLAVOR="ubuntu"
KAIROS_MODEL="generic"
KAIROS_RELEASE="v3.0.10"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"

**CPU architecture, OS, and Version:**

Linux kairos-test 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

When getting the value of a single key with `kairos-agent config get`, and that value is a boolean false. It will not return anything at all.

**To Reproduce**

```
root@kairos-test:~# printf "#cloud-config\ntest:\n  singleKeyA: false\n  singleKeyB: true" > /usr/local/cloud-config/test.yaml

root@kairos-test:~# kairos-agent c g test
singleKeyA: false
singleKeyB: true

root@kairos-test:~# kairos-agent c g test.singleKeyA

root@kairos-test:~# kairos-agent c g test.singleKeyB
true
```

**Expected behavior**

The tool should return the actual value instead of nothing:
```
root@kairos-test:~# kairos-agent c g test.singleKeyA
false
root@kairos-test:~# kairos-agent c g test.singleKeyB
true
```

**Logs**

none

**Additional context**

Looking through the code, it seems this is the line causing it:
https://github.com/kairos-io/kairos-sdk/blob/c643cb5e736bdd760ee26864aa57c305eb42e644/collector/collector.go#L494

According to jq docs, this is expected behavior as the alternative-operator in jq so another solution would be needed here:
https://jqlang.github.io/jq/manual/#alternative-operator

**Comment by Akvanvig** [comment]
See pr for a possible fix
https://github.com/kairos-io/kairos-sdk/pull/114

**Comment by jimmykarily** [comment]
Nice catch @Akvanvig , thanks for the PR. I will bump the sdk in the kairos-agent so that the fix makes it in some upcoming release.
