### ISSUE TITLE
elemental process does not have context of env variables set in Config.Install.Env in reset

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#259]
**Kairos version:**
1.1.3

**CPU architecture, OS, and Version:**
x86_64, core alpine 1.1.3

**Describe the bug**
elemental process does not have access to env variables set in Config.Install.Env in reset
[here](https://github.com/kairos-io/kairos/blob/ca53fe6c13544610022e7259debfc7a5572c5e4d/internal/agent/reset.go#L73)
Elemental will fail to pull images during reset as it would not have access to http proxy variables set in Config.Install.env. The values in Config.Install.env needs to be set in the environment before kairos reset is triggered.

**To Reproduce**
set the http proxy environment variable in Config.Install.Env and run kairos reset

**Expected behavior**
kairos reset should be able to work successfully in proxy environments by pulling in the env vars set in Config.Install.env

**Comment by mudler** [comment]
Let's make it the other way around - we should rather have a `reset.env`, and a global `env` which applies to all phases - having the `install` block having a business logic in the `reset` action would be quite suprising

**Comment by santhoshdaivajna** [comment]
updated the PR to have env under Config which applies to all phases, let me know your thoughts.
Keeping Config.Install.Env so that upgrades do not cause breaking changes.
