### ISSUE TITLE
kairos rocky core image needs /etc/rc.d/rc.local execute bit set.

### ISSUE THREAD

**Issue by sarg3nt** [kairos-io/kairos#2621]
**Kairos version:**
kairos rocky core from master as of around June 10th 2024 or so.

**CPU architecture, OS, and Version:**
AMD 64 bit

**Describe the bug**
During boot, an error is generated saying that `/etc/rc.d/rc.local` is not executable.  I don't have a recording from the logs as we build a new container and I've had `chmod +x /etc/rc.d/rc.local` in one of the build scripts for months now.  I've been meaning to report this since I found it and am just now getting to it.

**Comment by Itxaka** [comment]
Confirmed. Maybe its expected, would need to check the systemd service to understand what it actually tries to do.

![Image](https://github.com/user-attachments/assets/8ee87f49-f986-4920-a63f-106ade902b19)

**Comment by Itxaka** [comment]
```
systemd-rc-local-generator is a generator that checks whether /etc/rc.local exists and is executable, and if it is, pulls the rc-local.service unit into the boot process. This unit is responsible for running this script during late boot. The script is run after network.target, but in parallel with most other regular system services.
```

```
Support for /etc/rc.local is provided for compatibility with specific System V systems only. However, it is strongly recommended to avoid using this script today, and instead provide proper unit files with appropriate dependencies for any scripts to run during the boot process. Note that the path to the script is set at compile time and varies between distributions.
```

**Comment by Itxaka** [comment]
I would say this is expected in this case, its provided for compatibility and should not affect anything unless you are using rc.local to run any scripts or anything similar.

https://forums.rockylinux.org/t/rc-local-not-executable/7364/7

![Image](https://github.com/user-attachments/assets/1671dac3-792b-455d-8434-6cbb976707e0)


I think this can be closed as its a non-issue and if behaviour of this wants to be changed its either discuss with upstream (good luck there lol)  or enable it yourself with cloud-init configs if rc.local support is needed.

@sarg3nt Im closing this, feel free to reopen if you thing the answer is not valid, but not much we can and will do, we rather stick to upstream guidelines as close as possible :)
