### ISSUE TITLE
Address OpenSSF best practices issues

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2647]
https://scorecard.dev/viewer/?uri=github.com/kairos-io/kairos&sort_by=check-score&sort_direction=asc

**Comment by Itxaka** [comment]
some of the issues were fixed by tweaking renovate to use digests

**Comment by mauromorales** [comment]
Got it to green 🎉 and it should increase a bit more with some of the changes that are calculated by checking the last x commits.
