### ISSUE TITLE
Intermittent download failures with openSUSE base images in CI

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#265]
**Kairos version:**
This doesn't affect Kairos, but rather Kairos CI

**Describe the bug**
This is a tracker for all the occurences of download failures with `zypper`.  Currently those are cumulating and hitting us regularly, for example:
```
#86 13.11  - File './repodata/6ea614a64061dd1840adfa7deee42986daaab8916caaa16408c540f17a8ac790-deltainfo.xml.gz' not found on medium 'http://download.opensuse.org/update/leap/15.4/backports/'
#86 13.11  - Can't provide ./repodata/6ea614a64061dd1840adfa7deee42986daaab8916caaa16408c540f17a8ac790-deltainfo.xml.gz
#86 13.11 
```

**To Reproduce**

**Expected behavior**
I'd rather prefer to switch to a different base or build an image with all the packages needed for tests inside

**Logs**

**Additional context**
- https://github.com/kairos-io/kairos/pull/264
- https://github.com/kairos-io/osbuilder/actions/runs/3311250394/jobs/5466461592

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3355901718/jobs/5560531307

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3357122458/jobs/5562721753

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3360669745/jobs/5570168439

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3362375827/jobs/5574015725

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3380983339/jobs/5614381109

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3384839737/jobs/5622287645

**Comment by mudler** [comment]
```

                +iso | Problem retrieving files from 'Non-OSS Repository'.
                +iso | Location 'http://download.opensuse.org/distribution/leap/15.4/repo/non-oss/media.1/media' is temporarily unaccessible.
                +iso | Please see the above error message for a hint.
                +iso | Warning: Skipping repository 'Non-OSS Repository' because of the above error.
                +iso | Problem retrieving files from 'Main Repository'.
                +iso | Location 'http://download.opensuse.org/distribution/leap/15.4/repo/oss/media.1/media' is temporarily unaccessible.
                +iso | Please see the above error message for a hint.
                +iso | Warning: Skipping repository 'Main Repository' because of the above error.
```

Always repository issues..

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3393103238/jobs/5640868696 again repository issues

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3393103238/jobs/5640869268
https://github.com/kairos-io/kairos/actions/runs/3393103238/jobs/5640869486

**Comment by oz123** [comment]
https://github.com/kairos-io/provider-kairos/actions/runs/3911657040/jobs/6693065974

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos/actions/runs/3996665011/jobs/6858756068

**Comment by mudler** [comment]
seems to be better now? at least didn't happened for me since a while
