### ISSUE TITLE
bump projects to go 1.22 and fix snyk cve

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2670]
let's also produce fips versions of the binaries to be prepared for then that is certified.

## Acceptance Criteria
- We let the product team we are doing this so they know why and what they have to do to be able to consume 3.2.X
- All `kairos-io` golang repositories use go1.22 to build binaries (in pipelines)
- all `go.mod` files refer to go1.22 as well
- all packages (luet) are also built with go1.22 (even the fips ones)

**Comment by mauromorales** [comment]
This PR should address some of the issues related to the main kairos repo and it doesn't affect fips since it's just testing https://github.com/kairos-io/kairos/pull/2678

**Comment by Itxaka** [comment]
- https://github.com/kairos-io/kairos-agent/pull/405
 - https://github.com/kairos-io/immucore/pull/347
 - https://github.com/kairos-io/kairos-sdk/pull/168
 - https://github.com/kairos-io/provider-kairos/pull/594
 - https://github.com/kairos-io/kcrypt/pull/413
 - https://github.com/kairos-io/kcrypt-challenger/pull/70
 - https://github.com/kairos-io/enki/pull/135
 - https://github.com/kairos-io/AuroraBoot/pull/60
 - https://github.com/kairos-io/go-nodepair/pull/32
 - https://github.com/kairos-io/osbuilder/pull/172
 - https://github.com/kairos-io/cluster-api-provider-kairos/pull/29
 - https://github.com/kairos-io/entangle/pull/11

**Comment by Itxaka** [comment]
Everything merged and bumped, all of them also had a tag cut after the go version was bumped so they can be consumed from the packages repo

**Comment by Itxaka** [comment]
All packages updated in repos, consider this done
