### ISSUE TITLE
failed to detect selinux: read /proc/thread-self/attr/current: invalid argument

### ISSUE THREAD

**Issue by kaiehrhardt** [kairos-io/kairos#2689]
**Kairos version:**
```
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
KAIROS_IMAGE_LABEL="leap-15.6-standard-arm64-rpi4-v3.1.0-rc1-k3sv1.30.1-k3s1"
KAIROS_FLAVOR_RELEASE="leap-15.6"
KAIROS_RELEASE="v3.1.0-rc1"
KAIROS_SOFTWARE_VERSION="v1.30.1+k3s1"
KAIROS_MODEL="rpi4"
KAIROS_ID="kairos"
KAIROS_VERSION="v3.1.0-rc1-v1.30.1-k3s1"
KAIROS_ARTIFACT="kairos-opensuse-leap-15.6-standard-arm64-rpi4-v3.1.0-rc1-k3sv1.30.1+k3s1"
KAIROS_FLAVOR="opensuse"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_FAMILY="opensuse"
KAIROS_VARIANT="standard"
KAIROS_TARGETARCH="arm64"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/opensuse:leap-15.6-standard-arm64-rpi4-v3.1.0-rc1-k3sv1.30.1-k3s1"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_NAME="kairos-standard-opensuse-leap-15.6"
KAIROS_ID_LIKE="kairos-standard-opensuse-leap-15.6"
KAIROS_VERSION_ID="v3.1.0-rc1-v1.30.1-k3s1"
KAIROS_PRETTY_NAME="kairos-standard-opensuse-leap-15.6 v3.1.0-rc1-v1.30.1-k3s1
```

**CPU architecture, OS, and Version:**
```
Linux node-server-56d1 6.4.0-150600.23.7-default #1 SMP PREEMPT_DYNAMIC Fri Jun 14 14:33:11 UTC 2024 (33f31da) aarch64 aarch64 aarch64 GNU/Linux
```

**Describe the bug**

journalctl -xefu k3s
```
Jun 28 23:48:46 node-server-56d1 k3s[5691]: time="2024-06-28T23:48:46Z" level=fatal msg="failed to detect selinux: read /proc/thread-self/attr/current: invalid argument"
Jun 28 23:48:46 node-server-56d1 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
```

After tmp-fixing https://github.com/kairos-io/kairos/issues/2682 i ran into this error.

Based on https://github.com/kairos-io/kairos/issues/2682#issuecomment-2203283439 moved to this issue.

**Comment by Itxaka** [comment]
Can confirm!

**Comment by Itxaka** [comment]
Seems to be selinnux related, probably its missing the k3s-selinux packages or we should not enable selinux for rpi directly.

workaround: Add `selinux=0` to the grub cmdline to disable selinux.
more permanent workaround: `grub2-editenv /oem/grubenv set extra_cmdline=selinux=0` to make it permanent on boot

**Comment by Itxaka** [comment]
This affects amd64 opensuse 15.6 as well.

**Comment by Itxaka** [comment]
https://github.com/kairos-io/packages/pull/938 for disabling selinux in leap for now until we can port the k3s-selinux policies to it

**Comment by Itxaka** [comment]
should get in for 3.1.x final release :D

**Comment by kaiehrhardt** [comment]
Could you add this to a release candidate, so i can test it?

**Comment by Itxaka** [comment]
makes sense to me, let me get the updated framework in there and cut an rc2 which should fix both issues, the expansion and the selinux!

**Comment by Itxaka** [comment]
> Could you add this to a release candidate, so i can test it?

@kaiehrhardt https://github.com/kairos-io/kairos/releases/tag/v3.1.0-rc2 is ongoing, it will take a couple of hours to fully build all artifacts, but should contain both fixes for rpi

**Comment by kaiehrhardt** [comment]
@Itxaka Thank you so much <3
