### ISSUE TITLE
Support TRIM in LUKS partitions mounted by Kairos

### ISSUE THREAD

**Issue by kreeuwijk** [kairos-io/kairos#2693]
**Kairos version:**
3.0.14

**CPU architecture, OS, and Version:**
Ubuntu 24.04

**Describe the bug**
Kairos does not pass the `allow-discards` config option to `systemd-cryptsetup attach`, causing the mounted LUKS partitions to not support TRIM. As a result, SSD drive performance falls off a cliff after some time. When a LUKS partition is mounted from a non-rotational disk, the `allow-discards` option should be automatically added so that weekly `fstrim` runs can trim the LUKS partitions as well.

```
DEVICE=nvme0n1

if [ "$(cat /sys/block/$DEVICE/queue/rotational)" == "0" ]
then
  OPTIONS="tpm2-device=auto,allow-discards"
else
  OPTIONS="tpm2-device=auto"
fi
```

This example shows that `fstrim` functions correctly when `allow-discards` is set:
```
# /usr/lib/systemd/systemd-cryptsetup attach nvme0n1p2 $(findfs PARTLABEL=oem) - tpm2-device=auto,allow-discards

# mount /dev/mapper/nvme0n1p2 /oem

# fstrim -v /oem
/oem: 4.7 GiB (5027479552 bytes) trimmed
```

**To Reproduce**
Deploy Kairos with Trusted Boot and attempt to run `fstrim -v /oem`

**Expected behavior**
Non-rotational disks should use LUKS partitions that have TRIM support enabled.

**Comment by mudler** [comment]
that can't be taken as slightly as a bug - systemd-cryptsetup does not set discards on SSDs for a reason. We need to spike on this first to see what would be a good approach here, or even let this to be configurable by the end-user.

See for instance also: https://wiki.debian.org/SSDOptimization on the topic.

**Comment by mudler** [comment]
for the moment being - maybe we can investigate a workaround that does not require a patch release. E.g. a cloud config that can be shipped in the base image that remounts the partition with discard enabled on the HW that requires it.

**Comment by kreeuwijk** [comment]
We do not need remounting of any mountpoints. All that's needed is kcrypt being adjusted to pass the `allow-discards` option to the `systemd-cryptsetup` command when attaching the LUKS partition. This will allow weekly `fstrim` runs to perform TRIM on LUKS partitions, just like it does for regular `ext4` partitions.

**Comment by Itxaka** [comment]
workaround found:

`cryptsetup refresh --allow-discards DEVICE` will enable discards for the DEVICE while its mounted, it wont need to dettach/attach. This is only valid for attached devices. Once you detach and attach them the value will be lost and you will need to run it again

`cryptsetup refresh --persistent --allow-discards DEVICE` will do the same, but save the option to the luks header so on each dettach/attach operation the device will use that option forever. To remove the option just run the same but without the flag `cryptsetup refresh --persistent DEVICE`

**Comment by Itxaka** [comment]
@kreeuwijk confirmed this as working

**Comment by jimmykarily** [comment]
Planning decision: Let's try to implement this in immucore and control it with a config flag (in Kairos config).

**Comment by Itxaka** [comment]
After a small discussion


 - `--allow-insecure` flag will always be used as it refers to the future possibility of mounting unencrypted parts. It doesnt automatically enable the discard option, it just allows to do it
 - agent will gain new config option for mouting encrypted partition with discard flag. It wont affect anything on install
 - On boot, immucore will mount oem, read the config, get the value of the discard and remount /oem with that flag if needed
 - On boot, immucore will mount persistent directly with the option as it can read it from the config in oem directly
 - defaults will be the same, no discard option on anything

**Comment by kreeuwijk** [comment]
@Itxaka we can't you pass the `--allow-discards` option to cryptsetup by default? We don't want to set the `discard` flag on the filesystem mount, we only want `fstrim` to be able to perform TRIM in crypted filesystems during its weekly run...

**Comment by Itxaka** [comment]
> @Itxaka we can't you pass the `--allow-discards` option to cryptsetup by default? We don't want to set the `discard` flag on the filesystem mount, we only want `fstrim` to be able to perform TRIM on crypted filesystems during its weekly run...

We do? It's mentioned above, we will pass that to the crypt setup Luks creation by default?

**Comment by Itxaka** [comment]
kcrypt and agent will now create the luks encrypted partitions with the allow-discard option always enabled. 

As the OS now have an auto-trim service running, I dont think we need to go any further. Trim will be auto-run and it should trim the system automatically.

**Comment by Itxaka** [comment]
@kreeuwijk will this cover the current use-case? Encrypted partitions have the allow-discard option on by default, underlying mounts are NOT mounted witht he discard option, trim service still works on the timer.

Or is there some scenario missing here? Notice that nobody recommends using the discard option on encrypted mounts by default as it weakens security, so we would prefer to NOT allow mounting the underlying partitions with the discard option.

**Comment by kreeuwijk** [comment]
@Itxaka this is great, thank you!
