### ISSUE TITLE
RPI4 image won't boot (V3.0.14 -v3.0.12)

### ISSUE THREAD

**Issue by atlasoft** [kairos-io/kairos#2698]
**Kairos version:** 3.0.14, 3.0.12, probably other versions as well (didn't try)

**CPU architecture, OS, and Version:**

- alpine:3.19-core-arm64-rpi4-v3.0.14
- leap-15.5-standard-arm64-rpi4-v3.0.12-k3sv1.29.3-k3s1-img

**Describe the bug**
* Following https://kairos.io/docs/installation/raspberry/
* opensuse falls into a boot loop
* alpine shows recovery shell session

Shipped version of immucore is x86-64 (rpi should be arm64), this causes 

**To Reproduce**
- Follow https://kairos.io/docs/installation/raspberry/
- Download image
```bash
IMAGE=quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.0.14-k3sv1.29.3-k3s1-img
docker run -ti --rm -v "$(pwd):/image" quay.io/luet/base util unpack "$IMAGE" /image
```
- flash into SD as per the guide
- boot
- cry

**Expected behavior**
- Following the quickstart guide shouldn't make you cry

**Logs**
![WhatsApp Image 2024-07-04 at 7 42 56 PM](https://github.com/kairos-io/kairos/assets/7682842/9ea23b25-c9c6-4156-b959-192ac1dd84b6)

**Additional context**
Quick check of elf type: 
```bash
# cd $(mktemp -d)
# docker create  quay.io/kairos/alpine:3.19-core-arm64-rpi4-v3.0.14 --name dummy
# docker cp infallible_banach:/usr/bin/immucore .

# file immucore
immucore: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=P62TtHVZafAq3Tc2_6ol/CamDkzMEvEO3qomr-m2D/-ImOVWRBryCEfdlsJuxy/7gLBTPQckvmkma6CMvQt, stripped

# Check immucore binary runs on x86_64
# uname -a ; ./immucore 
Linux tokyo 6.6.35-2-lts #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 21:05:23 +0000 x86_64 GNU/Linux
2024-07-04T23:18:56+02:00 INF Immucore commit=none compiled with=go1.22.4 version=v0.1.34
2024-07-04T23:18:56+02:00 INF creating a runtime
2024-07-04T23:18:56+02:00 INF detecting boot state
2024-07-04T23:18:56+02:00 ERR could not get the image name from cmdline (i.e. cos-img/filename=/cOS/active.img)
could not get the image name from cmdline (i.e. cos-img/filename=/cOS/active.img)

```

Older version: (works)
```bash
# docker create --name dummy quay.io/kairos/alpine:3.19-core-arm64-rpi4-v2.5.0
# docker cp dummy:/usr/bin/immucore ./immucore-2.5.0
# file immucore-2.5.0 
immucore-2.5.0: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=PAfY7raZrcNCdk8Ivlt8/n6NWD5LOqcrcY-3f7pOG/c-pbWbRMaO-BYkcZGAbS/4hvMn0MhV8L8ig7hueu8, stripped
```

**Comment by mudler** [comment]
Can you test if this is still an issue with the 3.1.0 rc?

**Comment by atlasoft** [comment]
Indeed, it's duplicated, I can confirm it works with 3.1.0 RC2

Thanks!
