### ISSUE TITLE
spike: QC board

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2703]
This card is to track experiments with the QC board in order to boot a Kairos image.

**Comment by Itxaka** [comment]
While we are able to modify the efi.bin now and provide different boot efi files we cannot modify the partitions in any meaningful way and that blocks any kind of kairos real implementation on the device.

 - grub can be added but it wont see any usb devices which we could boot off the installation process
 - systemd-boot can be tweaked to provide different entries, including chainloading the grub efi file and efi shell but again, we cannot use that to boot from external devices
 - cant partition the device in any meaningful way, its hardcoded and even changing manually the partitions.xml and forcing it to format the system, the partitions dont appear anywhere
 - we can generate a fake system.img with our partitions and files on them but we cna only flash that to the single system partition, which creates a broken system partition with more partitions on it but those are innaccessible or empty.


The idea would be, as we cannot change the partitions during flahing the device, to have grub chainload the grub on a usb install media, so the agent could run the install as normal and create the proper partitions. Then the efi image would be a modified one that has grub which either loads the installer if a usb media is inserted or chainloads the active/passive images grub as normal kairos but we cannot control that, seems like during efi boot the usbs are not powered.


What we would need to continue:
 - a way to control the partition schema OR a way of flashing our own image into the system directly, not to a single partition
 - a way of booting off usb sticks
