### ISSUE TITLE
:building_construction: handle image pushing

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#271]
Currently images created with osbuilder are not pushed anywhere. We should allow to push those into a specific registry.

**Comment by jimmykarily** [comment]
This story will handle pushing to remote repositories: https://github.com/kairos-io/kairos/issues/513
Serving with nginx has already been implemented: https://github.com/kairos-io/osbuilder/pull/22 (documentation needs to be updated: https://kairos.io/docs/advanced/build/).

New issue created for docs: https://github.com/kairos-io/kairos/issues/1039
Closing this one.
