### ISSUE TITLE
Filter uki upgrade releases for non-uki systems, and viceversa

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2710]
Listing upgrading images, shows the following:

```
[root@fedora kairos]# kairos-agent upgrade list-releases --pre
Current image:
quay.io/kairos/fedora:40-core-amd64-generic-v3.1.0-rc2-5-gb093c1e

Available releases with higher version:
quay.io/kairos/fedora:40-core-amd64-generic-v3.1.0-rc2-uki
```

But since I'm on a non-uki release, this is unnecessary. It would be nice if we can detect the type of the system and only show related images

**Comment by jimmykarily** [comment]
Since UKI images are signed with certs and we don't produce our own signed images, when the OS is UKI based, we should:
1. tell them that there is a new version and they should generate a new image based on that and upgrade to it
2. point them to docs on how to do so.

**Comment by jimmykarily** [comment]
PR merged. Closing.
