### ISSUE TITLE
chore: revert systemd-boot to 255

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2727]
Follow-up of https://github.com/kairos-io/kairos/issues/2632.

As we are going to release a 3.1.1, let's revert to 255  until that's released to ease out cutting a release

**Comment by Itxaka** [comment]
Downgraded to 255 in main. Should be available in the framework soon™ 

Bump to 256 on https://github.com/kairos-io/packages/pull/967 but requires manual work to make it work (drop 255.patch)
