### ISSUE TITLE
feat: document how kairos evaluates a transition image

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2798]
> - Check image integrity
> - Check if the image is signed by the same entity (UKI-only)
> - Automatically reboot in case of kernel panics
> - There is a GRUB script that will do boot-assessment (non-UKI) at bootloader level if the image fails to start (e.g. after a broken upgrade)
> - systemd-boot fallbacks in case of failures (UKI-only)

response by @mudler

**Comment by jimmykarily** [comment]
partly explained here: https://github.com/kairos-io/packages/blob/15945f281bc475c12fa98cdb0cd0d8f0253317cc/packages/static/kairos-overlay-files/files/system/oem/08_grub.yaml#L5-L10

**Comment by jimmykarily** [comment]
- Check image integrity:
  - [uki](https://github.com/kairos-io/kairos-agent/blob/d4076796774f609b425d993067d4d9481b9bc320/pkg/uki/upgrade.go#L76) (not really the "integrity" but rather the signing)
  - non uki: we don't check anything

**Comment by jimmykarily** [comment]
I created a ticket to implement boot assessment in systemd-boot: https://github.com/kairos-io/kairos/issues/2864
In the meantime there is nothing to document around that.
