### ISSUE TITLE
Enabling kdump in Kairos

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2849]
Let's document how kdump can be enabled in Kairos. For now, let's do systemd only and opensuse (got customer interest in this).

Initial research shows that something like this should work:

Dockerfile:

```Dockerfile
 
RUN kernel=$(ls /lib/modules | head -n1) && depmod -a "${kernel}" && \

            dracut -v -N -f "/boot/initrd-${kernel}-kdump" "${kernel}" -a kdump && \

            ln -sf "initrd-${kernel}-kdump" /boot/initrd

RUN systemctl enable kdump-early && systemctl enable kdump
```
 
cloud config:

```cloud-init
grub_options:

    # additional Kernel option cmdline to apply

    extra_cmdline: crashkernel=315M,high crashkernel=72M,low
```

but there is something going on with the kdump service that tries to rebuild initramfs and fails because of the immutability.

@Itxaka suggested an override like this:

```
RUN mkdir -p /etc/systemd/system/kdump.service.d/
RUN echo "[Service]\nExecStart=\nExecStart=/usr/lib/kdump/load.sh" > /etc/systemd/system/kdump.service.d/override.conf
```

Links:

- https://www.kernel.org/doc/Documentation/kdump/kdump.txt
- https://github.com/openSUSE/kdump/blob/master/init/load.sh#L249

**Comment by Itxaka** [comment]
Good one! Would probably be able to do an example based of suse leap or opensuse.

A couple of comments:

This values seem to be based off the current machine, so they are not generic enough, they migth change depending on the machine:
`extra_cmdline: crashkernel=315M,high crashkernel=72M,low`

This doesnt really work becuase it echoes the \n literally, so a file with the override and a `COPY` instruction is needed. I have no idea how to echo proper line jumps in Dockerfiles:
`RUN echo "[Service]\nExecStart=\nExecStart=/usr/lib/kdump/load.sh" > /etc/systemd/system/kdump.service.d/override.conf`

**Comment by jimmykarily** [comment]
Yes, I'm playing with it now. I got past the echoing problem. My dockerfile looks like this now:

```
FROM quay.io/kairos/opensuse:leap-15.6-core-amd64-generic-v3.1.2

RUN mkdir -p /etc/systemd/system/kdump.service.d/
RUN echo "[Service]" >> /etc/systemd/system/kdump.service.d/override.conf && \
    echo "ExecStart=" >> /etc/systemd/system/kdump.service.d/override.conf && \
    echo "ExecStart=/usr/lib/kdump/load.sh" >> /etc/systemd/system/kdump.service.d/override.conf

RUN zypper ref && zypper in -y kdump kexec-tools makedumpfile
RUN kernel=$(ls /lib/modules | head -n1) && depmod -a "${kernel}" && \
            dracut -v -N -f "/boot/initrd-${kernel}-kdump" "${kernel}" -a kdump && \
            ln -sf "initrd-${kernel}-kdump" /boot/initrd

RUN systemctl enable kdump-early && systemctl enable kdump
```

I'm building it with:

```bash
docker build -t kdump-kairos .
```

and I'm building an iso with:

```
docker run -v "$PWD"/build-iso:/tmp/auroraboot -v /var/run/docker.sock:/var/run/docker.sock --rm -ti quay.io/kairos/auroraboot --set container_image="docker://kdump-kairos" --set "disable_http_server=true" --set "disable_netboot=true" --set "state_dir=/tmp/auroraboot"
```

but when I boot it, the kdump service doesn't start (in livecd mode at least):

```
x kdump.service - Load kdump kernel and initrd
     Loaded: loaded (/usr/lib/systemd/system/kdump.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/kdump.service.d
             `-override.conf
     Active: failed (Result: exit-code) since Mon 2024-09-09 07:50:47 UTC; 10s ago
   Main PID: 1400 (code=exited, status=6)
        CPU: 4ms

Sep 09 07:50:47 localhost systemd[1]: Starting Load kdump kernel and initrd...
Sep 09 07:50:47 localhost systemd[1]: kdump.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Sep 09 07:50:47 localhost systemd[1]: kdump.service: Failed with result 'exit-code'.
Sep 09 07:50:47 localhost systemd[1]: Failed to start Load kdump kernel and initrd.
```

**Comment by jimmykarily** [comment]
`/usr/lib/kdump/load.sh` doesn't seem to do much without the `--update` flag

**Comment by Itxaka** [comment]
no, its expected

> `/usr/lib/kdump/load.sh` doesn't seem to do much without the `--update` flag

it should, the update only marks the initrd recreation if needed. Maybe the scripts are different in opensuse VS suse micro (it was tested on suse micro)

**Comment by Itxaka** [comment]
Seems like on the opensuse script, the values of the kernel and initrd are hardcoded to `/var/lib/kdump{initrd,kernel}` for some reason.....

A simple soft link makes it work as expected

**Comment by Itxaka** [comment]
```
localhost:~ # ln -s /boot/initrd /var/lib/kdump/initrd
localhost:~ # ln -s /boot/vmlinuz /var/lib/kdump/kernel
localhost:~ # systemctl start kdump
localhost:~ # systemctl status kdump
* kdump.service - Load kdump kernel and initrd
     Loaded: loaded (/usr/lib/systemd/system/kdump.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/kdump.service.d
             `-override.conf
     Active: active (exited) since Mon 2024-09-09 08:49:54 UTC; 3s ago
    Process: 1890 ExecStart=/usr/lib/kdump/load.sh (code=exited, status=0/SUCCESS)
   Main PID: 1890 (code=exited, status=0/SUCCESS)
        CPU: 264ms

Sep 09 08:49:54 localhost systemd[1]: Starting Load kdump kernel and initrd...
Sep 09 08:49:54 localhost systemd[1]: Finished Load kdump kernel and initrd.
```

**Comment by Itxaka** [comment]
ok, I created a doc example to show how to generate a kdump enabled derivative, I think it encapsulates all the info that we need: https://github.com/kairos-io/kairos-docs/pull/256

**Comment by Itxaka** [comment]
docs are done, reproduced by @jimmykarily by following them so we can consider this done :D
