### ISSUE TITLE
LocalAI

### ISSUE THREAD

**Issue by jgautam** [kairos-io/kairos#2874]
In the The install document, the following bundle location does not work

**run://quay.io/kairos/community-bundles:localai_latest**

I think it should be replaced by the following:

**run://quay.io/kairos/community-bundles:LocalAI_latest**

**Comment by mauromorales** [comment]
@jimmykarily I transfered this issue from the docs to the main Kairos, repo but I see it change the status you previously placed for it, do you remember what it was?

**Comment by jimmykarily** [comment]
> @jimmykarily I transfered this issue from the docs to the main Kairos, repo but I see it change the status you previously placed for it, do you remember what it was?

No worries, I think I put it "Under review" for one of us to check. All good.

**Comment by mudler** [comment]
https://github.com/kairos-io/kairos-docs/pull/190
