### ISSUE TITLE
:bug: validate that kairos user is present

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2875]
We currently validate cloud-configs to create at least one user, but the validation should actually be, to create the `kairos` user as a minimum because without the `kairos` user it's not possible to use the system atm

**Comment by anthonyra** [comment]
I bet this is related to my issue I thought I was having with YIP.

https://github.com/mudler/yip/issues/176

Is the recommended work around to create two users as a minimum? The kairos and a custom one if desired?

**Comment by mauromorales** [comment]
@anthonyra indeed, atm if you plan to architect your node with additional N users, your config your have N+1 including the kairos user

**Comment by jimmykarily** [comment]
The `kairos` user [will be created either you create it or not](https://github.com/kairos-io/packages/blob/6772d339d17fa71de4b285cadbbe397faf7434ec/packages/static/kairos-overlay-files/files/system/oem/10_accounting.yaml#L11), but won't have a password (nor authorized ssh keys) unless you specify that in your cloud config.
You don't have to worry about the kairos user then, just create the one you want.

**Comment by mauromorales** [comment]
@jimmykarily yeah I remember we talked about this. I'm not sure what's the most user friendly way to address this problem. For those new in Kairos land, they think that they can create their own user, e.g. `mauro` without the need of making it an admin and without adding a password to the `kairos` user. So they end up with a system with 2 users but not able to log in.

For those more advanced, I can see how they may want to have only the `kairos` user without a password and in such scenarios the validation could be problematic.

Some ideas:

- do the validation and have an extra field for "kairos_user_without_password: true" or so
- do the validation but only trigger a warning (but probably will be ignored because atm we only do warnings anyways
- add a kairos user page to the documentation

**Comment by jimmykarily** [comment]
I tend to believe it's only a matter of documentation. If they add a user without a password, how would they expect to login? The only thing they need to know, is that additional users, don't become admins by default and they need to explicitly add them to the `admin` group in the cloud config. We tried to explain that here: https://github.com/kairos-io/kairos-docs/commit/be9bc623266ab0a3ff6790c4e838357d63cd9997 but maybe we need to add it to more places (?).

**Comment by Itxaka** [comment]
do we really need a kairos user? Why?

**Comment by jimmykarily** [comment]
What @itxaka said ^. If we required a `kairos` user anywhere, then that needs fixing. Maybe that's too big of a change for a patch release though? New ticket and push it to the next minor?

**Comment by mauromorales** [comment]
nicely put @Itxaka. yup that should be the ideal case, and indeed it can be a minor version not a patch

**Comment by jimmykarily** [comment]
I created a new ticket for this: https://github.com/kairos-io/kairos/issues/2921
