### ISSUE TITLE
AuroraBoot doesn't copy cloud config file

### ISSUE THREAD

**Issue by Ludea** [kairos-io/kairos#2876]
**Kairos version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

I try to create an iso with embed cloud config file.
After creating a vm and booting into it, cloud-config file is not present into filesystem.

**To Reproduce**

follow https://kairos.io/docs/installation/automated/#locally with 
```
#cloud-config

hostname: kairos
users:
- name: kairos
  passwd: kairos

install:
  device: "/dev/sda"
  reboot: true
  poweroff: false
  auto: true
  
k3s:
  enabled: true
```
**Expected behavior**

with this cloud-config, install kairos into automatic way

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
looks like aurora uses the overlay-iso flag to move files to the iso root, which should move the cloud config. Then Im guessing the dir being used is not either copied to the temp dir somehow

```
 enki --config-dir /config --debug --name kairos build-iso --squash-no-compression --overlay-iso /tmp/geniso3322135445
```

**Comment by Itxaka** [comment]
ok, doesnt seem like thats it, the issue is that once you set the container as the source, then the inject iso dissapears:


```
$ go run main.go --debug --set "disable_http_server=true"  --set "disable_netboot=true" --cloud-config /tmp/kaka/cloud_init.yaml 
4:33PM DBG
4:33PM DBG 1.
4:33PM DBG  <prepare-iso> (background: false)
4:33PM DBG  <download-iso> (background: false)
4:33PM DBG  <prepare-temp> (background: false)
4:33PM DBG  <prepare-netboot> (background: false)
4:33PM DBG
4:33PM DBG 2.
4:33PM DBG  <copy-cloud-config> (background: false)
4:33PM DBG
4:33PM DBG 3.
4:33PM DBG  <inject-cloud-config> (background: false)
4:33PM DBG
4:33PM DBG 4.
4:33PM DBG
4:33PM DBG 5.
4:33PM DBG

```
$ go run main.go --debug --set "disable_http_server=true"  --set "disable_netboot=true" --cloud-config /tmp/kaka/cloud_init.yaml --set container_image=quay.io/kairos/ubuntu:24.04-core-amd64-generic-master
4:33PM DBG
4:33PM DBG 1.
4:33PM DBG  <prepare-temp> (background: false)
4:33PM DBG  <prepare-netboot> (background: false)
4:33PM DBG  <prepare-iso> (background: false)
4:33PM DBG
4:33PM DBG 2.
4:33PM DBG  <container-pull> (background: false)
4:33PM DBG  <copy-cloud-config> (background: false)
4:33PM DBG
4:33PM DBG 3.
4:33PM DBG  <gen-iso> (background: false)
4:33PM DBG
4:33PM DBG 4.
4:33PM DBG
4:33PM DBG 5.
4:33PM DBG
```

so it has to be one of the switches that its wrong and doesnt enable that step, but this is intended for some reason.

**Comment by Itxaka** [comment]
oh I get it. Inject the cc into the iso is only valid if we donwload an ready to use iso, which makes sense.

If we generate an iso, then we can copy it on the fly to it. 


Makes sense now.

**Comment by Itxaka** [comment]
umm. Retrying now seem to make it work, wtf.

**Comment by Itxaka** [comment]
ok, something weird. If the file is called config.yaml, I get the file correctly. But if the file is called cloud_config.yaml I get a random dir in the root of the build with the the name:

![image](https://github.com/user-attachments/assets/06fbd156-5b8a-44b3-95ac-623e1aa737ba)


This was by setting `-v $PWD/config.yaml:/cloud_init.yaml` and `--cloud-config /cloud_init.yaml` .... what the hell

**Comment by Itxaka** [comment]
so yes, this works as long as the source config that you are mounting into the docker container exists. If it doesnt exists then it creates an empty one and aurora uses that as source, which means you end up with an empty config.

@Ludea can you check if this was the case for you?

**Comment by Itxaka** [comment]
This is both a code issue and docs issue. Its not really clear why it would fail and we dont advise against this weird docker behaviour in which it will make up files if your naming is wrong. So 2 patches to improve that.
One is the docs to warn about wrong naming for mounts
Second is to aurora to fail early and with a clear message if you specify a cc but the contents are empty

**Comment by Ludea** [comment]
I successfully created iso with cc into iso root !
I can see the file when mounting iso.

But when creating vm, cc is not read, i boot into live mode

**Comment by Ludea** [comment]
I have to open another ticket and close it?

BTW here a link with created iso
https://1drv.ms/u/c/41c46930202157f5/EaRe-WeL2s1Pre_37aYnNcYBaDt7dXELbxljEgIpMU0prw?e=966nIm

**Comment by Itxaka** [comment]
Cant reproduce either...

built iso with 
```
docker run -v $PWD/cloud_init.yaml:/cloud_init.yaml \
                    -v $PWD/build:/tmp/auroraboot \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    --rm -ti aurora --debug \
                    --set container_image=docker://quay.io/kairos/ubuntu:24.04-core-amd64-generic-master \
                    --set "disable_http_server=true" \
                    --set "disable_netboot=true" \
                    --cloud-config /cloud_init.yaml \
```

cloud config has:
```
#cloud-config

hostname: kairos
users:
- name: kairos
  passwd: kairos

install:
  device: "/dev/vda"
  auto: true
```

Get kairos.iso, add to vm and it boots and autoinstalls as expected:

![image](https://github.com/user-attachments/assets/d21152d7-844f-4db8-a540-0b6371e3737d)

**Comment by Itxaka** [comment]
ah nice, I can reproduce with your iso. Pleas enext time let me know that its Alpine, as alpine is special :D

In this case it makes sense. We mount the alpine DVD under `/media/root-ro` but the default installer does not look in there for config files, it looks under `/run/initramfs/live`

So maybe we need to change the initramfs on alpine to try to mount it there directly.

**Comment by Itxaka** [comment]
@Ludea Im gonna leave this issue open for the empty cc stuff that I did and create a new one to track the other issue

**Comment by Itxaka** [comment]
This is now fixed on Aurora Master and docs added to explain in case we hit this. The other issue is ongonig and waiting for the framework.
