### ISSUE TITLE
Small correction to Private registries authentication documentation

### ISSUE THREAD

**Issue by clyra** [kairos-io/kairos#2894]
The docs about Private registries authentication (https://kairos.io/docs/advanced/private_registry_auth/)  says that the DOCKER_CONFIG variable should point to a file, but it should point to a dir instead. 

long description below:

```
If set, DOCKER_CONFIG environment variable which points to a file.
```

But this doest not work.

```
root@m2:/oem# ls /oem/docker/
config.json
root@m2:/oem# export DOCKER_CONFIG=/oem/docker/config.json 
root@m2:/oem# kairos-agent upgrade --source oci:my-private-registry-with-password/my-kairos-ubuntu
[...]
2024-09-26T02:09:18Z INF Boot in uki mode result=false
failed initializing spec: failed calculating size: GET https://my-private-registry-with-password/my-kairos-ubuntu/manifests/latest: UNAUTHORIZED: unauthorized to access repository: my-kairos-ubuntu, action: pull: unauthorized to access repository: my-kairos-ubuntu, action: pull
```

Searching previous issues I found https://github.com/kairos-io/kairos/issues/1042#issuecomment-1669247199, which says that the variable should point to a dir instead of file. So I tried again:

```
export DOCKER_CONFIG=/oem/docker
root@m2:/oem# kairos-agent upgrade --source oci:my-private-registry-with-password/my-kairos-ubuntu
[...]
```
and it suceed.

**Comment by jimmykarily** [comment]
You are right @clyra : https://docs.docker.com/reference/cli/docker/#environment-variables 

```
The location of your client configuration files.
```

Thanks for reporting this! Here is the fix: https://github.com/kairos-io/kairos-docs/pull/273
