### ISSUE TITLE
Identify  system by other keys when installing grub

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#2895]
https://github.com/kairos-io/kairos-agent/blob/main/pkg/utils/grub.go#L214C40-L214C46

We use the KAIROS_FLAVOR key from os-release to try to identify if the image is an ubuntu one, as under EFI we need a workaround for ubuntu only.

But if we are using a source image for the install that its the upstream image directly, our kairos keys will not be there.

Ideally if the process is correct, the kairos keys should be there, as that means the image went through the kairos factory. But if thats not the case, the install still goes ok but you end up with a non booting system.

We should at least try to use other stuff in the os-release to identify the ubuntu machine (ID or ID_LIKE) to apply the workaround so we dont leave a broken system around.

**Comment by Itxaka** [comment]
This done, will be part of 3.2.1

Follow up is https://github.com/kairos-io/kairos/issues/2907

**Comment by mudler** [comment]
we need a new version of the framework with the agent still, right?

**Comment by mudler** [comment]
keeping it open until we have a framework image merged into kairos addressing this

**Comment by Itxaka** [comment]
on master
