### ISSUE TITLE
Fix device json schema to allow other device paths

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2906]
After this: https://github.com/kairos-io/kairos-agent/pull/552
we should now update the schema to allow these new paths: https://github.com/kairos-io/kairos-sdk/blob/156caa6f8c9066b99417912a572285c33ab44b3c/schema/install_schema.go#L14

Auroraboot fails with this if we don't:

```
Target OSs /etc/systemd/system/cloud_init.yaml does not pass validation. Quitting.
jsonschema: '/install/device' does not validate with file:///schema.json#/properties/install/$ref/properties/device/pattern: does not match pattern '^(auto|/|(/[a-zA-Z0-9_-]+)+)$'
```

Device used in original report: `/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

**Comment by HariniKrishnan** [comment]
Hi, can I work on this bug?

**Comment by jimmykarily** [comment]
> Hi, can I work on this bug?

By all means @HariniKrishnan! Give it a shot. If it takes too long we may have to pick it up within the core team to unblock people though.

**Comment by HariniKrishnan** [comment]
@jimmykarily When are we expecting the code, can I take a week's time?

**Comment by mudler** [comment]
> @jimmykarily When are we expecting the code, can I take a week's time?

Sure thing @HariniKrishnan ! Thank you :100:

**Comment by mauromorales** [comment]
@HariniKrishnan I'll assign you to the ticket, it's not to put any pressure but just to also see it on the dashboard that someone is on it. If you need help or more time, just let us know. Thanks!

**Comment by HariniKrishnan** [comment]
@mauromorales thanks a lot!

**Comment by HariniKrishnan** [comment]
whom should I reach out to for doubts reg this issue?

**Comment by mauromorales** [comment]
@HariniKrishnan I'd say the [slack channel](https://cloud-native.slack.com/archives/C0707M8UEU8) is probably the best place because then whoever in the team looks at it and knows, can start helping. Just keep in mind for the replies that we are mostly in EU timeline

**Comment by HariniKrishnan** [comment]
harini.krisnan@gmail.com is my email!!!

**Comment by jimmykarily** [comment]
> [harini.krisnan@gmail.com](mailto:harini.krisnan@gmail.com) is my email!!! can you please add me to you workspace!

You need to get a self-invitation here: https://slack.cncf.io/#kairos

**Comment by sarg3nt** [comment]
Hey @jimmykarily   Any idea when this might get fixed?
Thanks!

**Comment by jimmykarily** [comment]
> Hey @jimmykarily Any idea when this might get fixed? Thanks!

We planned it for the last sprint but nobody got a chance to fix it. Let's hope we get this done this week.

**Comment by jimmykarily** [comment]
The fix got merged in the kairos-agent. We just need to cut a new release of kairos-agent and kairos to make it consumable.

**Comment by sarg3nt** [comment]
@jimmykarily, did this get released in 3.2.2?  I don't see a mention of it so I'm assuming not.

**Comment by jimmykarily** [comment]
> @jimmykarily, did this get released in 3.2.2? I don't see a mention of it so I'm assuming not.

Yes the fix is in 3.2.2, I updated the release notes to say so (the first item in the list).

**Comment by jimmykarily** [comment]
> > @jimmykarily, did this get released in 3.2.2? I don't see a mention of it so I'm assuming not.
> 
> Yes the fix is in 3.2.2, I updated the release notes to say so (the first item in the list).

sorry, we did a mistake and we didn't bump the kairos-agent in the latest framework image :facepalm: . Please wait for 3.2.3 (coming soon)

**Comment by jimmykarily** [comment]
There: https://github.com/kairos-io/kairos/releases/tag/v3.2.3

**Comment by jimmykarily** [comment]
This should be fixed. I'll close but feel free to re-open if you face any issues.

**Comment by sarg3nt** [comment]
@jimmykarily This isn't working for us quite yet.

Our config has this in it

```yaml
install:
  device: "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0"
```

Error at the console:
![image](https://github.com/user-attachments/assets/4d6f6734-213a-4265-9e24-791a8d01fa45)

Looks like it is adding a `p1` at the end of the device path.  
Is this intentional or a bug?

**Comment by jimmykarily** [comment]
The `WARNING` report a pattern that is not matching the fixed one: https://github.com/kairos-io/kairos-sdk/blob/d334d86d4369929e47d569d9d8a6eeb4698e55ca/schema/install_schema.go#L14

It should use the new `"^(auto|/dev/.+)$"` but it's reporting [the old one](https://github.com/kairos-io/kairos-sdk/commit/6a23bb688243cc4352d382022a1adaae4ccdd07c#diff-f0a8c4c232aeb2ad7faa6e310659cc70d15d1fabb071dc56268b6e831f0ae204L14).

You need [kairos-agent >= v2.15.4](https://github.com/kairos-io/kairos-agent/releases/tag/v2.15.4) to get this fix. The logs report kairos-agent `v2.13.9`.

This can't be kairos `v3.2.4`.

**Comment by sarg3nt** [comment]
Wellllll . . . That's because someone . . and I'm not gong to name names here . . forgot to actually build the new image and, you know, use it.
It was me, I did it.
Sorry.  
![I9B24UPROhlvwFNsGexi5kMRV0L8YHZH2WFc0x9JzWA-2648090589](https://github.com/user-attachments/assets/ef6fad20-c2f8-4398-840b-8843e40855c9)
