### ISSUE TITLE
Change UKI Splash screen to something less frightening

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2923]
Until we can do this: https://github.com/kairos-io/kairos/issues/2899

let's make sure out default doesn't look so big and so red (like an error would).

**Comment by bencorrado** [comment]
If you start a branch for this let me know, happy to help.

**Comment by Itxaka** [comment]
for this just a simple default black screen was added, removing the big scary red letters :D

**Comment by Itxaka** [comment]
@bencorrado feel free to open a PR under https://github.com/kairos-io/go-ukify if you want to do the custom bmp values :)
