### ISSUE TITLE
edgevpn luet package uses old version

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2991]
Because the build script uses the 'tag' and not the version: https://github.com/kairos-io/packages/blob/608b1d23a802dbe902d0a5f8cdf722d393bd255c/packages/utils/edgevpn/definition.yaml#L4

we should get rid of one of the 2 to avoid confusion.

**Comment by bencorrado** [comment]
Fixed by https://github.com/kairos-io/packages/pull/1137

**Comment by jimmykarily** [comment]
And part of the kairos releases since [3.2.2](https://github.com/kairos-io/kairos/releases/tag/v3.2.2). Closing.
