### ISSUE TITLE
Update docs referencing enki to use AuroraBoot

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#3002]
In the latest release we deprecated Enki, but we still make reference to it in the docs https://github.com/kairos-io/kairos-docs/blob/main/content/en/docs/Advanced/sys-extensions.md#building-system-extensions-from-a-docker-image-with-enki

**Comment by mudler** [comment]
Besides referencing enki commands, there are for sure references to plain `osbuilder` image tools scripts around. Worth checking basically all commands that are referencing either osbuilder, enki, or auroraboot
