### ISSUE TITLE
Fix secure boot

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#3018]
SInce we started embedding grub artifacts in auroraboot (https://github.com/kairos-io/AuroraBoot/pull/102/files#diff-36043890c52c8201a8bc84238c219be45ce07bf172d89f693c7c54ffe70d046eR33), we no longer get the one from the distro so the OS and the shim are signed by 2 different keys. This may have broke secure boot in images built with latest auroraboot.

Let's look into it and if this is the case, we should not embed such artifacts but rather install the distro ones in the base images.

**Comment by Itxaka** [comment]
I was mistaken, the file we are bundling is the hybryd_boot.img which refers to booting under BIOS not under EFI.

For EFI we still use the grub.efi provided by the base image.
