### ISSUE TITLE
.MachineID seems to be Null

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#3038]
### Discussed in https://github.com/kairos-io/kairos/discussions/2987

<div type='discussions-op-text'>

<sup>Originally posted by **enyachoke** November  7, 2024</sup>
Hello folks. I am having an issue with the machine id not being set when I use node-{{ trunc 4 .MachineID }} The node name ends up being just `node` This used to work fine until I reinstalled my cluster recently.</div>

**Comment by jimmykarily** [comment]
Upon reboot, I get this:

```
[root@metal-b54c kairos]# cat /etc/hostname
metal-b54c
```

**Comment by jimmykarily** [comment]
It would help if we used the available logger to print the error here instead of ignoring it:

https://github.com/mudler/yip/blob/cfe101ef3151b37b820ce49811e8297eca8514e3/pkg/plugins/hostname.go#L33

:facepalm: 

I'll build a custom binary to check what's going on

**Comment by Itxaka** [comment]
Makes sense, on first boot machine-id may not be restored/generated yet by the time the hostname plugin hits. It's us the ones that generate it/restore from persistent on boot.

**Comment by jimmykarily** [comment]
yup, this hasn't kicked in when yip/kairos-agent tries to setup the hostname: https://github.com/kairos-io/packages/blob/500aa176ac2e8c67483e7e6d59fe311038419a79/packages/static/kairos-overlay-files/files/system/oem/00_rootfs.yaml#L146

thus there is no `/etc/machine-id` yet. On the next boot, I assume [the code right above](https://github.com/kairos-io/packages/blob/500aa176ac2e8c67483e7e6d59fe311038419a79/packages/static/kairos-overlay-files/files/system/oem/00_rootfs.yaml#L142) has restored it that's why it's available (?). But why does the restoration is always run in time while the creation is not?

the `hostname` plugin doesn't seem very reliable this way. Maybe we can set the hostname in a stage instead of top level? I see that the plugin takes a "stage" argument: https://github.com/mudler/yip/blob/614a362e7f7d3a5f4941a3a048b11b66493b8884/pkg/plugins/hostname.go#L22

**Comment by jimmykarily** [comment]
This config seems to work:

```
#cloud-config

stages:
    boot:
      - hostname: metal-{{ trunc 4 .MachineID }}
      - 
users:
    - groups:
        - admin
      name: kairos
      passwd: kairos
```

let me check if it also works on first boot

**Comment by jimmykarily** [comment]
yup, the above one works on first boot too:

```
metal-8bb5 login: kairos
Password:
[kairos@metal-8bb5 ~]$
```

@Itxaka do you think it makes sense to change our documentation and wherever we mention `hostname:` we do it under the `boot` stage?

**Comment by mauromorales** [comment]
shouldn't yip be aware that it should run at boot stage?

**Comment by Itxaka** [comment]
I think that the entries at top level (hostname, write_files, users) which are backwards compatible with cloud-config, maybe should be run later thant our custom files? the hostname runs under initramfs https://github.com/mudler/yip/blob/master/pkg/schema/loader_cloudinit.go#L110 and our machine-id stuff runs there as well, but probably it comes a bit later in the process (probably we load the top level entries and then the files in the system)

So either we move the hostname thing to run at a later stage when its at the top level (changes behaviour) or we make it so top level stuff is loaded after existing stages from files (changes behaviour as well) 

Or we document it with a big warning, that top level hostname may run before machine-id is available and to either not use machine id in the templating or moving the hostname to the boot stage instead.

**Comment by jimmykarily** [comment]
I'm in favor of running it at `boot` stage and call it a day. It's' the simplest change and it work, so :shrug: ...

**Comment by mauromorales** [comment]
I don't mind moving it at boot, but yes then it would be nice to have this documented somewhere, but I think the right place to document should be yip I guess
