### ISSUE TITLE
feat: Support private repository when using kairos-agent bundle-install

### ISSUE THREAD

**Issue by Bao0ne** [kairos-io/kairos#3057]
**Is your feature request related to a problem? Please describe.**

When I tried to use bundle to publish software, I found that it had no way to pull images from the private repository.

**Describe the solution you'd like**

Hope it will be supported when kairos-agent install-bundle：
* Provide private repository authentication
* Read repository information from the specified configuration file like luet install --config

**Additional context**

Currently, authentication information cannot be added when luet repo add, I try to make it support：https://github.com/mudler/luet/pull/370

In kairos-sdk：https://github.com/kairos-io/kairos-sdk/blob/d334d86d4369929e47d569d9d8a6eeb4698e55ca/bundles/bundles.go#L287

Is it expected to point the software installation location(--system-target) and repo config to the same location? I think most of the time software needs a separate directory for storage.

In kairos-sdk：https://github.com/kairos-io/kairos-sdk/blob/d334d86d4369929e47d569d9d8a6eeb4698e55ca/bundles/bundles.go#L304

**Comment by mudler** [comment]
PR was merged, thanks @Bao0ne ! 

https://github.com/mudler/luet/pull/370

Closing this Issue
