### ISSUE TITLE
 malformed /etc/machine-id issue on kairos Alpine dérivatives

### ISSUE THREAD

**Issue by j-landru** [kairos-io/kairos#3059]
**Context**
Kairos Alpine derivative 
as describe in [polymorphic OCI OS images with Kairos : abcd Alpine Based Containerized os Derivative](https://github.com/kairos-io/kairos/discussions/1875)

**Kairos version:**
KAIROS_VERSION="v3.2.1"

**CPU architecture, OS, and Version:**
architecture : X86_64
OS kernel :
- abcd4desktop run in live ISO mode in HVM : latest Alpine kernel : Linux locahost.localdomain 6.6.61-0-lts #1-Alpine SMP PREEMPT_DYNAMIC 2024-11-14 19:34:11 x86_64 Linux
- abcdic4desktop run in sysbox/docker or podman container : docker/podman : any host kernel

**Describe the bug**
Some init startup steps don't succeed due to invalid `/etc/machine-id` file content

On Alpine (Openrc init Linux) ephemeral machine-id can be setup at startup running `machine-id` openrc script at boot runlevel. That doesn't succeed due to invalid non empty`/etc/machine-id` file`. That latter is single byte file containing  an 0xa (ASCII LF code ?).

Alpine `/etc/init.d/machine-id` openrc script

```
#!/sbin/openrc-run

# Copyright (c) Natanael Copa
# This code is licensed under BSD-2-Clause

description="Generate machine-id if needed"

depend() {
        need root dev
}

start() {
        if [ -s /etc/machine-id ] ; then
                return 0
        fi
        ebegin "Generating machine-id"
        dd if=/dev/urandom status=none bs=16 count=1 \
                | md5sum | cut -d' ' -f1 > /etc/machine-id
        eend $?
}
```

`-s` file condition at start() stands for non empty file. But found a single byte invalid file

**To Reproduce**
Launch machine-id openrc script at boot runlevel.

**workaround**
Delete `/etc/machine-id` file before rc-adding script at boot run level.

**Excpected behaviour**
An empty `machine-id` file in initial Alpine kairos image.

In kairos `Dockerfile.kairos-alpine` dockerfile, at stanza :
```
# Set empty machine-id
# This prevents systemd from thinking that the machine is on first boot
# and recreating /etc/ dependencies in services and such
# do this before initramfs so its in the initramfs
```
maybe replace 
```
RUN echo "" > /etc/machine-id || true
```
by 
```
RUN rm -f /etc/machine-id && touch /etc/machine-id || true
```

**Comment by jimmykarily** [comment]
or

```
RUN printf "" > /etc/machine-id || true
```
