### ISSUE TITLE
Cannot run on win10 system

### ISSUE THREAD

**Issue by zy1818** [kairos-io/kairos#33]
c3os.exe Cannot run on win10 system

**Comment by mudler** [comment]
Hi!

Thanks for filing the issue, although I'm not a windows user - can you please provide a screenshot or a log of the failure?

**Comment by zy1818** [comment]
***@***.***
 
From: Ettore Di Giacinto
Date: 2022-06-25 17:03
To: c3os-io/c3os
CC: zy1818; Author
Subject: Re: [c3os-io/c3os] Cannot run on win10 system (Issue #33)
Hi!
Thanks for filing the issue, although I'm not a windows user - can you please provide a screenshot or a log of the failure?
―

**Comment by mudler** [comment]
A lot of things changed by now - please try again and let us know with the latest version, and re-open if necessary. Thanks!
