### ISSUE TITLE
DNS forwarding not functional on ARM Alpine image

### ISSUE THREAD

**Issue by DevOpsFu** [kairos-io/kairos#335]
**Kairos version:**
`kairos-alpine-arm-rpi-v1.1.4-k3sv1.25.2+k3s1.img.xz`

**Describe the bug**
DNS forwarding via the local DNS server does not seem to work.

**To Reproduce**
Configure the DNS forwarding, either in the cloud-config, like this:

```
  initramfs:
    - name: "Set up Ethernet interface"
      files:
        - path: /var/lib/connman/default.config
          permission: 0644
          content: |
            [service_eth0]
            Type = ethernet
            IPv4 = 172.16.0.5/24/172.16.0.254
            IPv6 = off
            Nameservers = 1.1.1.1
```

Or like this:

```
    - name: "Set DNS servers"
      dns:
        nameservers:
        - 1.1.1.1
        - 8.8.8.8
```

Try resolving a public DNS name. The forwarding does not seem to work.

**Expected behavior**
DNS resolution works correctly, forwarding queries to the nameservers specified.

**Logs**
N/A

**Additional context**
* `/etc/resolv.conf` is set to use `127.0.0.1` by connman.
* The connman DNS service is alive and bound to port 53 on localhost.
* Any queries to the local DNS service receive a `SERVFAIL` response.

**Comment by mauromorales** [comment]
I was able to reproduce the issue, don't know much about connman and how it sets up this proxy for dns, but I can see in the logs that it is unable to create an internal resolv.conf file

![image](https://github.com/kairos-io/kairos/assets/433958/26793553-ec9f-4c99-ba92-d88a2343f099)

**Comment by mauromorales** [comment]
This doesn't seem to be the cause of the issue since, I can create that directory, restart the service and then it successfully creates the file, but there's still no resolution. The file looks exactly the same as /etc/resolv.conf, which makes sense since it's being managed by connman

**Comment by mauromorales** [comment]
Came across this issue while debugging: https://github.com/rancher/k3os/issues/629

**Comment by mauromorales** [comment]
Ok I think I finally figured it out, seems to be related to the format of the configuration. From the connman docs, I found this:

```
[service_home_ethernet]
Type = ethernet
IPv4 = 192.168.1.42/255.255.255.0/192.168.1.1
IPv6 = 2001:db8::42/64/2001:db8::1
MAC = 01:02:03:04:05:06
Nameservers = 10.2.3.4,192.168.1.99
SearchDomains = my.home,isp.net
Timeservers = 10.172.2.1,ntp.my.isp.net
Domain = my.home
```

So I decided to use the same format, here's the same configuration form the issue (adapted for my network range):

```
#cloud-config
users:
  - name: kairos
    passwd: kairos
stages:
   initramfs:
    - name: "Set up Ethernet interface"
      files:
        - path: /var/lib/connman/default.config
          permission: 0644
          content: |
            [service_default]
            Type = ethernet
            IPv4 = 192.168.122.160/255.255.255.0/192.168.122.1
            IPv6 = off
            Nameservers = 1.1.1.1
```

This is how the resulting config file looks:

```

**Comment by mauromorales** [comment]
@DevOpsFu please excuse the very late reply and I hope this helps. I'm using Kairos 2.0.3

**Comment by DevOpsFu** [comment]
Thanks @mauromorales ! I appreciate the work you put into figuring this one out. 

After filing this issue I quickly moved over to the openSuSE version of Kairos to get me unblocked. I've been running that since then.

**Comment by mauromorales** [comment]
Fantastic, happy to hear you were able to proceed with the opensuse image
