### ISSUE TITLE
🔒  Add TLS support

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#346]
The challenger currently supports wss without TLS termination. Would be needed to support pinned certificates as well in order to avoid mitm during successfull challenges

Client(kcrypt-challenger) needs to be configured for TLS.  Depends on https://github.com/kairos-io/kairos/issues/399

**Comment by jimmykarily** [comment]
#399 is about changing [kcrypt](https://github.com/kairos-io/kcrypt) to accept configuration from a file. Here we are talking about [kcrypt-challenger](https://github.com/kairos-io/kcrypt-challenger). Maybe 399 means the challenger instead? Anyway, I'll check the 2 projects to see what's possible.
