### ISSUE TITLE
macOS cli binary

### ISSUE THREAD

**Issue by renanqts** [kairos-io/kairos#36]
First of all, thanks for the very nice project.

Currently, there is no such version for darwin binary (macOS users). Can we please add to the build process?

**Comment by renanqts** [comment]
Do you see any change apart from appending this list here?

https://github.com/c3os-io/c3os/blob/11158a12aa13b5181f9c16a5718db63b89a2f40b/.goreleaser.yaml#L7-L9

**Comment by mudler** [comment]
That's a good point, thanks for opening this up. 

Last time I've checked there where some deps that weren't compatible with Darwin. I've take care of edgevpn, so now compiles on Darwin just fine.

But yup, that should be it to enable Darwin builds

**Comment by mudler** [comment]
What we could do here is disable screenshots on macOS - at least we could feed it with an image. thoughts @jimmykarily ?

**Comment by jimmykarily** [comment]
> What we could do here is disable screenshots on macOS as that doesn't builds statically - at least we could feed it with an image. thoughts @jimmykarily ?

Disabling screenshots is one approach. The other alternative would be to build a non static binary for macos. After all, that binary is not supposed to run in a container (these are all linux right?) so the dynamic libraries will be in place.

**Comment by mudler** [comment]
> > What we could do here is disable screenshots on macOS as that doesn't builds statically - at least we could feed it with an image. thoughts @jimmykarily ?
> 
> Disabling screenshots is one approach. The other alternative would be to build a non static binary for macos. After all, that binary is not supposed to run in a container (these are all linux right?) so the dynamic libraries will be in place.

True, however when I've tried that IIRC the screenshot lib requires some x code libs. I'm not a MacOS expert to be able to judge, but guess would take us to some hops

**Comment by jimmykarily** [comment]
> > > What we could do here is disable screenshots on macOS as that doesn't builds statically - at least we could feed it with an image. thoughts @jimmykarily ?
> > 
> > 
> > Disabling screenshots is one approach. The other alternative would be to build a non static binary for macos. After all, that binary is not supposed to run in a container (these are all linux right?) so the dynamic libraries will be in place.
> 
> True, however when I've tried that IIRC the screenshot lib requires some x code libs. I'm not a MacOS expert to be able to judge, but guess would take us to some hops

Not an MacOS expert here either. Maybe it's just about documenting the dependencies...

**Comment by mudler** [comment]
Hi @renanqts , we are steering away to require any CLI with https://github.com/kairos-io/kairos/issues/772 - so I think this issue might be not needed anymore. Do you think it would be enough and satisfy your use-cases?

**Comment by renanqts** [comment]
Hey.

No no, we can close it. Thanks
