### ISSUE TITLE
Fips enabled Kairos flavors

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#361]
We want to enable and document the building of [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) enabled Kairos flavors.

For this we need to:

- [x] Build all our binaries with golang flags that enable FIPS. 
- [x] Document how to build a flavor with those packages.

aside the current ones which are statically built, needed for #116, we need the same binaries that we add to the rootfs built with fips to support BYOI:

- Ubuntu 20.04
- Ubuntu 22.04 (is not available yet)
- RH

Aside : we pack as a static binary, even if CGO_ENABLED=1 ?

Depends on https://github.com/kairos-io/kairos/issues/1498

**Comment by Itxaka** [comment]
Couple of things.

 - we now got fips packages for our golang stuff that its included in the system (kcrypt,kcrypt-challenger, immucore, kairos-agent)
 - only ubuntu 20.04 and lower is supported for fips
 - you need a ubuntu pro subscription to enable fips
 - you need to activate the pro subcription and run the enable-fips which will install packages, including kernel.
 - AFAIK if you are in container mode, it will refuse to install the kernel.


So a bit problematic IMHO, pro subscription has to be done on runtime so we can enable fips and bundle the packages in the rootfs. But that would make us miss the fips kernel?

**Comment by jimmykarily** [comment]
Let's do our part:

- Enable this in "factory"
- Document how people can build fips enabled ubuntu flavors
- Done

**Comment by Itxaka** [comment]
Packages are all built now under the fips category

**Comment by jimmykarily** [comment]
Created PR to build a fips framework image so that users can build their own flavor following our docs: https://github.com/kairos-io/kairos/pull/1544

**Comment by jimmykarily** [comment]
Framework image is there, docs are there. Done.

**Comment by jimmykarily** [comment]
Let's add a "fips" specific section in the docs page. Re-opening.

**Comment by mauromorales** [comment]
Closing since documentation has been added
