### ISSUE TITLE
Add FIPS dracut module

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#363]

**Comment by Itxaka** [comment]
cant we just...enable it? That only does self check of the crypto modules no?

alsoif we drop dracut from alpine then we need an alternative for it.

**Comment by mauromorales** [comment]
is there going to be FIPS in Alpine though?

**Comment by Itxaka** [comment]
Nope!

**Comment by mudler** [comment]
> cant we just...enable it? That only does self check of the crypto modules no?

Probably, shouldn't hurt enabling it.. 

> 
> alsoif we drop dracut from alpine then we need an alternative for it.

I guess that can come as a best effort later on, firstly should be supported by the kernel, dracut just does integrity checks

**Comment by mudler** [comment]
In the BYOI FIPS image examples we enable the dracut module, so there is nothing much to do here: https://github.com/kairos-io/kairos/blob/master/examples/byoi/fedora-fips/dracut.conf
