### ISSUE TITLE
openSUSE ARM image exceed release size

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#383]
ARM images are exceeding release size: https://github.com/kairos-io/kairos/actions/runs/3394246214

## Action items

Stop building ARM images as part of our releases, as ARM images involve anyhow usage beside virtualization - so it doesn't help the user anyhow, but instead document on how to pull those manually:

- [x] Provide step by step instruction to pull an image from the released artifacts, extract the raw image, and dd that (raw images get pushed also as container images)
- [ ] Drop Github ARM release jobs from pipelines - mind to keep releases to push container images containing the raw image file used to document the process

**Comment by jimmykarily** [comment]
This looks like a good place to document it: https://kairos.io/docs/reference/image_matrix/

**Comment by mudler** [comment]
yes, we should also add a link to it from https://kairos.io/docs/installation/raspberry/

**Comment by jimmykarily** [comment]
> yes, we should also add a link to it from https://kairos.io/docs/installation/raspberry/

Done: https://github.com/kairos-io/kairos/pull/450/files#diff-a7456db8a6fe0628f6725205b687bf24de19af1140d59baaebe876a092820ed6
