### ISSUE TITLE
📖 kubeadm,provider-k3s, and rke2 docs

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#385]
**Is your feature request related to a problem? Please describe.**
Currently providers are there, but we lack docs on how to consume them

**Describe the solution you'd like**
Docs and examples to show off how to consume the various provider images

**Describe alternatives you've considered**

**Additional context**

**Comment by mudler** [comment]
cc @paynejacob maybe something you can help with?

**Comment by paynejacob** [comment]
ref: https://github.com/kairos-io/kairos/discussions/1124

**Comment by mauromorales** [comment]
will be worked in #70
