### ISSUE TITLE
ipxe bootstrap

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#393]
### Discussed in https://github.com/kairos-io/kairos/discussions/392

<div type='discussions-op-text'>

<sup>Originally posted by **stelb** November  7, 2022</sup>
Hi,

i tried to install kairos with ipxe (more specific: netbootxyz/netboot.xyz)
I took the provided ipxe file as a start, but it bails out with:
"unable to mount root fs on unknown-block(0, 0)"

kernel and initrd is successfully loaded, is livenet include in initrd to support root=live:http://.. ?

Regards

Stefan</div>

Seems we are having issues with netbooting - maybe default rootfs compression?
Related to #214

**Comment by stelb** [comment]
Ok, I will try to use gzipped squash.

**Comment by stelb** [comment]
I repacked squashfs with gzip, and changed ipxe file to load from netboot server. still the same problem.
I have attached a serial device to my vm, so I can access the complete boot log

[    2.676357] /dev/root: Can't open blockdev
[    2.679550] usb 1-1: new full-speed USB device number 2 using uhci_hcd
[    2.684800] VFS: Cannot open root device "live:http://netboot/kairos-assets/kairos.squashfs" or unknown-block(0,0): error -6
[    2.693876] Please append a correct "root=" boot option; here are the available partitions:
[    2.700534] 0b00            4096 sr0 
[    2.700539]  driver: sr
[    2.706165] 0b01          563968 sr1 
[    2.706169]  driver: sr
[    2.711854] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

I found something else in the first few lines:

[    0.032991] Kernel command line: initrd=kairos-alpine-v1.1.6-k3sv1.25.3+k3s1-initrd ip=dhcp rd.cos.disable root=live:http://netboot/kairos-assets/kairos.squashfs netboot nodepair.disable console=tty1 console=ttyS0  rootfstype=squashfs rd.neednet=1 config_url= rd.live.debug=1
[    0.033339] Unknown kernel command line parameters "netboot ip=dhcp config_url=", will be passed to user space.

netboot and ip are not known to the kernel

full log: [boot.log](https://github.com/kairos-io/kairos/files/9955293/boot.log)

**Comment by mudler** [comment]
Interesting, this seems to work here:
```
#!ipxe
set url http://ip/
set kernel boot/kernel.xz
set initrd boot/kairos-alpine-v1.1.5-initrd
set rootfs rootfs.squashfs

kernel ${url}/${kernel} initrd=${initrd} config_url=http://... ip=dhcp rd.cos.disable root=live:${url}/${rootfs} netboot nodepair.enable console=tty1 console=ttyS0
initrd ${url}/${initrd}
boot
```

**Comment by stelb** [comment]
I built kairos-core-opensuse* with latest commit 62668d4ad44e61e87aaa694df18048ee429e8a7b
I copied them to my netboot installation to /kairos-assets

---
set url http://netboot/kairos-assets
set url http://192.168.40.211/kairos-assets
set kernel kairos-core-opensuse-kernel
set initrd kairos-core-opensuse-initrd
set rootfs kairos-core-opensuse.squashfs

kernel ${url}/${kernel} initrd=${initrd} config_url=http://... ip=dhcp rd.cos.disable root=live:${url}/${rootfs} netboot nodepair.enable console=tty1 console=ttyS0
initrd ${url}/${initrd}
boot
---
192.168.42.140 - - [08/Nov/2022:13:45:46 +0000] "GET /kairos-assets/kairos-core-opensuse-kernel HTTP/1.1" 200 11413408 "-" "iPXE/1.21.1+ (g6b2c)"
192.168.42.140 - - [08/Nov/2022:13:45:46 +0000] "GET /kairos-assets/kairos-core-opensuse-initrd HTTP/1.1" 200 76364664 "-" "iPXE/1.21.1+ (g6b2c)"

no rootfs pull, same error as above: 
[    0.036016][    T0] Unknown kernel command line parameters "netboot ip=dhcp config_url=", will be passed to user space.

unable to mount root

**Comment by stelb** [comment]
ok, after a lot of trying with options, debugging, changing networkcards/cpus, changing kernels/initrd/rootfs to otherwise working files I found one line in another ipxe File: imgfree, now I it's booting,
i have a different problem now, but probably that's my problem.

I am (not yet) ipxe expert .) everything else did with just a few attempts.

`
set url http://192.168.40.211/kairos-assets
set kernel kairos-core-opensuse-kernel
set initrd kairos-core-opensuse-initrd.gz
set rootfs kairos-core-opensuse.squashfs

set boot_params ip=dhcp net.ifnames=1 rd.cos.disable nodepair.disable console=tty1 console=ttyS0 rootfstype=squashfs root=live:${url}/${rootfs} rd.noverifyssl
set config_params config_url=${config}
set debug_params rd.live.debug=1 rd.net.dhcp.retry=5 rd.net.timeout.dhcp=300 rd.live.debug=1 loglevel=7

imgfree
kernel ${url}/${kernel} ${boot_params} ${config_params} ${debug_params} initrd=initrd.magic
initrd ${url}/${initrd}
echo
echo MD5sums:
md5sum ${kernel} ${initrd}
boot
`

**Comment by stelb** [comment]
### I found an issue with systemd-udevd:

Could not set AlternativeName= or apply AlternativeNamesPolicy= on ens18: File exists

If I add net.ifnames=0 net.biosnames=0 it seems to fix my problem

(Maybe systemd/systemd#16665? when I end up in emergency shell the if is named ens18, but udevd failed to rename)

### /dev/random
Then I need to have to add a RNG to my vm, otherwise log complains about /dev/random. it's the first vm that needs this, maybe if I change from kvm64 cpu to host or sth else it works.

### imgfree
I have to add imgfree before kernel/initrd lines. Otherwise I get a kernel panic
I do not understand this yet:

```
[    0.030363] Kernel command line: ip=dhcp netboot rd.cos.disable rodepair.enable console=tty1 console=ttyS0 root=live:https://github.com/kairos-io/kairos/releases/download/v1.1.6/kairos-ubuntu-20-lts-v1.1.6.squashfs net.ifnames=0 net.biosnames=0 config_url=http://192.168.40.211/cloudinit/kairos/config.yaml  initrd=kairos-ubuntu-20-lts-v1.1.6-initrd
...
[    3.045474] VFS: Cannot open root device "live:https://github.com/kairos-io/kairos/releases/download/v1.1" or unknown-block(0,0): error -6
```
The URL seems to be cut off?

**Comment by mudler** [comment]
Thanks for your deep dive @stelb, it was really helpful! 

I had occasion to reproduce some of the issues and there should be a bunch of fixes landing to alpine and openSUSE images regarding netboot (#443 ) in v1.2.0 #459 . I think that affected your use-case here as well

**Comment by stelb** [comment]
ok, I'll check again when v1.2.0 is ready

**Comment by stelb** [comment]
Hey @muddler,

I tested kairos-alpine-ubuntu / kairos-alpine-ubuntu(-k3s
- it boots up with standard kernel parameters
- /dev/random does not seem to be a major problem, just a log warning and maybe it's a bit slower, without RNG, I don't care :) there have been some more warnings before
```
[   21.522684] random: crng init done
[   21.525136] random: 135 urandom warning(s) missed due to ratelimiting
```
- i still have to use imgfree. all parameters are passed to the kernel, but at least the error has a truncated root parameter
```
[    0.036785] Kernel command line: ip=dhcp netboot rd.cos.disable nodepair.enable console=tty1 console=ttyS0 root=live:https://github.com/kairos-io/kairos/releases/download/v1.2.0/kairos-alpine-ubuntu-v1.2.0.squashfs config_url=http://192.168.40.211/cloudinit/kairos/config.yaml  initrd=kairos-alpine-ubuntu-v1.2.0-initrd
[    0.037017] Unknown kernel command line parameters "netboot ip=dhcp config_url=http://192.168.40.211/cloudinit/kairos/config.yaml", will be passed to user space.
[    0.037181] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)


[    3.056182] VFS: Cannot open root device "live:https://github.com/kairos-io/kairos/releases/download/v1.2" or unknown-block(0,0): error -6
```
I have no idea what's happening here. maybe it's netbootxyz/netboot.xyz#224. I think it's not a kairos problem.

**Comment by mudler** [comment]
thanks for getting back, Interesting! Care to share your setup? Might be really helpful for others and for us to reproduce the issue, we might documented a known issues with netboot.xyz

**Comment by stelb** [comment]
I'll cleanup my config and will describe/show  what I did to make it work

right now it's a bit messy because I tried so many things :)

**Comment by mudler** [comment]
That's perfectly fine and understandable, thanks! We are having a look at #441 so to avoid this back and forth in the future :slightly_smiling_face:

**Comment by stelb** [comment]
ok, I have my currently used working here: 

https://github.com/stelb/netboot.xyz-custom/blob/master/kairos.ipxe

It's reduced to one kairos version, dist and k3s version

I can install k3s server or agents with this (or I should actually, I am still struggling with the needed config)

You need a working netboot.xyz setup, I added a short description, how to add the repo to the menu.

kairos-debug.ipxe is broken right now, I used this to boot different images/versions but  there is no logic which combinations are valid

**Comment by stelb** [comment]
oh, and I got /dev/random Problems even while loading the kenel via https.. this has nothing to do with kairos, it's a proxmox/qemu problem or even something I misconfigured. Adding RNG device to the vm helps.

**Comment by stelb** [comment]
Hey @mudler,
as I have been busy with other things I forgot about that issue. I'll probably will try Kairos again, my home cluster still needs to be migrated from that k3os.
Cheers
Stefan
