### ISSUE TITLE
kcrypt configuration should be as oem config file

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#399]
**Is your feature request related to a problem? Please describe.**
Currently kcrypt takes config via cmdline, however, there should be a possibility to write such configs in yaml

**Describe the solution you'd like**
kcrypt-challenger to look over /oem and specific folder to get the config (wss_server, TLS certs, etc)

**Describe alternatives you've considered**

**Additional context**

**Comment by jimmykarily** [comment]
We currently [hardcoded](https://github.com/kairos-io/kcrypt-challenger/pull/8/files#diff-94d75f189ea8b05ff1476dce6652e33bf43bdb1fddade2736156f8366b4eb22bR19) a default location. @mudler do you think we should put it in a directory instead? e.g. `/oem/kcrypt/config`

**Comment by mudler** [comment]
here I was thinking more in the other way around, such as `kcrypt` to read `/oem` as a Config file, like `kairos` does currently (`config.Scan`...).

This is so then you can directly specify the kcrypt-challenger configuration when deploying a node in the main kairos configuration file, e.g :+1: 

```
#cloud-config

kcrypt-challenger:
  server: ....
  tls_cert: ...
```

**Comment by jimmykarily** [comment]
Depends on this kairos branch: https://github.com/kairos-io/kairos/tree/399-kcrypt-configuration
