### ISSUE TITLE
customizing arm image - repository problem

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#419]
I'm trying to customize an image which is build via `build-arm-image.sh` in a docker container.
So I have a `Dockerfile` starting with `FROM quay.io/kairos/kairos-alpine-arm-rpi:v1.1.6-k3sv1.25.3-k3s1` and being modified thereafter. The resulting image is now in my local docker and since `build-arm-image.sh` run inside a docker container it can't access this image.
I tried two different approaches but both failed:
- starting a local docker repo and accessing it -> failed since this repo is http but the `osbuilder-tools` container expects even for `host.docker.internal` an https repo
- using a directory where the resulting image is untared -> lead to errors, probably because the directory is on macOS ...

Of course I can now try my private AWS ECR but this seems to complicated...

There must be some easier way I'm missing...

**Comment by Ognian** [comment]
@mudler Hmm I'm using the `-v` and `--local` option already; I looked into the source code and it looks to me that the option does [nothig](https://github.com/kairos-io/osbuilder/blob/1f932a7644f1083d364b15542a356dfc440524de/tools-image/build-arm-image.sh#L150) shouldn't the option be added somehow [here](https://github.com/kairos-io/osbuilder/blob/1f932a7644f1083d364b15542a356dfc440524de/tools-image/build-arm-image.sh#L270)?

**Comment by mudler** [comment]
@Ognian correct, seems somehow that slipped - good catch! feel to take a stab a it? ``pull-image`` should take a `--local` as well in that case

**Comment by mudler** [comment]
Thanks! just saw it, looking good here :bow:  !
