### ISSUE TITLE
Ubuntu kernel drivers too old!

### ISSUE THREAD

**Issue by saamalik** [kairos-io/kairos#42]
**C3OS version:**
1.23.6-53

**CPU architecture, OS, and Version:**
x86, Ubuntu 20.04 LTS

**Describe the bug**
The _Lenovo P350 Tiny_ appliances have an embedded _I219-LM Ethernet card_. The _Ubuntu 20.04 LTS_ variant does have the _e1000e_ kernel drivers for intel network cards -- but the version is `3.2.6-k` -- over 8 years old from ~2015! Unfortunately, the Ethernet card is not claimed by the older drivers =/

**To Reproduce**
N/A

**Expected behavior**
The network card should be detected

**Logs**
N/A

**Additional context**
For an installer system like C3OS, it's not feasible to download and compile drivers for all hardware, but to mitigate a poor experience, perhaps it's best to switch _linux-image-generic-hwe-20.04_ which includes the working drivers for this hardware. If you agree, I'm happy to submit a PR to switch the build to use the newer kernel and kernel drivers.

**Comment by mudler** [comment]
Thanks for the report! 

The Ubuntu images don't get some love since a while, that's definitely a good point. 

Ubuntu 22.10 was already in my radar

**Comment by saamalik** [comment]
Would you like me a PR with support for 22.10? And just to confirm, you want 22.10 and not the LTS release (e.g: 22.04)?

Just let me know if you'd like me to test and make the change, maybe after #44 is implemented.

**Comment by mudler** [comment]
@saamalik that would be great, we have #62 already in, as the images currently in c3os are not bootable afaicr.

**Comment by mudler** [comment]
that should be fixed by now I guess? :)
