### ISSUE TITLE
create a single service to expose images

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#427]
images are currently exposed with a custom deployment for each one, instead we should serve the images from a single http endpoint

**Comment by jbalonso** [comment]
I just submitted https://github.com/kairos-io/kairos/discussions/456 and _then_ just saw this. Sorry! However, I did offer a specific proposal for how to go about this... would you like me to copy it all here?

**Comment by mudler** [comment]
apologize @jbalonso I just saw your comment now. However this card is fixed by now I think, right @jimmykarily ? Or is there any pending work?

**Comment by jimmykarily** [comment]
Yes it should be fixed since: https://github.com/kairos-io/osbuilder/pull/22
