### ISSUE TITLE
Cloud config log files not available

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#43]
**C3OS version:**
Alpine, latest

**CPU architecture, OS, and Version:**

**Describe the bug**
There are no logs for either cos-setup-boot and cos-setup-network.
Ideally, those should be also covered by logrotate (see #75)

**To Reproduce**

**Expected behavior**
Have logs in `/var/logs`, similarly as `cos-reconcile`

**Logs**

**Additional context**
Reported by @deekue in chat

**Comment by jimmykarily** [comment]
If these run as systemd services there should be logs in journalctl. Let's verify. If logs are now there, we should document how people can find those.

**Comment by Itxaka** [comment]
Also the agent now saves logs from every run into /var/log/kairos so this is not valid anymore
