### ISSUE TITLE
Encrypt partially with TPM

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#438]
**Is your feature request related to a problem? Please describe.**
Currently kcrypt works as an escrow server, however that doesn't spare from server side attacks

**Describe the solution you'd like**

We could lverage the TPM and add a salt to the stored secret such as also compromission on server-side is guaranteed, plus send it encrypted to the other party

**Additional context**

**Comment by jimmykarily** [comment]
Currently partially blocked by #399
