### ISSUE TITLE
`/var/lib/longhorn` is not shared mounted

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#440]
**Kairos version:**
1.1.7-alpine

**CPU architecture, OS, and Version:**

**Describe the bug**
Alpine can't be installed as `/var/lib/longhorn` seems to not be shared mounted

**To Reproduce**

**Expected behavior**

**Logs**
```
Warning  Failed          2m4s                kubelet            Error: failed to generate container "8424cf1a165ad1928a20fff7f65e863896018aedb1d8cbf47437b7dd8e7b6cee" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/var/lib/longhorn" but it is not a shared mount
```

**Additional context**

**Comment by christianprim** [comment]
Maybe a problem with mount propagation:

- Script for checking it: https://longhorn.io/docs/1.1.0/deploy/install/#using-the-environment-check-script
- Idea for a fix: https://slack-archive.rancher.com/t/555104/how-do-i-enable-mount-propagation-on-my-alpine-linux-k3s-ins
