### ISSUE TITLE
Netboot testing

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#441]
**Is your feature request related to a problem? Please describe.**
It is quite annoying to have to test netboot manually. besides, it makes hard to detect breakage

**Describe the solution you'd like**
Automation to take over - we run already suites as part of our CI spawning a VM, there shouldn't be anything blocking us to run a suite for netboot

**Describe alternatives you've considered**
Manually testing each time

**Additional context**
#214

**Comment by jimmykarily** [comment]
Work is happening here: https://github.com/kairos-io/kairos/tree/441-netboot-testing It's almost done. Some final touches, then commit squashing and will open a PR.
