### ISSUE TITLE
osbuilder image is multiplatform, but the packaged `elemental` is not

### ISSUE THREAD

**Issue by jbalonso** [kairos-io/kairos#451]
On an arm64 node:

```
$ kubectl logs -n hk-system opensuse-arm-rpi-v1-1-7-699d6bc7f4-tzfsd -c build-iso
+ /entrypoint.sh --debug --name opensuse-arm-rpi-v1-1-7 build-iso --date=false --overlay-iso /iso/iso-overlay --output /public dir:/rootfs
+ elemental --config-dir /config --debug --name opensuse-arm-rpi-v1-1-7 build-iso --date=false --overlay-iso /iso/iso-overlay --output /public dir:/rootfs
/entrypoint.sh: line 5: /usr/bin/elemental: cannot execute binary file: Exec format error
```

Without deeply investigating, it looks like `/usr/bin/elemental` is likely an amd64 binary rather than an arm64 binary, which would be required for the node in question.

**Comment by mudler** [comment]
good catch, yup we are consuming there images from packages that are not built multi-arch. 

@jimmykarily always had on top of my head - maybe we can do a simple post-ci process that links the various arches after builds happens on kairos-io/packages, or pick up luet to output multi-arch images directly.

**Comment by jbalonso** [comment]
It occurs to me that I found kairos-io/helm-charts#5 because I needed to use a `nodeSelector`... because I found that the controller (`osbuilder` _manager_) was not multiarch...

... which means I completely lost track of where the builder images come from (as opposed to the `osbuilder` _manager_).
