### ISSUE TITLE
Project mascot!

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#452]
**Is your feature request related to a problem? Please describe.**
I think the logo is nice et al, but I really like having mascots!!

Few random ideas from my side, some just because I like the animals in general :slightly_smiling_face:  :
- Alpaca! ( just :heart: )
- Capuchin monkey ( :monkey: )
- Armadillos ( :mouse: ) might even fit re immutability? :roll_eyes: 
- Flying squirrel ( :mouse: :bird: )
- Crested porcupine
- Snake (Immutability)
- Greek god
- .... put yours!

**Describe the solution you'd like**
Let's first start a discussion to gather some ideas to brainstorm, and maybe make this happen?! Maybe we can blend it with the logo, with the graphic site, or both!

**Comment by karl-cardenas-coding** [comment]
This going to sound super nerdy, but when I hear the name "Kairos," I think of the greek god. In Greek mythology, Kairos was known as the god of opportunity, good luck, and favorable moments. I'd say making your OS immutable main brings good opportunities and favorable moments compared to the opposite 😅

**Comment by mauromorales** [comment]
For what I can see, Kairos used to have wings on his feet ... not sure if a flying foot can be a mascot haha but it looks kinda cool when looking at images on google ... or maybe the mascot animal can have wings on his feet?

**Comment by mauromorales** [comment]
For an animal, I'd vote for a cheetah 🐱 because it is the fastest animal on earth, just like Kairos was really fast ⏩

**Comment by mauromorales** [comment]
We have a mascot now, so I'll close this ticket
