### ISSUE TITLE
Pull the complete elemental-toolkit cloud-config reference docs into Kairos docs

### ISSUE THREAD

**Issue by cybernetic-mountaineer** [kairos-io/kairos#458]
Found here: https://github.com/rancher/elemental-toolkit/blob/0d0f9a7a7fa79d5254389ddaff646fecaea98a8c/docs/content/en/docs/Reference/cloud_init.md

Recommending pulling the complete reference into this page: 
https://kairos.io/docs/reference/configuration/

Especially given the fork of elemental-toolkit, probably time to take full control of the config reference. Also a pain to jump between the docs. Thoughts?

**Comment by mudler** [comment]
Hi @cybernetic-mountaineer ! 

good point, this was indeed on the tip of my head already and completely forgot.  There are also other pieces that are not documented too, as support for cloning git repositories, and others I believe.

note: that docs are loosely a port of https://github.com/mudler/yip docs

**Comment by cybernetic-mountaineer** [comment]
Ah, true on the yip bit. Putting the whole config ref in one place will make development a lot easier. With some discussion I could drop a PR for this too. Don't imagine it'll take too long to consolidate it in one place.

**Comment by mudler** [comment]
That'd be great and really appreciated!

**Comment by cybernetic-mountaineer** [comment]
Beat me to it. Nice job @mudler and @jimmykarily ! Looks great.
