### ISSUE TITLE
🐧 Zfs support

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#510]
**Is your feature request related to a problem? Please describe.**

Zfs isn't supported currently as missing from core images https://github.com/kairos-io/kairos/tree/master/images

**Describe the solution you'd like**
Zfs to be shipped, so can be used for partitioning

**Additional context**
- [ ] Add zfs packages to flavors (check distro packages support, and be careful on how many deps introduces, in e.g. alpine)
- [ ] QA - can I create a zfs partition after install, and mount it over somewhere ? (vm with 2 disks)

**Comment by sdwilsh** [comment]
Would it also make sense to add `zfs-auto-snapshot` as well?  By default it installs some cron jobs that would probably want to be user-configurable (at least for Ubuntu, and I assume that's true for debian and others as well).
