### ISSUE TITLE
:seedling: Proper support for openRC in the oem layouts

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#511]
This is part of #116.

Currently we have separated system oem files for alpine: https://github.com/kairos-io/kairos/tree/master/overlay/files-alpine/system/oem .

While this works - it is harder to maintain in the context of #116, which would then require a separate workflow for alpine/openrc based systems.

This card is about:
- [ ] Reduce separated oem files for openrc-based distro, but instead configs should detect when we are using open-rc and acting accordingly
- [ ] Do not make anymore distinction about the flavor and init. Just use the init as a reference to detect if we have to run openRC commands or not ( e.g. https://github.com/kairos-io/kairos/blob/bca5b432e9cda5db13aca8f6ebed7ff2bd39596f/pkg/utils/system.go#L53)

**Comment by mauromorales** [comment]
This needs to be updated to reflect the new state of the project. Layout files have been extracted to packages: 

https://github.com/kairos-io/packages/tree/main/packages/static/kairos-overlay-files/files

And the go code in the kairos repo was extracted to the kairos-sdk repo: https://github.com/kairos-io/kairos-sdk/blob/8f54324703c2a88484cba31c22b8bd6b1cc26e8e/utils/utils.go#L122-L125

**Comment by jimmykarily** [comment]
If we have this, can we have only one framework image for all flavors? Let's discuss this in the planning meeting.

**Comment by Itxaka** [comment]
Checked and we already do this, we moved all configs to outside the kairos repo into a package and that package doesnt discriminate between flavors, is now a commo package installed during framework generation.


We are missing moving bootargs.cfg and config.txt for rpi into the generic package thougth.

**Comment by Itxaka** [comment]
done!
