### ISSUE TITLE
:building_construction: Central http server where to push result artifacts

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#515]
Instead of spawning up servers for all every artifact, we should have a single server that binds to a pvc that can be set, and makes artifacts available. Bonus points if this can be configured somehow (can I provide my own server?)

- [x] osbuilder should create jobs that push to a PVC rather then create a full server
- [x] osbuilder should cleanup with finalizers when the osartifact is removed
- [ ] chart, if setting up a server, should expose services/ingress configuration for exposing it
- [x] pushing results to the pod via kubernetes rest-api, re-use existing http server that could be also provided by the user (label to identify pod, path where to push where pvc is mounted)
- [x] QA tests

**Comment by jimmykarily** [comment]
Started a refactoring here: https://github.com/spectrocloud/kubesplit/tree/remove-dependencies
We need to be able to produce helm charts easily for fast iterations so we can't afford manual helm chart editing.

The libraries we used in kubesplit had some limitations (e.g. they couldn't replace maps with a string value, which is what you do when you create a helm template). E.g.
```
	Replacement: replaceKeyValue(`/spec/template/metadata/labels`, `{{- include "helm-chart.selectorLabels" . | nindent 10 }}`),
```

 and we figured out it's possible with with our jq `unstructured`  library from `kairos` repo.
Also those libraries are no longer maintained so we couldn't expect any new features.

**Comment by jimmykarily** [comment]
PR: https://github.com/spectrocloud/kubesplit/pull/1

**Comment by jimmykarily** [comment]
osbuilder work happening here: https://github.com/kairos-io/osbuilder/tree/515-central-server

**Comment by jimmykarily** [comment]
PR: https://github.com/kairos-io/osbuilder/pull/22/files
