### ISSUE TITLE
Alpine: use busybox ntpd

### ISSUE THREAD

**Issue by christianprim** [kairos-io/kairos#519]
**Kairos version:** alpine-ubuntu and probably alpine-opensuse-leap

**CPU architecture, OS, and Version:** amd64

**Describe the bug**
It could be just a problem for my server, but when openntpd is used, prometheus gives an alert:

```
 Clock on <hostname>:9796 is out of sync by more than 300s. Ensure NTP is configured correctly on this host.
```
I stopped the openntpd-service, patched `/etc/init.d/ntpd` to use the busybox binary (necessary since ntpd doesn't point to busybox), started the ntpd-service and the alert disappears.

(There would be no need for a patch if openntpd wasn't installed in the alpine flavor, ntpd would point to busybox)

**To Reproduce**
Join an alpine k3s-agent (no special config) to a cluster with prometheus monitoring and alerting installed. After a short period the alert is firing.

**Expected behavior**
No such errors.

**Question**
Is it mandatory to install a dedicated ntpd-package on alpine? Why not stick with the (working) busybox-version?

It could also help reduce confusion. See #476

**Comment by christianprim** [comment]
I can now confirm, that this nasty problem occurs on every server I installed alpine on. On every node I have to manually stop openntpd service, patch `/etc/init.d/ntpd` and start the busybox-version of ntpd to get rid of the message. Perhaps it is related to the fact, that openntpd not only acts as a client but also as a server which is not really needed here.

@mudler: I would recommend removing the openntpd package from alpine images:

In the file `images/Dockerfile.alpine-opensuse-leap` remove line 97 and the backslash from the previous one. That should do the trick.

(One has to test, if ntpd-service (busybox) is starting. But I think it should.)

**Comment by mudler** [comment]
good catch @christianprim , I think that should be trivial to fix indeed, I think there was just some overlap with openntpd at some point, but ntpd from busybox should fit just fine our case
