### ISSUE TITLE
:seedling: Auto eject ISO after install config option

### ISSUE THREAD

**Issue by avfuturist** [kairos-io/kairos#528]
**Is your feature request related to a problem? Please describe.**
I use ISOs to bootstrap baremetal nodes pretty frequently. One Issue I have is managing boot order. If the node reboots after installing Kairos, there's a good chance it boots from the ISO again after restart unless it's been ejected. I think we could make this easier via the cloud-config yaml. 

**Describe the solution you'd like**
I'd like to see an "install.eject_iso" boolean param in the cloud-config. That way if I specify to install to disk x and reboot after install, I can ensure the iso will get ejected before boot occurs. 

**Describe alternatives you've considered**
We could also set boot order, but that's going to require getting into machine BIOS / UEFI.

**Comment by mudler** [comment]
Thanks @avfuturist (and apologize for the delay).

This is possible already by passing by `--eject-cd` to `options` in the cloud config file, however this calls for an enhancement in UX and have it inside the `install` block as `ejectCD`.

**Comment by avfuturist** [comment]
Fantastic!
