### ISSUE TITLE
K3s service not running after upgrade on single node clusters

### ISSUE THREAD

**Issue by avfuturist** [kairos-io/kairos#549]
I deployed a single node system (VM on Hyper-V) from ISO kairos-alpine-ubuntu-v1.3.0-k3sv1.20.15+k3s1. I then deployed system-update-controller (following the docs [here](https://kairos.io/docs/upgrade/kubernetes/) and ran an update targeting kairos-ubuntu-20-lts-v1.3.0-k3sv1.25.4+k3s1...the upgrade took and worked perfectly buuut I never saw it come back into my K8s management platform (Portainer). So I SSH'd into the node and checked...k3s.service was inactive (dead). After restarting k3s with systemctl, it started right up and worked perfectly. I did this again with a different version of the same target image and had the exact same result. Upgrade works, systemd doesn't bring k3s back up. Not sure what my next troubleshooting step might be...open to ideas. 

If I use provider-kairos / k3s then single-node upgrades are going to be a key usecase. Hopefully that's possible...

**Comment by mudler** [comment]
Hey @cybernetic-mountaineer !

Apologize for the delay, did you upgraded from an openRC based to a systemd one? It would need a re-bootstrap on systems with incompatible inits as services are not enabled otherwise. This should be fixed by #69 , but for the time being we should document this.

**Comment by cybernetic-mountaineer** [comment]
I bet that’s exactly what happened. Kairos-alpine-ubuntu -> Kairos-ubuntu-20-lts I think.
