### ISSUE TITLE
✨ Add proxy and cacert attributes to clusterplugin.cluster object

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#555]
**Is your feature request related to a problem? Please describe.**

On the clusterplugin.cluster object add support for proxy and cacert attributes to be set which then can be used by the provider to set the values explicitly.

**Describe the solution you'd like**

Update the cluster object with env and cacert attributes.

**Comment by mudler** [comment]
Closing, as the PR was merged
