### ISSUE TITLE
:book: Add introduction videos and media section to our docs

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#601]
**Is your feature request related to a problem? Please describe.**
We do have few videos and blog posts that can be helpful to our docs:

- https://www.youtube.com/watch?v=kiDQujibz2k
- https://www.youtube.com/watch?v=doXT1jxyZe0
- https://thenewstack.io/livin-kubernetes-on-the-immutable-edge-with-kairos-project/

Aside, also the slides used in the video should be public as well

**Describe the solution you'd like**
The introduction video sounds a great fit for our quickstart. I think we should also have a separate section with media resources, blog posts, howtos, etc.

**Comment by mauromorales** [comment]
@mudler I wasn't able to find the slides, could you please share them?
