### ISSUE TITLE
:book: Update quickstart to use latest release

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#605]
**Is your feature request related to a problem? Please describe.**
The quickstart versions are hardcoded, so we are refering to 1.0 there

**Describe the solution you'd like**
Can we automate docs updating with latest release if tests are passing? I guess even a nightly job opening up a PR here could do

**Describe alternatives you've considered**
Manually updating docs

**Additional context**

**Comment by mauromorales** [comment]
Fixed in https://github.com/kairos-io/kairos-docs/pull/15
