### ISSUE TITLE
📖 documentation: kcrypt

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#624]
Document how to use kcrypt

Depends on:

- https://github.com/kairos-io/kairos/issues/399
- https://github.com/kairos-io/kairos/issues/346

but we can start documenting what we have after 399 and add more as we go.

**Comment by mudler** [comment]
Depends on https://github.com/kairos-io/kairos/issues/399

**Comment by mudler** [comment]
I'll start drafting docs without the TLS sections. leaving that for future improvement once we have something to work on
