### ISSUE TITLE
🌱 Research around UKI and tpm

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#625]
Preparation for this: https://github.com/kairos-io/kairos/issues/347

Collect information about UKI (links and all) and understand how it works together with tpm.

The result of this story should be a presentation to the team and a document with  a summary and links to read more.
We will keep improving the document as we learn more.

Timebox: 3 days

**Comment by Itxaka** [comment]
Some links I dont want to lose related to info about EFI, shells, UKI:

 - https://man.archlinux.org/man/systemd-stub.7
 - https://wiki.osdev.org/UEFI#UEFI_applications_in_detail
 - https://github.com/uapi-group/specifications/blob/main/specs/unified_kernel_image.md
 - https://man.archlinux.org/man/systemd-measure.1.en
 - https://manuais.iessanclemente.net/images/a/a6/EFI-ShellCommandManual.pdf
 - https://0pointer.net/blog/brave-new-trusted-boot-world.html

**Comment by mudler** [comment]
I'm closing this for now - we have enough pieces and seems we are already in good direction to support UKI. there will be follow ups stories as #873 that needs to be groomed and how to tackle that with the encryption afterward
