### ISSUE TITLE
🐧 tumbleweed flavor

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#65]
Currently the image definition is there, but lacks few things in order to boot properly. This card is to make the tumbleweed flavor functional and into releases.

- opensuse should then track `tumbleweed`
- new flavor "opensuse-leap" to track opensuse leap
- update docs, this is a breaking change in our repos (opensuse tracks tumbleweed now, and redirect users of leap to the new images)

**Comment by Itxaka** [comment]
picking this as it helps me get up to speed with all the building pieces. Shouldnt take long.

**Comment by Itxaka** [comment]
Do we really want to have opensuse tracking tumbleweed? I mean, we had issues in the past with tumbleweed being broken, plus on every rebuild you could get a broken image or missing deps or things like that?

Seeing that the opensuse flavor is the one that appears more prominent in the docs and so on, I would not target tumbleweed as our "opensuse" flavor, I would keep leap and tumbleweed separated and mention leap on the docs instead.
