### ISSUE TITLE
🐧 Alpine image with alpine kernel

### ISSUE THREAD

**Issue by christianprim** [kairos-io/kairos#653]
**Is your feature request related to a problem? Please describe.**
Till now, alpine flavor uses a kernel from ubuntu or opensuse-leap. It would be nice, if alpine could ship a real alpine image with an alpine kernel. One little step in this direction is done as `dracut` is in the testing branch of alpine linux.

The attached Dockerfile shows a possible solution to install `dracut` in the image:

**Dockerfile**
```
FROM quay.io/luet/base as luet
FROM alpine

# Install packages in the image. In a systemd-based system you would install systemd instead of openrc.
# Note, grub2 is a required dependency, along as an init system (currently openRC and systemd are supported)
RUN apk --no-cache add  \
      grub \
      grub-efi \
      grub-bios \
      bash \
      bonding \
      bridge \
      connman \
      gettext \
      squashfs-tools \
      openrc \
      parted \
      e2fsprogs \
      logrotate \
      busybox-openrc \
      dosfstools \
      coreutils \
      which \
      curl \
      nano \
      gawk \
      haveged \
      tar \
      rsync \
      bash-completion \
      blkid \
      ca-certificates \
      conntrack-tools \
      coreutils \
      cryptsetup \
      curl \
      dbus \
      dmidecode \
      dosfstools \
      e2fsprogs \
      e2fsprogs-extra \
      efibootmgr \
      eudev \
      fail2ban \
      findutils \
      gcompat \
      grub-efi \
      haveged \
      htop \
      hvtools \
      iproute2 \
      iptables \
      irqbalance \
      iscsi-scst \
      jq \
      kbd-bkeymaps \
      lm-sensors \
      libc6-compat \
      libusb \
      logrotate \
      lsscsi \
      lvm2 \
      lvm2-extra \
      mdadm \
      mdadm-misc \
      mdadm-udev \
      multipath-tools \
      ncurses \
      ncurses-terminfo \
      nfs-utils \
      open-iscsi \
      rbd-nbd \
      openrc \
      openssh-client \
      openssh-server \
      parted \
      procps \
      qemu-guest-agent \
      rng-tools \
      rsync \
      strace \
      smartmontools \
      sudo \
      tar \
      tzdata \
      util-linux \
      vim \
      wireguard-tools \
      wpa_supplicant \
      xfsprogs \
      xz \
      open-vm-tools \
      open-vm-tools-deploypkg \
      open-vm-tools-guestinfo \
      open-vm-tools-static \
      open-vm-tools-vmbackup \
      linux-lts
      
RUN apk --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing/ add dracut; exit 0

# Enable some services
RUN rc-update add sshd boot && \
    rc-update add connman boot  && \
    rc-update add acpid boot && \
    rc-update add hwclock boot && \
    rc-update add syslog boot && \
    rc-update add udev sysinit && \
    rc-update add udev-trigger sysinit && \
    rc-update add ntpd boot && \
    rc-update add crond && \
    rc-update add fail2ban

# Symlinks to make boot-assessment work
RUN ln -s /usr/sbin/grub-install /usr/sbin/grub2-install && \
    ln -s /usr/bin/grub-editenv /usr/bin/grub2-editenv

# Now we install Kairos dependencies below
COPY --from=luet /usr/bin/luet /usr/bin/luet

RUN mkdir -p /etc/luet/repos.conf.d && \
    luet repo add kairos -y --url quay.io/kairos/packages --type docker

RUN luet install -y \
        system/base-cloud-config \
        # dracut/immutable-rootfs \
        # dracut/network \
        static/grub-config \
        system/suc-upgrade \
        system/shim \
        system/grub2-efi \
        system/elemental-cli \
        init-svc/openrc

# Install kernels from the Kairos repositories, or regenerate the initrd with dracut
RUN dracut --force /boot/initrd-lts $(ls /lib/modules | head -n1) && \
    ln -sf /boot/initrd-lts /boot/initrd

# Enable services
RUN mkdir -p /etc/runlevels/default && \
    ln -sf /etc/init.d/cos-setup-boot /etc/runlevels/default/cos-setup-boot  && \
    ln -sf /etc/init.d/cos-setup-network /etc/runlevels/default/cos-setup-network  && \
    ln -sf /etc/init.d/cos-setup-reconcile /etc/runlevels/default/cos-setup-reconcile && \
    ln -sf /etc/init.d/kairos-agent /etc/runlevels/default/kairos-agent

# Optionally, put your fixed cloud config files in here following our docs https://kairos.io/docs/reference/configuration/
# RUN cp cloud.yaml /system/oem/configuration.yaml
```

**Important**
There is still a dependency on `systemd` at least in the commented packages (dracut/immutable-rootfs and dracut/network).

**Comment by jimmykarily** [comment]
We can start working on this, as soon as we stop relying on systemd in initramfs. Created a story here: https://github.com/kairos-io/kairos/issues/657

**Comment by mudler** [comment]
Now that immucore was merged, this is unblocked

**Comment by christianprim** [comment]
But immucore still depends on systemd....
```
dracut: dracut module 'immucore' will not be installed, because command '/systemd' could not be found!
dracut: dracut module 'kcrypt' will not be installed, because command '/systemd' could not be found!
...
dracut: dracut module 'immucore' cannot be found or installed.
```

I installed the following luet packages:
 INFO   📦  Package  dracut/immucore-0.0.12 installed
 INFO   📦  Package  system/immucore-0.0.12 installed
 INFO   📦  Package  static/grub-config-0.2 installed
 INFO   📦  Package  system/base-cloud-config-0.1 installed
 INFO   📦  Package  system/shim-2.06-150401 installed
 INFO   📦  Package  system/elemental-cli-0.20230222.1 installed
 INFO   📦  Package  system/suc-upgrade-0.1 installed
 INFO   📦  Package  system/kcrypt-0.5.1 installed
 INFO   📦  Package  init-svc/openrc-0.2-8 installed
 INFO   📦  Package  system/grub2-efi-2.06-150401 installed
 INFO   📦  Package  dracut/kcrypt-0.5.1 installed
 
 And tried to build the initrd with `dracut --force /boot/initrd-lts $(ls /lib/modules | head -n1)`

**Comment by mudler** [comment]
I think that's a misconfiguration, but we have at least https://github.com/kairos-io/kairos/issues/992 blocking this

**Comment by Itxaka** [comment]
Woah, I dunno, probably a few big pieces missing as I have only tested with UKI, not with a pivot system.

Unfortunately I got no cycles left to look at this now with 2.0 around the corner but if I got some time free i will have a quick look

**Comment by Itxaka** [comment]
> There is definitively a systemd dependency in https://github.com/kairos-io/immucore/blob/master/dracut/28immucore/module-setup.sh
> 
> It seems that dracut calls this check. Also I'm not fully sure if I'm looking in the right place.

Yes, indeed there is. Probably should check for openrc or something similar for alpine? And also provide an openrc file?

Sorry I'm not that familiar with alpine based systems 😀

**Comment by christianprim** [comment]
>  Probably should check for openrc or something similar for alpine? 

Yup. To check for openrc in bash do something like
```
if [ -f /sbin/rc-service ]; then
  <code if openrc is used>
fi
```
I think, this should work in `module-setup.sh`

> And also provide an openrc file?

Both `.service`-files must have their counterparts in openrc.

example for `immucore.service`:

```
#!/sbin/openrc-run
  
name="immucore"
command="/usr/bin/immucore"

depend() {
        need udev
        # don't think a before block is needed in openrc
        # before ...
}
```

Here is the list of all openrc-services running in kairos (FYI):

```
Runlevel: shutdown
Runlevel: default
 cos-setup-network                                                        [  started  ]
 kairos-agent                                                                [ failed ]
 cos-setup-reconcile                                [  started 70 day(s) 17:13:16 (0) ]
 cos-setup-boot                                                           [  started  ]
Runlevel: nonetwork
Runlevel: boot
 hwclock                                                                  [  started  ]
 connman                                                                  [  started  ]
 syslog                                                                   [  started  ]
 ntpd                                                                     [  started  ]
 sshd                                                                     [  started  ]
 acpid                                                                    [  started  ]
Runlevel: sysinit
 udev                                                                     [  started  ]
 udev-trigger                                                             [  started  ]
 fail2ban                                                                 [  started  ]
 crond                                                                    [  started  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed/wanted
 sysfs                                                                    [  started  ]
 devfs                                                                    [  started  ]
 hostname                                                                 [  started  ]
 modules                                                                  [  started  ]
 cgroups                                                                  [  started  ]
 fsck                                                                     [  started  ]
 root                                                                     [  started  ]
 localmount                                                               [  started  ]
 dbus                                                                     [  started  ]
Dynamic Runlevel: manual
 iscsid                                                                   [  started  ]
 k3s-agent                                          [  started 70 day(s) 17:07:30 (0) ]
```

Hope it helps

**Comment by christianprim** [comment]
A good place to look for openrc is https://wiki.gentoo.org/wiki/Handbook:X86/Working/Initscripts#Writing_initscripts

**Comment by christianprim** [comment]
Here is a nice converter for systemd-skripts to openrc: http://openrc.run/

It's not perfect, but it gives you an idea.

**Comment by Itxaka** [comment]
This line doesnt work for me:

`apk --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing/ add dracut; exit 0`


```
$ docker run -it --rm alpine
/ # apk --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing/ add dracut; exit 0
fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  dracut (no such package):
    required by: world[dracut]

```

Weird becuase I can see dracut in the list of packages: https://pkgs.alpinelinux.org/packages?name=dracut&branch=edge&repo=&arch=&maintainer=

**Comment by christianprim** [comment]
Strange.... It't worked yesterday on my side... But today it's not in the repository at the given URL. I will check for another repository.

But I think you can make a dracut module without systemd and hence it will work on alpine.

I'm not sure, but you can use hooks in dracut to specify at which point of the boot process your script is executed. So no need for an initsystem in the initramfs stage.

Take the example here:

```
# called by dracut
install() {
    inst_script "$moddir/netroot.sh" "/sbin/netroot"
    inst_simple "$moddir/net-lib.sh" "/lib/net-lib.sh"
    inst_hook pre-udev 50 "$moddir/ifname-genrules.sh"
    inst_hook cmdline 91 "$moddir/dhcp-root.sh"
    inst_multiple ip sed awk grep pgrep tr
    inst_multiple -o arping arping2
    dracut_need_initqueue
}
```
and the docs here: https://github.com/dracutdevs/dracut/blob/master/man/dracut.modules.7.asc

Just an idea to simplify the process.

**Comment by christianprim** [comment]
Or the formatted doc here: https://man7.org/linux/man-pages/man7/dracut.modules.7.html

**Comment by christianprim** [comment]
The dracut package was rebuilt yesterday... I would wait a bit. It will soon reappear.

**Comment by christianprim** [comment]
The build of dracut was ok: https://build.alpinelinux.org/buildlogs/build-edge-x86/community/dracut/dracut-059-r2.log

**Comment by christianprim** [comment]
Now dracut is in community, has left testing stage:

`apk --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community/ add dracut; exit 0`

**Comment by Itxaka** [comment]
> Strange.... It't worked yesterday on my side... But today it's not in the repository at the given URL. I will check for another repository.
> 
> But I think you can make a dracut module without systemd and hence it will work on alpine.
> 
> I'm not sure, but you can use hooks in dracut to specify at which point of the boot process your script is executed. So no need for an initsystem in the initramfs stage.
> 
> Take the example here:
> 
> ```
> # called by dracut
> install() {
>     inst_script "$moddir/netroot.sh" "/sbin/netroot"
>     inst_simple "$moddir/net-lib.sh" "/lib/net-lib.sh"
>     inst_hook pre-udev 50 "$moddir/ifname-genrules.sh"
>     inst_hook cmdline 91 "$moddir/dhcp-root.sh"
>     inst_multiple ip sed awk grep pgrep tr
>     inst_multiple -o arping arping2
>     dracut_need_initqueue
> }
> ```
> 
> and the docs here: [dracutdevs/dracut@`master`/man/dracut.modules.7.asc](https://github.com/dracutdevs/dracut/blob/master/man/dracut.modules.7.asc?rgh-link-date=2023-03-03T09%3A07%3A53Z)
> 
> Just an idea to simplify the process.

This is a great idea to be honest, running it directly without systemd will make it much more easier and currently nothing else on immucore should need systemd....maybe.. :D
