### ISSUE TITLE
🌱 Port dracut modules to standalone binary

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#657]
Background: https://github.com/kairos-io/kairos/issues/347 #163 https://github.com/kairos-io/kairos/issues/653

- Ping @mudler
- Make sure we cover QA e2e tests for it in kairos
- Port current logic to standalone binary that can be re-used outside of dracut

This component is needed to have Kairos booting with UKI - it will be the component that works both with the current layout and with UKI as a hybrid initramfs, and most importantly doesn't depend anymore on dracut+systemd.

WIP/ https://github.com/kairos-io/immucore

**Comment by jimmykarily** [comment]
There is also some background related to UKI that it missing from this story. @mudler will add it to the description (reminder).
