### ISSUE TITLE
Build Kairos appliances - Page refers to kubernetes only

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#672]
This page https://kairos.io/docs/advanced/build/ refers to kubernetes builds with osbuilder. It took me a while to found where the docs for the osbuilder stuff where because the page title is simply "build"

 - Probably link the page from osbuilder repo directly
 - Change the page title to "build on kubernetes" or something similar for ease of reach

**Comment by mudler** [comment]
Closing this in favor of #1053
