### ISSUE TITLE
🌱 Settle on a logging lib for kairos projects

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#682]
**Is your feature request related to a problem? Please describe.**

We need to log stuff in several kairos projects, we cannot just have whoever comes first to chose lib X and then another person choose lib Y as that could lead to integration issues afterwards, ugly logs and so on. Having consistent logging practices and outputs is nice.

**Describe the solution you'd like**

To settle in a lib to use for logging in all projects related to kairos.

**Describe alternatives you've considered**

No logging anything, YOLO

**Additional context**

**Comment by Itxaka** [comment]
I dont care to be honest, logrus works for me and I used it enough to have confidence that I can hack it around to do whatever we need. I hate Klog, I find it very human unfriendly.

Thats all the feedback from my side.

**Comment by mudler** [comment]
Zerolog seems also something getting lot of traction lately too
