### ISSUE TITLE
🐛 Manual install doesnt pick options from config file

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#687]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
When using a config file and doing manual install `kairos-agent manual-install CONFIG` supposedly there is an `options` key in the config that should be passed down to the installer.
Unfortunately this does not work as it uses a different path, so it loads the file and dumps it into `option["cc"]` and there is nothing to merge those options into the config properly.

An example of how its merged during a normal install is in https://github.com/kairos-io/kairos/blob/master/internal/agent/install.go#L85

**To Reproduce**
create config file with options, call `kairos-agent manual-install CONFIG`

**Expected behavior**

Options are respected and passed down

**Logs**

**Additional context**

**Comment by oz123** [comment]
@Itxaka did you mean that we should merge the options sections like in here:

https://github.com/kairos-io/kairos/blob/94175ca992948c13b039d4a863e84a09a61bdb54/internal/agent/install.go#L102

Indeed, it seems that this function `mergeOption` is called a few times before we call when running `Install`:

https://github.com/kairos-io/kairos/blob/94175ca992948c13b039d4a863e84a09a61bdb54/internal/agent/install.go#L237

When running `ManualInstall` we proceed to `RunInstall(options)` without running this merge.

https://github.com/kairos-io/kairos/blob/94175ca992948c13b039d4a863e84a09a61bdb54/internal/agent/install.go#L88

**Comment by Itxaka** [comment]
> @Itxaka did you mean that we should merge the options sections like in here:
> 
> https://github.com/kairos-io/kairos/blob/94175ca992948c13b039d4a863e84a09a61bdb54/internal/agent/install.go#L102
> 
> Indeed, it seems that this function `mergeOption` is called a few times before we call when running `Install`:
> 
> https://github.com/kairos-io/kairos/blob/94175ca992948c13b039d4a863e84a09a61bdb54/internal/agent/install.go#L237
> 
> When running `ManualInstall` we proceed to `RunInstall(options)` without running this merge.
> 
> https://github.com/kairos-io/kairos/blob/94175ca992948c13b039d4a863e84a09a61bdb54/internal/agent/install.go#L88
> 

Yep! Otherwise we lose options due to not merging properly
