### ISSUE TITLE
:bug: kairos.service may start before cos-setup-network

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#696]
When running in a cloud provider specifying a cloud config file (e.g. in openstack) the kairos.server (the installer) may start before the cos-setup-network service is done downloading cloud config files from the provider. In that case, our cloud-config is ignored and the installer continues by showing the QR code as if no cloud-config was provided.

Restarting the `kairos.service` with systemdctl makes it work (because now the cloud-config files are in place).

**Comment by mudler** [comment]
we discussed one of the possible solutions which we agreed on:

the datasource pulling should write a sentinel once it's done, and the kairos-agent installer wait for it. This should fix also https://github.com/kairos-io/kairos/issues/499

**Comment by Itxaka** [comment]
couldn't we make the kairos.service depend on the `cos-setup-network.service`?

`cos-setup-network.service` runs after `network-online.target`and even on a machine with no network that its launched properly.

Even without network, the real service that marks that you have connectivity is `systemctl-networkd-wait-online` IIRC, so we should be able to safely depend on `cos-setup-network.service` in our kairos services so we know that the metadata stuff was properly run by the time we reach the installer.


In fact, we should run our kairos stuff AFTER all the cos-setup-X services as any of those files can potentially be a source of configuration files no? There is nothing in the way of writing a yip file that adds the config in the reconcile stage....

**Comment by mudler** [comment]
> couldn't we make the kairos.service depend on the `cos-setup-network.service`?
> 
> `cos-setup-network.service` runs after `network-online.target`and even on a machine with no network that its launched properly.
> 
> Even without network, the real service that marks that you have connectivity is `systemctl-networkd-wait-online` IIRC, so we should be able to safely depend on `cos-setup-network.service` in our kairos services so we know that the metadata stuff was properly run by the time we reach the installer.
> 
> In fact, we should run our kairos stuff AFTER all the cos-setup-X services as any of those files can potentially be a source of configuration files no? There is nothing in the way of writing a yip file that adds the config in the reconcile stage....

To my knowledge, that should fire only if the node reaches the network-online target, which is the case only if there is an interface up: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

So we can't really make it depend on it, no? otherwise the kairos.service might not trigger at all if there is no interface

**Comment by mudler** [comment]
mmm and with openRC the sentinel approach might be better still, even if not nicer. so it doesn't really depend on waiting the init, but rather we do the waiting

**Comment by Itxaka** [comment]
> > couldn't we make the kairos.service depend on the `cos-setup-network.service`?
> > `cos-setup-network.service` runs after `network-online.target`and even on a machine with no network that its launched properly.
> > Even without network, the real service that marks that you have connectivity is `systemctl-networkd-wait-online` IIRC, so we should be able to safely depend on `cos-setup-network.service` in our kairos services so we know that the metadata stuff was properly run by the time we reach the installer.
> > In fact, we should run our kairos stuff AFTER all the cos-setup-X services as any of those files can potentially be a source of configuration files no? There is nothing in the way of writing a yip file that adds the config in the reconcile stage....
> 
> To my knowledge, that should fire only if the node reaches the network-online target, which is the case only if there is an interface up: [freedesktop.org/wiki/Software/systemd/NetworkTarget](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)
> 
> So we can't really make it depend on it, no? otherwise the kairos.service might not trigger at all if there is no interface

I thougth so, but on my VM with no nics, `network-online` is active and `cos-setup-network` run properly, which shouldn't if `network-online` failed....

I guess `network-online` takes into account if there is no network other than the `lo` device it should still reach the target. It doesnt mean there is connectivity...that is why the other more specific service are there? (`NetworkManager-wait-online.service` and  `systemd-networkd-wait-online.service`)

![image](https://user-images.githubusercontent.com/1447686/214003168-57b41407-6352-41a5-8455-e9868f940908.png)

**Comment by Itxaka** [comment]
> mmm and with openRC the sentinel approach might be better still, even if not nicer. so it doesn't really depend on waiting the init, but rather we do the waiting

ah yes, forgot we have openrc! In that case yes, its better. But the problem still happens if someone writes a yip file that writes the config during the reconcile stage no? installer may have triggered by that time (reconcile comes after network stage) but the installer may be already running.

**Comment by mudler** [comment]
> > mmm and with openRC the sentinel approach might be better still, even if not nicer. so it doesn't really depend on waiting the init, but rather we do the waiting
> 
> ah yes, forgot we have openrc! In that case yes, its better. But the problem still happens if someone writes a yip file that writes the config during the reconcile stage no? installer may have triggered by that time (reconcile comes after network stage) but the installer may be already running.

how that would work? I don't think we need to cover that scenario, we write the sentinel after we pull and we are settled on configs. any other config should come already before that (e.g. via files in the disk, etc) and the agent can still pick it up from the network via `config_url` (but that's part of the `kairos-agent` execution flow)

**Comment by mudler** [comment]
> > > couldn't we make the kairos.service depend on the `cos-setup-network.service`?
> > > `cos-setup-network.service` runs after `network-online.target`and even on a machine with no network that its launched properly.
> > > Even without network, the real service that marks that you have connectivity is `systemctl-networkd-wait-online` IIRC, so we should be able to safely depend on `cos-setup-network.service` in our kairos services so we know that the metadata stuff was properly run by the time we reach the installer.
> > > In fact, we should run our kairos stuff AFTER all the cos-setup-X services as any of those files can potentially be a source of configuration files no? There is nothing in the way of writing a yip file that adds the config in the reconcile stage....
> > 
> > 
> > To my knowledge, that should fire only if the node reaches the network-online target, which is the case only if there is an interface up: [freedesktop.org/wiki/Software/systemd/NetworkTarget](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)
> > So we can't really make it depend on it, no? otherwise the kairos.service might not trigger at all if there is no interface
> 
> I thougth so, but on my VM with no nics, `network-online` is active and `cos-setup-network` run properly, which shouldn't if `network-online` failed....
> 
> I guess `network-online` takes into account if there is no network other than the `lo` device it should still reach the target. It doesnt mean there is connectivity...that is why the other more specific service are there? (`NetworkManager-wait-online.service` and `systemd-networkd-wait-online.service`)
> 
> ![image](https://user-images.githubusercontent.com/1447686/214003168-57b41407-6352-41a5-8455-e9868f940908.png)

this sounds bad, also from systemd docs this sounds quite brittle - there is a `network.target`, a `network-online.target` (which is adviced to be used when interfaces are up and getting an IP) and a *wait-online service. I wonder if this makes sense at all - the whole purpose of waiting for a target is not to try to wait for each of them individually, but instead those should activate the target.
