### ISSUE TITLE
:bug: Kaios fails to boot on v1.4.0-k3sv1.26.0-k3s1

### ISSUE THREAD

**Issue by paynejacob** [kairos-io/kairos#706]
**Kairos version:**
kairos-provider v1.4.0-k3sv1.26.0-k3s1

**CPU architecture, OS, and Version:**
raspberry pi 3 B+

**Describe the bug**
fails to boot

**Comment by mudler** [comment]
I guess we can close this one if this is reproducible with `1.6.1`
