### ISSUE TITLE
consume luet as a binary in the elemental-cli

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#712]
- smaller footprint of bin (less dedups)
- split of concerns
- untied from versions (luet != elemental)

**Comment by Itxaka** [comment]
What is the advantage of doing this? Any points?

I mena, I get we get to drop a lot of code this way but calling other binaries...its kind of tricky,  dont have the same control as using the lib, makes it so we have more pieces to put in the system, while having it as a lib means that we control the whole lifecycle of the install or whatever we doing AND we get to override stuff that we migth not like (like the logging) and easily override other quirks or stuff that we need.
