### ISSUE TITLE
:bug: disable_dht: true leads to nodes not joining p2p network

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#715]
**Kairos version:**

master node:
 cat /etc/os-release 
NAME="kairos-opensuse"
VERSION="v1.4.0-k3sv1.26.0+k3s1"
ID="kairos"
ID_LIKE="kairos-opensuse"
VERSION_ID="v1.4.0-k3sv1.26.0+k3s1"
PRETTY_NAME="kairos-opensuse v1.4.0-k3sv1.26.0+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-opensuse"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse"

worker node:
cat /etc/os-release 
NAME="kairos-opensuse-arm-rpi"
VERSION="v1.4.0-k3sv1.26.0+k3s1"
ID="kairos"
ID_LIKE="kairos-opensuse-arm-rpi"
VERSION_ID="v1.4.0-k3sv1.26.0+k3s1"
PRETTY_NAME="kairos-opensuse-arm-rpi v1.4.0-k3sv1.26.0+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-opensuse-arm-rpi"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse"
**CPU architecture, OS, and Version:**

master:
 uname -a
Linux lp3dnode 5.14.21-150400.24.38-default #1 SMP PREEMPT_DYNAMIC Fri Dec 9 09:29:22 UTC 2022 (e9c5676) x86_64 x86_64 x86_64 GNU/Linux

worker:
uname -a
Linux rpi4node 5.14.21-150400.24.38-default #1 SMP PREEMPT_DYNAMIC Fri Dec 9 09:29:22 UTC 2022 (e9c5676) aarch64 aarch64 aarch64 GNU/Linux

**Describe the bug**

after setting `disable_dht` to true on both nodes, the p2p network was working, but after on more reboot, master and worker nodes where in separate networks and did not join to each other. Removing `disable_dht` and rebooting both nodes leads to the nodes joining the network and the cluster was operational again.

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by mudler** [comment]
@Ognian apologize for the late answer. Can you reproduce with 1.6.1? I didn't have tested with different arches so far, but I don't think that should have an impact here.

Can you also provide the logs of the `kairos-agent` when this happens?

**Comment by Ognian** [comment]
@mudler I upgraded yesterday to 1.6.1 and I'm now using kubevip. the kubevip setup requires disable_dht to be true. So since this works now in my setup (one rpi worker and one x86 master) it is no longer reproducible with 1.6.1.
As long as I was on 1.5.0 and 1.5.1 I did not test with disable_dht and unfortunately I did not have the logs from the 1.4.0 tests when this was a problem... So maybe you can close this issue...

**Comment by mudler** [comment]
cool, glad to hear! 

I'll close it then, if this pops-up again with 1.6.x feel free to re-create one!
