### ISSUE TITLE
:bug: WebUI syntax highlight is broken

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#732]
**Kairos version:**
master

Seems the CodeMirror syntax highlighter is broken:
![Screenshot from 2023-01-25 23-47-46](https://user-images.githubusercontent.com/2420543/214709291-673ef540-51bc-44bf-b18f-1bac6b95c482.png)
![Screenshot from 2023-01-25 23-48-32](https://user-images.githubusercontent.com/2420543/214709338-8a919dbd-f6f1-4c66-becf-6ab604a75831.png)

possibly caused by #610 ? cc @mauromorales

**Comment by mauromorales** [comment]
strange, I looked into it and had no issues, will have a look
