### ISSUE TITLE
:bug: Reset fails when encryption is enabled

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#733]
**Kairos version:**
[maser build](https://github.com/kairos-io/kairos/commit/2ada227c63ad1501173469ed52bb540c54fa64dc)

**CPU architecture, OS, and Version:**

**Describe the bug**
When trying to reset the machine, elemental can't find anymore `COS_PERSISTENT` (as it is encrypted), so the reset process skips deleting the `COS_PERSISTENT` partition

**To Reproduce**
Enable encryption, try to reset the machine

**Expected behavior**
The `COS_PERSISTENT` partition should be removed and recreated as usual. the `kcrypt` hook kicks in afterward to encrypt the partition with the passphrase.

**Logs**
![VirtualBox_test-encryption_26_01_2023_09_47_53](https://user-images.githubusercontent.com/2420543/214793793-96874ab6-1c68-483a-9619-5f0d17cddc36.png)

**Comment by mudler** [comment]
@paynejacob any news? is there anything blocking I can help with?

**Comment by paynejacob** [comment]
I have a working solution however it will require a few prs to complete.

The root of this problem was how elemental was listing block devices during reset.  It was not including mapper devices when listing volumes.  This meant it was trying to reset the encrypted partition it's self rather than the unencrypted mapper device.  To fix this I updated how the elemental cli looks up block devices to included mapped devices.  This introduced another issue where some distros did not boot with the latest version of the elemental cli.  This was because they were looking for configuration in `/boot/grub` instead of  `/boot/grub2/`.  I was able to fix this in kairos by adding a redirect to the grub2 directory.

PRS:

- https://github.com/rancher/elemental-cli/pull/433  This elemental pr will fix the mapping issue.
- https://github.com/kairos-io/kairos/pull/937 This kairos pr will fix the grub issue with newer versions of elemental cli.
- PENDING once elemental is released with the above fix we will need to add it to the packages repo and update kairos to use the latest version of elemental.

**Comment by Itxaka** [comment]
https://github.com/kairos-io/elemental-cli/pull/41

**Comment by mudler** [comment]
As discussed in the calls, this is not a blocker for `1.6.0`: 

a temporary workaround until we upstream a patch to ghw could be to have an `after-reset` stage hook which cleans up the contents of `/usr/local/*`

**Comment by Itxaka** [comment]
blergh, not an easy way to add this to ghw. Most of the methods toe xtract the disk info depend on udev but devicemapper is just a link to a different disk :/

probably a workaround is much nicer for now at least

**Comment by Itxaka** [comment]
If that gets merged we still need to bump the package in the kairo-io/packages and bump the repository in kairos, on the framework-profile.yaml with the new repo generated by the package merge. A bit convoluted.

elemental gets updated -> kairos packages bumps the version of elemental -> generates a new repo with those packages -> kairos is updated to use that repo

**Comment by Itxaka** [comment]
https://github.com/kairos-io/elemental-cli/pull/43 to workaround elemental
https://github.com/kairos-io/packages/pull/126 to bump kairos packages to include the fix

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kairos/pull/948/checks for elemental bump of packages

**Comment by Itxaka** [comment]
* Using artifacts(kairos-opensuse-leap.iso) from master commit da68d7b19fbb42bf9b49eee8b8c5f64240ae3b98: https://github.com/kairos-io/kairos/actions/runs/4250367881 :heavy_check_mark: 
 * Enable encryption for COS_PERSISTENT :heavy_check_mark: 
```
#node-config

install:
  auto: true
  reboot: true
  device: /dev/vda
  encrypted_partitions:
    - COS_PERSISTENT


stages:
   initramfs:
     - name: "Set user and password"
       users:
        kairos:
          passwd: "kairos"
       hostname: kairos-{{ trunc 4 .Random }}
```
 * Boot and let it install :heavy_check_mark: 
 * Create some files in the COS_RECOVERY partition :heavy_check_mark: 
 * Reboot into recovery :heavy_check_mark: 
 * Run `kairos-agent reset` :heavy_check_mark: 
```
WARNING: jsonschema: '' does not validate with file:///root/schema.json#/required: missing properties: 'users'
INFO[2023-02-23T10:03:22Z] Starting elemental version 0.20230222.1+kairos 
INFO[2023-02-23T10:03:22Z] Reset called                                 
INFO[2023-02-23T10:03:22Z] Unmounting disk partitions                   
INFO[2023-02-23T10:03:22Z] Formatting 'state' partition                 
INFO[2023-02-23T10:03:22Z] Formatting 'persistent' partition            
INFO[2023-02-23T10:03:22Z] Mounting disk partitions                     
INFO[2023-02-23T10:03:22Z] Running before-reset hook                    
INFO[2023-02-23T10:03:22Z] Copying /run/initramfs/cos-state/cOS/recovery.img source... 
INFO[2023-02-23T10:03:23Z] Finished copying /run/initramfs/cos-state/cOS/recovery.img into /run/cos/state/cOS/active.img 
INFO[2023-02-23T10:03:24Z] Installing GRUB..                            
INFO[2023-02-23T10:03:25Z] Grub install to device /dev/vda complete     
INFO[2023-02-23T10:03:25Z] Using grub config dir /run/cos/active/etc/cos/grub.cfg 
INFO[2023-02-23T10:03:25Z] Copying grub contents from /run/cos/active/etc/cos/grub.cfg to /run/cos/state/grub2/grub.cfg 
INFO[2023-02-23T10:03:26Z] Running after-reset-chroot hook              
INFO[2023-02-23T10:03:26Z] Setting default grub entry to Kairos         
INFO[2023-02-23T10:03:26Z] Copying /run/cos/state/cOS/active.img source... 
INFO[2023-02-23T10:03:27Z] Finished copying /run/cos/state/cOS/active.img into /run/cos/state/cOS/passive.img 
INFO[2023-02-23T10:03:28Z] Running after-reset hook                     
INFO[2023-02-23T10:03:28Z] Unmounting disk partitions                   
could not encrypt partition: not found
exit status 1
```
 * Check that the message `no Persistion partition found` does not appear :heavy_check_mark: 
 * Check that the message `Formatting 'persistent' partition` appears :heavy_check_mark: 
 * Reboot to active :heavy_check_mark: 
 * Check files are no there any longer, so persistent was formatted correctly :heavy_check_mark:

**Comment by Itxaka** [comment]
The only thing I can see its the message `could not encrypt partition: not found` but that also happened originally so maybe it requires a different issue. 

Marking this as closed.
