### ISSUE TITLE
:bug: CI: opensuse flavor fails in provider-kairos

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#743]
**Kairos version:**
1.5.0

https://github.com/kairos-io/provider-kairos/actions/runs/4019022358/jobs/6905361808

Since the split from tumbleweed to leap, seems the release pipelines were left behind

**Comment by paynejacob** [comment]
@Itxaka I think you already resolved this, ill transfer it to you to confirm.

**Comment by Itxaka** [comment]
Thanks @paynejacob ! Indeed this was fixed by https://github.com/kairos-io/provider-kairos/pull/204
