### ISSUE TITLE
kairos-agent does not work with a URL

### ISSUE THREAD

**Issue by sdwilsh** [kairos-io/kairos#764]
**Kairos version:**
(there might be some typos here; the vmware remote console doesn't let me copy text, so I had to type this manually)
```
NAME="kairos-ubuntu-22-lts"
VERSION="v1.5.1-k3sv1.26.1+k3s1"
ID="kairos"
ID_LIKE="Kairos-ubuntu-22-lts"
VERSION_ID="v1.5.1-k3sv1.26.1+k3s1"
PRETTY_NAME="kairos-ubuntu-22-lts v1.5.1-k3sv1.26.1+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-ubuntu-22-lts"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse-leap"
```

**CPU architecture, OS, and Version:**
```
Linux localhost.localdomain 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**
The program exists and outputs:
```
open http://10.10.0.20:9000/config.yml: no such file or directory
```

**To Reproduce**
1) On a server that the installer can talk to, write a config file and then host it with `python3 -m http.server 9000`
2) On the machine with the installer, run `sudo kairos-agent manual-install --reboot --device "auto" http://[ip addr of other machine]:9000/config.yml`

**Expected behavior**
As the help indicates, the installer will grab the config from the URL, and install it.

**Comment by sdwilsh** [comment]
My workaround is to just `curl -o config.yml http://10.10.0.20:9000/config.yml` and then pass the file instead.  Given that works, I know the URL is also correct.

**Comment by mudler** [comment]
thanks for the feedback @sdwilsh , this looks indeed a bug

**Comment by paynejacob** [comment]
I am able to reproduce this with the provider image as well as the core images.
