### ISSUE TITLE
🤖 CI: push `.img` files for arm in specific images

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#770]
Currently the images for ARM are pushed in the same image repository where the images used for upgrades and building artifacts are https://quay.io/repository/kairos/kairos-opensuse-arm-rpi?tab=tags .

This ticket is to push them in a separate repository:
- [x] Create a new repo for img files for each ARM flavor
- [x] Adapt CI
- [x] Adapt docs

https://kairos.io/docs/reference/image_matrix/#image-flavors

**Comment by mauromorales** [comment]
@mudler do you have a personal preference for the name? otherwise I was thinking to go with `kairos-opensuse-arm-rpi` for the upgrades and building and `kairos-opensuse-arm-rpi-img` for the image

**Comment by mudler** [comment]
sounds good here 👍

**Comment by mauromorales** [comment]
new repos:

- https://quay.io/repository/kairos/core-opensuse-leap-arm-rpi-img
- https://quay.io/repository/kairos/core-alpine-arm-rpi-img
- https://quay.io/repository/kairos/kairos-opensuse-leap-arm-rpi-img
- https://quay.io/repository/kairos/core-opensuse-tumbleweed-arm-rpi-img
- https://quay.io/repository/kairos/kairos-alpine-arm-rpi-img
- https://quay.io/repository/kairos/kairos-opensuse-tumbleweed-arm-rpi-img
- https://quay.io/repository/kairos/core-ubuntu-arm-rpi-img
- https://quay.io/repository/kairos/kairos-ubuntu-arm-rpi-img
- https://quay.io/repository/kairos/core-ubuntu-20-lts-arm-rpi-img
- https://quay.io/repository/kairos/kairos-ubuntu-20-lts-arm-rpi-img
- https://quay.io/repository/kairos/core-ubuntu-22-lts-arm-rpi-img
- https://quay.io/repository/kairos/kairos-ubuntu-22-lts-arm-rpi-img

**Comment by mauromorales** [comment]
@mudler while working on this, I found repos with other providers like https://quay.io/repository/kairos/core-opensuse-arm-rpi-rke2?tab=info . Would it be ok to remove those since they are empty?

**Comment by mudler** [comment]
I'm not sure if @venkatnsrinivasan was going to set CI for those, cc @venkatnsrinivasan ?

**Comment by venkatnsrinivasan** [comment]
yeah once we have the arm images issues resolved we were going to add CI to the repos. But specifically the core-opensuse-arm-rpi-xxx can be removed since we have images for leap and tumbleweed specifically and will likely use the same naming convention to add the opensuse flavore ?

**Comment by mauromorales** [comment]
I think it might be worth keeping those old repos for anyone using the old images ... but it's also confusing so I'm not strongly opinionated about it.

**Comment by jimmykarily** [comment]
All merged, closing.
