### ISSUE TITLE
🏗  infra dogfooding

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#771]
A  kairos cluster for the team to maintain, keep up to date and use for services (on need)

Use cases:

- Provide public accessible services ( e.g. provide ARM images to download via http )
- Pairing sessions
- Shared IDE (gitpod, e.g.)
- KubeVirt for Github actions workers
- Good resource and testing for blog posts!
 
From the moment is up, it should be part of our release process to test it in the infra (up to the interrupt)

## Acceptance criteria

- [x] There is a cluster (!)
- [x] Documentation how to access it, maintain it
- [x] Services:
  - [x] GH action on Kubevirt
  - [ ] Slack bot (@Interrupt + @DailyBot, ask @mudler)
  - [x] containerbay for OCI-based artifacts (e.g. ARM)
  - [ ] DNS Settings
  - [ ] ARM Hybrid Kubernetes workers for testing (?)
  - [ ] [Jitsi for our meetings](https://github.com/jitsi-contrib/jitsi-helm)

**Comment by mudler** [comment]
@jimmykarily I think we just need to setup fluxcd as a missing piece?

**Comment by jimmykarily** [comment]
Installed fluxcd on the "services" cluster and moved containerbay to a kustomization. It will now install automatically when a cluster is bootstrapped as described on the README.

TODO:
- Install fluxcd on the "CI" cluster too and migrate the GA workers to a kustomization. This might be tricky since it needs a fresh token (they expire after some time).

**Comment by jimmykarily** [comment]
> Installed fluxcd on the "services" cluster and moved containerbay to a kustomization. It will now install automatically when a cluster is bootstrapped as described on the README.
> 
> TODO:
> 
>     * Install fluxcd on the "CI" cluster too and migrate the GA workers to a kustomization. This might be tricky since it needs a fresh token (they expire after some time).

Deployed org level runners following this: https://github.com/actions/actions-runner-controller/blob/master/docs/choosing-runner-destination.md#adding-runners-to-an-organization

We now have 5 runners for the whole kairos-io organization. We can probable scale it up a bit but let's see first how it behaves with 5.

**Comment by jimmykarily** [comment]
On kcrypt-challenger we are using the self hosted runners for the e2e tests. The build time dropped to 50%:

https://github.com/kairos-io/kcrypt-challenger/actions/runs/4222474847

![image](https://user-images.githubusercontent.com/2794419/220111791-98189580-2985-4d1b-9b55-53755ca8d08b.png)

**Comment by jimmykarily** [comment]
We have 2 clusters, one for various service currently running [containerbay](https://github.com/Containerbay/containerbay) the other one running CI runners. I will close this issue now and we can keep adding workloads whenever we need them. The fluxcd layout and docs are in place.
