### ISSUE TITLE
:bug: CI is failing waiting for userdata to be loaded

### ISSUE THREAD

**Issue by paynejacob** [kairos-io/kairos#781]
https://github.com/kairos-io/kairos/actions/runs/4027327620/jobs/6950379445

**Comment by mudler** [comment]
just cross-posting from the chat:

Might be that `/oem` is not clean now that we wait, and elemental complains about mounting `/oem` after partitioning - as it is not clean anymore?

**Comment by mudler** [comment]
switching prio to high as blocks all PRs from being automatically merged on approvals

**Comment by mudler** [comment]
just for history reference, started since https://github.com/kairos-io/kairos/pull/742
