### ISSUE TITLE
Add a Dockerfiles linter

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#788]
**Is your feature request related to a problem? Please describe.**

Keeping Dockerfiles is tricky, packages get duplicated and unsorted, plus other issues. Using a linter for it allows us to let the CI keep them clean

**Describe the solution you'd like**

Use a linter like https://hadolint.github.io/hadolint/

**Describe alternatives you've considered**

**Additional context**

**Comment by sdwilsh** [comment]
Ideally, https://github.com/earthly/earthly/issues/2324 would allow us to add it to our Earthly lints we are already running.

Would adding the GitHub action be sufficient (although not ideal) here?  If yes, we'd want to use the [non-official one that allows shell expansion](https://github.com/marketplace/actions/hadolint-github-action) to avoid listing out all of the Docker files.
