### ISSUE TITLE
:penguin: Generic arm64 images

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#790]
**Is your feature request related to a problem? Please describe.**
We do have HW flavored images, however, there are cases when generic arm64 images, even with ISOs are a good fit too: that could work both for VMs on Macs, or HW generic arm hardware which support is streamlined

**Describe the solution you'd like**
Generic arm64 flavors, generating ISOs and such

**Describe alternatives you've considered**
Keep only dedicated images

**Comment by mudler** [comment]
Missing still: releases iso, and provider-kairos changes too

**Comment by mudler** [comment]
After our planning, we decided to:

- [ ] have only one flavor (opensuse-leap-arm-generic) published as part of the kairos-core release workflow, container images included
- [ ] have only one flavor for provider-kairos  and a k3s version only for testing

**Comment by Itxaka** [comment]
https://github.com/kairos-io/provider-kairos/pull/344 for provider-kairos arm64 images

**Comment by Itxaka** [comment]
provider-kairos OCI artifacts are now pushed to https://quay.io/repository/kairos/kairos-opensuse-leap-arm-generic
ISOs are also uploaded as artifacts

Both things are done on master pushes only.

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kairos/pull/1315
https://github.com/kairos-io/provider-kairos/pull/346

**Comment by Itxaka** [comment]
This has been merged, all completed. When the new release hits, we should see those artifacts as part of the release, plus images are already in their repos.
