### ISSUE TITLE
✨ improve RunBundles to support luet unpack images present on the filesystem

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#799]
**Is your feature request related to a problem? Please describe.**
bundles.RunBundles does not support reading image tar files from the filesystem and unpacking it into target location.

**Describe the solution you'd like**
containerInstaller support for --local and image path to be passed with file:// prefix.
So that luet can figure out that the image reference is a tar file. [here](https://github.com/mudler/luet/issues/317)

**Additional context**
This would remove the dependency of having to run docker daemon for unpacking container images present on the file sytem.

**Comment by santhoshdaivajna** [comment]
@mauromorales don't think #798 addresses this one.

**Comment by mauromorales** [comment]
@santhoshdaivajna no, it doesn't.

Even if the package doesn't require the container runtime, some of these packages do require the runtime to execute, right? Sorry if it's a silly question, I'm still too new to Luet.

**Comment by santhoshdaivajna** [comment]
yes in some cases. In airgap scenario, there might be images copied to filesystem and contain runtime might not be available  in those environments. This PR is to address that specific use case.
