### ISSUE TITLE
Encrypting User Data with Kairos - missing kubectl command(s)

### ISSUE THREAD

**Issue by antongisli** [kairos-io/kairos#839]
the document mentions some kubectl commands are needed to add the TPM hash, but I couldn't find the kubectl command or examples.

**Comment by jimmykarily** [comment]
I guess you mean here: https://kairos.io/docs/advanced/partition_encryption/#register-a-node

There is a sealedvolume resource that you have to apply right below but I agress, we can make it more clear.
