### ISSUE TITLE
load the images to any CRI on start from the local filesystem in providers

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#858]
**Is your feature request related to a problem? Please describe.**

Preload the images into CRI from local file system in the kairos providers.

**Describe the solution you'd like**

In the providers conditionally check the path provided for archive files and load into containerd or any CRI on start.

**Describe alternatives you've considered**

**Additional context**

* to preload the CRI with archived (tar) images from the filesystem.

**Comment by jimmykarily** [comment]
@santhoshdaivajna is this done?

**Comment by santhoshdaivajna** [comment]
yes!
