### ISSUE TITLE
Creating missing repos for image push by providers

### ISSUE THREAD

**Issue by rishi-anand** [kairos-io/kairos#864]
**Is your feature request related to a problem? Please describe.**

In kairos 1.5.0, opensuse repo is changed to -leap and -tumbleweed . In providers, we are bumping up kairos version to 1.5.0 and opensuse image to opensuse-leap and I have noticed that repos `core-opensuse-leap-k3s`, `core-opensuse-leap-rke2` and `core-opensuse-leap-kubeadm` aren’t there as of now and release build of providers will fail.

**Describe the solution you'd like**

Repos should be present so that provider images can be pushed.

**Describe alternatives you've considered**

**Additional context**

**Comment by mudler** [comment]
done :+1:
