### ISSUE TITLE
Build UKI's with osbuilder

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#870]
To stay consistent with [the plan we have for "factory"](https://github.com/kairos-io/kairos/issues/1633#issuecomment-1827262555) we should implement this in enki and use enki in our pipelines to produce the UKI files.

- [x] #2170
- [x] #2174
- [x] #2171
- [x] #2175
- [x] #2176

**Comment by jimmykarily** [comment]
WIP branch: https://github.com/kairos-io/enki/tree/870-build-uki

**Comment by mudler** [comment]
we need also docs on how to generate keys, ISO and signed EFI files (similarly to Talos docs).

**Comment by mauromorales** [comment]
@Itxaka regarding this item:

> check about /usr/lib/systemd/boot/efi/linuxx64.efi.stub and /usr/lib/systemd/boot/efi/systemd-bootx64.efi who should generate these files on other systems than fedora? in the meantime add them to the checkDeps

If I understand correctly, these files exist if the `systemd-boot` package is installed. So I guess we can trust they will always be in the right dir.

Will we ever need an arm version? probably not needed now but just wondering if we need to specifically check for the file or at least just validate that thers an efi and an efi.sub file under this location

**Comment by Itxaka** [comment]
> @Itxaka regarding this item:
> 
> > check about /usr/lib/systemd/boot/efi/linuxx64.efi.stub and /usr/lib/systemd/boot/efi/systemd-bootx64.efi who should generate these files on other systems than fedora? in the meantime add them to the checkDeps
> 
> If I understand correctly, these files exist if the `systemd-boot` package is installed. So I guess we can trust they will always be in the right dir.
> 
> Will we ever need an arm version? probably not needed now but just wondering if we need to specifically check for the file or at least just validate that thers an efi and an efi.sub file under this location

Yep to the first, we can assume they will be there always I think.

For the second question.... I don't know. Probably yeah we better make sure we can build arm64 ukia fron the start. We can probably leverage the arch value and add an arch flag to cross build them

**Comment by mauromorales** [comment]
thanks for the quick reply and my bad I just see you already made a comment in the original PR about this

**Comment by mudler** [comment]
Closing this issue as it is complete
