### ISSUE TITLE
:seedling: Bootmanager for UKI

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#871]
Options to evaluate, considering static measured boot support in the picture (each one of those have pro/cons):
 UKI = systemd-stub + kernel +initrd

- Native EFI + UKI
- systemd-boot + UKI
- GRUB2 + UKI
- ... (?)

Motivations
  - is it easy measurable?
    -  systemd-boot + UKI looks like

**Comment by Itxaka** [comment]
Some more context:

 UKI can bee booted directly from the UEFI interface, after all its an EFI binary. But as soon as you do that, there is no version management, nor boot assesmentet, nor visibility on what you are booting unless you want to enter into the UEFI and select your EFI binary from there directly.

Having a bootloader in front brings a host of improvements to this process. Easy way of seeing your choices, boot assesment in some cases (systemd-boot), automatic fallback Active->Passive-Recovery (which is also possible with UEFI directly but its not as clear, as EFI logging is not that good)


Another point to check, if we use a bootloader to boot the UKI, do we need to bundle systemd-stub in the UKI image?? I guess so, but maybe we dont and its one piece less.

**Comment by mudler** [comment]
We have evaluated the solutions, with having in mind the following criteria : 

- Lifecycle ( Upgrade/reset/install actions)
- Boot measurement
- Boot assessment
- Maintainability (code base, etc.)

Taking into consideration, that we have to still develop the UKI upgrade/reset/install mode into the lifecycle management portion of our stack.

|                                    | Having a boot manager in front  (systemd-boot/GRUB2)                               | NOT Having a boot manager in front    (native EFI)                           |
|------------------------------------|----------------------------------------------------------------|------------------------------------------------------------------|
| **Lifecycle ( Upgrade/reset/install actions)** | Slightly more complex as it has to consider the boot manager efi file. Need to update efi file to avoid invalidating boot measurement hashes. (BAD) | Simple, as it has to manage only one file. Need to manage EFI entries of the shell manually from the running OS. (MEH) |
| **Boot measurement**                        | "Slightly" more complex as it has to take into account of an additional file. (MEH)                                     | Simple, as it comes for "free" with UKI, and it's just one file. (GOOD)                                    |
| **Boot assessment**                        | Assessment capabilities remain untouched. Can port the current GRUB logic to systemd-boot or simplify the logics with systemd-boot. (GOOD) | Lose current boot assessment strategies tied with GRUB and kernel panics. Can assess boot during early init stages to check if booted or not and react accordingly. (MEH) |
| **Maintainability (code base, etc.)**     | Changes required on lifecycle management and additional steps for boot measurement. (BAD, also for security)                                  | Very simple, as it is one file. Everything related to creating, managing, and debugging becomes extremely simple. (GOOD)  |


We decided that we are going to try with Native EFI, also because, whatever we build around it, it's easy to extend to a boot manager later if we go back at this.
