### ISSUE TITLE
:book: Demo about p2p

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#878]
Request from slack:

> Could we please get a demo of the p2p functionality, specifically about whether it would help with ETCD not getting in trouble when DHCP gives a node a new IP address?

This is about showing a deployment HA, or single-master with static, fixed IPs assigned by the VPN

## Acceptance criteria

- [x] Use [AuroraBoot](https://kairos.io/docs/reference/auroraboot/) to show how to do that on multiple-machines (netboot is fine, manual steps can be given too)
- [x] Use a HA, or a single-master deployment model. See also https://kairos.io/docs/installation/p2p/
- [x] Make a video to embed in our docs
- [x] Make sure to highlight that the VirtualIP's created by the VPN are static, but nodes can change the underlying IP without any issue (`etcd` is bound to the vpn for communicating within the cluster)
- [x] Enhance related docs pages with the outcome of this card

**Comment by mudler** [comment]
cc @antongisli

**Comment by mudler** [comment]
The video has been recorded, I'm going to update the docs with what we have discussed about and with the new diagrams.

I'm thinking also could cover also #752.  Let's see how it goes.

**Comment by antongisli** [comment]
where can one find the video? :)

**Comment by mudler** [comment]
We are still cutting it and preparing it for uploading, it will be available afterwards in our documentation, for the time being we updated our docs with the content of it: 

- Documentation: https://kairos.io/docs/architecture/network/
- Demo outline: https://kairos.io/docs/examples/p2p_e2e/

**Comment by mudler** [comment]
Moving to under review, as we are waiting from our side

**Comment by mudler** [comment]
This is done

**Comment by antongisli** [comment]
thx guys awesome work!
