### ISSUE TITLE
:seedling: Support runtime registry authentication for updates

### ISSUE THREAD

**Issue by shoop** [kairos-io/kairos#932]
**Is your feature request related to a problem? Please describe.**
I'm currently evaluating Kairos and I pushed a customized OS image to a private registry. However currently there is no way for me to specify registry credentials when trying to run `kairos-agent upgrade --image=...`.

**Describe the solution you'd like**
Some configuration location to specify registry credentials. For k3s-based images this can probably be integrated with secrets management, however my use case requires core images without k3s hence also an alternative secrets location.

**Describe alternatives you've considered**
Not sure there are any, let me know.

**Additional context**
N/A

**Comment by mudler** [comment]
Great point, thanks @shoop for filing the issue. 

Currently this can be workarounded when upgrading manually with two steps:

1. `elemental pull-image ...`
2. `elemental upgrade --system.uri dir:...`

Nevertheless, the agent should expose a nicer way for this, and we should document how this works in Kubernetes

**Comment by jmaerki** [comment]
> Great point, thanks @shoop for filing the issue.
> 
> Currently this can be workarounded when upgrading manually with two steps, similarly can be adapted for installations:
> 
>     1. `elemental pull-image ...`
> 
>     2. `elemental upgrade --system.uri dir:...`
> 
> 
> Nevertheless, the agent should expose a nicer way for this, and we should document how this works in Kubernetes

That worked for me, thanks. Some more details for those not familiar with `elemental`:

```
mkdir tmp
sudo elemental pull-image --auth-server-address <registry-host> --auth-username <user> --auth-password <pass> \
  <registry-host>/kairos/kairos-ubuntu-22-lts:v1.6.1-k3sv1.24.10-k3s1-extended tmp/kairos.img
sudo elemental upgrade --system.uri dir:/home/kairos/tmp/kairos.img/
```

...then reboot.

**Comment by mudler** [comment]
@Itxaka I guess this needs still to be exposed in the upgrade command of the agent?

**Comment by Itxaka** [comment]
Yes. I hate how I cant link from one PR to an issue without github closing it :/

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kairos/pull/1179 adds the correct flags into the upgrade command so they will be passed to elemental.

**Comment by Itxaka** [comment]
We still need a more decent way of passing this flags, maybe use env vars so they are not exposed in the command directly, but that would requires changes to the agent and elemental at the same time.

Auth stuff need to be reworked fully
