### ISSUE TITLE
📖  Customize generated ISO cmdline with `AuroraBoot`

### ISSUE THREAD

**Issue by areitz86** [kairos-io/kairos#938]
**Is your feature request related to a problem? Please describe.**
Kairos by default uses console=ttyS0. For many systems you need to adapt this (e.g. console=ttyS0,115200n8 for a lot of serial terminals that have the chip embedded, so that you can plugin via usb). It would be nice to be able to adapt this for both, iso files created (so I can follow an automated install for example) and for the containers (so that I can see the bootup on an installed system). Another possible example is the panic parameter, that is highly volatile in embedded environments.

**Describe the solution you'd like**
I would like to be able to give own grub parameters that will be stored in the iso when creating a custom iso with aurora.

**Describe alternatives you've considered**
Patched it manually, works. But I guess I'm not alone with this.

**Comment by mudler** [comment]
That's a great idea, this ideally should be part of `AuroraBoot`. Thanks @areitz86 !

**Comment by mudler** [comment]
It is all about documentation now
