### ISSUE TITLE
How to get the debian cloudImage working

### ISSUE THREAD

**Issue by nano2007** [kairos-io/kairos#955]
### Discussed in https://github.com/kairos-io/kairos/discussions/954

<div type='discussions-op-text'>

<sup>Originally posted by **nano2007** February 24, 2023</sup>
I am trying to follow the documentation to create a debian based cloud image. The yaml file for creating the osartifact manifest is:

[kairos-debian.yaml.txt](https://github.com/kairos-io/kairos/files/10821089/kairos-debian.yaml.txt)

I then create a VM in a KVM box by importing the created raw disk image. Here are the boot logs:

[kairos-debian-boot.log](https://github.com/kairos-io/kairos/files/10821077/kairos-debian-boot.log)

After the VM boots, I do not see an installation or reboot happening.

The same config file works for the opensuse:latest image (where I can see the installation and reboot and the COS_STATE and COS_PERSISTENT partitions exist after the reboot).

Any help is greatly appreciated. Thank you !

</div>

**Comment by nano2007** [comment]
Same problem seen with ubuntu:latest too.

**Comment by mudler** [comment]
Hey @nano2007 :wave: we did released `1.6.0` that had bunch of fixes, some regarding debian especially. Is the issue persisting? I can't notice nothing wrong in your setup for now

**Comment by nano2007** [comment]
> Hey @nano2007 👋 thanks for bringing this up!
> 
> we did released `1.6.0` that had bunch of fixes, some regarding debian especially. Is the issue persisting? I can't notice nothing wrong in your setup for now

I did try the 1.6.1 release and this is fixed. Thanks @mudler :)

There are some problems I am facing though (not all of them related to cloudImages):

- The machine gets an IP address from via dhcp, but there is no /etc/resolv.conf and hence all name resolutions fail. If I do a "dhcpclient <iface>" then the /etc/resolv.conf file gets created.
- I am trying to do some customisation of the image , but I am not able to figure out what lifecycle-events are applicable for a cloudImage creation.
- Also does auroraboot support creation of cloudImages? I do not see an option for this in the docs.

**Comment by mudler** [comment]
> > Hey @nano2007 wave thanks for bringing this up!
> > we did released `1.6.0` that had bunch of fixes, some regarding debian especially. Is the issue persisting? I can't notice nothing wrong in your setup for now
> 
> I did try the 1.6.1 release and this is fixed. Thanks @mudler :)

Awesome! glad to hear! Can we close this issue right?

> 
> There are some problems I am facing though (not all of them related to cloudImages):
> 
>     * The machine gets an IP address from dhcp, but there is no /etc/resolv.conf and hence all name resolutions fail. If I do a "dhcpclient " then the /etc/resolv.conf file gets created.

Sounds like a bug to me

> 
>     * I am trying to do some customisation of the image , but I am not able to figure out what lifecycle-events are applicable for a cloudImage creation.

Can you expand in a thread? I'd be happy to help, but I need a little bit of more context

> 
>     * Also does auroraboot support creation of cloudImages? I do not see an option for this in the docs.

At the moment it doesn't, please file up a ticket for it so we will extend it :) 


Could you file up separate bugs/discussions so we can tackle them in our sprints? thank you!

**Comment by nano2007** [comment]
resolved by release 1.6.1.

For the other problems I am seeing I will start new discussion threads/bugs.

Thanks!
