### ISSUE TITLE
:bug: :hedgehog: Run initramfs stage from immucore

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#992]
**Kairos version:**
master

**CPU architecture, OS, and Version:**

**Describe the bug**
Immucore should run the initramfs stage. Should be the last step in immucore, but there may be some issues with it.

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by mudler** [comment]
this is also relevant for #653

**Comment by mudler** [comment]
Also needed for UKI - there is no initramfs stage after switch_root

**Comment by Itxaka** [comment]
Doesnt look feasible to do on non UKI paths.

initramfs is run at the end, just before the switch_root, and run inside the /sysroot with a chrooted env.
This works because its done as an independent service that can trigger much later in the init process.
Meanwhile immucore runs pretty early in the init process to setup the whole thing. 
This means that some things may not be ready at the time immucore can run initramfs stage as other services havent run.

Also big problem, with CD booting, the stages are also run as they are independent services that dont require immutable-rootfs. But currently on immucore we dont run anything during cd boot.

We could run the initramfs stage during CD, but nothing will be mounted at that time, so it will fail.

Also adding a bug as rootfs should be run during CD boot as its done now.


An alternative would be to do the cdrom mounting ourselves, but that probably collides with whatever dmsquash-live dracut module is doing to automount the CD, so it means a lot of work probably. Our dracut module could disable the dmsquash module but...yikes.

**Comment by Itxaka** [comment]
This is done as master immucore :D
