### ISSUE TITLE
:seedling: Add LVM activation support for OEM and recovery partitions for ARM images

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/kairos#997]
**Is your feature request related to a problem? Please describe.**
Currently ARM images have no OEM partition. As part of this pull request , support for LVM based partitions was add to the arm image builder tools - https://github.com/kairos-io/osbuilder/pull/25 .  
Presently LVM partitions for OEM and recovery are not activated at boot time to take effect.  Need some enhancements to get these picked up.
**Describe the solution you'd like**
Activate LVM partitions on boot to mount OEM partitions. Also boot from LVM into recovery mode.

see #622

**Comment by Itxaka** [comment]
@venkatnsrinivasan Is there any way I can easily test this? Do I need to generate raw images for rpi or something? Or is this possible in a normal install with an ISO?

**Comment by venkatnsrinivasan** [comment]
I only made changes to creating the raw rpi images script so for now you need to generate raw images using the build-arm-image.sh in osbuilder. I used UTM on mac /rpi to test. Another option could be to do  manual install using an iso and before rebooting convert the COS_OEM and COS_RECOVERY to LVM. I did that initially.

**Comment by mudler** [comment]
we have some bits describing how to test LVM on amd64 here: https://github.com/kairos-io/infra-as-code

**Comment by Itxaka** [comment]
I been testing this with the following cloud-config extra steps:

```
stages:
  after-install:
    - name: "Set LVM"
      commands:
        - |
          umount /dev/vda5
          pvcreate /dev/vda5 -f
          pvcreate /dev/vdb
          vgcreate PersistentLVM /dev/vda5 /dev/vdb
          lvcreate -n Persistent -l 100%FREE PersistentLVM
          mkfs.ext4 -L COS_PERSISTENT /dev/mapper/PersistentLVM-Persistent
```

**Comment by Itxaka** [comment]
incredibly enough, this works out of the box due to dracut-initqueue mounting the lvm module and activating it by itself.

But in the case of COS_OEM, this does not trigger properly, probably a race condition between immucore trying to mount it and dracut enabling the module

```
[    6.762075] immucore[890]: <nil> ERR error="no such device" options=["rw","suid","dev","exec","async"] type= what=/dev/disk/by-label/COS_OEM where=/sysroot/oem
```

**Comment by Itxaka** [comment]
Seems like indeed, immucore should run `lvm vgchange -ay` at the start of the DAG so anything on LVM is activated and ready to be used

**Comment by Itxaka** [comment]
```
[   11.011233] immucore[863]: <nil> ERR work/pkg/mount/state.go:167 > error="no such device" options=["rw","suid","dev","exec","async"] type= what=/dev/disk/by-label/COS_OEM where=/sysroot/oem
```

Looks like the `DiskFSType` which checks the disk type is being run before COS_OEM is available, so it cannot infer the type properly?

**Comment by mauromorales** [comment]
I saw this error when trying to boot the Ubuntu RPi

**Comment by Itxaka** [comment]
> I saw this error when trying to boot the Ubuntu RPi

yep! Looks like the function is being run at the start of immucore. That works nice for existing fs, but for anything that gets mounted or appears later, it doesnt work. Just added a just-in-time check for fs when trying to mount to fix this, in case things change between start and the mount command which should fix this.

**Comment by Itxaka** [comment]
Im wondering if upgrade will even work. As long as we are just using the labels it should but...meh it migth not.

**Comment by Itxaka** [comment]
> Im wondering if upgrade will even work. As long as we are just using the labels it should but...meh it migth not.

seems liek it does as we dont touch the oem partition :D

**Comment by Itxaka** [comment]
blocked by https://github.com/kairos-io/kairos/issues/1330

**Comment by Itxaka** [comment]
Lvm support is in
